// Original teaching notes. Tutorials remain on their authors' sites.
const x = 'https://ts.xcatliu.com/';
const o = 'https://www.typescriptlang.org/docs/handbook/';
const s = (label, url, section) => ({ label, url, ...(section ? { section } : {}) });
export const sources = {
  intro: s('xcatliu · 什么是 TypeScript', x + 'introduction/what-is-typescript.html'),
  hello: s('xcatliu · Hello TypeScript', x + 'introduction/hello-typescript.html'),
  primitive: s('xcatliu · 原始数据类型', x + 'basics/primitive-data-types.html'),
  any: s('xcatliu · 任意值', x + 'basics/any.html'),
  inference: s('xcatliu · 类型推论', x + 'basics/type-inference.html'),
  union: s('xcatliu · 联合类型', x + 'basics/union-types.html'),
  object: s('xcatliu · 对象的类型——接口', x + 'basics/type-of-object-interfaces.html'),
  array: s('xcatliu · 数组的类型', x + 'basics/type-of-array.html'),
  function: s('xcatliu · 函数的类型', x + 'basics/type-of-function.html'),
  assertion: s('xcatliu · 类型断言', x + 'basics/type-assertion.html'),
  declaration: s('xcatliu · 声明文件', x + 'basics/declaration-files.html'),
  builtin: s('xcatliu · 内置对象', x + 'basics/built-in-objects.html'),
  alias: s('xcatliu · 类型别名', x + 'advanced/type-aliases.html'),
  literal: s('xcatliu · 字符串字面量类型', x + 'advanced/string-literal-types.html'),
  tuple: s('xcatliu · 元组', x + 'advanced/tuple.html'),
  enum: s('xcatliu · 枚举', x + 'advanced/enum.html'),
  class: s('xcatliu · 类', x + 'advanced/class.html'),
  classInterface: s('xcatliu · 类与接口', x + 'advanced/class-and-interfaces.html'),
  generic: s('xcatliu · 泛型', x + 'advanced/generics.html'),
  merging: s('xcatliu · 声明合并', x + 'advanced/declaration-merging.html'),
  lint: s('xcatliu · 代码检查', x + 'engineering/lint.html'),
  basics: s('官方 · 基础与类型擦除', o + '2/basic-types.html'),
  everyday: s('官方 · 常见类型', o + '2/everyday-types.html'),
  narrowing: s('官方 · 类型收窄', o + '2/narrowing.html'),
  functions: s('官方 · 函数', o + '2/functions.html'),
  objects: s('官方 · 对象类型', o + '2/objects.html'),
  generics: s('官方 · 泛型', o + '2/generics.html'),
  keyof: s('官方 · keyof', o + '2/keyof-types.html'),
  typeof: s('官方 · typeof 类型操作符', o + '2/typeof-types.html'),
  indexed: s('官方 · 索引访问类型', o + '2/indexed-access-types.html'),
  conditional: s('官方 · 条件类型与 infer', o + '2/conditional-types.html'),
  mapped: s('官方 · 映射类型', o + '2/mapped-types.html'),
  template: s('官方 · 模板字面量类型', o + '2/template-literal-types.html'),
  utilities: s('官方 · 内置工具类型', o + 'utility-types.html'),
  compatibility: s('官方 · 类型兼容性', o + 'type-compatibility.html'),
  classes: s('官方 · 类', o + '2/classes.html'),
  modules: s('官方 · 模块', o + '2/modules.html'),
  resolution: s('官方 · 模块解析参考', o + 'modules/reference.html'),
  dts: s('官方 · 声明文件', o + 'declaration-files/introduction.html'),
  moduleDts: s('官方 · 模块声明模板', o + 'declaration-files/templates/module-d-ts.html'),
  merge: s('官方 · 声明合并', o + 'declaration-merging.html'),
  namespace: s('官方 · 命名空间与模块', o + 'namespaces-and-modules.html'),
  config: s('官方 · TSConfig 配置参考', 'https://www.typescriptlang.org/tsconfig/'),
  dom: s('官方 · DOM 操作', o + 'dom-manipulation.html'),
  migration: s('官方 · 从 JavaScript 迁移', o + 'migrating-from-javascript.html'),
  jsdoc: s('官方 · JSDoc 类型标注', o + 'jsdoc-supported-types.html'),
  satisfies: s('官方 · satisfies 操作符', o + 'release-notes/typescript-4-9.html#the-satisfies-operator'),
  const: s('官方 · const 断言', o + 'release-notes/typescript-3-4.html#const-assertions'),
  evolving: s('官方 · 未初始化变量的类型追踪', o + 'release-notes/typescript-2-1.html#improved-any-inference'),
  decorators: s('官方 · 装饰器', o + 'release-notes/typescript-5-0.html#decorators'),
  wangDecorators: s('网道 · 装饰器', 'https://wangdoc.com/typescript/decorator'),
};
const l = (title, goal, note, refs) => ({ title, goal, note, sourceIds: refs.split(' ') });
const c = (title, summary, lessons) => ({ title, summary, lessons });
const raw = [
  c('TS 到底做了什么', '建立编译检查与实际执行的边界。', [
    l('JS 与 TS 的关系', '识别类型信息与实际业务逻辑。', '已有 JavaScript 行为仍然存在。类型标注表达预期，编译器把代码中的用法与预期进行比较；标注本身不会自动修复业务逻辑。', 'intro basics'),
    l('类型错误与运行错误', '判断问题在检查时还是执行时出现。', '类型检查基于已知的声明和控制流。网络返回值、手写声明以及外部数据可能与预期不同；没有红线不表示业务永远正确。', 'hello basics'),
    l('类型擦除', '解释编译后的 JavaScript 保留了什么。', '接口、类型别名和大多数标注不会生成运行时对象。想检查实际数据，必须编写可执行的判断；不要对接口使用 instanceof。', 'intro basics'),
    l('第一个 TS 项目', '读懂文件、入口、编译和检查的关系。', 'tsc 根据项目配置分析文件。noEmit 可以只检查类型；输出 JavaScript 与检查是否成功是两个需要分别确认的结果。', 'hello config'),
    l('读懂错误信息', '找到实际类型与期望类型的冲突。', '先定位文件和行号，再沿着错误里的属性路径寻找冲突。不要只修改报错行：函数参数或数据定义可能才是问题来源。', 'hello everyday'),
    l('严格模式入门', '修复空值和隐式 any，而非关闭检查。', '本课程显式使用 strict。可选值在访问前需要检查；没有上下文的参数需要恰当标注。编译设置是题目条件的一部分。', 'any config'),
  ]),
  c('日常类型与类型推断', '知道值有哪些可能，知道信息在哪里丢失。', [
    l('原始类型', '为文本、数字、布尔值和特殊值选择类型。', '使用小写 string、number、boolean 表达原始值。null 与 undefined 有自己的类型；symbol 和 bigint 用于不同的数据需求。', 'primitive everyday'),
    l('注解与推断', '决定何时标注，何时保留自动推断。', '初始化与上下文可以提供类型。显式标注适合公共边界；过宽的标注可能丢失有用信息。未初始化变量会受赋值流与编译选项影响。', 'inference evolving'),
    l('字面量与类型扩大', '预测 const、let 和对象属性的类型。', '常量值与可变位置的推断可能不同。对象用 const 绑定并不让属性只读；需要保留具体值时考虑字面量标注或 as const。', 'literal const'),
    l('any、unknown 与 never', '安全处理未知值和不可能发生的分支。', 'any 放弃许多检查；unknown 要求先证明值的形状；never 表示没有可能值。它们不能互相当作方便的占位符。', 'any narrowing'),
    l('void 与返回值', '区分返回值未被使用和函数无法正常结束。', 'void 常表示调用方不使用返回值；never 表示没有正常返回路径。回调赋值的规则还需要结合调用方契约理解。', 'function functions'),
    l('赋值兼容性', '判断一个值是否满足目标类型的要求。', '赋值要看来源提供什么、目标要求什么。联合类型允许范围内的值，而不能因为一时赋过某个值就永久改变变量的声明类型。', 'union compatibility'),
    l('内置类型', '使用 Date、Promise、Map 与 Set 的类型信息。', '内置类型描述对象可用的方法。泛型参数描述容器中的值；有相应类型声明不代表目标运行环境一定提供该 API。', 'builtin config'),
  ]),
  c('联合类型与类型收窄', '把多种情况分别处理清楚。', [
    l('联合类型', '用多种候选类型表达输入范围。', 'A | B 表示值属于候选之一。使用某个分支独有的能力前，要先证明当前值属于该分支。', 'union everyday'),
    l('共有属性', '找出可以直接使用和必须判断的属性。', '对未收窄的联合值，只能直接使用每种候选都支持的成员。属性同名也要考虑其值类型是否不同。', 'union narrowing'),
    l('条件收窄', '用 typeof、相等比较和空值判断建立证据。', '分支条件会改变分支内部可确定的类型。真值判断会同时排除空字符串和零，不能总把它当作仅判断缺失。', 'union narrowing'),
    l('对象收窄', '用 in 与 instanceof 识别对象能力。', 'in 检查属性存在；instanceof 检查运行时原型关系。可选属性可能出现在两侧，接口没有运行时构造函数。', 'object narrowing'),
    l('判别联合', '让业务状态和有效字段保持对应。', '为不同状态提供各自的对象分支，共享一个字面量判别字段。这样成功数据与失败原因不会被建模成任意组合。', 'union narrowing'),
    l('自定义类型守卫', '把可靠的运行时判断封装为类型守卫。', '返回 value is T 的函数给调用方提供类型证据。编译器不会替你验证判断逻辑充分，所以必须测试错误输入。', 'assertion narrowing'),
    l('穷尽检查', '让新增状态暴露尚未处理的分支。', '所有联合成员被处理后，剩余值应是 never。新增成员时，最后的穷尽检查会提醒你补全逻辑。', 'union narrowing'),
  ]),
  c('对象、数组与接口', '表达数据结构，排除无效组合。', [
    l('对象属性', '区分必需、可选和只读属性。', '可选属性可能不存在；读取结果要考虑 undefined。readonly 限制通过该类型写入，不等于运行时冻结。', 'object objects'),
    l('type 与 interface', '为数据结构选择合适的声明方式。', '二者都能描述对象。类型别名还能表达联合等类型；接口可扩展与合并。选择要与维护需求一致。', 'alias object'),
    l('数组', '准确描述可变和只读的元素集合。', 'Array<T> 与 T[] 描述同类元素集合。只读数组能接收更多只读输入，适合只遍历不修改的函数参数。', 'array objects'),
    l('元组', '约束有位置含义的参数或返回值。', '元组把位置与类型关联起来，适合坐标或状态对。可选、剩余元素表达长度变化，但不是任意长度数组的替代。', 'tuple objects'),
    l('索引签名', '处理键名未知的字典数据。', '索引签名规定动态键对应的值。已声明属性也必须满足相关索引约束；字典读取是否包含 undefined 受配置影响。', 'object objects'),
    l('额外属性检查', '解释字面量与已有对象的检查差异。', '直接传入新对象字面量通常有额外属性检查。赋给变量不等于数据变成精确对象，结构兼容仍然起作用。', 'object objects'),
    l('结构化类型', '根据形状判断对象是否兼容。', '大多数对象兼容性按结构比较，无需显式 implements。相同基础类型的业务 ID 也会兼容，需要额外约束时再设计品牌类型。', 'object compatibility'),
    l('互斥字段', '消除状态模型中的非法组合。', '把互斥情况拆成联合成员，让每种情况只拥有自身字段。单个对象上堆很多可选属性常常允许业务上无意义的组合。', 'union objects'),
  ]),
  c('函数与回调', '描述调用方式和返回关系。', [
    l('参数与返回类型', '让函数边界既明确又保留推断。', '参数描述调用要求，返回类型描述承诺。公共函数可标注返回类型，让遗漏返回值和错误分支更早暴露。', 'function functions'),
    l('可选、默认与剩余参数', '表达合法的参数数量和顺序。', '可选参数在实现中可能为 undefined；默认值可以补足缺省输入。剩余参数可用数组或元组准确描述。', 'function functions'),
    l('回调函数', '让回调参数由调用上下文推断。', '回调接收什么由调用方契约决定。不要把实际上总会提供的参数标成可选，否则调用者要无端处理 undefined。', 'function functions'),
    l('异步函数', '表达 Promise 中成功结果的类型。', 'async 的正常结果放进 Promise。失败不会自动成为返回类型中的 error 字段，需要自己选择抛错或结果联合的约定。', 'builtin functions'),
    l('函数重载', '描述不同输入对应的不同输出。', '调用方看到的是重载签名；实现签名需要覆盖这些情况。只有输入范围变化而输出相同，通常用联合类型更简单。', 'function functions'),
    l('this 参数', '声明方法需要的调用上下文。', '函数的 this 可以显式标注，避免取出方法后丢失上下文。箭头函数捕获外层 this，与普通方法行为不同。', 'function functions'),
    l('联合、重载还是泛型', '根据输入输出关系选择函数接口。', '联合适合有限分支；重载表达有限的对应关系；泛型保留任意调用类型间的关联。没有关联的泛型参数只会增加负担。', 'function generics'),
  ]),
  c('泛型', '保留信息，让复用保持准确。', [
    l('泛型保留关系', '使返回值保留调用时的具体类型。', '泛型占位符由每次调用确定，连接输入与输出。把返回值写成 any 会丢失这一关系，写成固定联合也可能过宽。', 'generic generics'),
    l('泛型函数与接口', '把可复用结构参数化。', '类型参数可以属于一次函数调用，也可以属于整个接口。放置位置决定使用者在什么时机选择类型。', 'generic generics'),
    l('泛型约束', '只要求实现实际需要的能力。', 'T extends U 表示 T 至少满足 U，同时保留调用方的具体类型。约束不是允许你返回任何一个 U。', 'generic generics'),
    l('多个类型参数', '连接两个容器或输入输出之间的关系。', '多个参数用于描述不同角色，不必强迫不同输入使用同一类型。每个参数都应出现在有意义的关系中。', 'generic generics'),
    l('默认值与推断', '减少调用负担并识别推断失败原因。', '优先让参数值提供推断依据。类型默认值只在无法确定且允许省略时发挥作用，不是把所有输入都改成默认类型。', 'generic generics'),
    l('keyof 约束', '保证访问的键来自当前对象。', 'K extends keyof T 把键限制到 T 的属性，T[K] 则保留对应值类型。使用 string 作为键通常丢失这一联系。', 'generic keyof indexed'),
    l('有效的泛型设计', '删除没有意义的泛型和不安全承诺。', '调用者可随意指定但实现无法验证的返回类型参数容易制造虚假承诺。把类型参数绑定到输入或校验器上。', 'generic functions'),
  ]),
  c('组合与派生类型', '从已有模型生成一致的接口。', [
    l('交叉类型', '组合约束并识别属性冲突。', 'A & B 要同时满足两方。相同属性的类型冲突可能让属性成为 never；交叉不是覆盖后面的属性。', 'alias objects'),
    l('keyof', '从类型获取合法属性名。', 'keyof 得到键的联合。索引签名、数字键等会影响结果，不能把所有对象的 keyof 都假定为 string。', 'keyof'),
    l('类型位置的 typeof', '从真实配置值派生类型。', '类型位置的 typeof 获取值的静态类型；运行时 typeof 返回字符串。二者语法相似但用途不同。', 'typeof inference'),
    l('索引访问类型', '取得属性、多个属性或元素的类型。', 'T[K] 让类型定义跟随源模型变化。数组的 [number] 表示任意元素类型，元组还能用具体位置索引。', 'indexed array'),
    l('as const', '为配置与枚举式对象保留字面量。', 'const 断言保留具体值并使字面量结构只读。它不会执行 Object.freeze，也不能替代运行时防修改。', 'const literal'),
    l('satisfies', '校验配置同时保留具体结构信息。', 'satisfies 用目标类型检查表达式，同时保留表达式的有用推断。它不负责运行时校验，也不是任意类型转换。', 'satisfies'),
    l('常用工具类型', '组合 Partial、Pick、Omit、Record 等工具。', '工具类型从现有模型生成新视图。多数浅层工具只改变第一层；嵌套数据是否变化必须逐层分析。', 'utilities'),
    l('派生业务模型', '从单一数据模型生成创建与更新参数。', '创建、更新、展示往往共享字段但权限不同。先明确不可由客户端修改的字段，再用工具类型组合契约。', 'utilities objects'),
  ]),
  c('条件类型与类型运算', '实现有边界、能解释的类型工具。', [
    l('条件类型', '根据类型关系选出结果类型。', 'T extends U ? X : Y 是类型层面的分支，与运行时 if 不同。结果取决于类型可赋值关系。', 'conditional'),
    l('infer', '从匹配的结构中提取类型。', 'infer 在条件类型的匹配位置引入待推断变量。它适合提取函数返回值、数组元素和 Promise 内部值。', 'conditional utilities'),
    l('分布式条件类型', '预测联合成员逐个计算后的结果。', '裸类型参数参与条件时，联合通常逐个分配计算。元组包裹可以表达对整个联合进行一次判断。', 'conditional'),
    l('映射类型', '遍历键并修改属性的类型或修饰符。', '映射类型遍历一个键集合。可选和 readonly 修饰符可保留、增加或去掉，用来生成可复用的数据视图。', 'mapped'),
    l('键重映射', '按条件过滤键或生成新键名。', '映射中的 as 可更改键。映射到 never 能移除该键；键的值类型仍可从原对象索引获得。', 'mapped'),
    l('模板字面量类型', '约束有规则的字符串并关联事件载荷。', '模板字面量类型组合字符串结构。与 keyof、条件类型配合可以连接事件名和数据；过大的组合会影响可读性。', 'template'),
    l('递归类型', '处理树、嵌套数组和有限深度的结构。', '递归类型需要清楚的终止条件。区分纯类型递归与运行时遍历，两者都需要处理边界与可维护性。', 'conditional objects'),
    l('类型复杂度', '选用简单工具并识别过度抽象。', '类型工具的目标是清楚约束程序。优先复用内置工具，避免不必要的深层递归、巨大联合和难读的错误信息。', 'utilities conditional'),
  ]),
  c('类型行为与常见误判', '用证据解释那些看似矛盾的结果。', [
    l('控制流中的类型变化', '跟踪赋值和分支对当前类型的影响。', '当前位置的收窄类型可能比声明类型窄。赋值合法性仍受声明类型约束；闭包和再次赋值会影响能保留的证据。', 'inference evolving narrowing'),
    l('兼容性与精确对象', '区分可赋值和字段完全一致。', '结构兼容通常允许多余字段。字面量的额外检查不等于整个类型系统采用精确对象语义。', 'object compatibility'),
    l('函数参数兼容', '理解替换回调时的参数范围。', '接收范围更窄的回调可能无法处理调用者传来的值。strictFunctionTypes 与方法签名还有差异，题目必须明确写法。', 'compatibility functions'),
    l('可选属性与 undefined', '区分缺少属性和显式 undefined。', '读取可选属性时要考虑缺失；写入是否允许显式 undefined 还取决于 exactOptionalPropertyTypes。', 'objects config'),
    l('断言与非空断言', '知道哪些写法只改变检查器的认知。', '断言不会转换实际数据。非空断言不会在运行时补上值；satisfies 也不会验证远端 JSON。', 'assertion satisfies'),
    l('unknown 边界', '用检查把外部值变成可信数据。', '先把不可信输入保持为 unknown，再确认对象、属性和值类型。每一步证据都应对应真实的运行时判断。', 'narrowing any'),
    l('编译通过的陷阱', '识别 any 传播、错误声明和不安全承诺。', '静态检查依赖你给出的前提。错误声明和宽泛类型会让检查器失去信息，运行测试与类型测试应共同保护边界。', 'assertion declaration basics'),
  ]),
  c('类、枚举与特殊语法', '能阅读并维护不同风格的 TS 项目。', [
    l('类与继承', '为实例、构造函数和继承行为建立类型。', '类同时有运行时构造函数和实例类型。静态成员属于构造函数，实例成员属于创建出的对象。', 'class classes'),
    l('访问控制与只读', '区分 TS 限制与 JavaScript 私有字段。', 'public、protected、private 描述类型检查层面的访问；#private 是 JavaScript 运行时机制。readonly 也不等于深冻结。', 'class classes'),
    l('接口、抽象类与实现', '验证实现满足契约并识别未实现成员。', 'implements 检查实例结构，不会自动提供接口方法的实现，也不总会把方法参数自动标注好。抽象类可包含共享实现。', 'classInterface classes'),
    l('枚举与字面量联合', '根据运行时需要选择状态表示。', '枚举有自身的生成与赋值规则；字面量联合主要在类型层面表达候选值。不要假设每种枚举都生成相同的反向映射。', 'enum literal'),
    l('声明合并', '理解接口和模块扩展的组合效果。', '声明合并把特定同名声明组合起来。合并的成员需要兼容；给已有库扩展类型还需要实际运行实现支持。', 'merging merge'),
    l('装饰器', '理解标准装饰器的调用与类型约束。', '装饰器处理声明的行为，适用语法与编译选项相关。课程标准装饰器任务固定版本；旧 experimentalDecorators 作为单独对照。', 'wangDecorators decorators'),
    l('历史语法与命名空间', '读懂 namespace 并与现代模块对照。', '命名空间和 ES 模块的组织机制不同。维护旧项目时先确认输出与加载方式，再决定迁移方案。', 'namespace modules'),
  ]),
  c('模块与声明文件', '让多文件代码和第三方库保留类型。', [
    l('导入与导出', '连接多个文件中的值和类型。', '模块边界决定名字是否可见。默认导出与具名导出要与导入方式对应；类型存在不代表运行值存在。', 'modules'),
    l('类型导入', '区分 import type 与运行时依赖。', '仅用于类型的位置可用 import type。需要调用或实例化时必须有运行时值，不能把类型导入当作普通导入。', 'modules declaration'),
    l('模块解析', '按环境定位模块文件与声明。', '路径、扩展名、包信息与 moduleResolution 一起决定解析。编译器认识别名，不代表运行时加载器自动认识它。', 'resolution config'),
    l('声明文件的作用', '为既有 JS 描述类型而不虚构运行实现。', '.d.ts 描述外部代码的契约，不会提供函数体。声明与真实库不一致时，编译通过也可能运行失败。', 'declaration dts'),
    l('编写库声明', '描述函数、对象与可导出的模块接口。', '先观察库实际导出什么，再写对应声明。正例和反例共同检查声明是否准确，不能只用一条成功调用验证。', 'declaration moduleDts'),
    l('第三方类型来源', '分辨自带声明、@types 和本地补充声明。', '类型可能由库本身、独立类型包或本地文件提供。重复或不兼容的版本可能导致错误，要先找实际加载的声明。', 'declaration resolution'),
    l('环境与全局类型', '区分浏览器、Node 和自己的全局声明。', '不同环境提供不同的全局对象。把类型库加进配置只能让编译器知道名字，不能让运行环境凭空获得能力。', 'builtin config'),
    l('公共类型组织', '减少循环依赖和重复模型。', '共享契约应有清晰的归属。业务层内部细节不必全部导出；类型导入可以避免不必要的运行依赖。', 'modules declaration'),
  ]),
  c('编译配置与工程诊断', '根据错误定位环境、文件和依赖。', [
    l('项目文件范围', '判断 files、include 和 exclude 的作用。', '配置决定入口文件范围，导入关系还会带入依赖。排除路径不等于阻止所有被导入的文件进入项目。', 'config'),
    l('严格检查选项', '通过修复代码适应明确的检查规则。', 'strict 组合多项检查；exactOptionalPropertyTypes、noUncheckedIndexedAccess 等还需要单独明确。不要假定 strict 开启了所有检查。', 'config'),
    l('target 与 lib', '区分语法输出、类型声明和运行时支持。', 'target 控制部分语法的输出；lib 提供标准 API 声明。二者都不自动为缺失 API 安装 polyfill。', 'builtin config'),
    l('module 与 moduleResolution', '按运行或打包环境选择一致配置。', '模块生成和模块寻找是相关但不同的工作。浏览器打包、直接 Node 执行需要不同的配合方式。', 'resolution config'),
    l('检查与输出', '理解 noEmit、声明输出与构建结果。', '类型检查、JS 输出、声明输出是不同目标。检查失败是否还能输出取决于配置；存在输出文件不等于检查成功。', 'config dts'),
    l('编译、检查与打包', '区分转译、类型检查、Lint 和打包。', '去掉类型语法的工具可能没有做语义检查。项目需明确哪一步真正检查类型，哪一步负责打包与运行。', 'lint basics config'),
    l('多项目配置', '理解 extends 与项目引用的用途。', '共享配置可减少差异；项目引用帮助组织编译边界。不同应用的环境类型仍需要分别指定。', 'config'),
    l('排查工程错误', '沿导入链和配置找到问题根源。', '先确认当前用的是哪个编译器和配置，再定位实际读取的文件。复制另一项目的设置可能掩盖而不是解决问题。', 'resolution config'),
  ]),
  c('浏览器、网络与 JS 迁移', '把类型保护延伸到真实数据边界。', [
    l('DOM 与空值', '安全处理查询不到元素的情况。', 'DOM 查询可能返回 null，匹配到的节点也未必是你想要的具体元素。先验证存在和元素类别，再访问专属属性。', 'builtin dom'),
    l('表单与事件', '从事件中安全取得输入数据。', '事件 target 可能为空或不是输入框。用真实检查或明确的元素引用取得值，不要把所有事件目标强行断言成输入框。', 'dom narrowing'),
    l('fetch 与远端数据', '区分请求成功、HTTP 成功和数据有效。', '请求完成后仍要检查 HTTP 状态与响应结构。Promise<User> 这样的承诺需要有实现证据，不能只靠把 JSON 断言成 User。', 'builtin narrowing'),
    l('运行时数据校验', '构建能拒绝脏数据的解析函数。', '从 unknown 出发验证对象、字段类型与业务约束。成功返回可信数据，失败给出可处理的错误信息。', 'narrowing assertion'),
    l('JS 检查与 JSDoc', '在不立即改扩展名时引入检查。', 'allowJs、checkJs 和 JSDoc 可以支持渐进迁移。声明需要与代码同步，不能只用注释让错误消失。', 'migration jsdoc'),
    l('逐步迁移', '选择模块边界并保持现有功能。', '先稳定外部接口和测试，再迁移内部实现。把不可信入口集中起来处理，有助于减少全项目传播的 any。', 'migration'),
    l('清理 any 与断言', '逐步恢复被绕过的检查。', '优先处理跨模块传播的 any 和外部数据断言。每次收紧类型都应有调用测试，避免只把 any 换成另一种宽泛承诺。', 'assertion migration'),
  ]),
  c('独立完成 TS 项目', '把课程知识用在可运行的学习任务管理器中。', [
    l('项目：任务数据模型', '表达任务、标签和状态的合法组合。', '从业务规则出发定义模型。完成时间只属于完成状态，任务 ID 和标题有明确边界，后续模块共享这一契约。', 'union objects'),
    l('项目：公共业务函数', '实现创建、修改、筛选与排序。', '公共函数应有可预测输入输出，明确是否修改原数据。类型检查和运行测试分别验证接口与行为。', 'functions utilities'),
    l('项目：异步状态', '管理加载、成功、失败和重试。', '用判别联合表示异步状态，避免同时出现成功数据与错误。测试不仅覆盖成功，还覆盖失败与恢复。', 'narrowing functions'),
    l('项目：导入数据', '把未知导入值校验成任务集合。', '外部文件不受类型系统约束。按记录验证并报告错误，不要让一个错误字段在后续页面中才引发异常。', 'narrowing'),
    l('项目：多文件协作', '拆分数据契约、逻辑与展示边界。', '模块间只暴露必要能力。调整一个模块时，用其他模块的类型检查和行为测试确认契约没有被破坏。', 'modules declaration'),
    l('项目：类型审查', '修复宽泛类型、断言和重复定义。', '审查的结果应能让非法调用被拒绝，同时保持合法流程可用。不要以减少红线数量作为唯一目标。', 'utilities compatibility'),
    l('项目：新增业务状态', '利用类型错误找到需要共同修改的位置。', '为任务增加新状态时，让数据模型、筛选与展示同步变化。穷尽检查是变化时的提醒，迁移数据也需要对应处理。', 'narrowing mapped'),
  ]),
];
export const chapters = raw.map((chapter, i) => ({
  ...chapter, id: `t${String(i + 1).padStart(2, '0')}`,
  lessons: chapter.lessons.map((lesson, j) => ({ ...lesson,
    id: `t${String(i + 1).padStart(2, '0')}-l${String(j + 1).padStart(2, '0')}`,
    prerequisite: j > 0 ? `t${String(i + 1).padStart(2, '0')}-l${String(j).padStart(2, '0')}` : null,
  })),
}));
export const lessons = chapters.flatMap((c) => c.lessons);
