export function addAsyncDepthExercises({ choice }) {
  const cases = [
    ['callbacks','错误优先回调应优先处理错误','底层意外同时传入 err 和 result。上层要避免把失败结果当作成功，哪种处理顺序最可靠？','callback(error,{id:1});',['先检查 error；若非 null/undefined 则结束失败分支，不处理 result','先渲染 result，再记录 error','只要 result 非空就忽略 error','把 error 和 result 拼成字符串'],['error-first 约定把首参数留给失败。','失败时成功值不应被信任。','分支需要明确 return 或 else。'],'错误优先回调要先处理错误并退出；即使同时给出 result，也不能当成成功结果。'],
    ['callbacks','外层同步 catch 捕不到未来的回调异常','setTimeout 回调稍后抛错，包围 setTimeout 调用的同步 try/catch 能捕获它吗？','try{setTimeout(()=>{throw Error("later")},0)}catch(e){log(e)}',['不能；回调在后续任务中运行，已离开当前 try/catch','能；setTimeout 自动把异常传回调用处','只有延迟为 0 才能','能；所有异步回调都继承调用处的异常处理栈'],['try/catch 只覆盖当前同步执行路径。','计时器回调随后才执行。','要在回调内部处理或用 Promise 约定传播。'],'未来任务里的异常不在设置计时器时的调用栈中，外层同步 catch 不会捕获。'],
    ['promise-basics','resolve 另一个 Promise 会采用其状态','外层 Promise 调用 resolve(inner)，inner 稍后以 7 完成。外层最终结果是什么？','const inner=Promise.resolve(7);const outer=new Promise(resolve=>resolve(inner));',['fulfilled 为 7，而不是把 inner 对象作为普通结果','fulfilled 为 inner 这个 Promise 对象','永远 pending','立即 rejected'],['Promise 的 resolve 会吸收 Promise/thenable。','外层等待 inner 的最终状态。','最终值是 inner 的完成值。'],'用另一个 Promise 结算时，外层会采用其状态和最终值，得到 7。'],
    ['promise-basics','resolve 的返回值无关结算结果','下面 Promise 最终 fulfilled 的值是什么？','const p=new Promise(resolve=>{const x=resolve(3);return 9});',['3','9','undefined','resolve(3) 的返回值 x'],['Promise executor 的 return 不用于结算。','resolve(3) 决定完成值。','executor 的返回值被忽略。'],'resolve(3) 使 p 以 3 完成；executor return 9 不会替换该值。'],
    ['promise-chaining','then 返回普通值会传给后续 then','下面最终值是什么？','Promise.resolve(2).then(x=>x*3).then(x=>x+1);',['7','6','3','Promise 对象本身作为最终值'],['第一个处理器返回普通数字 6。','链上的下一个 Promise 以该值完成。','第二个处理器计算 6+1。'],'then 返回值成为后续链的输入，最终完成值为 7。'],
    ['promise-chaining','then 内抛错会跳过下一个成功处理器','第一个 then 抛出 Error 后，紧接着的成功处理器会怎样？','Promise.resolve(1).then(()=>{throw Error("bad")}).then(()=>log("ok"));',['不会运行；链转为 rejected，需 catch 或拒绝处理器','仍运行并输出 ok','把 Error 对象当普通值传入后续成功处理器','链会自动从头重试'],['then 处理器同步抛错会拒绝它返回的 Promise。','后续只提供成功处理器。','拒绝会沿链传播。'],'抛错使该链节拒绝；下一个只有成功处理器的 then 会被跳过。'],
    ['promise-error-handling','catch 返回备用值会恢复链','请求 Promise 拒绝后，catch 返回 "cached"，后续成功 then 会收到什么？','request().catch(()=> "cached").then(value=>show(value));',['"cached"；catch 的普通返回值使链恢复 fulfilled','原始 Error；catch 不能改变状态','undefined；catch 返回值被忽略','后续 then 永远不会运行'],['catch 也是 then 的拒绝处理器。','返回普通值会完成它返回的 Promise。','下一个成功分支接收该值。'],'catch 返回备用值可以把预期失败转成正常完成，后续 then 收到 cached。'],
    ['promise-error-handling','finally 自己失败会覆盖原结果','原 Promise 以 5 完成，但 finally 回调抛出 Error("cleanup")。之后链是什么状态？','Promise.resolve(5).finally(()=>{throw Error("cleanup")});',['rejected，原因是 cleanup 错误','fulfilled 为 5','fulfilled 为 undefined','永远 pending'],['finally 正常完成才保留原结果。','finally 自己抛错会产生新的拒绝。','清理失败不应被误认为成功。'],'finally 回调抛错会覆盖原先的 fulfilled 结果，让返回的 Promise 拒绝。'],
    ['promise-api','allSettled 保留每项结果','两个输入一个完成为 1、一个拒绝为 Error。Promise.allSettled 最终状态与结果结构是什么？','',['它自身 fulfilled，返回按输入顺序包含 fulfilled 与 rejected 状态对象的数组','它自身 rejected，原因是第二项 Error','只返回成功值 [1]','只返回失败列表'],['allSettled 等待所有输入结束。','单个拒绝被记录成结果项。','整体 Promise 仍完成。'],'Promise.allSettled 返回每项状态记录，不因其中一个拒绝而整体拒绝。'],
    ['promise-api','空输入时不同组合器的结果','Promise.all([]) 与 Promise.any([]) 分别如何结算？','',['all 以 [] 完成；any 以 AggregateError 拒绝','两者都永远 pending','两者都以 [] 完成','all 拒绝；any 完成'],['all 不需要等待任何项即可给出空结果。','any 需要至少一个成功。','没有候选项意味着 any 无法成功。'],'Promise.all([]) 完成为空数组；Promise.any([]) 没有可成功项，会以 AggregateError 拒绝。'],
    ['promisify','多结果回调不能只取第一个值','旧 API 回调约定为 callback(error,first,second)。普通“只接收 value”的 promisify 会丢掉什么？','',['会丢掉 second；应明确把成功结果收集成数组或对象','会自动把 first、second 合并成字符串','会自动返回两个独立 Promise','不会丢失任何结果，Promise 可完成多个独立值'],['Promise 只能以一个值完成。','这个值可以是数组或对象。','包装器必须自己组合多个结果。'],'如果包装器只读取第二个回调参数，后续成功参数会丢失；可把它们收集为数组。'],
    ['promisify','包装器需保留方法接收者','把对象方法 obj.read 包装为 Promise 版本后，再以 obj.readAsync() 调用。若原 read 内部使用 this.base，包装器应怎样调用原方法？','',['用普通函数包装并通过 fn.apply(this,[...args,callback]) 转发','用箭头包装并总传 undefined 作为 this','只执行 fn(...args)，this 永远自动保留','把 this.base 在包装时固定复制到全局变量'],['方法依赖调用时接收者。','包装器也应取得同一次调用的 this。','apply 可转发接收者和参数。'],'普通函数包装器保留动态 this，再用 apply 传给原方法。'],
    ['promisify','同步抛错也应成为拒绝','回调式函数在调用时同步抛错。包装器用 new Promise 的 executor 内调用该函数，会怎样？','',['返回的 Promise 拒绝，原因是同步抛出的错误','new Promise 一定同步把错误抛出给外层调用者','Promise 自动以 undefined 完成','回调会被自动调用一次'],['Promise executor 受到构造器的异常处理。','同步抛错会转为拒绝。','外层包装函数仍返回 Promise。'],'在 Promise executor 中发生的同步异常会拒绝该 Promise，调用方可用 catch/await 处理。'],
    ['microtask-queue','计时器任务之间会清空微任务','两个计时器按登记顺序到期，第一个回调里排入微任务 M。通常日志顺序是什么？','setTimeout(()=>{log("T1");queueMicrotask(()=>log("M"))},0);setTimeout(()=>log("T2"),0);',['T1、M、T2','T1、T2、M','M、T1、T2','T2、T1、M'],['每个计时器回调是独立任务。','第一个任务结束后会处理其排入的微任务。','然后才运行下一个计时器任务。'],'第一个计时器输出 T1，随后清空微任务输出 M，再执行第二个计时器输出 T2。'],
    ['microtask-queue','持续追加微任务可能推迟页面任务','一个微任务每次执行又 queueMicrotask 自己，且从不停下。最可能影响什么？','',['浏览器可能长期无法进入下一任务和渲染，形成微任务饥饿','setTimeout 回调总会在每次微任务后立刻插入','微任务会自动只运行 100 次','页面渲染会强制中断任何微任务链'],['运行时通常在下一任务前清空微任务队列。','微任务不断追加，队列难以清空。','渲染和计时器因此可能被推迟。'],'不断自我追加的微任务可阻止事件循环进入下一任务，造成响应与渲染延迟。'],
    ['microtask-queue','await 普通值仍让出当前同步栈','async 函数内执行 await 5。await 后的日志会先于紧接调用之后的同步日志吗？','async function run(){log("A");await 5;log("B")}run();log("C");',['不会；顺序 A、C、B','会；顺序 A、B、C','顺序 C、A、B','await 5 会抛 TypeError'],['await 会把后续执行安排为异步续体。','await 之前的 A 同步发生。','调用外的同步 C 在续体 B 前执行。'],'即使等待普通值，async 函数也会在 await 后暂停，外层同步代码先运行。'],
    ['async-await','try/catch 要包住真正的 await','异步函数想把请求拒绝转成 fallback。哪种结构能在同一函数里捕获拒绝？','',['try { return await request() } catch (e) { return fallback }','try { return request() } catch (e) { return fallback }','try { request().then(x=>x) } catch (e) { return fallback }','return request(); catch (e) { return fallback }'],['request 返回 Promise。','不 await 时，后续拒绝不会同步进入当前 catch。','await 把拒绝转换为当前 async 函数里的异常。'],'把 await 放在 try 内，拒绝才会被该 catch 捕获并转为备用结果。'],
    ['async-await','独立请求并发启动的写法','两个互不依赖的请求都要完成后再组合结果。哪种写法能先启动二者，再等待全部？','',['const a=requestA(); const b=requestB(); const [x,y]=await Promise.all([a,b]);','const x=await requestA(); const y=await requestB();','const x=await requestA(); const b=requestB();','await requestA(); await requestA();'],['独立请求不必串行等待。','先调用两次可并发发起。','Promise.all 等待两者并保持输入顺序。'],'先同时启动两个请求，再用 Promise.all 等待，避免无必要的串行耗时。']
  ];
  const indexes=new Map();
  for (const [lessonId,title,prompt,example,options,hints,explanation] of cases) {
    const index=(indexes.get(lessonId)||0)+1;
    indexes.set(lessonId,index);
    choice(lessonId+'-depth-'+String(index).padStart(2,'0'),lessonId,title,prompt,example,options,0,hints,explanation);
  }
}
