export function addDataDepthExercises({ choice, code }) {
  const cases = [
    ['primitives-methods','原始值与包装对象不严格相等','下面两个结果分别是什么？','const text="hi"; const boxed=new String("hi");\ntext===boxed; typeof boxed;',['false、"object"','true、"string"','true、"object"','false、"string"'],['new String 创建对象。','字符串原始值的 typeof 是 string。','严格相等不把对象自动拆箱。'],'包装对象与原始字符串类型不同，严格比较为 false；boxed 的 typeof 为 object。'],
    ['primitives-methods','调用数字字面量方法的语法','想把十进制数字 255 转成十六进制字符串 "ff"。哪种表达式在语法和结果上都正确？','',['(255).toString(16)','255.toString(16)','255.toString("ff")','new Number(255) === 255'],['数字字面量后的小数点有语法歧义。','圆括号可明确调用对象方法。','进制参数 16 产生十六进制表示。'],'(255).toString(16) 合法并返回 "ff"；数字字面量也可写 255..toString(16)。'],
    ['number','toFixed 的类型与补零','调用 (1.2).toFixed(3) 后，结果的类型和值是什么？','',['字符串 "1.200"','数字 1.2','字符串 "1.2"','数字 1.200'],['toFixed 以固定小数位数格式化。','不足的位数会补零。','返回值是字符串。'],'toFixed(3) 返回字符串 "1.200"，用于展示时不能当成未转换的数字。'],
    ['number','Number.isNaN 与全局 isNaN','对于文本 "oops"，哪组判断结果正确？','Number.isNaN("oops"); isNaN("oops");',['false、true','true、true','false、false','true、false'],['Number.isNaN 不做类型转换。','全局 isNaN 会先尝试数值转换。','"oops" 转数字是 NaN。'],'Number.isNaN("oops") 为 false；全局 isNaN 先转换，因转换结果为 NaN 而返回 true。'],
    ['string','slice 与 substring 的负索引','对 text="abcdef" 执行两个调用，结果分别是什么？','text.slice(-2); text.substring(-2);',['"ef"、"abcdef"','"ef"、"ef"','"ab"、"abcdef"','"abcdef"、"ef"'],['slice 的负索引从尾部算。','substring 把负参数视为 0。','只传一个参数时都截取到结尾。'],'slice(-2) 从倒数第二个位置开始得到 ef；substring(-2) 等同 substring(0)，得到整串。'],
    ['string','不可变字符串与替换结果','下面最终输出什么？','let text="A-B"; text.replace("-","/"); console.log(text);',['"A-B"','"A/B"','undefined','抛 TypeError'],['字符串是不可变原始值。','replace 返回新字符串。','没有把返回值重新赋给 text。'],'replace 不会原地修改 text；必须接住返回值才会保存替换结果。'],
    ['array','delete 与 splice 的区别','对 ["a","b","c"] 执行 delete items[1]。之后 length 和索引 1 的存在性如何？','const items=["a","b","c"]; delete items[1];',['length 仍为 3，1 in items 为 false','length 变 2，1 in items 为 true','length 仍为 3，items[1] 为 null','length 变 1，1 in items 为 false'],['delete 删除属性，不移动后续元素。','数组 length 不因中间属性删除而缩短。','该位置成为空位。'],'delete 造成空位，length 保持 3；若想移动元素应使用 splice。'],
    ['array','push 的返回值不是数组','下面 result 的值是什么？','const items=[1]; const result=items.push(2,3);',['3','[1,2,3]','[2,3]','undefined'],['push 会原地追加多个元素。','它返回新长度。','原数组此时长度为 3。'],'push 返回追加后的数组长度 3，而非数组本身。'],
    ['array-methods','some 的短路可避免多余计算','数组 [2,5,8] 使用 some 查找大于 4 的元素，回调记录访问值。结束后记录是什么？','const seen=[]; [2,5,8].some(x=>{seen.push(x);return x>4});',['[2,5]','[2,5,8]','[5]','[]'],['some 在首次真值结果处结束。','先访问 2，条件为假。','访问 5 时条件为真，不再访问 8。'],'some 会短路；找到 5 后立即返回 true，不再处理 8。'],
    ['iterable','迭代器本身可能只用一次','source 的 Symbol.iterator 返回自身；连续展开两次分别得到什么？','const source={i:0,[Symbol.iterator](){return this},next(){return this.i<2?{value:++this.i,done:false}:{done:true}}};\nconst first=[...source]; const second=[...source];',['[1,2] 与 []','[1,2] 与 [1,2]','[] 与 [1,2]','两次都抛 TypeError'],['迭代器的游标 i 保存在 source 上。','第一次展开把游标推进到 2。','第二次没有重置游标。'],'source 同时是迭代器，展开会消耗其内部状态；第二次展开时已经结束。'],
    ['iterable','迭代器提前结束时的清理','自定义迭代器实现了 return()。for...of 在第一次循环中执行 break，通常会发生什么？','',['迭代器的 return() 会被调用以进行关闭','for...of 总会读完全部元素才执行 break','只调用 next()，绝不调用 return()','return() 仅在迭代器抛错时调用'],['break 提前离开迭代。','迭代协议有关闭过程。','return() 可用于释放关联资源。'],'for...of 提前退出时会尝试关闭迭代器，调用其 return() 方法。'],
    ['map-set','Map 的键不经字符串化','Map 分别写入数字 1 和字符串 "1"，最后 size 是多少？','const m=new Map(); m.set(1,"number"); m.set("1","text");',['2','1','0','抛 TypeError'],['Map 的键可以是任意值。','数字与字符串的类型不同。','它们不是同一个键。'],'Map 保留数字 1 与字符串 "1" 两个不同键，size 为 2。'],
    ['map-set','Set 保留首次插入顺序','对 Set 依次 add("a"), add("b"), add("a")，展开后是什么？','const set=new Set(); set.add("a"); set.add("b"); set.add("a"); [...set];',['["a","b"]','["a","b","a"]','["b","a"]','["a"]'],['重复元素不会新增位置。','Set 遍历遵循插入顺序。','再次 add 已有值不移动它。'],'Set 去重并保留首次插入顺序，再次添加 a 不改变顺序。'],
    ['weakmap-weakset','WeakMap 键必须是合适的引用值','下列哪种写入对 WeakMap 合法且可用来按对象身份缓存？','',['const key={id:1}; cache.set(key,"cached")','cache.set(1,"cached")','cache.set("user-1","cached")','cache.set(null,"cached")'],['WeakMap 主要用于对象键。','数字、字符串与 null 不能作为这里的键。','键身份由对象引用决定。'],'用对象作为 WeakMap 键可按身份缓存；原始数字、字符串和 null 不能作键。'],
    ['weakmap-weakset','值为 undefined 与键不存在','WeakMap 可把一个对象键显式映射到 undefined。怎样区分这个键是否存在？','const key={}; const cache=new WeakMap([[key,undefined]]);',['cache.has(key) 为 true；cache.get(key) 虽为 undefined 仍表示记录存在','cache.get(key) 为 undefined，所以记录不存在','cache.size 为 1，因此可证明任意 key 都存在','只能遍历 cache.keys() 检查'],['get 的结果不能区分缺失和显式 undefined。','has 查询这个具体键是否有记录。','WeakMap 无 size 或 keys 接口。'],'cache.has(key) 检查记录是否存在，与缓存值本身是否为 undefined 无关。'],
    ['weakmap-weakset','WeakSet 适合记录对象标记','需要标记“已处理过”的 DOM 节点，且不想仅因标记集合阻止节点回收。哪种结构最贴合？','',['WeakSet，以节点对象为成员','Set，以节点 id 字符串为成员','普通数组，永不删除节点','对象字面量，以节点转成的字符串为键'],['按对象身份标记。','无需遍历全部已处理节点。','弱集合不保活成员对象。'],'WeakSet 适合为对象保存不可枚举、无需计数的弱标记。'],
    ['keys-values-entries','不可枚举和 Symbol 属性是否进入 Object.entries','对象有一个可枚举字符串键 a、一个不可枚举字符串键 hidden、一个 Symbol 键 s。Object.entries 返回哪些项？','const s=Symbol("s"); const o={a:1,[s]:3}; Object.defineProperty(o,"hidden",{value:2});',['只有 [["a",1]]','包含 a、hidden、s 三项','包含 a 与 hidden 两项','包含 a 与 s 两项'],['Object.entries 只看自身可枚举字符串属性。','hidden 不可枚举。','Symbol 键也不会进入。'],'Object.entries 仅返回可枚举的自有字符串键值对，本例只有 a。'],
    ['keys-values-entries','Object.fromEntries 的覆盖行为','输入条目里两次出现相同字符串键 x。Object.fromEntries 的 x 最终是什么？','Object.fromEntries([["x",1],["x",2]]).x;',['2','1','[1,2]','undefined'],['条目按顺序写入对象。','同名属性后写覆盖先写。','不会自动合并成数组。'],'后一个 x=2 覆盖前一个 x=1，所以最终是 2。'],
    ['destructuring-assignment','解构重命名与默认值','下面得到的 userId 和 role 分别是什么？','const item={id:0}; const {id:userId,role="viewer"}=item;',['0、"viewer"','undefined、"viewer"','0、undefined','抛 SyntaxError'],['id:userId 表示重命名。','0 是有效值。','role 缺失时使用默认值。'],'userId 取得 id 的 0；缺失 role 使用默认字符串 viewer。'],
    ['destructuring-assignment','剩余属性仍是浅层引用','解构得到 rest 后修改 rest.settings.theme，原对象会怎样？','const source={id:1,settings:{theme:"light"}};\nconst {id,...rest}=source; rest.settings.theme="dark";',['source.settings.theme 也变成 "dark"','source.settings.theme 保持 "light"','rest.settings 自动成为不可变对象','解构 rest 时立即抛错'],['对象 rest 创建新的外层对象。','嵌套 settings 仍保存同一个引用。','修改其内部属性会被两边看到。'],'rest 是浅拷贝；嵌套 settings 仍共享，因此修改内部主题会影响 source。'],
    ['date','无效日期不能只看 instanceof','new Date("bad") 返回什么类型的值？要判断它是否有效，哪种办法可靠？','const d=new Date("bad");',['仍是 Date 对象；可检查 Number.isNaN(d.getTime())','返回 null；用 d===null 判断','立即抛 SyntaxError；用 try/catch 判断','返回字符串 Invalid Date；用 typeof 判断'],['构造器会创建 Date 对象。','内部时间值可为 NaN。','getTime 暴露该时间值。'],'无效日期仍是 Date 实例，但时间值为 NaN；检查 getTime 可区分。'],
    ['date','UTC 日期不能靠本地 getter 分组','事件时间戳要按 UTC 年月日分组，为什么不能直接用 getFullYear/getMonth/getDate？','',['这些 getter 使用运行环境本地时区，跨时区可能得到不同日期','这些 getter 总返回毫秒时间戳','这些 getter 只支持闰年','这些 getter 会改变原 Date 的时间戳'],['同一时间点在不同时区可属于不同日历日。','本地 getter 与 UTC getter 是不同系列。','分组规则必须明确时区。'],'本地 getter 依赖用户时区；UTC 分组应使用 UTC getter 或明确的 UTC 格式化。'],
    ['json','对象属性和数组元素中的 undefined','JSON.stringify 对对象属性值 undefined 与数组元素 undefined 的处理有何不同？','JSON.stringify({a:undefined}); JSON.stringify([undefined]);',['"{}" 与 "[null]"','"{\\"a\\":null}" 与 "[null]"','两者都抛错','"{}" 与 "[]"'],['对象中的该属性会被省略。','数组要保留位置。','数组中的 undefined 会写成 null。'],'对象属性值 undefined 会被省略；数组对应位置会变成 null。'],
    ['json','reviver 可恢复明确的日期字段','JSON.parse 得到的 createdAt 是字符串。若应用希望只把这个字段转换成 Date，哪种做法更明确？','',['用 reviver 按键名 createdAt 与格式验证后转换，并检查无效日期','假设 JSON.parse 自动把所有 ISO 字符串变 Date','直接对所有字符串调用 new Date','改写 JSON 文本中的所有引号'],['JSON 标准没有日期类型。','解析后默认是字符串。','reviver 可针对特定键进行转换，但仍需验证。'],'JSON.parse 默认不恢复 Date；可用 reviver 按字段与格式显式转换。']
  ];
  const indexes=new Map();
  for (const [lessonId,title,prompt,example,options,hints,explanation] of cases) {
    const index=(indexes.get(lessonId)||0)+1;
    indexes.set(lessonId,index);
    choice(`${lessonId}-depth-${String(index).padStart(2,'0')}`,lessonId,title,prompt,example,options,0,hints,explanation);
  }
}
