export function addEventDepthExercises({ choice }) {
  const cases = [
    ['introduction-browser-events','onclick 赋值会替换旧处理器','先给 button.onclick 赋函数 A，再给 button.onclick 赋函数 B，同时通过 addEventListener 注册 C。一次点击会运行哪些？','',['B 和 C','A、B 和 C','只有 B','只有 C'],['onclick 是一个可赋值的处理器槽。','第二次赋值覆盖 A。','addEventListener 的 C 独立保留。'],'第二次 onclick 赋值替换 A，但 addEventListener 注册的 C 仍存在。'],
    ['introduction-browser-events','用 AbortSignal 批量移除监听器','多个监听器注册时都传 {signal: controller.signal}。调用 controller.abort() 后会怎样？','',['这些监听器会被移除，无需逐个保留处理函数引用','只会移除最后注册的监听器','监听器继续运行直到页面刷新','abort 会立即触发这些监听器各执行一次'],['signal 可把监听器生命周期与控制器关联。','abort 会取消关联监听器。','不需要为这批监听器逐个调用 removeEventListener。'],'同一 AbortSignal 可管理一组监听器；abort 后关联监听器不再响应事件。'],
    ['bubbling-and-capturing','祖先捕获阶段提前停止传播','祖先 div 的 click 捕获监听器调用 stopPropagation。点击深层 button 时，button 自己的 click 监听器通常会运行吗？','',['不会；事件在到达目标前被祖先截断','会；stopPropagation 只影响冒泡阶段','会；目标监听器总是先于捕获监听器','只会运行 button 上的冒泡监听器'],['捕获从祖先向目标前进。','在祖先上停止传播会阻止继续走到目标。','stopPropagation 不只可在冒泡阶段调用。'],'捕获阶段在祖先停止传播，事件无法继续到达深层 button。'],
    ['bubbling-and-capturing','移除捕获监听器时匹配阶段','同一 handler 通过 addEventListener("click",handler,{capture:true}) 注册。下列移除方式哪项匹配？','',['removeEventListener("click",handler,{capture:true})','removeEventListener("click",handler)','removeEventListener("click",()=>handler(),{capture:true})','button.onclick=null'],['函数对象要相同。','捕获标志也要一致。','省略第三参数默认匹配非捕获监听器。'],'移除监听器时需要相同事件类型、函数引用和 capture 标志。'],
    ['event-delegation','在表格中防止处理外层嵌套表格','外层 table 委托处理 td 点击，某 td 内还嵌套子 table。取得 event.target.closest("td") 后，怎样避免把子表格的 td 当成外层单元格？','',['确认 td.closest("table") === outerTable','只确认 outerTable.contains(td)','只检查 td.tagName === "TD"','把监听器从 table 移到 document'],['外层 table 也包含嵌套表格的 td。','contains 无法区分属于哪个表格。','检查最近的 table 是否正是外层表格。'],'td.closest("table") 能确定该单元格所属的最近表格，避免处理嵌套表格单元格。'],
    ['event-delegation','动态删除后仍由容器接收新项目','列表使用父容器事件委托。删除旧 li 后插入全新的 li，为什么不必重新给新 li 注册 click？','',['监听器在仍存在的父容器上，冒泡会把新 li 的点击送来','新 li 自动复制了旧 li 的监听器','所有 li 天生都有相同 click 回调','删除旧 li 会把监听器转给下一个 li'],['事件监听器没有绑定在单个 li 上。','新 li 的点击会沿祖先链冒泡。','稳定容器仍在接收事件。'],'委托依赖父容器和事件冒泡，动态子项无需各自注册监听器。'],
    ['default-browser-action','passive 监听器不能取消滚动','给 touchmove 注册 {passive:true} 的监听器，回调里调用 preventDefault() 想阻止滚动。哪项最准确？','',['不会按预期取消默认滚动；passive 声明不取消默认行为','一定取消滚动，因为 preventDefault 永远有效','会阻止事件冒泡但继续滚动','只要 return false 就能补救'],['passive 表示处理器承诺不取消默认动作。','浏览器可据此优化滚动。','需要取消时不能把该监听器声明为 passive。'],'passive 监听器中的 preventDefault 不会有效取消默认滚动。'],
    ['default-browser-action','addEventListener 中 return false 的作用','链接通过 addEventListener("click",()=>false) 注册监听器。点击后，仅返回 false 能否阻止默认导航？','',['不能；应对事件调用 preventDefault()','能；与 HTML 内联 onclick 完全相同','能；但只对外链有效','不能；需要调用 stopPropagation()'],['不同事件注册方式的 return false 语义不同。','addEventListener 不把返回值当成取消信号。','preventDefault 明确取消可取消事件的默认行为。'],'addEventListener 的回调返回 false 不取消默认导航，应使用 event.preventDefault()。'],
    ['default-browser-action','父级检查子级是否已取消默认行为','子按钮监听器调用 preventDefault()；事件冒泡到父容器。父容器希望跳过已取消的动作，应检查哪个属性？','',['event.defaultPrevented','event.bubbles','event.target.disabled','event.isTrusted'],['取消状态会记录在事件对象上。','冒泡并不因 preventDefault 自动停止。','父处理器可读取 defaultPrevented。'],'defaultPrevented 表示默认行为已被某个处理器取消，父容器可据此避免重复动作。'],
    ['dispatch-events','自定义事件默认不冒泡','new CustomEvent("update",{detail:{id:1}}) 在子元素派发，父元素只注册 update 监听器。默认情况下父元素能收到吗？','',['不能；需显式设置 bubbles:true','能；所有 CustomEvent 默认冒泡','能；因为 detail 是对象','不能；CustomEvent 永远不能冒泡'],['CustomEvent 的 bubbles 选项默认为 false。','父级通常靠冒泡接收子元素事件。','派发时显式指定 bubbles:true。'],'自定义事件默认不冒泡，父容器监听器要接收需设置 bubbles:true。'],
    ['dispatch-events','dispatchEvent 同步运行监听器','代码先 push("before")，调用 element.dispatchEvent(event)，随后 push("after")；监听器中 push("listener")。数组顺序通常是什么？','',['before、listener、after','before、after、listener','listener、before、after','before、after，监听器不会运行'],['dispatchEvent 是同步派发。','监听器会在调用返回前运行。','之后才执行 after。'],'dispatchEvent 同步调用监听器，因此顺序是 before、listener、after。'],
    ['dispatch-events','CustomEvent 的 detail 是同一个对象引用','const payload={count:1}; const e=new CustomEvent("update",{detail:payload}); 派发前把 payload.count 改为 2。监听器读取 e.detail.count 通常得到什么？','',['2；detail 保留对象引用','1；创建事件时自动深拷贝','undefined；detail 只能是字符串','抛 TypeError；事件不能携带对象'],['detail 不会自动深拷贝任意对象。','payload 和 e.detail 指向同一对象。','派发前的改动可被监听器看到。'],'detail 保留 payload 对象引用，监听器读取到更新后的 count=2。']
  ];
  const indexes = new Map();
  for (const [lessonId, title, prompt, example, options, hints, explanation] of cases) {
    const index = (indexes.get(lessonId) || 0) + 1;
    indexes.set(lessonId, index);
    choice(`${lessonId}-depth-${String(index).padStart(2, '0')}`, lessonId, title, prompt, example, options, 0, hints, explanation);
  }
}
