export function addBrowserReviewExercises({ choice }) {
  const variants = [
    ['modifying-document','同一节点不能追加两次','代码把同一个 li 先 append 到 #a，再 append 到 #b。最终该 li 在哪里？','const li=document.createElement("li");\na.append(li);\nb.append(li);',['只在 #b 中；第二次 append 会移动节点','同时在 #a 和 #b 中','只在 #a 中','两个容器都没有'],['DOM 节点只有一个父节点。','append 已存在节点会移动它。','要复制需 cloneNode。'],'第二次 append 会把同一节点从 #a 移到 #b，不会复制。'],
    ['browser-environment','宿主全局对象的差异','一个函数既可能在浏览器主线程，也可能在 Web Worker 中运行。怎样避免错误地把 window 当成普遍存在的全局入口？','',['使用 globalThis 访问通用全局对象，并按环境检查特定 API','所有环境都直接使用 window','把 window 定义成字符串','把 document 作为 globalThis 的别名'],['window 属于浏览器窗口环境。','Worker 没有页面 window/document。','globalThis 提供跨环境的全局引用。'],'globalThis 是跨环境获取全局对象的方式；DOM 等宿主 API 仍要按当前环境检查是否存在。'],
    ['dom-nodes','空白文本节点影响遍历','给一个元素设置 innerHTML="  <span>A</span>" 后，为什么 firstChild 不一定是 span？','',['前导空格可形成文本节点，firstElementChild 才跳过非元素节点','innerHTML 总会删除空格','span 一定会被放到最后','firstChild 只能返回属性节点'],['DOM 保留文本节点。','前导空格也是文本。','Element 专用遍历只考虑元素。'],'空白字符可能成为文本节点，所以 firstChild 可指向文本；firstElementChild 指向第一个元素子节点。'],
    ['dom-navigation','向上寻找包含当前元素的容器','按钮深嵌在卡片里，点击时要定位最近的 .card 祖先，且按钮本身也可能带 .card。最直接的方法是什么？','',['event.target.closest(".card")','event.target.parentElement.parentElement 固定向上两层','document.querySelector(".card")','event.target.children[0]'],['嵌套层数可能变化。','closest 从当前元素开始向祖先查找。','仍应确认结果属于预期根容器。'],'closest 按选择器寻找当前元素或最近祖先，避免依赖固定 DOM 层级。'],
    ['searching-elements-dom','静态集合与动态 DOM','const nodes=document.querySelectorAll(".item") 后，新加一个 .item。旧 nodes.length 会自动增加吗？','',['不会；querySelectorAll 返回静态 NodeList，需要重新查询','会；所有 DOM 集合都实时更新','只有设置 innerHTML 才会增加','nodes 会变成 null'],['不是所有 DOM 集合都具有相同实时性。','querySelectorAll 返回静态结果。','重新查询可得到新增项。'],'querySelectorAll 的 NodeList 是静态快照。动态新增元素不会改变旧集合长度。'],
    ['basic-dom-node-properties','textContent 与 innerHTML 的输出差异','元素内部是 <b>Hi</b>。分别读取 textContent 与 innerHTML，最接近什么？','',['"Hi" 与 "<b>Hi</b>"','都返回 "Hi"','都返回 HTML 标签字符串','textContent 返回 b 元素对象'],['textContent 汇总文本。','innerHTML 序列化内部标记。','读取与写入语义也不同。'],'textContent 读取纯文本 Hi；innerHTML 读取包含标签的 HTML 字符串。'],
    ['dom-attributes-and-properties','attribute 与 property 的当前值','输入框 HTML 初始 value="A"，用户在页面输入了 B。读取 input.value 与 input.getAttribute("value") 通常分别得到什么？','<input value="A">',['"B" 与 "A"','"A" 与 "B"','都是 "B"','都是 "A"'],['属性可保存初始标记值。','DOM property 反映控件当前状态。','用户输入通常更新 value property。'],'input.value 表示当前输入值 B；value 特性通常仍是初始标记 A。'],
    ['styles-and-classes','类名和内联样式的职责','需要让很多卡片统一切换主题，并保留各卡片原有 class。哪种方式更稳妥？','',['对每张卡片使用 classList.add/remove("dark")，规则写在 CSS 中','给每张卡片设置 className="dark" 覆盖所有类','循环给每个样式属性写内联值','直接修改 document.styleSheets 中随机规则'],['className 赋值会替换已有类。','classList 可增删单个类。','统一视觉规则更适合放在 CSS。'],'classList 可以保留其他类并切换主题类；样式细节由 CSS 统一维护。'],
    ['size-and-scroll','滚动条对可见宽度的影响','要测量元素内部可用于内容的宽度（含 padding，不含边框与纵向滚动条），应优先看哪个属性？','',['clientWidth','offsetWidth','scrollTop','getAttribute("width")'],['clientWidth 是内部可见区域宽度。','offsetWidth 包含边框。','scrollTop 是滚动位置，不是宽度。'],'clientWidth 表示元素内侧的可见宽度，包含 padding，但不含边框及垂直滚动条占据的宽度。'],
    ['size-and-scroll-window','视口与整页高度','想判断文档内容是否比当前可见窗口高。下面哪组值更贴近要比较的量？','',['文档滚动高度与窗口可见高度','window.scrollY 与 document.title','元素的 className 与 style','history.length 与 screen.width'],['一个量是整页内容高度。','另一个量是视口高度。','scrollY 只是当前滚动位置。'],'比较文档滚动高度与视口高度可判断页面是否需要纵向滚动；不能拿滚动位置当内容高度。'],
    ['coordinates','把鼠标视口坐标换成文档坐标','mousemove 事件给出 clientY=40，窗口 scrollY=260。该指针相对文档顶部的 y 约为多少？','',['300','40','220','260'],['clientY 相对视口。','scrollY 是视口相对文档的偏移。','两者相加。'],'文档坐标约为 40+260=300。'],
    ['introduction-browser-events','监听器选项与移除','同一个 handler 先以 capture:true 注册。移除时只写 removeEventListener("click",handler) 会怎样？','',['通常无法移除捕获阶段注册的监听器；移除时也要匹配 capture','一定成功，因为只比较函数','会删除所有 click 监听器','会自动改成 once:true'],['移除监听器要匹配类型、函数与捕获标记。','省略第三参数通常表示 capture:false。','应传 true 或 {capture:true}。'],'removeEventListener 的捕获标记必须与注册时匹配，否则捕获监听器仍在。'],
    ['bubbling-and-capturing','stopPropagation 不影响同元素其他监听器','按钮上注册了两个 click 监听器。第一个调用 stopPropagation()，第二个会怎样？','',['通常仍会在同一元素上运行；若要阻止后续同元素监听器需 stopImmediatePropagation()','一定不会运行','会改在捕获阶段运行','会自动移除'],['stopPropagation 主要阻止继续向其他节点传播。','同一目标上的其他监听器是另一回事。','stopImmediatePropagation 有更强的停止语义。'],'stopPropagation 不会自动取消同一元素后续监听器；stopImmediatePropagation 才会阻止它们继续运行。'],
    ['default-browser-action','取消默认动作的前提','在被动 passive:true 的 wheel 监听器里调用 preventDefault()，通常会怎样？','',['不能有效阻止默认滚动；需要重新设计监听选项与交互','一定阻止滚动','自动把监听器改成 passive:false','把事件改成 click'],['passive 表示承诺不阻止默认行为。','浏览器可以据此优化滚动。','确需取消时不能使用被动监听器。'],'passive:true 监听器中的 preventDefault 不能有效取消默认滚动；应按需要使用非被动监听并控制性能成本。'],
    ['dispatch-events','程序触发事件与真实用户操作','代码用 button.dispatchEvent(new MouseEvent("click")) 触发监听器。event.isTrusted 通常是什么？','',['false，脚本创建的事件不属于浏览器派发的可信用户事件','true，因为事件类型是 click','undefined，因为 MouseEvent 没有这个属性','只要 bubbles:true 就是 true'],['事件由脚本创建。','isTrusted 用于区分用户代理派发与脚本派发。','不要把它当唯一授权机制。'],'脚本构造并派发的事件通常 isTrusted 为 false；权限判断仍应在可靠边界进行。'],
    ['mouse-events-basics','点击次数与事件类型','应用想区分单击与双击。dblclick 的触发时机与 click 的关系最准确的是？','',['双击操作通常也会先产生 click 事件，不能假设 dblclick 替代它们','dblclick 会取消所有 click','dblclick 只在右键发生','click 只能发生一次'],['浏览器事件按用户动作依次触发。','双击通常包含两次点击。','单击动作若需延迟判定，要设计处理策略。'],'双击通常伴随 click 事件。若单击和双击逻辑互斥，不能只分别监听而忽略时序。'],
    ['mousemove-mouseover-mouseout-mouseenter-mouseleave','进入子元素时的 relatedTarget','父元素监听 mouseout，指针只是从父元素区域移到它的子元素。怎样避免把这次移动当成真正离开父元素？','',['检查 event.relatedTarget 是否仍被父元素包含','只检查 event.clientX 是否大于 0','所有 mouseout 都表示离开父元素','把监听器改成 keydown'],['mouseout 在父子边界也可能发生。','relatedTarget 表示指针去往的元素。','仍在父容器内时不算真正离开。'],'检查 relatedTarget 是否位于父元素内部，可以过滤父子节点之间的移动。'],
    ['mouse-drag-and-drop','拖动中鼠标离开元素','自定义拖动仅在被拖元素上监听 mousemove。快速移动时指针离开元素，拖动可能中断。更可靠的基本做法是什么？','',['拖动期间在 document 等稳定范围监听移动与抬起，并在结束时清理','每次移动都重新创建元素','只把 z-index 设为负数','把元素设置 display:none'],['指针可能移出被拖元素。','监听范围应覆盖整个拖动过程。','结束时移除临时监听器。'],'把临时移动/抬起监听器放在稳定的更大范围，拖动结束后清理，能避免离开元素时失去事件。'],
    ['pointer-events','指针捕获为何有用','拖动组件在 pointerdown 时调用 setPointerCapture(event.pointerId)。主要作用是什么？','',['后续该指针事件即使移出元素也会继续发送给捕获元素','把指针位置固定在原地','取消其他所有指针','自动阻止页面缩放'],['拖动中指针可能离开组件区域。','捕获改变事件的目标路由。','仍需在 pointerup/cancel 处理结束状态。'],'指针捕获让指定指针后续事件继续交给捕获元素，适合拖动等连续交互。'],
    ['keyboard-events','输入法组合期间的快捷键','编辑器在 keydown 时处理 Enter 提交，但中文输入法选词也可能产生键盘事件。怎样减少误提交？','',['检查 event.isComposing 等组合输入状态，再决定是否提交','所有 keydown 都直接提交','只检查 event.repeat','只要 key 是 Enter 就永远提交'],['输入法正在组合文本时不应贸然提交。','KeyboardEvent 提供组合状态线索。','还要按组件交互语义处理。'],'处理 Enter 快捷键时应考虑输入法组合状态，避免把选词确认误当表单提交。'],
    ['onscroll','降低滚动回调的布局抖动','scroll 回调里反复交替读取尺寸和写入 style。哪种改法更可能降低布局抖动？','',['批量读取所需布局值，再集中写入；必要时用 requestAnimationFrame 合并更新','在每次循环中再多读一次 offsetWidth','把所有逻辑放进同步 while 循环','给每个子元素单独注册多个 scroll 监听器'],['读布局值可能触发布局计算。','读写交替会造成重复计算。','批处理并按帧更新更稳妥。'],'先读后写，尽量减少强制同步布局；高频滚动更新可按帧合并。'],
    ['form-elements','同名控件不一定只有一个','表单有两个 name="tag" 的复选框。用 form.elements.namedItem("tag") 读取时，为什么不能总假设得到单个 input？','',['同名控件可能组成 RadioNodeList 等集合，需要按类型处理','浏览器会随机删除一个','namedItem 只能读取 id','复选框不能出现在表单里'],['同一个 name 可对应多个控件。','返回值可能是集合式对象。','不能直接当作单个输入框取 value。'],'多个同名表单控件会影响 elements 的返回形式。代码应处理单个控件与同名集合的差异。'],
    ['focus-blur','程序聚焦为何没成功','代码在 input 上调用 focus()，但它位于 display:none 的容器里。最可能发生什么？','',['元素不可见且不可聚焦，调用不会形成预期焦点','浏览器会自动显示容器','focus 会把容器移动到 body','focus 会直接抛出 SyntaxError'],['焦点需要元素处于可交互布局状态。','隐藏元素通常不能成为焦点。','先确保元素可见且允许聚焦。'],'display:none 下的控件通常无法取得实际焦点；应在展示后聚焦，并检查当前 document.activeElement。'],
    ['events-change-input','程序设置 value 是否自动触发 input','执行 input.value="new" 后，是否能依赖浏览器自动派发 input 事件来更新业务状态？','',['不能；脚本赋值通常不自动派发 input，必要时显式调用同步逻辑或派发事件','能，所有 property 赋值都会派发 input','只有 value 是数字时会','只有设置 className 时会'],['input 事件主要来自用户编辑。','程序直接赋值与用户输入不是同一事件来源。','更新状态应主动调用同步代码。'],'脚本设置 value 通常不会自动触发 input 事件。业务状态不应仅靠等待该事件更新。'],
    ['forms-submit','requestSubmit 与 submit 的区别','代码想以编程方式触发表单提交，并保留原生校验与 submit 事件。优先用什么？','',['form.requestSubmit()','form.submit()','form.dispatchEvent(new Event("click"))','form.reset()'],['原生 submit() 会跳过部分正常提交流程。','requestSubmit 更接近激活提交按钮。','它会触发校验和 submit 事件。'],'requestSubmit 会走原生提交前校验与 submit 事件流程；直接 submit() 会绕过这些步骤。'],
    ['onload-ondomcontentloaded','延迟脚本与 DOMContentLoaded','页面使用 defer 脚本读取 DOM。DOMContentLoaded 会在该 defer 脚本执行前还是执行后触发？','<script defer src="app.js"></script>',['通常在 defer 脚本执行后触发','总在它执行前触发','完全随机','只有图片下载完才能触发'],['defer 脚本会在解析后执行。','DOMContentLoaded 需要等待这些延迟脚本。','图片加载通常不构成同样的等待条件。'],'DOMContentLoaded 通常在 HTML 解析及 defer 脚本执行后触发。'],
    ['script-async-defer','async 脚本的顺序风险','页面按顺序放置两个 async 外部脚本，第二个依赖第一个定义的变量。主要风险是什么？','',['async 按下载完成时机执行，不能保证文档顺序','async 保证严格文档顺序','async 永远不会在 DOMContentLoaded 前运行','async 只支持内联脚本'],['async 下载与解析并行。','执行时机取决于资源到达。','依赖顺序的脚本不应直接这样安排。'],'async 脚本的执行顺序不保证与标签顺序一致，因此直接依赖前一个脚本容易产生竞态。'],
    ['onload-onerror','脚本 load 不等于业务成功','动态 script 的 load 事件触发后，是否足以证明脚本里的业务初始化函数执行成功？','',['不一定；load 说明资源加载完成，脚本执行中的业务错误还需单独处理','一定，load 包含所有异步业务结果','不一定，但 error 事件会自动捕获所有业务异常','只有脚本放在 head 才能证明'],['资源加载与业务逻辑是不同层次。','脚本可能加载成功却在执行中报错。','业务初始化应有明确成功/失败信号。'],'script load 只能说明资源层面成功加载，不能替代运行时错误处理或业务初始化确认。'],
    ['mutation-observer','观察回调何时批量收到变更','连续同步 append 两个子节点后，MutationObserver 回调通常如何收到通知？','',['在当前同步代码结束后异步收到记录，可能一次回调含多条 mutation 记录','每次 append 前同步执行回调','只会看到最后一个变更','必须手动调用 observer.flush()'],['观察器不会在每次 DOM 操作中同步重入。','变更记录可被批量交付。','回调里检查 records。'],'MutationObserver 的记录通常在同步代码后批量交付，回调可一次收到多个变更记录。'],
    ['selection-range','Range 与用户当前选择','代码创建 Range 并设置边界，但页面没有显示选中高亮。还需要做什么？','const range=document.createRange();\nrange.selectNodeContents(element);',['取得 window.getSelection()，清除旧范围并 addRange(range)','只调用 range.toString()','把 range 赋给 element.value','给 element 添加 selected 类就一定同步用户选择'],['Range 只是一个范围对象。','用户当前选择由 Selection 管理。','把 Range 加入 Selection 才会显示选择。'],'Range 描述边界；将其加入当前 Selection 后，浏览器才把它作为用户可见选择。'],
    ['event-loop','微任务不能打断长同步任务','同步循环执行两秒，中间已经排队的 Promise.then 回调会何时运行？','Promise.resolve().then(()=>log("micro"));\nwhile (Date.now()<end) {}',['循环结束后，当前任务让出执行权时','循环中每 16ms 自动运行','在 Promise.resolve 调用前','永远不会运行'],['JavaScript 主线程执行当前同步任务。','微任务要等当前调用栈清空。','长任务会拖延响应和微任务。'],'同步循环占用主线程期间，微任务无法插入执行；要等当前任务结束后才处理。']
  ];
  for (const [lessonId,title,prompt,example,options,hints,explanation] of variants) {
    choice(`${lessonId}-review-01`,lessonId,title,prompt,example,options,0,hints,explanation);
  }
}
