// Original teaching notes. External works are linked for further reading, not copied here.
export const sources = {
  overview: 'https://www.xiaolincoding.com/network/',
  journey: 'https://www.xiaolincoding.com/network/1_base/what_happen_url.html',
  model: 'https://www.xiaolincoding.com/network/1_base/tcp_ip_model.html',
  os: 'https://www.xiaolincoding.com/network/1_base/how_os_deal_network_package.html',
  ip: 'https://www.xiaolincoding.com/network/4_ip/ip_base.html',
  ping: 'https://www.xiaolincoding.com/network/4_ip/ping.html',
  tcp: 'https://www.xiaolincoding.com/network/3_tcp/tcp_interview.html',
  tcpFeature: 'https://www.xiaolincoding.com/network/3_tcp/tcp_feature.html',
  http: 'https://www.xiaolincoding.com/network/2_http/http_interview.html',
  httpOptimize: 'https://www.xiaolincoding.com/network/2_http/http_optimize.html',
  rsa: 'https://www.xiaolincoding.com/network/2_http/https_rsa.html',
  ecdhe: 'https://www.xiaolincoding.com/network/2_http/https_ecdhe.html',
  httpsOptimize: 'https://www.xiaolincoding.com/network/2_http/https_optimize.html',
  http2: 'https://www.xiaolincoding.com/network/2_http/http2.html',
  http3: 'https://www.xiaolincoding.com/network/2_http/http3.html',
  websocket: 'https://www.xiaolincoding.com/network/2_http/http_websocket.html',
  rpc: 'https://www.xiaolincoding.com/network/2_http/http_rpc.html',
  httpSpec: 'https://www.rfc-editor.org/rfc/rfc9110.html',
  cacheSpec: 'https://www.rfc-editor.org/rfc/rfc9111.html',
  tcpSpec: 'https://www.rfc-editor.org/rfc/rfc9293.html',
  tlsSpec: 'https://www.rfc-editor.org/rfc/rfc8446.html',
  h3Spec: 'https://www.rfc-editor.org/rfc/rfc9114.html',
  devtools: 'https://developer.chrome.com/docs/devtools/network/reference',
  cookies: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Set-Cookie',
  cors: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS',
  csrf: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html',
  xss: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html',
  authorization: 'https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html',
  authentication: 'https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html',
};

const raw = [
  { title: '一张网页是怎么出现的', summary: '先看全程，再拆开每一段。', lessons: [
    ['谁在通信', '分清浏览器、源站、代理与 CDN 的角色。', '打开网页像一次接力：浏览器发起请求，沿途可能经过代理或缓存，最终由某个服务给出响应。同一页的资源也可能来自不同域名。', 'journey', '1.1'],
    ['读懂网址', '拆出协议、主机、端口、路径、查询与片段。', '网址既指出去哪里，也说明要哪份资源。片段由浏览器在本地处理，不会随 HTTP 请求目标发送。', 'journey', '1.7'],
    ['网络为什么分层', '说清不同层各自处理的问题。', '应用层表达想获取什么，传输层处理端到端通信，网络层寻找目标，链路层负责当前这一跳。分层让变化局限在相关部分。', 'model', '1.3'],
    ['一次访问的时间线', '排列 DNS、连接、请求与页面资源加载。', '典型的新连接先定位地址，再建立传输连接与安全会话，随后交换 HTTP 消息。缓存和连接复用会让实际路径变短。', 'journey', '1.4'],
    ['第一次看 Network 面板', '从浏览器记录中找到主文档和后续资源。', 'Network 记录是观察浏览器网络行为的证据。先区分文档、脚本、图片，再看状态、大小与时间，避免仅凭页面症状猜测。', 'devtools', '—'],
  ]},
  { title: '地址、DNS 与寻路', summary: '搞清数据怎样找到目标服务。', lessons: [
    ['IP 地址', '区分域名与 IPv4、IPv6 地址。', '域名便于人记忆，IP 地址用于网络层定位。一个域名可能解析到多个地址，地址也可能随网络和时间改变。', 'ip', '1.4'],
    ['局域网与 MAC 地址', '理解本地一跳如何交付数据。', '跨网络通信也要先把帧交给本地下一跳。链路层地址服务于这一跳，不等于远端网站的 IP 地址。', 'ip', '1.4'],
    ['子网与默认网关', '判断目标是否在本地网络。', '子网前缀帮助设备判断目标能否直接到达。目标不在本地时，数据通常先交给默认网关。', 'ip', '1.4'],
    ['路由与 NAT', '追踪跨网络转发与地址转换。', '路由器根据目标地址决定下一跳。NAT 让内部地址与外部通信关联起来，但不会代替应用层身份认证。', 'ip', '1.4'],
    ['DNS 记录', '知道域名查询可能返回什么信息。', 'DNS 回答的是名称相关信息，不直接提供网页内容。不同记录承担地址、别名和其他不同用途。', 'journey', '1.5'],
    ['DNS 查询与缓存', '解释首次和再次访问的差异。', '解析结果可能来自浏览器、系统或递归解析器的缓存。排障时应先确认用的是哪份结果及其有效期。', 'journey', '1.5'],
    ['端口与 Socket', '解释同一设备如何区分不同服务。', 'IP 负责定位主机，端口帮助定位服务；连接由两端地址和端口等信息共同区分。', 'os', '1.4'],
  ]},
  { title: 'TCP、UDP 与可靠传输', summary: '从报文时间线理解连接、丢包和流量。', lessons: [
    ['TCP 与 UDP', '根据通信需求选择传输方式。', 'TCP 提供有序的字节流与可靠交付机制；UDP 保留报文边界，应用可按需要自行设计可靠性。选择取决于场景，而非一个协议总比另一个好。', 'tcp', '1.4'],
    ['TCP 建立连接', '解释三次握手和双方的初始序列号。', '握手使双方确认彼此可达并协商连接状态。题目会让你根据 SYN 和 ACK 重建过程，而非背三句话。', 'tcp', '1.4'],
    ['TCP 关闭连接', '分析挥手、半关闭与 TIME_WAIT。', 'TCP 两个方向可以分别结束发送。最后的等待状态服务于可靠关闭与旧报文处理。', 'tcp', '1.4'],
    ['丢包与重传', '从序列号和确认号识别缺失数据。', '发送端不能把“已发送”当成“对方已收到”。确认、计时和重传共同处理途中丢失的报文。', 'tcpFeature', '1.4'],
    ['滑动窗口与流量控制', '区分能发送多少与接收端能接多少。', '接收窗口反映接收方当前可用空间。窗口变化会影响发送节奏，避免压垮接收方。', 'tcpFeature', '1.4'],
    ['拥塞控制', '识别网络拥堵而非接收端缓慢。', '即使接收方有空间，路径也可能承受不了大量数据。拥塞控制根据网络反馈调整发送量。', 'tcpFeature', '1.4'],
    ['连接异常', '定位超时、重置、断网与进程退出。', '连接故障需要看最后一个成功的步骤：没有建立连接、传输中断、还是对端明确拒绝。不同现象的处理方向不同。', 'tcp', '1.4'],
  ]},
  { title: '真正读懂 HTTP', summary: '从可读的 HTTP/1.1 报文建立语义。', lessons: [
    ['请求与响应', '区分资源请求与服务器的处理结果。', '客户端发送请求，服务器给出响应；状态码描述本次请求的结果，响应体承载内容或错误说明。', 'http', '2.1'],
    ['请求目标', '区分 URI、路径和查询参数。', '请求目标用于指向要操作的资源。路径与查询参数经常一起出现，但它们不是同一种语法角色。', 'http', '2.4'],
    ['HTTP 方法', '判断 GET、POST、PUT、DELETE、HEAD 的语义。', '方法表达对资源的意图。安全与幂等描述的是方法语义，不能只看请求有没有 body 或接口名字。', 'httpSpec', '2.5'],
    ['状态码', '按场景识别 1xx 到 5xx。', '先看状态码类别，再看具体含义。相近的两个码也可能有关键差异，例如“没有内容”和“内容未改变”。', 'http', '4.1'],
    ['请求报文', '构造请求行、首部与请求体。', 'HTTP/1.1 的文本报文让协议结构可见。请求行说明方法和目标，首部给出元数据，空行之后才是可选的消息体。', 'http', '3.2'],
    ['响应报文', '读懂状态行、首部与响应体。', '响应可以包含表示资源的数据，也可以只给出控制信息。题目会要求你根据完整报文判断浏览器接下来做什么。', 'http', '3.2'],
    ['内容类型与编码', '区分媒体类型、字符集与内容编码。', 'Content-Type 说明内容是什么，Content-Encoding 说明内容怎样编码。两者解决不同问题，不能互相替代。', 'http', '3.3'],
    ['部分内容与协商', '理解范围请求和不同表示的选择。', '客户端下载文件片段时可请求指定字节范围。服务器也可能根据请求条件选择语言、格式或压缩形式。', 'http', '3.5'],
    ['中间服务器', '区分虚拟主机、代理、网关与源站。', '一个 IP 可以服务多个域名，请求也可能经过中间节点。排障时要识别响应究竟由谁生成。', 'http', '5.1'],
  ]},
  { title: '首部、状态与缓存', summary: '把 Cookie、跳转和缓存放进真实请求链。', lessons: [
    ['常用首部', '按用途选择常见请求与响应字段。', '首部字段是上下文，不是孤立词汇。Host 指向目标主机，Content-Type 描述表示类型，Authorization 携带认证信息。', 'http', '6.1'],
    ['Cookie 与会话', '追踪浏览器如何保存并发送状态。', 'HTTP 请求本身不记住上一次请求。服务器可以通过 Cookie 标识会话，再根据服务端状态处理后续请求。', 'http', '2.8'],
    ['重定向', '追踪 Location 和跳转链。', '重定向告诉客户端下一步去哪里。分析时要同时看状态码、目标地址和后续请求，避免只看到最终页面。', 'http', '4.3'],
    ['缓存存了什么', '判断缓存键与响应能否复用。', '缓存通常按请求方法和目标 URI 等信息选取响应；存过一个响应不代表任意请求都能复用它。', 'cacheSpec', '5.3'],
    ['缓存新鲜度', '计算响应何时仍可直接使用。', '新鲜度决定已存响应在何时可以复用。强制刷新或请求指令可能改变一次访问的路径。', 'cacheSpec', '6.3'],
    ['协商缓存', '解释 ETag、条件请求与 304。', '本地响应过期后，客户端可带验证条件询问服务器。若表示未改变，服务器可让客户端继续使用已有内容。', 'cacheSpec', '5.3'],
    ['私有与共享缓存', '判断用户数据是否可被中间缓存复用。', '浏览器缓存面向一个使用者，共享缓存可能服务很多人。带身份的响应尤其需要明确缓存边界。', 'cacheSpec', '5.3'],
    ['旧页面故障', '定位资源更新后仍看到旧内容的原因。', '查出旧页面要核对 HTML、脚本、CDN 和浏览器各层的缓存策略，再决定应改文件名还是首部。', 'http', '5.3'],
  ]},
  { title: 'HTTPS 与 TLS', summary: '看懂信任、握手与错误提示。', lessons: [
    ['HTTPS 要解决什么', '从窃听、篡改、冒充理解安全目标。', '加密保护传输内容，完整性检测识别改动，身份认证帮助确认连接的另一端。三者缺一都可能留下问题。', 'rsa', '7.1'],
    ['加密与摘要的角色', '分清对称加密、公钥、签名和摘要。', '这些工具各自解决不同问题。握手常用公钥相关机制确认身份或协商秘密，大量应用数据用高效的对称加密保护。', 'rsa', '7.2'],
    ['证书与信任链', '检查域名、签发者与有效期。', '证书把公钥与身份信息关联起来。浏览器要验证证书链、名称和有效性，而不是看到“有证书”就信任。', 'rsa', '7.2'],
    ['TLS 握手总览', '按顺序理解协商、验证与密钥建立。', '握手让两端选择参数并确认共享的秘密。具体消息随 TLS 版本变化，核心问题始终是身份和密钥。', 'tlsSpec', '7.2'],
    ['密钥交换与前向保密', '说明临时密钥协商的意义。', '临时密钥协商可以减少长期密钥泄露带来的历史通信风险。题目重在判断风险，而非手算曲线。', 'ecdhe', '7.2'],
    ['证书错误', '从浏览器警告推断错误位置。', '域名不匹配、到期或不受信任都会影响验证。不能用“忽略警告”当成修复。', 'rsa', '7.2'],
    ['会话恢复', '理解再次连接为何可能更快。', '已建立过安全会话的双方可能复用部分信息，减少下次连接的工作；仍须遵守相应的安全限制。', 'httpsOptimize', '7.2'],
    ['HTTPS 排障', '区分混合内容、TLS 失败和 HTTP 错误。', 'HTTPS 页面加载 HTTP 子资源、握手失败和收到 5xx 是不同问题。先确认失败发生在连接的哪一层。', 'httpsOptimize', '7.2'],
  ]},
  { title: '现代 Web 通信', summary: '理解版本演进并为场景选协议。', lessons: [
    ['HTTP/1.1 连接', '解释持久连接和请求排队。', '复用连接能减少重复建连成本，但连接里的请求安排也会影响等待时间。不要把 HTTP 长连接和 TCP Keepalive 混为一谈。', 'httpOptimize', '2.7'],
    ['队头阻塞', '识别等待发生在哪一层。', '一个未完成的工作可能挡住后续工作。要准确说出阻塞发生在应用消息、单个连接还是传输层。', 'http2', '9.4'],
    ['HTTP/2 帧与流', '理解一个连接上并行的消息流。', 'HTTP/2 将消息编码成帧，并用流区分并发请求。应用语义仍属于 HTTP，改变的是传输表示。', 'http2', '9.4'],
    ['HTTP/2 首部压缩', '解释重复首部怎样减少开销。', '同站请求往往重复携带许多首部。压缩机制降低这些重复元数据的传输成本，但不等于压缩响应体。', 'http2', '9.4'],
    ['QUIC 入门', '知道 QUIC 在 HTTP/3 中承担的角色。', 'QUIC 在 UDP 之上提供连接、流和可靠传输等机制。HTTP/3 把 HTTP 语义映射到 QUIC。', 'http3', '—'],
    ['HTTP/3', '比较 HTTP/2 与 HTTP/3 的传输路径。', 'HTTP/3 保留 HTTP 请求与响应语义，改变底层连接方式。比较版本时先分清应用语义与传输机制。', 'h3Spec', '—'],
    ['WebSocket', '判断何时需要持久的双向消息通道。', '当双方需要随时发送消息时，WebSocket 提供了不同于逐次请求响应的通信模型。题目将比较消息流而非只背握手字段。', 'websocket', '9.3'],
    ['选择通信方案', '为表单、通知、聊天等场景解释取舍。', '普通请求、SSE、WebSocket 和 RPC 面向的交互方式不同。选择时关注谁发起消息、时延和连接成本。', 'rpc', '9.1'],
  ]},
  { title: '身份认证与 Web 安全', summary: '在真实登录流程中发现安全边界。', lessons: [
    ['认证与授权', '区分身份确认与操作许可。', '登录确认请求者是谁，授权决定其能访问哪些资源。已登录并不意味着可访问所有用户的数据。', 'authorization', '8.1'],
    ['认证方式', '比较基础认证、会话和令牌流程。', '不同方式传递凭据与维持状态的方式不同。历史方法要能识别，现代应用要根据威胁与体验选择。', 'authentication', '8.2'],
    ['Cookie 安全属性', '在登录场景中配置 Secure、HttpOnly、SameSite。', '这些属性分别约束传输、脚本访问和跨站发送行为；它们不能互相替代。', 'cookies', '6.7'],
    ['同源策略与 CORS', '判断跨域请求与预检的结果。', '浏览器同源策略约束脚本读取跨源响应。CORS 通过响应首部声明允许的跨源访问范围。', 'cors', '—'],
    ['CSRF', '识别浏览器自动携带凭据的风险。', '当攻击者诱导浏览器向已登录站点发起请求时，服务端不能只凭 Cookie 就认定这是用户本意。', 'csrf', '11.4.3'],
    ['XSS 与输出处理', '识别不可信数据进入页面的路径。', '把外部文本当作可执行页面内容会改变页面行为。输出时应按上下文正确处理不可信数据。', 'xss', '11.2.1'],
    ['综合安全配置', '查找 HTTPS、Cookie、认证和跨域配置的冲突。', '安全问题常来自多项配置同时作用。先画出凭据如何产生、保存、发送和校验，再修复错误边界。', 'authentication', '11.3'],
  ]},
  { title: '性能与故障排查', summary: '用证据定位慢、断、错。', lessons: [
    ['读瀑布图', '区分等待、下载、重定向与阻塞。', '瀑布图展示请求在时间轴上的活动。先找关键请求和依赖关系，再判断总耗时由哪一段决定。', 'devtools', '—'],
    ['慢在哪一段', '区分 DNS、建连、TLS、服务端处理和下载。', '“慢”是一个现象而非根因。不同阶段耗时高需要不同的调查路径。', 'devtools', '—'],
    ['HTTP 错误与连接错误', '区分收到错误响应与根本没收到响应。', '4xx 和 5xx 仍是 HTTP 响应；DNS、连接或 TLS 失败时可能根本没有 HTTP 状态码。', 'http', '4.1'],
    ['弱网与超时', '分析丢包、重试、慢下载与超时。', '超时发生在等待某一步过久之后。排障先问超时发生在连接前、响应前还是传输途中。', 'tcpFeature', '—'],
    ['代理与 CDN 链路', '定位错误是在浏览器、中间层还是源站。', '中间层会改变缓存、路径与错误表现。把每层可观察到的响应与日志连起来，才知道问题在哪。', 'http', '5.2'],
    ['基础排查工具', '读懂 ping、curl、简化抓包和系统收发路径。', '不同工具观察不同层：ping 测网络可达性，curl 检查 HTTP 交换，抓包展示传输细节。单个工具不能证明所有层正常。', 'ping', '—'],
    ['提出并验证优化', '先建立基线，再验证优化是否有效。', '一次只针对已识别的瓶颈采取措施，比较前后指标。缓存、连接复用和减少资源量适用于不同的瓶颈。', 'httpOptimize', '—'],
  ]},
  { title: '综合实战', summary: '独立提出假设、选择证据并解释修复。', lessons: [
    ['网页首次加载', '串起 DNS、IP、TCP、TLS、HTTP 和资源加载。', '完整的网页加载由多条请求组成。根据时间线逐层解释，让每个观察结果都有对应原因。', 'journey', '—'],
    ['用户看到旧页面', '联合排查浏览器缓存、CDN 和资源版本。', '先确认究竟哪个资源旧，再找它由哪一层提供。不能把强制刷新当作面向所有用户的长期修复。', 'cacheSpec', '—'],
    ['登录接口失败', '联合检查方法、状态码、Cookie、CORS 和会话。', '登录故障可能在浏览器发送凭据、服务端验证或跨源读取阶段。逐步验证比盲目改配置更可靠。', 'http', '—'],
    ['HTTPS 报错', '从证书、域名、连接和代理定位问题。', '先确认是否已建立 TCP 连接，再看 TLS 是否完成，最后看有没有 HTTP 响应。', 'rsa', '—'],
    ['弱网下重复提交', '分析超时、重试、连接中断与幂等性。', '用户未收到响应不代表服务端没有处理。重复提交前应判断操作是否可安全重试。', 'httpSpec', '—'],
    ['独立排障结业题', '用跨章节证据提出并检验假设。', '最终挑战只给症状和可选调查工具。先选择最有信息量的下一步，再从证据定位根因并解释修复。', 'overview', '—'],
  ]},
];

export const chapters = raw.map((chapter, chapterIndex) => ({
  id: `g${String(chapterIndex + 1).padStart(2, '0')}`,
  title: chapter.title,
  summary: chapter.summary,
  lessons: chapter.lessons.map(([title, goal, explain, sourceKey, book], lessonIndex) => ({
    id: `g${String(chapterIndex + 1).padStart(2, '0')}-l${String(lessonIndex + 1).padStart(2, '0')}`,
    title, goal, explain, source: sources[sourceKey], sourceLabel: sources[sourceKey].includes('xiaolincoding.com') ? '小林 coding · 对应文章' : sources[sourceKey].includes('mozilla.org') ? 'MDN · 对应文档' : sources[sourceKey].includes('owasp.org') ? 'OWASP · 安全指南（英文）' : sources[sourceKey].includes('rfc-editor.org') ? 'RFC · 协议原文（英文）' : 'Chrome DevTools · 操作指南', book,
  })),
}));
