import { mc, task, ok, bad, run } from './author.mjs';
const id=n=>`t04-l${String(n).padStart(2,'0')}`;
const m=(l,n,title,prompt,options,explanation,hints,extra={})=>mc(id(l),n,title,prompt,options,explanation,hints.split('｜'),extra);
const t=(l,n,title,prompt,files,solution,tests,explanation,hints,extra={})=>task(id(l),n,title,prompt,files,solution,tests,explanation,hints.split('｜'),extra);
export const questions=[
 m(1,1,'缺失与必需','Profile={name:string;nickname?:string}。严格空值检查下读取 nickname，类型是什么？',['string | undefined','string，因为对象存在','never，属性可能不存在','null | string'],'对象存在并不能证明可选字段存在。读取可选字符串必须考虑 undefined。','对象和属性是否存在是两个问题。｜问号允许省略该字段。｜读取时保留缺失的可能。'),
 m(1,2,'只读不是冻结','const source={id:1}; const view:Readonly<{id:number}>=source; source.id=2; view.id 的值是什么？',['2，只读视图没有复制或冻结对象','1，Readonly 自动生成快照','编译报错，source 也自动变成只读','undefined，只读字段不可读取'],'readonly 限制通过该类型进行写入，不控制其他可变别名，也不会生成运行时冻结逻辑。','两个变量指向同一对象。｜写入发生在可变的 source 上。｜只读类型不会生成副本。',{stage:'reason'}),
 m(1,3,'可选和带 undefined 的必需字段','A={name?:string}，B={name:string|undefined}。哪个描述正确？',['{} 能赋给 A，不能赋给 B','{} 能赋给两者','{} 不能赋给两者','只有 B 可以省略 name'],'可选性描述字段是否能省略；值类型含 undefined 不会自动让必需字段变成可选。','字段存在要求与值的范围分开判断。｜B 仍然要求有 name。｜B 可以显式写 name:undefined。'),
 t(1,4,'修复昵称显示','保留 User 的属性契约，修复 display：nickname 缺失时使用 name；空昵称保留为空字符串。',
  'export type User={readonly id:number;name:string;nickname?:string};\nexport function display(user:User):string{return user.nickname.toUpperCase();}',
  'export type User={readonly id:number;name:string;nickname?:string};\nexport function display(user:User):string{return user.nickname??user.name;}',[
   ok('可省略昵称','import {display,User} from "./main";const u:User={id:1,name:"林"};const s:string=display(u);'),
   bad('身份不可写','import {User} from "./main";const u:User={id:1,name:"林"};u.id=2;'),
   bad('姓名必需','import {User} from "./main";const u:User={id:1};'),
  ],'?? 仅在 null 或 undefined 时回退。这里可选字段读取可能为 undefined；空文本仍是有效昵称。','不要假设 nickname 一定存在。｜空字符串不能触发回退。｜使用空值合并选择昵称或姓名。',{
   runtime:[run('保留姓名和昵称语义','const {display}=load("main.js");equal(display({id:1,name:"Lin"}),"Lin");equal(display({id:1,name:"Lin",nickname:""}),"");equal(display({id:1,name:"Lin",nickname:"小林"}),"小林");')],
   wrongSolutions:[{'main.ts':'export type User={readonly id:number;name:string;nickname?:string};export function display(u:User):string{return u.nickname||u.name;}'}],
  }),
 m(1,5,'浅层只读的边界','type State={readonly settings:{theme:string}}。对 state.settings.theme 赋值会因为 readonly 而被禁止吗？',['不会，readonly 修饰的是 settings 属性的重新赋值','会，所有嵌套层都递归只读','只有赋相同字符串才允许','取决于是否使用 const 声明 state'],'只读修饰默认是浅层的。禁止替换 settings 不等于禁止修改 settings 指向的对象内部属性。','观察 readonly 具体修饰哪一个属性。｜内部 theme 没有只读修饰。｜若需深层约束，要在内部类型继续表达。',{stage:'reason'}),
 t(1,6,'设计创建参数','导出 CreateTask：readonly id:string、title:string、可选 dueAt:Date。实现 summary(task)，返回 title，不修改输入。',
  'export type CreateTask={id:string;title?:string;dueAt:Date};\nexport function summary(task:CreateTask):string{return task.title;}',
  'export type CreateTask={readonly id:string;title:string;dueAt?:Date};\nexport function summary(task:CreateTask):string{return task.title;}',[
   ok('无截止日期也合法','import {CreateTask,summary} from "./main";const a:CreateTask={id:"a",title:"读书"};const b:CreateTask={id:"b",title:"写字",dueAt:new Date()};const s:string=summary(a);'),
   bad('标题不能缺失','import {CreateTask} from "./main";const a:CreateTask={id:"a"};'),
   bad('ID 不可改写','import {CreateTask} from "./main";const a:CreateTask={id:"a",title:"读书"};a.id="b";'),
   bad('日期不能是文本','import {CreateTask} from "./main";const a:CreateTask={id:"a",title:"读书",dueAt:"今天"};'),
  ],'从需求分别推导必需性、可变性和值类型，不能用可选属性掩盖缺少必需数据的问题。','逐个检查三个字段的要求。｜title 必需，dueAt 可省略。｜readonly 只修饰 id。',{
   runtime:[run('标题原样返回且不修改输入','const {summary}=load("main.js");const task=Object.freeze({id:"a",title:"  读书  "});equal(summary(task),"  读书  ");')],
  }),
 m(1,7,'默认值的位置','Options={retries?:number}。函数希望省略时重试 3 次，显式 0 时不重试，哪种读取符合需求？',['options.retries ?? 3','options.retries || 3','Number(options.retries) || 3','把 retries 改成必需字段就会自动填 3'],'类型描述不会填充默认值，实际逻辑需要区分缺失和零。空值合并保留有效的零值。','重试零次有独立业务含义。｜|| 会把零当成需要回退的值。｜默认值需要运行时代码。',{stage:'reason'}),
 t(1,8,'迁移：更新可选字段','导出 Profile={readonly id:string;name:string;bio?:string} 和 Patch={name?:string;bio?:string}。实现 update(profile,patch)，返回新对象：patch 字段为 undefined 时保留原值，空文本正常覆盖。',
  'export type Profile={readonly id:string;name:string;bio?:string};\nexport type Patch={name?:string;bio?:string};\nexport function update(profile:Profile,patch:Patch):Profile{return {...profile,...patch};}',
  'export type Profile={readonly id:string;name:string;bio?:string};\nexport type Patch={name?:string;bio?:string};\nexport function update(profile:Profile,patch:Patch):Profile{return {...profile,name:patch.name??profile.name,bio:patch.bio??profile.bio};}',[
   ok('支持独立补丁','import {update} from "./main";update({id:"a",name:"Lin"},{});update({id:"a",name:"Lin"},{name:undefined,bio:""});'),
   bad('补丁不能修改 ID','import {update} from "./main";update({id:"a",name:"Lin"},{id:"b"});'),
   bad('姓名不能传数字','import {update} from "./main";update({id:"a",name:"Lin"},{name:3});'),
  ],'展开补丁会让显式 undefined 覆盖原字段；本题要求 undefined 表示不更新，因此应按字段处理。默认配置允许给可选字段显式传 undefined。','直接展开会覆盖哪些原值？｜每个字段要区别 undefined 与空字符串。｜在复制对象后为字段应用 ?? 回退。',{
   runtime:[run('合并不损失原值','const {update}=load("main.js");const p=Object.freeze({id:"a",name:"Lin",bio:"旧"});const n=update(p,{name:undefined,bio:""});equal(n,{id:"a",name:"Lin",bio:""});check(n!==p);equal(update(p,{}),p);equal(update(p,{name:"新"}).name,"新");')],
  }),
 m(1,9,'复测：删除必需属性','严格模式下，Item={title:string;note?:string}，为什么可以删除 note 却不能直接删除 title？',['删除 title 会破坏必需字段的类型契约','title 是字符串，字符串不能被删除','只有名称为 note 的属性可以删除','问号会自动在运行时删除字段'],'可选字段允许不存在，必需字段则承诺存在。严格检查会拒绝破坏该承诺的 delete 操作。','删除后的对象还满足原类型吗？｜note 缺失仍然合法。｜title 缺失不符合 Item。'),
 t(1,10,'复测：只读商品视图','导出 Product={readonly sku:string;price:number;label?:string}。实现 rename(product,label:string|undefined)，返回新的 Product，label 为 undefined 时删除 label 属性，否则设置为给定值；保留 sku 和 price。',
  'export type Product={readonly sku:string;price:number;label?:string};\nexport function rename(product:Product,label:string|undefined):Product{return {...product,label};}',
  'export type Product={readonly sku:string;price:number;label?:string};\nexport function rename(product:Product,label:string|undefined):Product{const next={...product};if(label===undefined){delete next.label;}else{next.label=label;}return next;}',[
   ok('商品支持可选标签','import {Product,rename} from "./main";const p:Product={sku:"a",price:10};const n:Product=rename(p,undefined);rename(p,"");'),
   bad('商品编号只读','import {Product} from "./main";const p:Product={sku:"a",price:10};p.sku="b";'),
   bad('价格必须存在','import {Product} from "./main";const p:Product={sku:"a"};'),
  ],'赋值 undefined 与删除属性的运行时结构不同；in 和 Object.keys 能区分。本题要求实际删除，同时通过复制保护原对象。','检查题目要求的是值缺失还是键不存在。｜复制后可以删除可选属性。｜undefined 分支 delete，其余分支赋值。',{
   runtime:[run('删除而非设置 undefined','const {rename}=load("main.js");const p=Object.freeze({sku:"a",price:10,label:"旧"});const n=rename(p,undefined);check(!("label" in n));equal(n,{sku:"a",price:10});check(n!==p);equal(rename(p,""),{sku:"a",price:10,label:""});equal(p.label,"旧");')],
  }),
 m(2,1,'两种对象声明','type User={id:string} 与 interface User{id:string} 在普通对象参数建模上，哪项正确？',['两者都能描述对象形状，调用者不必通过特定构造器创建','只有 interface 支持对象属性','type 必须搭配类才可使用','interface 会创建运行时校验器'],'普通对象结构都可以用两者表达。选择声明方式不会自动引入构造行为或运行时检查。','先看两种声明描述的成员。｜两者都可以作为函数参数的类型。｜类型声明本身不是构造器。'),
 m(2,2,'联合状态用什么声明','希望 Mode 直接表示 "view" | "edit"，哪种声明直接满足需求？',['type Mode = "view" | "edit"','interface Mode = "view" | "edit"','interface Mode { "view" | "edit" }','class Mode = "view" | "edit"'],'类型别名可以命名联合、原始类型和其他类型表达式；接口声明不是给任意类型表达式起别名的语法。','这里需要命名一个联合。｜不需要额外包装对象。｜type 可以直接放在联合表达式前。'),
 m(2,3,'重复接口的效果','同一模块里两次声明 interface Config，分别包含 host:string 与 port:number，最终 Config 是什么？',['同时要求 host 与 port 的接口','两个独立的同名类型，由编译器随机选一个','后者覆盖前者，只要求 port','自动变成 host 或 port 二选一的联合'],'兼容的同名接口声明会合并成员。合并不是覆盖，也不是联合。重复的类型别名则不能这样合并。','接口支持声明合并。｜两个不同字段会被累积。｜结果要求同时满足两部分。'),
 t(2,4,'修复非法联合接口','保留函数行为，将 Mode 改为能表示 "view" 或 "edit" 的合法类型声明。实现 canEdit，仅 edit 返回 true。',
  'export interface Mode = "view" | "edit";\nexport function canEdit(mode:Mode):boolean{return mode==="edit";}',
  'export type Mode="view"|"edit";\nexport function canEdit(mode:Mode):boolean{return mode==="edit";}',[
   ok('两个模式合法','import {Mode,canEdit} from "./main";const a:Mode="view";const b:Mode="edit";const result:boolean=canEdit(a);'),
   bad('不支持未知模式','import {Mode} from "./main";const mode:Mode="delete";'),
  ],'联合是 type 可以命名的类型表达式。函数仍负责实际业务判断，改类型声明不会自动实现权限逻辑。','报错来自声明语法而非比较运算。｜interface 不能直接等于联合。｜用 type 命名两个字面量的联合。',{
   runtime:[run('只允许编辑模式','const {canEdit}=load("main.js");equal(canEdit("view"),false);equal(canEdit("edit"),true);')],
  }),
 m(2,5,'扩展冲突何时暴露','interface Base{id:string}。尝试 interface Child extends Base{id:number}，会发生什么？',['在声明扩展关系时报告不兼容','Child 自动把 id 改为 string | number','Base 的 id 被全局替换成 number','只在创建 Child 实例时才可能报错'],'接口扩展要求继承成员保持兼容，不能用不兼容的属性类型覆盖。交叉类型遇到冲突的结果还可能不同，不能当成同一种覆盖机制。','子接口必须满足基接口。｜number 不能满足 string 字段。｜扩展关系本身已经冲突。',{stage:'reason'}),
 t(2,6,'为带身份的数据建模','导出 Entity 接口含 readonly id:string；导出 Article 类型，必须同时有 Entity 的字段与 title:string。声明方式自选。实现 heading(article)，返回 id + ": " + title。',
  'export interface Entity {readonly id:string}\nexport type Article={title:string};\nexport function heading(article:Article):string{return article.title;}',
  'export interface Entity {readonly id:string}\nexport interface Article extends Entity {title:string}\nexport function heading(article:Article):string{return article.id+": "+article.title;}',[
   ok('文章满足两部分契约','import {Article,Entity,heading} from "./main";const a:Article={id:"p1",title:"TS"};const entity:Entity=a;const s:string=heading(a);'),
   bad('身份不可缺失','import {Article} from "./main";const a:Article={title:"TS"};'),
   bad('标题不可缺失','import {Article} from "./main";const a:Article={id:"p1"};'),
   bad('继承身份只读','import {Article} from "./main";const a:Article={id:"p1",title:"TS"};a.id="p2";'),
  ],'extends 可以重用基础接口，交叉类型等其他结构正确的实现也可以满足需求。评判重点是公开契约和行为，不是与参考答案逐字相同。','Article 要同时拥有身份和标题。｜继承时要保留只读约束。｜heading 使用两个字段组成文本。',{
   runtime:[run('身份与标题都显示','const {heading}=load("main.js");equal(heading({id:"p1",title:"TS"}),"p1: TS");equal(heading({id:"x",title:""}),"x: ");')],
  }),
 m(2,7,'接口能不能描述函数','interface Formatter {(value:number):string} 是否是合法的函数类型？',['是，接口可包含调用签名','否，接口只能描述非函数对象','否，函数类型只能由 type 表达','是，但调用后返回接口实例'],'JavaScript 函数也是对象，接口可以描述调用签名及属性。不能将 type/interface 的选择简化为“函数只能用 type”。','观察括号中的调用参数和冒号后的返回值。｜这是一条调用签名。｜接口并不局限于普通数据字段。',{stage:'reason'}),
 t(2,8,'迁移：可调用的格式器','导出 Formatter，要求它既能以 (value:number) 调用并返回 string，又拥有 readonly unit:string。实现 formatWith(formatter,value)，返回 formatter(value) + formatter.unit。',
  'export type Formatter={readonly unit:string};\nexport function formatWith(formatter:Formatter,value:number):string{return String(value)+formatter.unit;}',
  'export interface Formatter {(value:number):string;readonly unit:string}\nexport function formatWith(formatter:Formatter,value:number):string{return formatter(value)+formatter.unit;}',[
   ok('可调用且携带元数据','import {Formatter,formatWith} from "./main";const f:Formatter=Object.assign((n:number)=>n.toFixed(1),{unit:"kg"});const s:string=formatWith(f,2);const out:string=f(2);'),
   bad('只有字段还不够','import {Formatter} from "./main";const f:Formatter={unit:"kg"};'),
   bad('调用结果必须为文本','import {Formatter} from "./main";const f:Formatter=Object.assign((n:number)=>n,{unit:"kg"});'),
   bad('单位属性不可写','import {Formatter} from "./main";declare const f:Formatter;f.unit="m";'),
  ],'调用签名和普通属性可以存在于同一个接口。实际函数对象可以用 Object.assign 附加元数据；格式化逻辑应委托给传入函数。','一个值要同时满足可调用与属性要求。｜接口内部可以同时写调用签名和字段。｜运行时记得真正调用 formatter。',{
   runtime:[run('使用传入的格式策略','const {formatWith}=load("main.js");const f=Object.assign(n=>n.toFixed(2),{unit:"kg"});equal(formatWith(f,2),"2.00kg");const g=Object.assign(n=>"["+n+"]",{unit:"m"});equal(formatWith(g,0),"[0]m");')],
  }),
 m(2,9,'复测：声明方式是否校验输入','将 API 响应的类型从 type User 改成 interface User，能自动拒绝服务器返回的错误字段吗？',['不能，两种声明都不会自动生成运行时校验','能，interface 自动验证 JSON','能，只要接口字段不是可选','不能，但改成 extends 就可以'],'这两种类型声明都会在输出 JavaScript 时被擦除。真实外部数据需要可执行的校验逻辑。','关注类型声明是否生成运行代码。｜服务器数据在编译之后才到达。｜自动校验需要额外实现。'),
 t(2,10,'复测：接口与联合协作','导出 Named 接口，包含 name:string；导出 NamedResult，合法形状只有 {ok:true;value:Named} 或 {ok:false;message:string}。实现 describe，成功返回姓名，失败返回 "失败: " 加 message。',
  'export interface Named {name:string}\nexport type NamedResult={ok:boolean;value?:Named;message?:string};\nexport function describe(result:NamedResult):string{return result.message??"";}',
  'export interface Named {name:string}\nexport type NamedResult={ok:true;value:Named}|{ok:false;message:string};\nexport function describe(result:NamedResult):string{return result.ok?result.value.name:"失败: "+result.message;}',[
   ok('两类完整结果','import {NamedResult,describe} from "./main";const a:NamedResult={ok:true,value:{name:"Lin"}};const b:NamedResult={ok:false,message:"缺失"};const s:string=describe(a);'),
   bad('成功必须带值','import {NamedResult} from "./main";const a:NamedResult={ok:true};'),
   bad('失败必须有原因','import {NamedResult} from "./main";const a:NamedResult={ok:false};'),
   bad('值必须符合接口','import {NamedResult} from "./main";const a:NamedResult={ok:true,value:{name:3}};'),
  ],'接口描述稳定的对象形状，别名命名多个对象分支组成的联合。两种方式可以协作，无需为了统一风格牺牲准确性。','先把 Named 定义为对象接口。｜成功和失败应该拆成两个分支。｜根据 ok 收窄后读取对应字段。',{
   runtime:[run('按状态读取数据','const {describe}=load("main.js");equal(describe({ok:true,value:{name:"Lin"}}),"Lin");equal(describe({ok:false,message:"缺失"}),"失败: 缺失");')],
  }),
 m(3,1,'联合元素与联合数组','(string|number)[] 和 string[]|number[] 的区别是什么？',['前者允许同一数组混合两类元素，后者要求数组满足某一个分支','完全相同，都禁止混合','前者只能放两个元素','后者自动按元素类型拆分成两个数组'],'括号决定联合发生在元素层还是数组层。混合数组通常不满足纯字符串数组或纯数字数组。','先定位方括号作用于什么。｜元素联合允许逐项选择候选。｜数组联合要求整体满足其中一种数组类型。'),
 m(3,2,'读取函数的参数','函数只遍历输入，既要接收 number[] 又要接收 readonly number[]，参数如何声明？',['readonly number[]','number[]','[number]','readonly number'],'只读数组参数不要求调用者授予写入能力，因此可接收可变和只读数组。反方向则可能让只读数据通过函数被修改。','实现是否需要 push 或 sort？｜只读参数只要求读取能力。｜可变数组也具备读取能力。'),
 m(3,3,'默认索引检查的局限','关闭 noUncheckedIndexedAccess 时，const items:number[]=[]; const x:number=items[0] 可以通过类型检查。这说明什么？',['默认检查没有保证该索引实际存在，运行时仍可能得到 undefined','空数组会自动补零','number[] 保证至少一项','访问索引会抛出 TypeError'],'普通数组允许为空。默认配置下索引类型可能乐观地给出元素类型，不能据此推断运行时一定存在。','数组类型没有非空承诺。｜编译通过不等于边界数据有效。｜需要边界逻辑或更严格的索引检查。'),
 t(3,4,'修复只读输入排序','实现 sorted(values:readonly number[]):number[]，按数值升序返回新数组，禁止修改输入。',
  'export function sorted(values:readonly number[]):number[]{return values.sort();}',
  'export function sorted(values:readonly number[]):number[]{return [...values].sort((a,b)=>a-b);}',[
   ok('两类数组都可读取','import {sorted} from "./main";const a:readonly number[]=[10,2];const b:number[]=sorted(a);sorted([3,1]);b.push(4);'),
   bad('字符串元素不合法','import {sorted} from "./main";sorted(["2"]);'),
  ],'sort 会修改被调用的数组，而且默认按字符串顺序比较。先复制再提供数值比较器，同时满足只读输入和数值排序需求。','错误有可变性和比较规则两部分。｜使用展开生成可变副本。｜提供 (a,b)=>a-b 比较器。',{
   runtime:[run('数值排序且不共享数组','const {sorted}=load("main.js");const a=Object.freeze([10,2,-1,2]);equal(sorted(a),[-1,2,2,10]);equal(sorted([]),[]);const b=[1];check(sorted(b)!==b);equal(b,[1]);')],
   wrongSolutions:[{'main.ts':'export function sorted(values:readonly number[]):number[]{return [...values].sort();}'}],
  }),
 m(3,5,'只读数组中的对象','const users:readonly {name:string}[]=[{name:"A"}]。users[0].name="B" 在默认索引配置下会被 readonly 禁止吗？',['不会，只读数组限制数组结构，不自动把元素对象的属性变成只读','会，readonly 自动递归所有层','只在数组长度为一时允许','只有用 const 声明元素才禁止'],'readonly 数组不允许 push 或替换索引，但元素对象仍按自身类型决定可变性。需要元素属性只读时应另外声明。','数组容器与元素对象是两个层次。｜元素的 name 没有只读修饰。｜只读数组不是深冻结。',{stage:'reason'}),
 t(3,6,'设计非空文本集合','实现 clean(values:readonly string[]):string[]：去除每项两端空白，删除处理后为空的项，保留原顺序和重复值，不修改输入。',
  'export function clean(values:readonly string[]):string[]{return [...values];}',
  'export function clean(values:readonly string[]):string[]{return values.map(value=>value.trim()).filter(value=>value.length>0);}',[
   ok('接受只读输入并返回可变结果','import {clean} from "./main";const input:readonly string[]=[" a "];const result:string[]=clean(input);result.push("b");'),
   bad('数字不能混入','import {clean} from "./main";clean(["a",1]);'),
  ],'数组变换可以拆成标准化和过滤两步。去重不是本题要求，不能因使用 Set 而丢失重复值。','先处理每个元素，再决定是否保留。｜trim 之后再检查长度。｜map 和 filter 都返回新数组。',{
   runtime:[run('处理空白而不去重','const {clean}=load("main.js");const input=Object.freeze([" a ","  ","a"," b","\t"]);equal(clean(input),["a","a","b"]);equal(clean([]),[]);')],
  }),
 m(3,7,'只读结果交给可变参数','declare const input:readonly string[]; function append(xs:string[]){xs.push("x")}。应该如何安全地调用而不改变 input？',['append([...input])','append(input)','把 input 断言成 string[] 后传入','readonly 会让 append 内的 push 自动失效'],'复制创建一个独立的可变数组，允许被调用者修改。断言只改变编译时视图，不能建立运行时隔离。','append 明确要求写入。｜原输入没有授权这种写入。｜副本可以由调用者独立拥有。',{stage:'reason'}),
 t(3,8,'迁移：合并多组标签','实现 merge(groups:readonly (readonly string[])[]):string[]，按分组顺序展开成新数组，保留重复标签，不修改任意输入分组。',
  'export function merge(groups:readonly (readonly string[])[]):string[]{return [];} ',
  'export function merge(groups:readonly (readonly string[])[]):string[]{return groups.flatMap(group=>[...group]);}',[
   ok('内外两层均可只读','import {merge} from "./main";const groups:readonly (readonly string[])[]=[["a"],[]];const result:string[]=merge(groups);merge([["b"]]);'),
   bad('每组必须由字符串组成','import {merge} from "./main";merge([[1]]);'),
   bad('不能直接传字符串序列','import {merge} from "./main";merge(["a"]);'),
  ],'内外两层只读分别保护分组容器和各组数组。展开后的结果是新的单层可变数组，但这不代表深复制任意对象。','输入有两层数组。｜需要展开一层并保持顺序。｜flatMap 或循环逐项收集都可以。',{
   runtime:[run('分组展平且保持重复','const {merge}=load("main.js");const groups=Object.freeze([Object.freeze(["a","b"]),Object.freeze([]),Object.freeze(["a"])]);equal(merge(groups),["a","b","a"]);equal(merge([]),[]);')],
  }),
 m(3,9,'复测：别名和副本','const a=[1,2]; const b:readonly number[]=a; const c=[...a]; a.push(3)。b.length 与 c.length 分别是多少？',['3 和 2','2 和 2','3 和 3','这段代码因 b 只读而无法编译'],'只读标注不创建副本，b 仍引用 a；展开创建的新数组 c 不会随着 a 的长度变化。','区分类型标注和数组创建表达式。｜b 与 a 指向同一数组。｜c 是在 push 之前创建的副本。'),
 t(3,10,'复测：安全读取首项','实现 first(values:readonly number[]):number|undefined，空数组返回 undefined，否则返回第一项。返回类型必须如实保留缺失可能。',
  'export function first(values:readonly number[]):number{return values[0]??0;}',
  'export function first(values:readonly number[]):number|undefined{return values[0];}',[
   ok('接收只读集合','import {first} from "./main";const a:readonly number[]=[];const n:number|undefined=first(a);'),
   bad('调用者必须处理缺失','import {first} from "./main";const n:number=first([1]);'),
   bad('拒绝文本集合','import {first} from "./main";first(["1"]);'),
  ],'空数组并不是数字零。即使默认索引推断比较宽松，对外返回类型仍应反映实际缺失行为。','先确定空输入的真实返回值。｜返回契约需要包含 undefined。｜读取索引零即可保留正确行为。',{
   runtime:[run('空输入与零不混淆','const {first}=load("main.js");equal(first([]),undefined);equal(first([0,2]),0);equal(first([7,8]),7);')],
  }),
 m(4,1,'位置含义','[string,number] 与 (string|number)[] 有什么关键区别？',['元组约束前者的长度和各位置类型，后者不能保证首项是字符串','二者都必须恰好两项','后者比前者更严格','前者运行时变成对象而非数组'],'元组为特定位置提供契约；普通联合元素数组只约束每个元素来自候选范围。二者在运行时都是数组。','关注索引零与索引一分别允许什么。｜普通数组没有固定位置承诺。｜类型信息不改变运行时容器。'),
 m(4,2,'标签会生成字段吗','type Point=[x:number,y:number]。point.x 可以用来读取第一个坐标吗？',['不可以，标签提供文档提示，读取仍用索引或解构','可以，标签自动创建对象属性','只有 x 可读，y 不可读','仅 readonly 元组支持标签属性'],'具名元组标签帮助编辑器展示含义，不会给数组生成 x 和 y 属性。','编译后是否还有标签声明？｜实际值仍是数组。｜用 point[0] 或解构读取。'),
 m(4,3,'可选元素的长度','type Request=[path:string,timeout?:number]。length 的可能类型是什么？',['1 | 2','number，元组从不保留长度','2','0 | 1 | 2'],'固定加可选元素的元组允许两种长度，但第一个必需元素不可省略。读取可选位置还要考虑 undefined。','第一个元素必需。｜第二个可以省略。｜因此只有两个合法长度。'),
 t(4,4,'修复坐标返回契约','实现 point(x:number,y:number)，明确返回 [number,number] 元组，并保持输入坐标顺序。',
  'export function point(x:number,y:number):number[]{return [x,y];}',
  'export function point(x:number,y:number):[number,number]{return [x,y];}',[
   ok('调用者获得确定位置','import {point} from "./main";const p:[number,number]=point(1,2);const x:number=p[0];'),
   bad('不存在第三个坐标','import {point} from "./main";const p=point(1,2);const z=p[2];',[2493]),
   bad('坐标不接受文本','import {point} from "./main";point("1",2);'),
  ],'函数返回普通数组时无法保证恰好两个元素。显式元组契约让调用者获得位置和长度信息。','实现的两个元素是正确的。｜问题在公开返回类型丢失长度。｜将返回标注改为双元素元组。',{
   runtime:[run('坐标顺序保持','const {point}=load("main.js");equal(point(-1,2),[-1,2]);equal(point(0,0),[0,0]);')],
  }),
 m(4,5,'元组能保证运行时长度吗','const pair:[number,number]=[1,2]; pair.push(3) 在当前编译器下可通过。这说明什么？',['可变元组的部分数组方法仍能改变运行时长度，静态契约并非冻结','元组长度类型自动更新为 3','pair[2] 从此会通过静态检查','所有元组都禁止 push，此代码不可能通过'],'可变元组仍暴露数组变更方法，不应把静态长度信息当成运行时不变量。只读元组可约束经该视图进行的变更，但也不是冻结。','检查可变数组方法是否存在。｜编译器不会按每次 push 重建声明类型。｜只读元组更适合固定记录输入。',{stage:'reason'}),
 t(4,6,'设计坐标距离入口','导出 Point=readonly [x:number,y:number]。实现 distance(a:Point,b:Point):number，返回欧氏距离，不修改坐标。',
  'export type Point=number[];\nexport function distance(a:Point,b:Point):number{return 0;}',
  'export type Point=readonly [x:number,y:number];\nexport function distance(a:Point,b:Point):number{return Math.hypot(a[0]-b[0],a[1]-b[1]);}',[
   ok('只读双坐标可用','import {Point,distance} from "./main";const a:readonly [number,number]=[0,0];const p:Point=a;const n:number=distance(p,[3,4]);'),
   bad('缺少一个坐标','import {Point} from "./main";const p:Point=[1];'),
   bad('坐标不可重写','import {Point} from "./main";const p:Point=[1,2];p[0]=3;'),
   bad('不接受三维坐标','import {distance} from "./main";distance([1,2,3],[0,0]);'),
  ],'只读元组同时描述固定位置和读取意图。Math.hypot 根据两个坐标差计算距离，避免只计算单轴或曼哈顿距离。','类型先限定为两个数值位置。｜距离需要两个轴的差。｜Math.hypot(dx,dy) 计算平方和的平方根。',{
   runtime:[run('两轴距离且不修改坐标','const {distance}=load("main.js");equal(distance(Object.freeze([0,0]),Object.freeze([3,4])),5);equal(distance([-1,-1],[-1,-1]),0);equal(distance([3,4],[0,0]),5);')],
  }),
 m(4,7,'剩余元素元组','type Row=[name:string,...scores:number[]]。哪一项符合这个类型？',['["Lin"] 和 ["Lin",80,90] 都符合','[] 符合，因为 scores 可以为空','[80,"Lin"] 符合，因为类型顺序不重要','["Lin","80"] 符合，因为剩余参数自动转换'],'剩余部分可为零项，但必需的首项仍需要提供。每个剩余位置必须是 number，不会自动转换字符串。','把首项要求与剩余项要求分开。｜剩余数组可以为空。｜首项必须始终是字符串。',{stage:'reason'}),
 t(4,8,'迁移：带名称的分数组','导出 Row=readonly [name:string,...scores:number[]]；实现 total(row)，返回 [name,分数总和] 的可变双元素元组。允许没有分数，此时总和为 0。',
  'export type Row=readonly [name:string,...scores:number[]];\nexport function total(row:Row):[string,number]{return [row[0],0];}',
  'export type Row=readonly [name:string,...scores:number[]];\nexport function total(row:Row):[string,number]{const [name,...scores]=row;return [name,scores.reduce((sum,value)=>sum+value,0)];}',[
   ok('不同分数数量','import {Row,total} from "./main";const r:Row=["Lin",1,2];const pair:[string,number]=total(r);total(["Lin"]);'),
   bad('名称不能缺失','import {Row} from "./main";const r:Row=[];'),
   bad('分数必须是数值','import {total} from "./main";total(["Lin","90"]);'),
  ],'解构将固定首项与剩余数字数组分开，后续计算就不再需要处理字符串与数字的联合。reduce 的初值保证空分数集合合法。','先把 name 从剩余分数中解构出来。｜剩余部分自然是数字数组。｜求和时从零开始。',{
   runtime:[run('名字和求和结果保持对应','const {total}=load("main.js");equal(total(Object.freeze(["Lin",80,90])),["Lin",170]);equal(total(["空"]),["空",0]);equal(total(["调整",10,-2]),["调整",8]);')],
  }),
 m(4,9,'复测：普通数组不能保证参数数目','function move(x:number,y:number){}; const coords=[1,2]; move(...coords) 为什么会报错？',['coords 被推断为普通数组，无法保证正好提供两个位置','展开语法不能用于函数调用','数字数组必须先转成字符串','move 必须返回元组才可调用'],'固定参数的调用需要可证明的位置契约。把 coords 声明为元组或使用合适的 const 断言，可以保留这些信息。','字面量包含两项不等于变量类型固定长度。｜coords 后续可能被改变长度。｜需要元组契约提供确定位置。'),
 t(4,10,'复测：可选超时参数','导出 Request=readonly [path:string,timeout?:number]；实现 resolve(request):[string,number]，省略或显式 undefined 时超时设为 1000，保留显式 0。',
  'export type Request=readonly [path:string,timeout?:number];\nexport function resolve(request:Request):[string,number]{return [request[0],request[1]||1000];}',
  'export type Request=readonly [path:string,timeout?:number];\nexport function resolve(request:Request):[string,number]{return [request[0],request[1]??1000];}',[
   ok('可选位置与结果契约','import {resolve,Request} from "./main";const r:Request=["/",undefined];const out:[string,number]=resolve(r);resolve(["/"]);'),
   bad('路径不可缺失','import {Request} from "./main";const r:Request=[];'),
   bad('超时不可为文本','import {resolve} from "./main";resolve(["/","1000"]);'),
  ],'可选元组元素读出来可能为 undefined，与可选对象字段一样需要缺省处理。空值合并保留零值。','第二项是可选而不是永远有数字。｜零不是缺失。｜使用 ?? 得到完整的双元素结果。',{
   runtime:[run('可选位置和零','const {resolve}=load("main.js");equal(resolve(["/"]),["/",1000]);equal(resolve(["/a",undefined]),["/a",1000]);equal(resolve(["/b",0]),["/b",0]);equal(resolve(["/c",50]),["/c",50]);')],
  }),
 m(5,1,'字典声明承诺什么','type Prices={[key:string]:number} 在默认索引配置下表示什么？',['字符串索引访问按 number 检查，但不保证每一个键实际存在','对象预先拥有全部字符串键','键只能使用字符串字面量 key','读取不存在的键自动返回 0'],'索引签名描述动态键的值类型，不负责创建属性。读取缺失属性仍可能得到 undefined，需根据配置与业务处理。','类型声明不会创建属性。｜键名未知不代表所有键都存在。｜值类型检查与运行时存在性需要区分。'),
 m(5,2,'固定属性也受约束','interface Stock {[key:string]:number;name:string} 为什么报错？',['name 也是字符串键，其值必须满足 number 索引签名','索引签名不能与固定属性共存','name 是 TypeScript 保留字','接口只允许一种属性名字'],'字符串索引包含固定字符串属性，因此固定属性的值必须兼容索引签名。若元数据类型不同，可以将动态字典放进独立字段。','试着用 stock["name"] 读取它。｜这个读取不能同时承诺仅数字又返回文本。｜拆开元数据与动态值可以避免冲突。'),
 m(5,3,'数字索引与字符串索引','一个类型同时具有数字和字符串索引签名时，数字索引值类型为什么必须兼容字符串索引值类型？',['JavaScript 对普通对象的数字属性访问会使用对应字符串键','数字索引在运行时总是被删除','数字索引的优先级永远更低','只因 TypeScript 不支持数字键'],'普通对象的 obj[1] 和 obj["1"] 会访问同一属性，两个签名不能对同一个值给出不兼容承诺。','比较 1 与 "1" 的属性访问。｜属性键会经过转换。｜数字索引描述的值必须也满足字符串访问规则。'),
 t(5,4,'修复缺失商品价格','保留 Prices 的索引签名，实现 lookup(prices,key):number|undefined，返回对应值，缺失时保持 undefined。已开启 noUncheckedIndexedAccess。',
  'export type Prices={[key:string]:number};\nexport function lookup(prices:Prices,key:string):number{return prices[key];}',
  'export type Prices={[key:string]:number};\nexport function lookup(prices:Prices,key:string):number|undefined{return prices[key];}',[
   ok('读取结果保留缺失','import {Prices,lookup} from "./main";const p:Prices={apple:2};const n:number|undefined=lookup(p,"apple");'),
   bad('调用者不能忽略缺失','import {lookup} from "./main";const n:number=lookup({},"none");'),
   bad('价格不能为文本','import {Prices} from "./main";const p:Prices={apple:"2"};'),
  ],'严格索引检查为可能不存在的动态键加入 undefined。函数的返回契约需要如实暴露缺失，而不是断言或补零掩盖问题。','动态 key 未必对应已有属性。｜当前配置会提醒缺失可能。｜返回类型包含 undefined。',{
   compilerOptions:{noUncheckedIndexedAccess:true},
   runtime:[run('缺失与零价格不同','const {lookup}=load("main.js");equal(lookup({apple:2},"apple"),2);equal(lookup({},"none"),undefined);equal(lookup({free:0},"free"),0);')],
  }),
 m(5,5,'动态字典还是有限键','状态配置只允许 draft 和 published，并且两项都必须存在。单纯 {[key:string]:boolean} 足够吗？',['不够，它没有要求这两个特定键必需，也允许其他字符串键','足够，索引签名会从变量名推断合法键','足够，空对象不能赋给索引签名','只需把 key 改名为 status 就能限定'],'有限键的完整配置应该声明明确属性，或使用有限键的映射类型。宽字符串索引表达的是开放字典。','先检查空对象是否满足这个索引签名。｜它没有列出任何必需键。｜有限集合应使用更具体的类型。',{stage:'reason'}),
 t(5,6,'设计带元数据的库存','导出 Inventory={name:string;quantities:{[sku:string]:number}}。实现 quantity(inventory,sku)，找到数值则返回该值，缺失时返回 0。启用严格索引检查。',
  'export type Inventory={name:string;[sku:string]:number};\nexport function quantity(inventory:Inventory,sku:string):number{return inventory[sku];}',
  'export type Inventory={name:string;quantities:{[sku:string]:number}};\nexport function quantity(inventory:Inventory,sku:string):number{return inventory.quantities[sku]??0;}',[
   ok('名字与数字字典分离','import {Inventory,quantity} from "./main";const i:Inventory={name:"仓库",quantities:{a:2}};const n:number=quantity(i,"a");'),
   bad('库存值必须为数字','import {Inventory} from "./main";const i:Inventory={name:"仓库",quantities:{a:"2"}};'),
   bad('仓库名字必需','import {Inventory} from "./main";const i:Inventory={quantities:{}};'),
  ],'把不同语义的数据放在独立层级，避免名字也受到数字索引签名约束。缺失库存的回退是函数明确执行的业务规则。','name 不能放在纯数字值的索引范围里。｜把数量集中在 quantities 下。｜动态读取后用 ?? 提供零库存。',{
   compilerOptions:{noUncheckedIndexedAccess:true},
   runtime:[run('已知与未知 SKU','const {quantity}=load("main.js");const i={name:"仓库",quantities:{a:8,b:0}};equal(quantity(i,"a"),8);equal(quantity(i,"b"),0);equal(quantity(i,"missing"),0);')],
  }),
 m(5,7,'只读索引的限制','type Labels={readonly [key:string]:string}。readonly 在这里阻止什么？',['通过 Labels 类型的引用给任意索引赋值','读取动态键','运行时所有别名修改底层对象','对象被 JSON.stringify 序列化'],'只读索引签名限制该视图的写入，不影响读取，也不冻结底层对象。别名仍可能拥有其他可变类型。','readonly 修饰的是索引的写入能力。｜它不生成运行时代码。｜读取和序列化仍然可用。',{stage:'reason'}),
 t(5,8,'迁移：只读标签查找','导出 Labels={readonly [key:string]:string}，实现 label(labels,key)，不存在时返回 key，存在时返回值，空文本也算存在。启用严格索引检查。',
  'export type Labels={readonly [key:string]:string};\nexport function label(labels:Labels,key:string):string{return labels[key]||key;}',
  'export type Labels={readonly [key:string]:string};\nexport function label(labels:Labels,key:string):string{return labels[key]??key;}',[
   ok('读取只读字典','import {Labels,label} from "./main";const labels:Labels={save:"保存"};const s:string=label(labels,"save");'),
   bad('不可通过视图修改','import {Labels} from "./main";const labels:Labels={save:"保存"};labels.save="Save";',[2542]),
   bad('标签值不能是数值','import {Labels} from "./main";const labels:Labels={save:1};'),
  ],'只读索引提供读取约束，空值合并则实现缺失回退。空文本可能表达有意隐藏标签，不应被真假值判断替换。','字典值为空不等于键缺失。｜输入只用于读取。｜以 undefined 而非假值作为回退条件。',{
   compilerOptions:{noUncheckedIndexedAccess:true},
   runtime:[run('空标签也被保留','const {label}=load("main.js");const labels=Object.freeze({save:"保存",hidden:""});equal(label(labels,"save"),"保存");equal(label(labels,"hidden"),"");equal(label(labels,"missing"),"missing");')],
  }),
 m(5,9,'复测：继承属性不是自有项','对普通对象 {} 使用 "toString" in obj 会得到 true。若业务要求只查自有配置项，应注意什么？',['in 会包含原型链，需用自有属性检查区分','in 只检查自有属性，因此必定是编译器错误','索引签名会自动删除原型链','把 obj 标为 readonly 就会解决'],'索引签名不改变对象原型；in 与自有属性检查的语义不同。处理配置字典时要明确是否允许继承属性。','想想 toString 从哪里来。｜in 会沿原型链检查。｜Object.hasOwn 只检查对象自己的属性。'),
 t(5,10,'复测：只读取自有配置','导出 Settings={readonly [key:string]:string|undefined}。实现 own(settings,key):string|undefined，仅返回自有属性的值，继承属性视为不存在。启用严格索引检查。',
  'export type Settings={readonly [key:string]:string|undefined};\nexport function own(settings:Settings,key:string):string|undefined{return settings[key];}',
  'export type Settings={readonly [key:string]:string|undefined};\nexport function own(settings:Settings,key:string):string|undefined{return Object.hasOwn(settings,key)?settings[key]:undefined;}',[
   ok('允许显式未设置的配置','import {Settings,own} from "./main";const s:Settings={theme:"dark",missing:undefined};const out:string|undefined=own(s,"theme");'),
   bad('不能把读取结果当作必有字符串','import {own} from "./main";const s:string=own({},"theme");'),
   bad('配置不可写','import {Settings} from "./main";const s:Settings={};s.theme="dark";',[2542]),
  ],'业务上的自有键检查不能用直接读取或 in 替代。Object.hasOwn 不依赖对象自己的 hasOwnProperty 方法，支持无原型对象和同名字段。','先确认键属于对象自身。｜不要直接调用可能被覆盖的实例方法。｜用 Object.hasOwn 后再读取值。',{
   compilerOptions:{noUncheckedIndexedAccess:true},
   runtime:[run('隔离原型与自有配置','const {own}=load("main.js");const s=Object.create({theme:"inherited"});s.locale="zh";equal(own(s,"theme"),undefined);equal(own(s,"locale"),"zh");equal(own({},"toString"),undefined);const plain=Object.create(null);plain.hasOwnProperty="own";equal(own(plain,"hasOwnProperty"),"own");')],
  }),
 m(6,1,'新鲜字面量的检查','function show(user:{name:string}){}。show({name:"Lin",age:20}) 为什么报错？',['新对象字面量会接受额外属性检查，age 不在目标类型里','所有对象类型都永久禁止额外字段','age 是保留属性名','函数只能接收变量，不能接收字面量'],'额外属性检查有助于发现拼写和契约错误，但不意味着 TypeScript 对所有对象采用精确字段匹配。','先关注实参是不是直接写出的对象字面量。｜目标声明没有 age。｜这是额外属性检查的典型场景。'),
 m(6,2,'先存变量会怎样','const user={name:"Lin",age:20}; function show(x:{name:string}){}; show(user) 可以通过，说明什么？',['已有对象可以按结构兼容赋值，age 不会因此被删除','编译器在调用前删除 age','user 自动变成只含 name 的新对象','额外属性检查从此在整个项目关闭'],'已有变量具备目标必需结构即可兼容。类型视图变窄不会改变原对象的实际字段。','user 满足目标要求的 name 字段。｜类型兼容不等于对象转换。｜调用时仍传递同一个对象。'),
 m(6,3,'拼写错误不应靠索引签名掩盖','Options={timeout?:number}，传入 {timeuot:100} 报错。最合理的修复是什么？',['修正为 timeout 并确认调用意图','增加任意键的 any 索引签名','用双重断言绕过检查','关闭 strict，让拼写错误成为合法配置'],'这类诊断常揭示未生效的选项。放宽契约不会让拼错的字段被业务逻辑正确读取。','检查字段名称是否符合 API。｜编译器提示可能正是运行问题的根源。｜修正拼写而不是抹去约束。'),
 t(6,4,'修复请求选项拼写','保留 Options={timeout?:number} 和外部 readTimeout 契约；修复 exported configured 使其读取 timeout=250。不要放宽接口或使用断言。',
  {'main.ts':'import {readTimeout} from "./reader";\nexport const configured=readTimeout({timeuot:250});'},
  {'main.ts':'import {readTimeout} from "./reader";\nexport const configured=readTimeout({timeout:250});'},[
   ok('配置返回数字','import {configured} from "./main";const n:number=configured;'),
   bad('结果不应变成文本','import {configured} from "./main";const s:string=configured;'),
  ],'修改拼错的字段即可让选项生效。辅助模块固定，保证修复发生在调用处，而不是随意改变公共契约。','错误发生在传入的对象字面量。｜辅助模块读取的字段名是 timeout。｜将 timeuot 更正为 timeout。',{
   supportFiles:{'reader.ts':'export type Options={timeout?:number};export function readTimeout(options:Options):number{return options.timeout??1000;}'},
   runtime:[run('选项实际生效','const {configured}=load("main.js");equal(configured,250);')],
  }),
 m(6,5,'类型标注是否清理对象','const source={id:"u1",token:"secret"}; const publicUser:{id:string}=source; JSON.stringify(publicUser) 会包含 token 吗？',['会，类型标注不会移除实际属性','不会，标注相当于字段白名单','只在关闭 strict 时包含','类型声明会让 JSON.stringify 抛错'],'序列化读取实际对象属性。要过滤敏感字段必须构造新的对象，不能依赖较窄的类型标注。','publicUser 是否经过实际复制和筛选？｜它仍指向 source。｜序列化不读取 TypeScript 类型。',{stage:'reason'}),
 t(6,6,'设计公开用户投影','导出 Source={id:string;name:string;token:string}、PublicUser={id:string;name:string}。实现 publish(source):PublicUser，只返回 id 和 name 的新对象，实际结果不得含 token。',
  'export type Source={id:string;name:string;token:string};\nexport type PublicUser={id:string;name:string};\nexport function publish(source:Source):PublicUser{return source;}',
  'export type Source={id:string;name:string;token:string};\nexport type PublicUser={id:string;name:string};\nexport function publish(source:Source):PublicUser{return {id:source.id,name:source.name};}',[
   ok('公开数据契约','import {Source,PublicUser,publish} from "./main";const s:Source={id:"1",name:"Lin",token:"secret"};const p:PublicUser=publish(s);'),
   bad('公开视图不提供 token','import {publish} from "./main";const p=publish({id:"1",name:"Lin",token:"secret"});p.token;'),
   bad('源数据要求 token','import {Source} from "./main";const s:Source={id:"1",name:"Lin"};'),
  ],'更窄的返回标注可以隐藏静态访问，但无法剔除运行时字段。显式选择字段构造新对象，才能同时满足类型视图和数据输出要求。','初始实现已经可能通过类型检查。｜问题在返回的实际对象没有变。｜只复制允许公开的两个字段。',{
   runtime:[run('公开结果不携带额外数据','const {publish}=load("main.js");const s=Object.freeze({id:"1",name:"Lin",token:"secret",debug:true});const p=publish(s);equal(p,{id:"1",name:"Lin"});check(p!==s);check(!("token" in p));check(!JSON.stringify(p).includes("secret"));')],
   wrongSolutions:[{'main.ts':'export type Source={id:string;name:string;token:string};export type PublicUser={id:string;name:string};export function publish(source:Source):PublicUser{return {...source};}'}],
  }),
 m(6,7,'展开字段的检查边界','type A={id:string}; const extra={debug:true}; const a:A={id:"x",...extra} 可通过，意味着什么？',['展开带入的额外字段不一定触发同样的字面量检查，debug 仍存在','debug 会自动被删除','所有显式额外字段也因此合法','a 的静态类型必然包含 debug'],'对象展开使额外属性检查的行为不同于直接写出同名字段。它仍不会清理实际数据，不能当作精确对象校验。','区分直接声明的字段与展开带入的字段。｜类型检查不是运行时字段过滤。｜通过不代表实际对象只有 id。',{stage:'reason'}),
 t(6,8,'迁移：清理搜索参数','导出 Input={query:string;page:number;debug:boolean}、Search={query:string;page:number}。实现 toSearch(input)，返回仅有 query、page 的新对象，query 去两端空白，page 保持原值。',
  'export type Input={query:string;page:number;debug:boolean};\nexport type Search={query:string;page:number};\nexport function toSearch(input:Input):Search{return {...input,query:input.query.trim()};}',
  'export type Input={query:string;page:number;debug:boolean};\nexport type Search={query:string;page:number};\nexport function toSearch(input:Input):Search{return {query:input.query.trim(),page:input.page};}',[
   ok('转换契约','import {toSearch,Search} from "./main";const s:Search=toSearch({query:" TS ",page:2,debug:true});'),
   bad('公开结果没有 debug','import {toSearch} from "./main";toSearch({query:"x",page:1,debug:false}).debug;'),
   bad('页码不是文本','import {toSearch} from "./main";toSearch({query:"x",page:"1",debug:false});'),
  ],'只覆盖 query 的展开复制仍带着 debug。明确构造对外对象才能执行字段筛选，类型标注负责校验而非清理。','展开会保留未被覆盖的所有字段。｜返回契约较窄不会删字段。｜创建只含目标两个字段的新字面量。',{
   runtime:[run('转换和字段白名单同时成立','const {toSearch}=load("main.js");const input=Object.freeze({query:" TS ",page:0,debug:true});equal(toSearch(input),{query:"TS",page:0});equal(input.query," TS ");')],
  }),
 m(6,9,'复测：satisfies 的位置','const options={timeout:100,timeuot:200} satisfies {timeout:number} 会怎样？',['会指出额外字段 timeuot，不会自动删除它','静默删除 timeuot','把两个值相加作为 timeout','只要 timeout 存在就总能通过'],'satisfies 会检查表达式是否满足目标类型；对这个新鲜字面量仍有额外属性检查，但它不执行运行时转换。','这里仍然是直接写出的字面量。｜检查发生在声明位置。｜satisfies 不是清理函数。',{sourceIds:['objects','satisfies']}),
 t(6,10,'复测：在配置声明处发现拼写错误','导出 options，对象实际只能有 timeout:number 和 retries:number，值分别为 250 和 2。修复初始代码，可以保留 satisfies 在声明处检查完整契约；options 必须保留准确的键和值类型，不允许断言。',
  'export const options={timeout:250,retires:2} satisfies {timeout:number;retries:number};',
  'export const options={timeout:250,retries:2} satisfies {timeout:number;retries:number};',[
   ok('配置字段完整且可以正常读取','import {options} from "./main";const timeout:number=options.timeout;const retries:number=options.retries;'),
   bad('没有拼错的键','import {options} from "./main";options.retires;'),
   bad('不允许任意动态配置键','import {options} from "./main";const key:keyof typeof options="unexpected";'),
  ],'satisfies 在声明位置验证对象是否符合契约，但不会替你改正拼写或删除多余字段。正确拼写和字段值都需要由实现保证。','先比较声明中的字段名和目标契约。｜retires 和 retries 的拼写不同。｜保持 satisfies 检查，并修正对象键。',{
   sourceIds:['objects','satisfies'],
   runtime:[run('配置对象真实键和值','const {options}=load("main.js");equal(options,{timeout:250,retries:2});')],
  }),
 m(7,1,'结构满足即可使用','interface HasId{id:string}，class User{id="u1"} 没有写 implements HasId。User 实例能赋给 HasId 吗？',['能，公开结构满足即可，不要求显式 implements','不能，接口必须注册实现类','只有构造器名字相同才可以','必须先转成 JSON'],'普通公开对象成员按结构比较，implements 可以帮助检查类声明，但不是对象兼容的必经注册步骤。','目标需要什么成员？｜实例已经拥有字符串 id。｜兼容性通常不看声明名字。'),
 m(7,2,'同形状业务 ID','type UserId=string; type OrderId=string。OrderId 能传给要求 UserId 的参数吗？',['能，这两个别名没有创造互不兼容的名义类型','不能，名字不同即不兼容','只有值以 user 开头才可以','编译器会自动查询 ID 所属表'],'普通别名只是给同一种类型起名，不会建立运行时身份或名义隔离。需要更强区分时可另行学习品牌类型或使用具有判别字段的结构。','先展开两个别名。｜底层类型都只有 string。｜业务命名并不自动变成编译约束。'),
 m(7,3,'只看已有变量的结构','const a={id:"x",enabled:true}; const b:{id:string}=a 可以，但 const c:{id:string;enabled:boolean}=b 为什么不可以？',['b 的公开类型没有保证 enabled 存在','b 的对象在赋值时被删除了 enabled','boolean 不能与 string 共存','只有单向变量赋值语法合法'],'运行对象仍可能有字段，但静态类型只能承诺声明中保留的信息。较宽结构可满足较小需求，不代表较小契约反向保证更多字段。','检查的是 b 的类型而不是猜测历史来源。｜b 只承诺 id。｜c 还要求 enabled。'),
 t(7,4,'修复过度具体的参数','实现 label(item)，只需要 item.name:string，返回大写姓名。允许已有变量携带 id、角色等更多字段，也允许只含 name 的对象。',
  'export function label(item:{id:string;name:string;role:string}):string{return item.name.toUpperCase();}',
  'export function label(item:{name:string}):string{return item.name.toUpperCase();}',[
   ok('最小对象和更丰富变量都可用','import {label} from "./main";const user={id:"1",name:"Lin",role:"admin"};const s:string=label(user);label({name:"Jia"});'),
   bad('姓名必需','import {label} from "./main";label({id:"1"});'),
   bad('姓名必须是文本','import {label} from "./main";label({name:1});'),
  ],'参数应表达实现真正依赖的能力。无关必需字段会阻止原本可处理的数据传入；已有丰富对象仍可按结构满足最小需求。','函数体只使用了哪个字段？｜删除无关的参数类型要求。｜保留 name:string 即可。',{
   runtime:[run('按最小能力处理','const {label}=load("main.js");equal(label({name:"Lin"}),"LIN");equal(label({id:"1",name:"jia",role:"admin"}),"JIA");')],
  }),
 m(7,5,'类兼容的例外','两个无继承关系的类都有 private token:string，能仅因私有字段名字相同就互相赋值吗？',['不能，私有成员的声明来源会影响兼容性','能，TypeScript 对所有成员永远只比较名字','能，只要 token 当前值相同','不能，因为所有类都完全采用名义类型'],'结构化类型有例外。类的 private/protected 成员会引入声明来源约束，不能把普通公开对象的规则无条件套到它们身上。','这里成员不是 public。｜私有成员来自不同的类声明。｜检查会考虑来源而不仅是名字。',{stage:'reason',sourceIds:['compatibility','classes']}),
 t(7,6,'设计最小日志依赖','导出 Logger，要求有 write(message:string):void 方法。实现 report(logger,message)，恰好调用一次 write，传入 "[app] " + message。不要求 logger 属于某个类。',
  'export interface Logger {write(message:string):void}\nexport function report(logger:Logger,message:string):void{}',
  'export interface Logger {write(message:string):void}\nexport function report(logger:Logger,message:string):void{logger.write("[app] "+message);}',[
   ok('类和普通对象都可满足依赖','import {Logger,report} from "./main";const logger:Logger={write(message:string){}};report(logger,"x");class Memory{write(message:string){};clear(){}}report(new Memory(),"y");'),
   bad('方法参数必须兼容文本','import {report} from "./main";report({write(value:number){}},"x");'),
   bad('写入能力不可缺失','import {Logger} from "./main";const logger:Logger={};'),
  ],'按能力定义接口可以接收真实实现和测试替身。运行测试验证委托行为，避免空函数只靠返回 void 通过。','参数只需要一个写入能力。｜不要限定某个构造函数。｜把消息加前缀后传给 write。',{
   runtime:[run('真实委托一次','const {report}=load("main.js");const seen=[];const logger={write(message){check(this===logger);seen.push(message);}};report(logger,"ready");equal(seen,["[app] ready"]);')],
  }),
 m(7,7,'多余数据仍在对象里','函数接受 {id:string}，调用方传入已有的 {id,token} 对象。函数在运行时能通过 Object.keys 看到 token 吗？',['能，结构兼容没有创建删减后的对象','不能，函数参数会自动执行字段过滤','只有 any 参数能看到实际字段','进入函数时所有额外键都会变成 undefined'],'类型描述控制静态使用方式；实际引用仍指向原对象。不要用结构兼容替代字段过滤或安全边界。','传参是否创建新对象？｜Object.keys 检查运行时对象。｜类型视图不会改变真实属性。',{stage:'reason'}),
 t(7,8,'迁移：可替换的存储实现','导出 Store，包含 read(key:string):string|undefined。实现 loadTitle(store)，读取键 title，缺失时返回 "未命名"，空字符串原样保留。允许任意满足结构的对象实现。',
  'export interface Store {read(key:string):string|undefined}\nexport function loadTitle(store:Store):string{return store.read("title")||"未命名";}',
  'export interface Store {read(key:string):string|undefined}\nexport function loadTitle(store:Store):string{return store.read("title")??"未命名";}',[
   ok('结构匹配的替身','import {Store,loadTitle} from "./main";const store={read(key:string){return key==="title"?"TS":undefined;},clear(){}};const s:Store=store;const title:string=loadTitle(s);'),
   bad('读取结果不能是数字','import {Store} from "./main";const s:Store={read(key:string){return 1;}};'),
   bad('读方法不能缺失','import {loadTitle} from "./main";loadTitle({});'),
  ],'最小存储接口使函数不依赖某个浏览器 API 或类。缺省行为属于函数逻辑，必须保留合法的空字符串。','关注 read 的参数和返回契约。｜先用固定键 title 读取。｜用 ?? 区分缺失和空文本。',{
   runtime:[run('不同实现保持相同行为','const {loadTitle}=load("main.js");const keys=[];equal(loadTitle({read(key){keys.push(key);return "";}}),"");equal(keys,["title"]);equal(loadTitle({read(){return undefined;}}),"未命名");equal(loadTitle({read(){return "TS";}}),"TS");')],
  }),
 m(7,9,'复测：多一个必需字段','A={id:string}，B={id:string;name:string}。已有 B 变量可赋给 A，而 A 不一定能赋给 B，根本原因是什么？',['B 提供了 A 的全部需求，A 没有承诺 B 所需的 name','字段越少的类型永远更严格','名字按字母排序决定赋值方向','编译器只检查第一个字段'],'类型是对能力的承诺。能提供更多字段的值可以满足只读取较少字段的需求，但反向需要额外证据。','把目标类型看作需求清单。｜B 的清单覆盖 A。｜A 无法证明额外 name 存在。'),
 t(7,10,'复测：业务身份的结构区分','普通字符串别名不能区分身份。导出 UserRef={kind:"user";id:string} 与 OrderRef={kind:"order";id:string}；实现 userPath(ref:UserRef)，返回 "/users/"+encodeURIComponent(ref.id)，拒绝 OrderRef。',
  'export type UserRef={kind:string;id:string};\nexport type OrderRef={kind:string;id:string};\nexport function userPath(ref:UserRef):string{return "/users/"+ref.id;}',
  'export type UserRef={kind:"user";id:string};\nexport type OrderRef={kind:"order";id:string};\nexport function userPath(ref:UserRef):string{return "/users/"+encodeURIComponent(ref.id);}',[
   ok('用户身份合法','import {UserRef,userPath} from "./main";const ref:UserRef={kind:"user",id:"a"};const s:string=userPath(ref);'),
   bad('订单身份不能混用','import {OrderRef,userPath} from "./main";const ref:OrderRef={kind:"order",id:"a"};userPath(ref);'),
   bad('判别字段不可省略','import {UserRef} from "./main";const ref:UserRef={id:"a"};'),
  ],'通过不同的字面量字段建立不同结构，编译器才有证据区分两类业务身份。URL 编码负责实际路径安全，不由类型自动执行。','不要只给同一种 string 起两个名字。｜kind 使用不同字面量。｜构造路径时编码 id。',{
   runtime:[run('用户路径编码','const {userPath}=load("main.js");equal(userPath({kind:"user",id:"a/b"}),"/users/a%2Fb");equal(userPath({kind:"user",id:"a b"}),"/users/a%20b");')],
  }),
 m(8,1,'两个可选字段的漏洞','type Content={text?:string;url?:string} 是否表达“文本和链接必须二选一”？',['没有，它允许都缺失，也允许同时存在','是，两个问号自动形成互斥','只保证不能同时存在','只保证至少存在一个'],'独立可选属性各自决定是否出现，并没有表达字段之间的关联。互斥业务需要联合分支和必要约束。','分别枚举每个字段存在或缺失的情况。｜组合有四种而不是两种。｜问号不负责表达二选一。'),
 m(8,2,'普通联合并非精确异或','type Input={text:string}|{url:string}。已有变量同时含 text 和 url，为何仍可能赋给 Input？',['它按结构满足至少一个分支，联合本身不禁止额外属性','联合运行时随机删除一个字段','TypeScript 所有联合都会退化为 any','只有属性顺序决定是否通过'],'联合表示满足候选分支之一，并不自动要求其他字段绝对不存在。要禁止另一种字段，可在对应分支将它声明为可选 never。','每个分支是否已经被该变量满足？｜结构兼容通常允许多余成员。｜互斥需要额外表达禁止的字段。'),
 m(8,3,'可选 never 与配置','type Text={text:string;url?:never}，开启 exactOptionalPropertyTypes 后，显式 url:undefined 是否允许？',['不允许，若属性存在其值必须满足 never','允许，所有可选属性永远可赋 undefined','允许，只要 text 非空','不允许，因为所有可选属性都被禁用'],'精确可选属性配置区分字段不存在和字段存在但为 undefined。默认关闭时，可选 never 对显式 undefined 的约束会更宽松。','先区分省略属性与写入 undefined。｜精确可选属性不会自动扩展写入类型。｜never 没有可提供的正常值。',{sourceIds:['objects','config']}),
 t(8,4,'修复内容来源的互斥约束','导出 Input，要求 text:string 与 url:string 恰好提供一个，另一个字段禁止出现；实现 render，文本原样返回，链接返回 "链接: "+url。本题开启精确可选属性。',
  'export type Input={text?:string;url?:string};\nexport function render(input:Input):string{return input.text??"链接: "+input.url;}',
  'export type Input={text:string;url?:never}|{url:string;text?:never};\nexport function render(input:Input):string{return input.text!==undefined?input.text:"链接: "+input.url;}',[
   ok('两种来源单独可用','import {Input,render} from "./main";const a:Input={text:""};const b:Input={url:"/a"};const s:string=render(a);render(b);'),
   bad('不能都缺失','import {Input} from "./main";const a:Input={};'),
   bad('已有对象混合也不允许','import {Input} from "./main";const both={text:"a",url:"/a"};const a:Input=both;'),
   bad('不能显式塞入 undefined','import {Input} from "./main";const a:Input={text:"a",url:undefined};',[2375]),
  ],'联合分支让每种来源都有必需字段，可选 never 排除另一种字段。精确可选属性进一步区分省略和显式 undefined。','拆成文本分支与链接分支。｜每个分支禁止另一字段。｜空文本有效，不要用真假值判定来源。',{
   compilerOptions:{exactOptionalPropertyTypes:true},
   runtime:[run('空文本与链接正确区分','const {render}=load("main.js");equal(render({text:""}),"");equal(render({text:"hello"}),"hello");equal(render({url:"/docs"}),"链接: /docs");')],
  }),
 m(8,5,'模式字段不能孤立声明','{mode:"password"|"token";password?:string;token?:string} 为什么仍允许无效登录数据？',['mode 与两个可选字段没有建立关联','字面量联合不能用于属性','password 字段名会被编译器忽略','只要给 mode 加 readonly 就能自动关联'],'需要将密码模式和令牌模式写成独立对象分支，才能根据 mode 保证所需凭据存在。只读约束与字段关联是不同问题。','mode 的候选没有控制其他字段的必需性。｜每一种模式需要自己的契约。｜用判别联合连接模式和数据。',{stage:'reason'}),
 t(8,6,'设计登录请求','导出 Login：密码模式为 {mode:"password";username:string;password:string;token?:never}，令牌模式为 {mode:"token";token:string;username?:never;password?:never}。实现 credential，密码模式返回 username+":"+password，令牌模式返回 "Bearer "+token。',
  'export type Login={mode:"password"|"token";username?:string;password?:string;token?:string};\nexport function credential(input:Login):string{return input.token??"";}',
  'export type Login={mode:"password";username:string;password:string;token?:never}|{mode:"token";token:string;username?:never;password?:never};\nexport function credential(input:Login):string{return input.mode==="password"?input.username+":"+input.password:"Bearer "+input.token;}',[
   ok('两种凭据','import {Login,credential} from "./main";const a:Login={mode:"password",username:"u",password:"p"};const b:Login={mode:"token",token:"t"};const s:string=credential(a);credential(b);'),
   bad('密码模式缺少密码','import {Login} from "./main";const a:Login={mode:"password",username:"u"};'),
   bad('令牌模式不含密码','import {Login} from "./main";const both={mode:"token" as const,token:"t",password:"p"};const a:Login=both;'),
   bad('密码模式不能混入令牌','import {Login} from "./main";const a:Login={mode:"password",username:"u",password:"p",token:"t"};'),
  ],'判别字段连接模式与必需凭据，禁止字段约束进一步排除混用。示例仅练习数据建模，不代表完整认证协议。','先将两种模式分开声明。｜每种模式列出必需和禁止字段。｜根据 mode 分支后读取凭据。',{
   compilerOptions:{exactOptionalPropertyTypes:true},
   runtime:[run('按模式构造凭据','const {credential}=load("main.js");equal(credential({mode:"password",username:"u",password:"p"}),"u:p");equal(credential({mode:"token",token:"t"}),"Bearer t");')],
  }),
 m(8,7,'联合不能自动校验服务器响应','将 fetch 返回的数据断言成严格互斥联合后，服务器发来的混合字段会自动被拒绝吗？',['不会，类型声明和断言不能代替运行时校验','会，never 字段在网络层被过滤','会，编译器会访问远程接口验证','只有关闭 strict 才不会拒绝'],'类型约束检查编译期可见的赋值。外部数据应从 unknown 出发实际检查，确认模式、字段和值符合要求。','数据何时到达程序？｜断言不会生成校验代码。｜外部边界需要执行真实判断。',{stage:'reason'}),
 t(8,8,'迁移：读取异步状态','导出 State：idle、loading 分支仅允许各自 status，禁止 data/error；success 必需 data:string 且禁止 error；failure 必需 error:string 且禁止 data。实现 message，分别返回 "未开始"、"加载中"、data、"错误: "+error。',
  'export type State={status:"idle"|"loading"|"success"|"failure";data?:string;error?:string};\nexport function message(state:State):string{return state.data??state.error??"";}',
  'export type State={status:"idle"|"loading";data?:never;error?:never}|{status:"success";data:string;error?:never}|{status:"failure";error:string;data?:never};\nexport function message(state:State):string{switch(state.status){case "idle":return "未开始";case "loading":return "加载中";case "success":return state.data;case "failure":return "错误: "+state.error;}}',[
   ok('四种有效状态','import {State,message} from "./main";const a:State={status:"idle"};const b:State={status:"loading"};const c:State={status:"success",data:""};const d:State={status:"failure",error:"x"};const s:string=message(a);'),
   bad('成功不能无数据','import {State} from "./main";const s:State={status:"success"};'),
   bad('加载中不携带旧数据','import {State} from "./main";const s:State={status:"loading",data:"old"};'),
   bad('成功与错误不能同时存在','import {State} from "./main";const both={status:"success" as const,data:"ok",error:"bad"};const s:State=both;'),
  ],'状态模型应按照产品约定决定字段关系。本题明确不保留加载中的旧数据，因此将它禁止；其他业务若需要保留应设计不同契约。','逐个写出状态对应的合法字段。｜不能用一组独立可选属性代替关联。｜switch 根据 status 读取正确字段。',{
   compilerOptions:{exactOptionalPropertyTypes:true},
   runtime:[run('各状态呈现不同信息','const {message}=load("main.js");equal(message({status:"idle"}),"未开始");equal(message({status:"loading"}),"加载中");equal(message({status:"success",data:""}),"");equal(message({status:"failure",error:"断网"}),"错误: 断网");')],
  }),
 m(8,9,'复测：业务约束有多强','互斥类型能保证 password:string 一定是非空字符串吗？',['不能，string 包括空字符串，内容约束还需校验','能，必需字段必然非空','能，只要排除了 token','只有 interface 可以保证非空'],'字段存在、基础类型正确和业务内容有效是不同层次。密码非空、长度等规则需要进一步建模与运行校验。','必需表示不能省略字段。｜空字符串仍然属于 string。｜内容规则需要额外证据。'),
 t(8,10,'复测：分页模式互斥','导出 Page：偏移模式 {mode:"offset";offset:number;cursor?:never} 或游标模式 {mode:"cursor";cursor:string;offset?:never}。实现 query，返回 "offset="+offset 或 "cursor="+encodeURIComponent(cursor)。',
  'export type Page={mode:"offset"|"cursor";offset?:number;cursor?:string};\nexport function query(page:Page):string{return "offset="+(page.offset??0);}',
  'export type Page={mode:"offset";offset:number;cursor?:never}|{mode:"cursor";cursor:string;offset?:never};\nexport function query(page:Page):string{return page.mode==="offset"?"offset="+page.offset:"cursor="+encodeURIComponent(page.cursor);}',[
   ok('两类有效分页','import {Page,query} from "./main";const a:Page={mode:"offset",offset:0};const b:Page={mode:"cursor",cursor:"a"};const s:string=query(a);query(b);'),
   bad('模式必须有对应值','import {Page} from "./main";const p:Page={mode:"cursor"};'),
   bad('变量中也不能混合分页字段','import {Page} from "./main";const mixed={mode:"offset" as const,offset:0,cursor:"a"};const p:Page=mixed;'),
   bad('偏移不能是文本','import {Page} from "./main";const p:Page={mode:"offset",offset:"0"};'),
  ],'两种分页方式各有必需参数，互斥联合阻止混合请求。offset 为零仍然有效，不能依赖真假值选择模式。','用 mode 而非参数真假值选择分支。｜在每个分支禁止另一种字段。｜游标可能包含特殊字符，需要编码。',{
   compilerOptions:{exactOptionalPropertyTypes:true},
   runtime:[run('零偏移和特殊游标','const {query}=load("main.js");equal(query({mode:"offset",offset:0}),"offset=0");equal(query({mode:"offset",offset:20}),"offset=20");equal(query({mode:"cursor",cursor:"a+b/="}),"cursor=a%2Bb%2F%3D");')],
  }),
];
