import { mc, task, ok, bad, run } from './author.mjs';
const id=n=>`t07-l${String(n).padStart(2,'0')}`;
const m=(l,n,title,prompt,options,explanation,hints,extra={})=>mc(id(l),n,title,prompt,options,explanation,hints.split('｜'),extra);
const t=(l,n,title,prompt,files,solution,tests,explanation,hints,extra={})=>task(id(l),n,title,prompt,files,solution,tests,explanation,hints.split('｜'),extra);
export const questions=[
 m(1,1,'交叉不是二选一','type User={id:string}&{name:string} 表示什么？',['一个值同时满足 id 和 name 两组要求','值只需满足其中一组','编译器在运行时将两个对象相加','后面的类型覆盖前面的所有字段'],'交叉要求同时成立，与联合的候选含义不同。它只描述约束，不生成对象合并代码。','把 & 理解为同时满足。｜两个必需字段都不能缺少。｜真实对象仍需由运行代码创建。'),
 m(1,2,'同名字段冲突','type Broken={id:string}&{id:number}，Broken["id"] 为什么不能放普通字符串或数字？',['它必须同时满足 string 和 number，因此该字段类型为 never','后面的 number 覆盖 string','前面的 string 覆盖 number','自动变成 string|number'],'交叉并非对象展开。相同属性也要同时满足约束，不兼容的基础类型使该字段不可正常赋值。','比较同时满足与先后覆盖的区别。｜普通值不能同时是字符串和数字。｜该字段交叉成为 never。'),
 m(1,3,'对象展开与类型交叉','const merged={...a,...b} 在同名属性上用 b 覆盖 a，是否说明它总能安全声明成 A&B？',['不能，运行时覆盖可能不满足 A 对同名属性的要求','能，交叉定义就是后者覆盖','能，编译器会保留两个同名属性','只有使用 const 才能保证'],'对象展开有顺序覆盖语义，交叉要求两者同时成立。组合模型时必须检查字段冲突，不能把通用合并一概标成 A&B。','运行时最终只剩一个同名属性值。｜这个值是否还满足 A？｜不兼容时就不能声称同时满足。'),
 t(1,4,'修复把联合误当组合','导出 Identified={id:string}、Named={name:string}、User。User 必须同时满足前两种结构。实现 label(user:User)，返回 id+": "+name。',
  'export type Identified={id:string};\nexport type Named={name:string};\nexport type User=Identified|Named;\nexport function label(user:User):string{return user.id+": "+user.name;}',
  'export type Identified={id:string};\nexport type Named={name:string};\nexport type User=Identified&Named;\nexport function label(user:User):string{return user.id+": "+user.name;}',[
   ok('同时具备两种能力','import {User,Identified,Named,label} from "./main";const user:User={id:"u1",name:"Lin"};const a:Identified=user;const b:Named=user;const s:string=label(user);'),
   bad('姓名不能缺失','import {User} from "./main";const user:User={id:"u1"};'),
   bad('身份不能缺失','import {User} from "./main";const user:User={name:"Lin"};'),
  ],'联合允许只满足一个分支，不能保证同时读取 id 与 name。交叉表达此处的组合要求，但仍由对象值提供两个字段。','实现需要同时读取两个字段。｜二选一不足以满足它。｜用交叉组合 Identified 和 Named。',{
   runtime:[run('组合字段共同参与展示','const {label}=load("main.js");equal(label({id:"u1",name:"Lin"}),"u1: Lin");equal(label({id:"x",name:""}),"x: ");')],
  }),
 m(1,5,'可选字段与必需字段交叉','type A={name?:string}&{name:string}。name 能省略吗？',['不能，必须同时满足第二部分的必需字段要求','能，前一个问号优先','能，交叉会让所有字段变可选','取决于对象创建顺序'],'同时满足可选要求与必需要求仍必须提供字段。交叉不会按左右顺序选择其中一方的可选性。','检查第二部分允许空对象吗？｜不允许，所以整体也不能。｜两个约束都要成立。',{stage:'reason'}),
 t(1,6,'设计读写服务的组合契约','导出 Reader={read:(key:string)=>string|undefined}、Writer={write:(key:string,value:string)=>void}、Store=Reader&Writer。实现 copy(store,from,to):boolean，源键不存在返回 false 且不写入；否则写到目标并返回 true，空字符串也要复制。',
  'export type Reader={read:(key:string)=>string|undefined};\nexport type Writer={write:(key:string,value:string)=>void};\nexport type Store=Reader&Writer;\nexport function copy(store:Store,from:string,to:string):boolean{const value=store.read(from);if(!value)return false;store.write(to,value);return true;}',
  'export type Reader={read:(key:string)=>string|undefined};\nexport type Writer={write:(key:string,value:string)=>void};\nexport type Store=Reader&Writer;\nexport function copy(store:Store,from:string,to:string):boolean{const value=store.read(from);if(value===undefined)return false;store.write(to,value);return true;}',[
   ok('同时提供读写的对象','import {Store,copy} from "./main";const store:Store={read:key=>"",write:(key,value)=>{}};const result:boolean=copy(store,"a","b");'),
   bad('只读能力不够','import {Store} from "./main";const store:Store={read:key=>"x"};'),
   bad('只写能力不够','import {Store} from "./main";const store:Store={write:(key,value)=>{}};'),
  ],'交叉适合组合独立能力，copy 同时依赖读取和写入。值存在性仍由运行逻辑判断，空文本不能被误认成不存在。','类型要求读与写都存在。｜空字符串是有效源值。｜只对 undefined 提前返回。',{
   runtime:[run('读写协作与缺失处理','const {copy}=load("main.js");const writes=[];const store={read:key=>key==="empty"?"":key==="value"?"text":undefined,write:(key,value)=>writes.push([key,value])};equal(copy(store,"empty","a"),true);equal(copy(store,"value","b"),true);equal(copy(store,"missing","c"),false);equal(writes,[["a",""],["b","text"]]);')],
  }),
 m(1,7,'交叉不会创建品牌字段','把 string & {readonly brand:"UserId"} 当成类型后，普通字符串会在运行时自动拥有 brand 吗？',['不会，交叉类型不生成属性或校验代码','会，编译器给字符串增加对象字段','会，但只有开发模式生成','会，readonly 负责注入字段'],'类型层的品牌约束与运行表示可以不同，但品牌值必须通过可信边界建立。声明交叉不会自动改变原始值，也不授权随意断言。','类型擦除后是否还有 brand 声明？｜交叉描述约束，不执行构造。｜不要从类型字段推断实际新增属性。',{stage:'reason'}),
 t(1,8,'迁移：冲突字段不能用交叉覆盖','已有 User={id:string;name:string} 与 Audit={id:number;revision:number}。导出 Record，分别在 user 和 audit 字段保存二者，避免同名 id 冲突；实现 describe(record)，返回 user.id+"/"+audit.id+"@"+audit.revision。',
  'export type User={id:string;name:string};\nexport type Audit={id:number;revision:number};\nexport type Record=User&Audit;\nexport function describe(record:Record):string{return String(record.id);}',
  'export type User={id:string;name:string};\nexport type Audit={id:number;revision:number};\nexport type Record={user:User;audit:Audit};\nexport function describe(record:Record):string{return record.user.id+"/"+record.audit.id+"@"+record.audit.revision;}',[
   ok('冲突字段分别保存','import {Record,describe} from "./main";const record:Record={user:{id:"u1",name:"Lin"},audit:{id:2,revision:3}};const s:string=describe(record);'),
   bad('用户 ID 不能变成数字','import {Record} from "./main";const record:Record={user:{id:1,name:"Lin"},audit:{id:2,revision:3}};'),
   bad('审计 ID 不能变成文本','import {Record} from "./main";const record:Record={user:{id:"u1",name:"Lin"},audit:{id:"2",revision:3}};'),
  ],'交叉不能把不兼容的 id 合并成一个字段。两种身份都需要保留时，按语义分组比强行交叉更准确，也避免运行时覆盖造成数据丢失。','两个 id 属于不同业务实体。｜不要让它们争用同一个属性。｜用 user 和 audit 两个嵌套字段保留完整数据。',{
   runtime:[run('两种 ID 都保留','const {describe}=load("main.js");equal(describe({user:{id:"u1",name:"Lin"},audit:{id:2,revision:3}}),"u1/2@3");')],
  }),
 m(1,9,'复测：判别字段冲突','{kind:"a";value:string}&{kind:"b";count:number} 为什么不能正常构造？',['同一 kind 不可能同时为两个不同字面量，交叉会被判为不可能','交叉自动选择 kind:"b"','value 与 count 不能共存','类型字段顺序错误'],'不兼容的判别属性可能使整个交叉化简为 never。交叉不是表达两个可选状态的工具，二选一应使用联合。','一个对象的 kind 当前只有一个值。｜两个字面量要求互不相容。｜不要用交叉表达候选状态。'),
 t(1,10,'复测：为所有联合分支添加公共字段','导出 Event=({kind:"text";text:string}|{kind:"count";count:number})&{requestId:string}。实现 render(event)，文本返回 requestId+":"+text，计数返回 requestId+":"+count。',
  'export type Event={kind:"text";text:string;requestId:string}|{kind:"count";count:number};\nexport function render(event:Event):string{return event.kind==="text"?event.requestId+":"+event.text:String(event.count);}',
  'export type Event=({kind:"text";text:string}|{kind:"count";count:number})&{requestId:string};\nexport function render(event:Event):string{return event.requestId+":"+(event.kind==="text"?event.text:event.count);}',[
   ok('两种分支都有公共身份','import {Event,render} from "./main";const a:Event={kind:"text",text:"a",requestId:"r1"};const b:Event={kind:"count",count:0,requestId:"r2"};const s:string=render(b);'),
   bad('计数分支也必须有公共字段','import {Event} from "./main";const e:Event={kind:"count",count:1};'),
   bad('分支专属字段仍必需','import {Event} from "./main";const e:Event={kind:"text",requestId:"r1"};'),
  ],'将公共要求与整个联合相交，可让每个候选都具备 requestId，同时保留判别字段与专属数据的关联。括号清楚表达组合范围。','公共字段需要作用于整个联合。｜先写两种分支，再与 Trace 结构交叉。｜收窄后读取对应的 text 或 count。',{
   runtime:[run('每个事件都包含身份','const {render}=load("main.js");equal(render({kind:"text",text:"",requestId:"r1"}),"r1:");equal(render({kind:"count",count:0,requestId:"r2"}),"r2:0");')],
  }),
 m(2,1,'keyof 作用于什么','type User={id:string;age:number}; type Key=keyof User，Key 是什么？',['"id" | "age"','string | number','User 的所有运行时值组成的数组','["id","age"] 元组'],'keyof 在类型层面取得可用属性名的联合，不返回值类型，也不生成键数组。','区分属性名与属性值。｜结果在类型空间中。｜两个键组成字面量联合。'),
 m(2,2,'联合类型的公共键','type A={id:string;name:string}; type B={id:string;price:number}; keyof (A|B) 为什么只有 id？',['未经收窄的联合只能保证两边共有的属性','联合会删除其他实际属性','keyof 总只返回第一个字段','name 与 price 因为值类型不同互相覆盖'],'对未知分支的联合，只有共有键能安全直接访问。若想取得所有分支各自的键，需要另一种类型运算，而非直接 keyof 联合。','当前值可能是 A 或 B。｜哪些属性两种情况下都可读？｜id 是共同保证。'),
 m(2,3,'字符串索引签名的键','type Dict={[key:string]:boolean}，keyof Dict 为何包含 number？',['普通对象的数字属性访问也映射到字符串键，类型考虑这类访问','boolean 自动转换成数字','所有 keyof 都等于 number','字符串索引签名只允许数字'],'字符串索引覆盖动态字符串属性，数字访问会使用相应字符串键，因此 keyof 此类字典包含 string 与 number。symbol 不因此自动合法。','比较 dict[1] 与 dict["1"]。｜它们访问同一个普通属性。｜因此数字索引也在允许范围。'),
 t(2,4,'从模型派生字段名','只读 model.ts 提供 User。导出 Field=keyof User，并实现 read(user:User,key:Field):User[Field] 返回选定字段。测试会给模型增加字段，派生类型应自动跟随，不能手写当前字段名联合。',
  {'main.ts':'import type {User} from "./model";\nexport type Field="name"|"age";\nexport function read(user:User,key:Field):User[Field]{return user[key];}'},
  {'main.ts':'import type {User} from "./model";\nexport type Field=keyof User;\nexport function read(user:User,key:Field):User[Field]{return user[key];}'},[
   ok('当前字段合法','import {Field,read} from "./main";const key:Field="age";const value:string|number=read({name:"Lin",age:2},key);'),
   bad('未知字段仍被拒绝','import {Field} from "./main";const key:Field="missing";'),
   {...ok('模型增加字段后自动可用','import {Field,read} from "./main";const key:Field="active";const value:string|number|boolean=read({name:"Lin",age:2,active:true},key);'),supportFiles:{'model.ts':'export type User={name:string;age:number;active:boolean};'}},
  ],'用 keyof 将字段范围绑定到源模型。模型变化测试能区分真实派生与手写一份当前恰好相同的联合。User[Field] 则表达这些字段可能返回的值类型。','模型是唯一字段来源。｜删除手工枚举的键。｜使用 keyof User。',{
   supportFiles:{'model.ts':'export type User={name:string;age:number};'},
   runtime:[run('按键读取实际值','const {read}=load("main.js");equal(read({name:"Lin",age:2},"name"),"Lin");equal(read({name:"Lin",age:2},"age"),2);')],
  }),
 m(2,5,'Object.keys 不等于 keyof 数组','为什么 Object.keys(value) 通常返回 string[]，而不是自动成为 (keyof T)[]？',['运行对象可能有静态类型未列出的额外属性，且 Object.keys 只返回可枚举自有字符串键','因为 keyof 不支持数组','因为所有对象键都是未知类型','因为 Object.keys 会删除类型信息中的字段'],'静态形状不一定精确枚举实际对象的全部属性，数字键还会以字符串形式返回，symbol 则不在 Object.keys 结果里。不能随手认为两者完全等价。','结构兼容允许已有对象多一些字段。｜再考虑数字与 symbol 键。｜运行键枚举与静态键集合有不同规则。',{stage:'reason'}),
 t(2,6,'设计开放字典的键类型','导出 Scores={[name:string]:number}、ScoreKey=keyof Scores；实现 lookup(scores,key:ScoreKey):number|undefined，仅返回自有属性值，不存在返回 undefined。应接受字符串及数字键，拒绝 symbol。',
  'export type Scores={[name:string]:number};\nexport type ScoreKey=string;\nexport function lookup(scores:Scores,key:ScoreKey):number|undefined{return scores[key];}',
  'export type Scores={[name:string]:number};\nexport type ScoreKey=keyof Scores;\nexport function lookup(scores:Scores,key:ScoreKey):number|undefined{return Object.hasOwn(scores,key)?scores[key]:undefined;}',[
   ok('字符串和数字都是合法索引','import {ScoreKey,lookup} from "./main";const a:ScoreKey="alice";const b:ScoreKey=1;const n:number|undefined=lookup({1:3},b);'),
   bad('没有 symbol 索引签名','import {ScoreKey} from "./main";const key:ScoreKey=Symbol();'),
   bad('字典值仍是数字','import {lookup} from "./main";lookup({alice:"3"},"alice");'),
  ],'keyof 字符串索引字典包括数字访问；查找仍要处理键不存在的运行事实。自有属性检查避免把原型上的成员当成分数。','ScoreKey 不应只写 string。｜用 keyof Scores 保留索引语义。｜读取前检查 Object.hasOwn。',{
   runtime:[run('数字键与原型属性','const {lookup}=load("main.js");equal(lookup({1:3},1),3);equal(lookup({alice:0},"alice"),0);equal(lookup({},"missing"),undefined);equal(lookup({},"toString"),undefined);')],
  }),
 m(2,7,'交叉类型的键','A={id:string}、B={name:string}，keyof (A&B) 包含什么？',['"id" | "name"','never','只有 "id"','只有 "name"'],'交叉要求两个结构同时成立，因此组合对象提供两侧键。它与 keyof 联合只取共同可访问键的规则不同。','交叉对象必须同时具备两侧成员。｜每个字段都可以直接访问。｜因此键集合覆盖两侧。',{stage:'reason'}),
 t(2,8,'迁移：只允许联合共有字段','只读 model.ts 提供 A、B。导出 SharedKey=keyof(A|B)，实现 common(value:A|B,key:SharedKey):(A|B)[SharedKey]。只允许不经收窄也能访问的公共键；测试会新增双方共有字段。',
  {'main.ts':'import type {A,B} from "./model";\nexport type SharedKey=keyof A|keyof B;\nexport function common(value:A|B,key:SharedKey):unknown{return value[key];}'},
  {'main.ts':'import type {A,B} from "./model";\nexport type SharedKey=keyof(A|B);\nexport function common(value:A|B,key:SharedKey):(A|B)[SharedKey]{return value[key];}'},[
   ok('公共 ID 可读取','import {common,SharedKey} from "./main";const key:SharedKey="id";const id:string=common({id:"a",name:"Lin"},key);'),
   bad('单侧字段不能作为公共键','import {SharedKey} from "./main";const key:SharedKey="name";'),
   {...ok('新增公共键自动加入','import {SharedKey,common} from "./main";const key:SharedKey="active";const value:string|boolean=common({id:"a",name:"Lin",active:true},key);'),supportFiles:{'model.ts':'export type A={id:string;name:string;active:boolean};export type B={id:string;price:number;active:boolean};'}},
  ],'keyof(A|B) 与 keyof A | keyof B 不同：前者表示联合可安全访问的公共键，后者包含所有单侧键。模型变化时真实派生会自动更新。','先决定要公共键还是所有键。｜这里不能预先知道是哪一个分支。｜对整个联合应用 keyof。',{
   supportFiles:{'model.ts':'export type A={id:string;name:string};export type B={id:string;price:number};'},
   runtime:[run('两种分支都能读取公共 ID','const {common}=load("main.js");equal(common({id:"a",name:"Lin"},"id"),"a");equal(common({id:"b",price:3},"id"),"b");')],
  }),
 m(2,9,'复测：可选属性仍属于键集合','type User={id:string;nickname?:string}，keyof User 是否包含 nickname？',['包含，键合法与值是否存在是两回事','不包含，keyof 忽略所有可选字段','只在运行对象真的有 nickname 时包含','只在关闭 strict 时包含'],'keyof 描述类型声明允许的属性名。可选字段仍是已知字段，读取值时才需要考虑 undefined。','问号允许省略，不等于属性名不存在于模型。｜键集合来自类型。｜读取类型负责表达缺失。'),
 t(2,10,'复测：组合模型的全部键','只读 model.ts 提供 Identity 与 Details。导出 Full=Identity&Details、FullKey=keyof Full，并实现 keysAllowed(...keys:FullKey[]):FullKey[] 原样收集键。模型增删字段后键集合必须跟随。',
  {'main.ts':'import type {Identity,Details} from "./model";\nexport type Full=Identity&Details;\nexport type FullKey="id"|"name";\nexport function keysAllowed(...keys:FullKey[]):FullKey[]{return keys;}'},
  {'main.ts':'import type {Identity,Details} from "./model";\nexport type Full=Identity&Details;\nexport type FullKey=keyof Full;\nexport function keysAllowed(...keys:FullKey[]):FullKey[]{return keys;}'},[
   ok('当前两侧键都合法','import {keysAllowed} from "./main";keysAllowed("id","name");'),
   bad('未声明键被拒绝','import {keysAllowed} from "./main";keysAllowed("missing");'),
   {...ok('新增字段进入键集合','import {keysAllowed} from "./main";keysAllowed("id","name","active");'),supportFiles:{'model.ts':'export type Identity={id:string};export type Details={name:string;active:boolean};'}},
   {...bad('删除字段退出键集合','import {keysAllowed} from "./main";keysAllowed("name");'),supportFiles:{'model.ts':'export type Identity={id:string};export type Details={active:boolean};'}},
  ],'对组合模型整体求 keyof，避免维护另一份容易过期的键列表。增删模型的测试同时验证键集合能够扩大与缩小。','Full 已经组合了源类型。｜不要再手写它的字段名。｜FullKey 直接使用 keyof Full。',{
   supportFiles:{'model.ts':'export type Identity={id:string};export type Details={name:string};'},
   runtime:[run('保持键顺序和重复项','const {keysAllowed}=load("main.js");equal(keysAllowed("name","id","name"),["name","id","name"]);equal(keysAllowed(),[]);')],
  }),
 m(3,1,'两个 typeof 的不同用途','const config={retries:3}; type Config=typeof config 与 const label=typeof config 中，两个 typeof 分别做什么？',['前者获取静态类型，后者在运行时得到 "object"','两者都返回字符串 "object"','两者都生成接口','前者复制对象，后者冻结对象'],'类型位置的 typeof 引用值的静态类型，编译后被擦除；表达式位置的 typeof 是 JavaScript 运算符，产生类型分类字符串。','观察 typeof 出现在类型声明还是表达式中。｜前者结果是类型。｜后者结果是运行时字符串。'),
 m(3,2,'从 const 对象获取的类型','const config={mode:"light",retries:3}; type Config=typeof config。没有 as const 时，mode 通常是什么类型？',['string，因为对象属性仍可改写','只能是字面量 "light"','readonly "light"','unknown'],'const 固定的是变量绑定，不自动让对象属性只读或保持字面量。typeof 获取已经推断出的类型，不会重新替你收窄。','能否执行 config.mode="dark"？｜可以改属性，推断通常扩大为 string。｜typeof 只是获取这个已有结果。'),
 m(3,3,'typeof 不能当作任意表达式求值器','type Result=typeof make() 为什么不是合法的类型查询写法？',['类型查询不接受这种函数调用表达式；可从返回值变量获取类型，或使用 ReturnType<typeof make>','因为 make 不能返回对象','因为 typeof 只能用于数字','因为调用会在编译时访问网络'],'类型位置 typeof 主要用于标识符及属性路径，不会执行任意表达式。函数的返回类型可以通过专门的类型工具获取。','类型检查不应执行函数来猜结果。｜先引用函数的类型。｜ReturnType 可以提取它的返回类型。',{sourceIds:['typeof','utilities']}),
 t(3,4,'让配置类型跟随真实值','只读 config.ts 导出 settings。导出 Config=typeof settings，并实现 clone(value:Config):Config，浅复制为新对象。测试会给 settings 增加字段，不允许维护一份独立字段声明。',
  {'main.ts':'import {settings} from "./config";\nexport type Config={url:string;retries:number};\nexport function clone(value:Config):Config{return {...value};}'},
  {'main.ts':'import {settings} from "./config";\nexport type Config=typeof settings;\nexport function clone(value:Config):Config{return {...value};}'},[
   ok('初始配置契约','import {Config,clone} from "./main";const c:Config={url:"/api",retries:2};const n:number=clone(c).retries;'),
   bad('字段类型仍受检查','import {Config} from "./main";const c:Config={url:"/api",retries:"2"};'),
   {...ok('新增字段自动保留','import {Config,clone} from "./main";const c:Config={url:"/api",retries:2,secure:true};const b:boolean=clone(c).secure;'),supportFiles:{'config.ts':'export const settings={url:"/api",retries:3,secure:true};'}},
  ],'真实配置值作为类型来源，typeof 避免同步维护另一份形状。对象展开执行浅复制，类型查询本身不创建副本。','settings 是值，需要查询其静态类型。｜Config 使用 typeof settings。｜复制行为仍由 {...value} 实现。',{
   supportFiles:{'config.ts':'export const settings={url:"/api",retries:3};'},
   runtime:[run('配置副本独立','const {clone}=load("main.js");const source=Object.freeze({url:"/x",retries:0});const result=clone(source);equal(result,source);check(result!==source);')],
  }),
 m(3,5,'typeof 不提供深复制或验证','把外部值断言为 typeof settings，是否会复制 settings 的默认字段或者检查外部值？',['都不会，typeof 是类型查询，断言也不执行复制或校验','会复制所有默认字段','会按 settings 的当前值逐项校验','会自动删除外部额外字段'],'类型查询只是引用静态类型。默认合并、字段清理和外部数据校验都是单独的运行操作。','表达式中是否有实际复制代码？｜是否有判断字段的代码？｜类型声明不能代替这些操作。',{stage:'reason'}),
 t(3,6,'设计与已有函数一致的接口','只读 formatter.ts 导出 format。导出 Formatter=typeof format；实现 preserve(formatter:Formatter):Formatter，原样返回函数。函数签名变化后 Formatter 应自动跟随，不能手写当前参数和返回类型。',
  {'main.ts':'import {format} from "./formatter";\nexport type Formatter=(value:number)=>string;\nexport function preserve(formatter:Formatter):Formatter{return formatter;}'},
  {'main.ts':'import {format} from "./formatter";\nexport type Formatter=typeof format;\nexport function preserve(formatter:Formatter):Formatter{return formatter;}'},[
   ok('当前函数调用契约','import {Formatter,preserve} from "./main";const f:Formatter=value=>value.toFixed(1);const s:string=preserve(f)(2);'),
   bad('当前函数拒绝文本参数','import {preserve} from "./main";preserve(value=>String(value))("2");'),
   {...ok('签名变化自动更新','import {Formatter,preserve} from "./main";const f:Formatter=(text,enabled)=>enabled?text.length:0;const n:number=preserve(f)("abc",true);'),supportFiles:{'formatter.ts':'export function format(text:string,enabled:boolean):number{return enabled?text.length:0;}'}},
  ],'typeof 对函数值取得完整调用类型，不局限于对象属性。用它建立别名可以让调用契约随原函数变化，避免两份签名漂移。','函数也是一个运行值。｜typeof format 得到它的函数类型。｜preserve 只传递引用，不改写函数。',{
   supportFiles:{'formatter.ts':'export function format(value:number):string{return value.toFixed(1);}'},
   runtime:[run('不执行或替换传入函数','const {preserve}=load("main.js");let calls=0;const f=value=>{calls++;return String(value);};const result=preserve(f);check(result===f);equal(calls,0);equal(result(2),"2");equal(calls,1);')],
  }),
 m(3,7,'先 typeof 再 keyof','已有 const routes={home:"/",login:"/login"}，为何用 keyof typeof routes 获取路由名？',['routes 是值，先取得其类型，再从类型取键','keyof 可以直接执行 routes 函数','typeof 会生成路由名数组','两个运算符只是装饰，可以删掉'],'keyof 需要类型操作数，typeof routes 把已有值的静态类型带入类型表达式。结果是键的联合，不是运行时列表。','routes 位于值空间。｜类型查询搭起值到类型的引用。｜再对所得类型使用 keyof。',{stage:'reason'}),
 t(3,8,'迁移：由路由表生成合法名称','只读 routes.ts 导出 routes。导出 RouteName=keyof typeof routes，函数 path(name:RouteName):string 返回路由表对应路径。测试会新增路由，类型与查找应同步支持。',
  {'main.ts':'import {routes} from "./routes";\nexport type RouteName="home"|"login";\nexport function path(name:RouteName):string{return routes[name];}'},
  {'main.ts':'import {routes} from "./routes";\nexport type RouteName=keyof typeof routes;\nexport function path(name:RouteName):string{return routes[name];}'},[
   ok('已有路由可访问','import {RouteName,path} from "./main";const name:RouteName="home";const value:string=path(name);'),
   bad('未知路由被拒绝','import {path} from "./main";path("missing");'),
   {...ok('新增路由无需修改类型','import {RouteName,path} from "./main";const name:RouteName="profile";const value:string=path(name);'),supportFiles:{'routes.ts':'export const routes={home:"/",login:"/login",profile:"/me"};'}},
  ],'路由表成为名称和路径的共同来源。typeof 获取表结构，keyof 生成可用名称，实际读取仍是 routes[name]。','不要重复手写路由名称。｜对 routes 先 typeof 再 keyof。｜新字段会自动进入合法键范围。',{
   supportFiles:{'routes.ts':'export const routes={home:"/",login:"/login"};'},
   runtime:[run('返回对应路径','const {path}=load("main.js");equal(path("home"),"/");equal(path("login"),"/login");')],
  }),
 m(3,9,'复测：查询嵌套属性类型','const app={network:{retries:3,timeout:1000}}。type Network=typeof app.network 是否只取得嵌套 network 的类型？',['是，可以通过属性路径查询已存在值的静态类型','否，typeof 永远返回整个 app 类型','否，点语法只能在运行表达式使用','是，但查询会删除 app.network'],'类型查询支持属性路径，适合从某个真实值中引用嵌套部分。它既不复制也不改变原对象。','app.network 是可查询的值路径。｜只查询该路径指向的静态类型。｜没有运行时修改发生。'),
 t(3,10,'复测：从嵌套默认值推导网络配置','只读 defaults.ts 导出 defaults={network:{retries:3,timeout:1000},theme:"light"}。导出 Network=typeof defaults.network，实现 totalTimeout(config:Network):number，返回 (retries+1)*timeout。测试会增加网络配置字段，Network 应自动要求该字段。',
  {'main.ts':'import {defaults} from "./defaults";\nexport type Network={retries:number;timeout:number};\nexport function totalTimeout(config:Network):number{return (config.retries+1)*config.timeout;}'},
  {'main.ts':'import {defaults} from "./defaults";\nexport type Network=typeof defaults.network;\nexport function totalTimeout(config:Network):number{return (config.retries+1)*config.timeout;}'},[
   ok('仅接收网络部分','import {Network,totalTimeout} from "./main";const c:Network={retries:2,timeout:100};const n:number=totalTimeout(c);'),
   bad('不能混成整个配置对象','import {Network} from "./main";const c:Network={network:{retries:2,timeout:100},theme:"dark"};'),
   {...ok('嵌套新增字段自动可用','import {Network} from "./main";const c:Network={retries:2,timeout:100,secure:true};const secure:boolean=c.secure;'),supportFiles:{'defaults.ts':'export const defaults={network:{retries:3,timeout:1000,secure:true},theme:"light"};'}},
   {...bad('新增必需字段不能省略','import {Network} from "./main";const c:Network={retries:2,timeout:100};'),supportFiles:{'defaults.ts':'export const defaults={network:{retries:3,timeout:1000,secure:true},theme:"light"};'}},
  ],'查询嵌套值可让局部模型跟随真实默认配置。数值计算仍是业务实现；这里 retries 表示额外重试次数，因此总尝试次数加一。','查询路径应止于 defaults.network。｜保留新增字段的必需性。｜计算包括首次尝试。',{
   supportFiles:{'defaults.ts':'export const defaults={network:{retries:3,timeout:1000},theme:"light"};'},
   runtime:[run('包含首次尝试的预算','const {totalTimeout}=load("main.js");equal(totalTimeout({retries:0,timeout:100}),100);equal(totalTimeout({retries:2,timeout:100}),300);equal(totalTimeout({retries:2,timeout:0}),0);')],
  }),
 m(4,1,'类型索引读取什么','type User={name:string;age:number}; type Age=User["age"] 得到什么？',['number','"age"','某个用户当前的年龄值','keyof User'],'类型索引查询属性的静态类型，不执行运行时读取，也不产生字段名联合。','方括号左侧是类型。｜右侧选择属性名。｜结果为该属性的值类型。'),
 m(4,2,'多个属性一起索引','User["name"|"age"] 为什么得到 string|number？',['类型索引分别读取候选字段，再合并值类型','自动生成包含两个字段的新对象','只取后一个 age','把两个值转换为字符串'],'联合键索引取得多个属性的值类型联合，不等于 Pick 那样保留字段结构，也不保留单个键与值的配对。','结果是属性值类型，不是对象。｜两个字段分别是 string 和 number。｜候选结果合成联合。'),
 m(4,3,'数组的 number 索引','type Item=readonly {id:string}[]; Item[number] 表示什么？',['数组任意元素的类型 {id:string}','数组的 length 类型','索引必须恰好名为 number','一个新的可变数组'],'在类型位置用 number 索引数组得到元素类型。readonly 约束容器变更，不会把元素类型自动变成数组。','number 代表数值索引类型。｜询问该位置存放哪种元素。｜结果不再是数组容器。'),
 t(4,4,'让字段类型跟随模型','只读 model.ts 导出 User。导出 Age=User["age"]，实现 keep(value:Age):Age 原样返回。测试会改变 age 的类型，不能写死为 number。',
  {'main.ts':'import type {User} from "./model";\nexport type Age=number;\nexport function keep(value:Age):Age{return value;}'},
  {'main.ts':'import type {User} from "./model";\nexport type Age=User["age"];\nexport function keep(value:Age):Age{return value;}'},[
   ok('当前年龄类型','import {Age,keep} from "./main";const age:Age=2;const n:number=keep(age);'),
   bad('当前年龄不接受文本','import {Age} from "./main";const age:Age="2";'),
   {...ok('源字段变化后自动跟随','import {Age,keep} from "./main";const age:Age={years:2};const n:number=keep(age).years;'),supportFiles:{'model.ts':'export type User={name:string;age:{years:number}};'}},
  ],'索引访问避免重复声明属性类型。源字段改成结构化年龄后，Age 与函数契约应自动更新，而不是继续接受旧数字。','直接引用 User 的 age 属性类型。｜不要在派生处手写 number。｜使用 User["age"]。',{
   supportFiles:{'model.ts':'export type User={name:string;age:number};'},
   runtime:[run('原值保持','const {keep}=load("main.js");equal(keep(0),0);equal(keep(20),20);')],
  }),
 m(4,5,'可选字段的索引结果','type User={nickname?:string}; User["nickname"] 是否包含 undefined？',['包含，读取可选字段仍可能缺失','不包含，索引访问让字段必需','只有运行时索引才包含','结果是 never'],'索引访问保留属性读取时的类型信息。若需要去掉空值，应明确使用额外类型操作，并确保对应运行逻辑真实验证。','可选属性允许不存在。｜类型索引不会验证某个具体对象。｜所以仍保留 undefined。',{stage:'reason'}),
 t(4,6,'从集合类型派生元素','只读 model.ts 提供 Rows。导出 Row=Rows[number]；实现 first(rows:Rows):Row|undefined，返回第一项或 undefined。元素模型增加字段后 Row 必须自动包含该字段。',
  {'main.ts':'import type {Rows} from "./model";\nexport type Row={id:string};\nexport function first(rows:Rows):Row|undefined{return rows[0];}'},
  {'main.ts':'import type {Rows} from "./model";\nexport type Row=Rows[number];\nexport function first(rows:Rows):Row|undefined{return rows[0];}'},[
   ok('获取元素而非数组类型','import {Row,first} from "./main";const row:Row={id:"a"};const value:Row|undefined=first([row]);'),
   bad('元素不是容器','import {Row} from "./main";const row:Row=[{id:"a"}];'),
   {...ok('元素新增字段自动进入结果','import {Row,first} from "./main";const row:Row={id:"a",active:true};const result=first([row]);if(result){const b:boolean=result.active;}'),supportFiles:{'model.ts':'export type Rows=readonly {id:string;active:boolean}[];'}},
  ],'Rows[number] 提取数组元素，函数额外保留空集合可能产生的 undefined。元素派生与数组非空性是不同问题。','number 索引描述任意元素位置。｜返回可能为空不能省略 undefined。｜运行时读取索引零。',{
   supportFiles:{'model.ts':'export type Rows=readonly {id:string}[];'},
   runtime:[run('空集合与原元素引用','const {first}=load("main.js");equal(first([]),undefined);const row={id:"a"};check(first(Object.freeze([row]))===row);')],
  }),
 m(4,7,'元组索引与数组索引','type Pair=[string,number]，Pair[0] 和 Pair[number] 分别是什么？',['string 与 string|number','都为 string','都为 number','string 与 [string,number]'],'固定数字索引保留指定位置；number 覆盖所有数值位置，结果合并所有元素类型。不要把所有元素联合当作整个元组。','0 指向一个明确位置。｜number 表示可能的数值位置。｜两者精度不同。',{stage:'reason'}),
 t(4,8,'迁移：提取事件载荷','只读 events.ts 提供 Event，其 payload 可以是两种对象。导出 Payload=Event["payload"]；实现 payloadOf(event:Event):Payload 返回原载荷，不复制。事件模型新增载荷分支时必须自动支持。',
  {'main.ts':'import type {Event} from "./events";\nexport type Payload={text:string}|{count:number};\nexport function payloadOf(event:Event):Payload{return event.payload;}'},
  {'main.ts':'import type {Event} from "./events";\nexport type Payload=Event["payload"];\nexport function payloadOf(event:Event):Payload{return event.payload;}'},[
   ok('当前载荷两种形状','import {Payload,payloadOf} from "./main";const a:Payload={text:"a"};const b:Payload={count:0};payloadOf({payload:a});'),
   bad('载荷不接受原始文本','import {Payload} from "./main";const p:Payload="a";'),
   {...ok('新增载荷分支自动可用','import {Payload,payloadOf} from "./main";const p:Payload={done:true};payloadOf({payload:p});'),supportFiles:{'events.ts':'export type Event={payload:{text:string}|{count:number}|{done:boolean}};'}},
  ],'属性本身若是联合，索引访问就保留这个联合。不要在另一个位置重复枚举分支，否则新增事件载荷后容易遗漏更新。','唯一载荷定义位于 Event。｜通过属性索引取得它。｜实现返回 event.payload。',{
   supportFiles:{'events.ts':'export type Event={payload:{text:string}|{count:number}};'},
   runtime:[run('载荷保持原引用','const {payloadOf}=load("main.js");const value={count:0};check(payloadOf({payload:value})===value);equal(payloadOf({payload:{text:""}}),{text:""});')],
  }),
 m(4,9,'复测：值变量不能直接当类型键','const key="age"; type Age=User[key] 为什么不正确？',['key 是值变量，类型索引需要类型，可使用 User[typeof key]','所有属性索引必须使用数字','const 变量不能保存键','必须把 key 改名为 Age'],'类型位置不能把普通值名直接当类型名。typeof key 可以查询其字面量类型，再用于类型索引。','key 声明在值空间。｜索引表达式这里需要类型。｜用 typeof 将其静态类型带入。'),
 t(4,10,'复测：从嵌套响应数组获取实体','只读 api.ts 导出 Response={data:{items:readonly {id:string}[]};total:number}。导出 Entity=Response["data"]["items"][number]；实现 ids(items:readonly Entity[]):string[]，按顺序返回 id。实体新增字段后 Entity 自动更新。',
  {'main.ts':'import type {Response} from "./api";\nexport type Entity={id:string};\nexport function ids(items:readonly Entity[]):string[]{return items.map(item=>item.id);}'},
  {'main.ts':'import type {Response} from "./api";\nexport type Entity=Response["data"]["items"][number];\nexport function ids(items:readonly Entity[]):string[]{return items.map(item=>item.id);}'},[
   ok('嵌套数组元素可用','import {Entity,ids} from "./main";const entity:Entity={id:"a"};const values:string[]=ids([entity]);'),
   bad('元素必须有 ID','import {Entity} from "./main";const entity:Entity={};'),
   {...ok('深层实体新增字段被保留','import {Entity} from "./main";const entity:Entity={id:"a",name:"Lin"};const name:string=entity.name;'),supportFiles:{'api.ts':'export type Response={data:{items:readonly {id:string;name:string}[]};total:number};'}},
  ],'逐层索引沿着响应结构定位实体类型，最后用 number 提取数组元素。这样响应模型变化会传播到依赖类型，而不必维护重复接口。','先取得 data，再取得 items。｜此时仍是数组类型。｜最后用 [number] 提取元素。',{
   supportFiles:{'api.ts':'export type Response={data:{items:readonly {id:string}[]};total:number};'},
   runtime:[run('按原序提取 ID','const {ids}=load("main.js");equal(ids(Object.freeze([{id:"b"},{id:"a"},{id:"b"}])),["b","a","b"]);equal(ids([]),[]);')],
  }),
 m(5,1,'const 绑定与 const 断言','const a={mode:"dark"}; const b={mode:"dark"} as const。二者的 mode 类型有何区别？',['a.mode 通常为可写 string，b.mode 为只读字面量 "dark"','二者都只读且为 "dark"','a 比 b 更严格','b 会在运行时复制 a'],'const 绑定不禁止对象属性变化。const 断言保留字面量，并对该字面量结构提供只读属性信息。','关注属性而非变量绑定。｜a.mode 仍然可写。｜b 保留具体字面量并限制写入。'),
 m(5,2,'常量数组的推断','const point=[1,2] as const 的类型更接近哪一个？',['readonly [1,2]','number[]','readonly number 且不是数组','[number,number] 且可以写入任意数字'],'数组字面量使用 const 断言可以形成只读元组，同时保留位置上的具体字面量值。它仍然是运行时数组。','位置数量已明确。｜每个位置也有具体值。｜只读元组同时表达这两部分信息。'),
 m(5,3,'as const 会冻结对象吗','const config={mode:"dark"} as const，是否等价于在运行时执行 Object.freeze？',['不等价，const 断言不生成冻结操作','等价，两者都会递归冻结','等价，但只在严格模式冻结','不等价，因为 as const 会删除对象'],'as const 只改变类型推断；Object.freeze 是实际运行操作，而且其冻结也不是默认递归。不要用静态只读推断运行时不可修改。','查看编译后的断言是否还存在。｜类型操作不会调用 Object.freeze。｜运行时防修改需要单独实现。'),
 t(5,4,'修复判别字段被扩大','导出 action，运行值为 {type:"increment",amount:1}。要求 type 精确为 "increment"、amount 精确为 1，两个属性都只读。使用 const 断言或等价精确只读类型，不做运行时冻结。',
  'export const action={type:"increment",amount:1};',
  'export const action={type:"increment",amount:1} as const;',[
   ok('精确的判别与数值','import {action} from "./main";const type:"increment"=action.type;const amount:1=action.amount;'),
   bad('即使同值也不允许写入','import {action} from "./main";action.type="increment";'),
   bad('数值属性不可写','import {action} from "./main";action.amount=1;'),
  ],'const 断言使字面量保持精确信息，便于作为判别联合成员使用。只读赋值测试使用相同值，避免仅靠字面量类型限制掩盖缺少 readonly 的问题。','普通 const 对象仍有可写属性。｜需要保留具体值与只读修饰。｜在对象字面量后使用 as const。',{
   runtime:[run('值保持且没有运行冻结','const {action}=load("main.js");equal(action,{type:"increment",amount:1});equal(Object.isFrozen(action),false);')],
  }),
 m(5,5,'外部引用不会自动深只读','const values=[1,2]; const box={values} as const。box.values.push(3) 为什么仍可能合法？',['const 断言保留 values 原有的可变数组类型，只限制 box.values 被替换','as const 完全不限制任何属性','push 会自动创建副本','只有数字 3 可以被追加'],'字面量内部的引用保留被引用值的既有类型。const 断言不是把任意已有对象图递归转换为不可变结构的工具。','values 先前是什么类型？｜被引用时仍是 number[]。｜只读引用与只读数组不是同一约束。',{stage:'reason'}),
 t(5,6,'设计精确的状态常量表','导出 states，值为 {idle:"IDLE",loading:"LOADING",done:"DONE"}，属性只读且保留字面量；导出 State=(typeof states)[keyof typeof states]。合法 State 只能是三个大写值。',
  'export const states={idle:"IDLE",loading:"LOADING",done:"DONE"};\nexport type State=(typeof states)[keyof typeof states];',
  'export const states={idle:"IDLE",loading:"LOADING",done:"DONE"} as const;\nexport type State=(typeof states)[keyof typeof states];',[
   ok('合法状态值','import {State,states} from "./main";const a:State="IDLE";const b:State="LOADING";const c:State="DONE";const exact:"IDLE"=states.idle;'),
   bad('普通文本不是状态','import {State} from "./main";const a:State="OTHER";'),
   bad('键名不等于状态值','import {State} from "./main";const a:State="idle";',[2322,2820]),
   bad('常量表属性不可写','import {states} from "./main";states.idle="IDLE";'),
  ],'先保留对象的字面量值，再用索引访问提取值联合。若值已扩大为 string，索引访问无法凭空恢复三个具体状态。','keyof 取得键，不是值。｜值联合需要对象类型再索引键联合。｜先用 as const 保留精确值。',{
   runtime:[run('常量表与声明一致','const {states}=load("main.js");equal(states,{idle:"IDLE",loading:"LOADING",done:"DONE"});')],
  }),
 m(5,7,'不能事后恢复所有字面量','const input=someFunction(); 直接对任意 input 写 input as const，为何通常不是合法修复？',['const 断言只能用于受支持的字面量等表达式，不能任意恢复已有变量丢失的信息','因为 const 断言只能用于字符串','因为函数结果永远是 any','因为必须先执行 Object.freeze'],'const 断言有语法适用范围，不是将任何表达式强行变成精确常量的万能操作。应在创建字面量时保留信息，或设计合适的返回契约。','已有变量未必保留最初字面量。｜断言并不执行反向推断。｜从值的构造位置处理更可靠。',{stage:'reason'}),
 t(5,8,'迁移：固定位置的请求描述','导出 request，其运行值为 ["GET","/users"]。要求类型为 readonly ["GET","/users"]；实现 describe() 返回 request[0]+" "+request[1]。不冻结数组。',
  'export const request=["GET","/users"];\nexport function describe():string{return request[0]+" "+request[1];}',
  'export const request=["GET","/users"] as const;\nexport function describe():string{return request[0]+" "+request[1];}',[
   ok('位置与字面量精确','import {request,describe} from "./main";const tuple:readonly ["GET","/users"]=request;const method:"GET"=request[0];const path:"/users"=request[1];const text:string=describe();'),
   bad('数组不可追加','import {request} from "./main";request.push("GET");'),
   bad('已有位置不可改写','import {request} from "./main";request[0]="GET";'),
   bad('不存在第三个位置','import {request} from "./main";request[2];',[2493]),
  ],'const 断言将数组字面量推断为精确只读元组，保留请求方法与路径的固定位置。它不会在运行时把数组变成另一种结构。','普通数组推断不保留固定长度。｜需要只读元组与具体值。｜在数组字面量后加 as const。',{
   runtime:[run('仍是普通数组值','const {request,describe}=load("main.js");check(Array.isArray(request));equal(request,["GET","/users"]);equal(describe(),"GET /users");equal(Object.isFrozen(request),false);')],
  }),
 m(5,9,'复测：只读数组交给可变参数','一个 as const 数组不能传给要求 string[] 的函数时，若函数确实只读取输入，优先怎样修改？',['将函数参数改为 readonly string[]','用双重断言抹掉只读','把所有常量数组改成 any','让函数运行前删除 readonly 属性'],'只读参数表达读取需求，既能接收可变数组，也能接收只读元组。readonly 是类型修饰，不是可删除的运行属性。','先判断被调用函数是否真的需要写入。｜读取契约可以接收更多输入。｜调整参数比绕过检查更合理。'),
 t(5,10,'复测：从只读选项元组导出值联合','导出 sizes=["small","medium","large"] 的只读精确元组，导出 Size=(typeof sizes)[number]，实现 indexOf(size:Size):number 返回对应索引。拒绝其他尺寸字符串。',
  'export const sizes=["small","medium","large"];\nexport type Size=(typeof sizes)[number];\nexport function indexOf(size:Size):number{return sizes.indexOf(size);}',
  'export const sizes=["small","medium","large"] as const;\nexport type Size=(typeof sizes)[number];\nexport function indexOf(size:Size):number{return sizes.indexOf(size);}',[
   ok('合法尺寸集合','import {Size,sizes,indexOf} from "./main";const s:Size="medium";const tuple:readonly ["small","medium","large"]=sizes;const n:number=indexOf(s);'),
   bad('拒绝未知尺寸','import {indexOf} from "./main";indexOf("huge");'),
   bad('常量数组不可改写','import {sizes} from "./main";sizes[0]="small";'),
  ],'typeof sizes 取得只读元组，number 索引提取各位置值的联合。如果缺少 const 断言，元素类型会扩大为 string，无法限制尺寸范围。','先保留元组元素的字面量。｜再用 number 索引提取元素联合。｜运行查找复用同一份 sizes。',{
   runtime:[run('类型与查找共用选项表','const {sizes,indexOf}=load("main.js");equal(sizes,["small","medium","large"]);equal(indexOf("small"),0);equal(indexOf("medium"),1);equal(indexOf("large"),2);')],
  }),
 m(6,1,'satisfies 的任务','const value=expression satisfies Target 主要做什么？',['检查表达式满足 Target，并保留有用的表达式类型信息','把任何表达式强制转换成 Target','运行时检查 JSON','自动删除额外属性'],'satisfies 是编译期兼容检查，不执行转换或运行校验。上下文可能影响推断，所以也不能笼统说它永远完全不影响推断。','先区分检查与转换。｜不兼容的表达式会报错。｜结果仍保留表达式的具体信息。'),
 m(6,2,'标注与检查的差异','配置值允许 string 或 [number,number,number]，为何用 satisfies 可以让具体颜色字段继续使用字符串方法？',['它可以检查整个配置，同时保留该字段实际推断为 string 的信息','它自动给数组添加字符串方法','它将所有字段变成 any','因为 satisfies 不检查值类型'],'显式宽标注可能让字段读取变成联合；satisfies 在验证目标约束的同时保留具体结构，减少不必要的再次收窄。','目标允许多种值不代表每个字段都必须变宽。｜实际字面量提供了具体类型。｜检查与保留推断可以同时做到。'),
 m(6,3,'是否等同于 as','不符合 Target 的值写 as Target 和 satisfies Target，为什么不能认为两者等价？',['satisfies 要求兼容，断言表达让编译器接受所声称的类型，不能替代验证','两者都自动验证运行数据','satisfies 会转换值而 as 不会','只有 as 能用于对象'],'断言与兼容检查有不同意图。satisfies 不应该被描述成更漂亮的类型强转，也不会替断言生成业务校验。','表达式是否真的满足约束是关键。｜检查失败应暴露问题。｜不要用断言消除真实的不兼容。'),
 t(6,4,'保留颜色字段的具体类型','导出 palette，值为 {red:[255,0,0],green:"#00ff00"}。检查它满足 Record<"red"|"green",string|[number,number,number]>，同时 red 应为三数字元组、green 为 string；实现 upperGreen() 返回绿色文本的大写。',
  'export const palette:Record<"red"|"green",string|[number,number,number]>={red:[255,0,0],green:"#00ff00"};\nexport function upperGreen():string{return palette.green.toUpperCase();}',
  'export const palette={red:[255,0,0],green:"#00ff00"} satisfies Record<"red"|"green",string|[number,number,number]>;\nexport function upperGreen():string{return palette.green.toUpperCase();}',[
   ok('保留每个字段的实际结构','import {palette,upperGreen} from "./main";const color:string=palette.green;const rgb:[number,number,number]=palette.red;const upper:string=upperGreen();'),
   bad('绿色字段不能写入数组','import {palette} from "./main";palette.green=[0,255,0];'),
   bad('元组不能缺少分量','import {palette} from "./main";palette.red=[1,2];'),
  ],'Record 在这里表示两个颜色键都需要存在且值符合范围。satisfies 检查范围，同时让 green 保持字符串、red 获得元组上下文。','宽标注让 green 变成联合。｜把标注换成表达式后的 satisfies 检查。｜目标中的元组也提供上下文。',{
   runtime:[run('配置值和具体方法可用','const {palette,upperGreen}=load("main.js");equal(palette,{red:[255,0,0],green:"#00ff00"});equal(upperGreen(),"#00FF00");')],
  }),
 m(6,5,'satisfies 是否只读','const config={retries:3} satisfies {retries:number} 后执行 config.retries=4，是否因为 satisfies 而被禁止？',['不会，satisfies 本身不是只读修饰','会，它等同于 as const','会，所有 const 对象都不可改属性','只在生产构建中禁止'],'满足目标类型不意味着字段被冻结或只读。需要保留只读字面量时可以结合 as const，并确保目标接受只读结构。','检查目标有没有 readonly。｜普通属性推断仍为 number。｜只读要求需要单独表达。',{stage:'reason'}),
 t(6,6,'设计只读且受检查的菜单','导出 menu，值为 [{label:"首页",path:"/"},{label:"文档",path:"/docs"}]。既保持只读元组和字面量，又检查每项有 label:string、path:string。实现 labels() 返回新的可变 string[]。',
  'export const menu=[{label:"首页",path:"/"},{label:"文档",path:"/docs"}] satisfies readonly {label:string;path:string}[];\nexport function labels():string[]{return menu.map(item=>item.label);}',
  'export const menu=[{label:"首页",path:"/"},{label:"文档",path:"/docs"}] as const satisfies readonly {label:string;path:string}[];\nexport function labels():string[]{return menu.map(item=>item.label);}',[
   ok('字面量与位置保持','import {menu,labels} from "./main";const path:"/"=menu[0].path;const label:"文档"=menu[1].label;const values:string[]=labels();values.push("其他");'),
   bad('只读项目不能改写','import {menu} from "./main";menu[0].path="/";'),
   bad('只读集合不能追加','import {menu} from "./main";menu.push({label:"首页",path:"/"});'),
  ],'as const 负责保留字面量与只读结构，satisfies 负责检查字段契约。目标数组也写 readonly，才能正确接收只读元组。','两个操作各有职责。｜在字面量后先 as const 再 satisfies。｜labels 使用 map 创建新数组。',{
   runtime:[run('只读配置生成可变结果','const {menu,labels}=load("main.js");equal(menu,[{label:"首页",path:"/"},{label:"文档",path:"/docs"}]);const values=labels();values.push("其他");equal(labels(),["首页","文档"]);')],
  }),
 m(6,7,'可选属性不会自动补齐','const config={host:"localhost"} satisfies {host:string;port?:number} 后，config.port 是否自动成为可读属性？',['不会，检查通过不代表在结果类型或运行对象中补出缺省字段','会，值自动设为 undefined','会，值自动设为 80','只在启用 strict 时补齐'],'satisfies 检查输入符合可选契约，但表达式本身没有 port。它不会把目标中所有可选字段都添加到表达式结构。','原对象实际提供了哪些字段？｜可选表示可以不提供。｜检查不会补造属性。',{stage:'reason'}),
 t(6,8,'迁移：修复配置键拼写并保留精确类型','导出 routes，键只能且必须为 home、docs，每项有 path:string 与 auth:boolean。home 为 {path:"/",auth:false}，docs 为 {path:"/docs",auth:true}。用 const 断言与 satisfies 或等价精确检查保持字面量和只读。',
  'export const routes={home:{path:"/",auth:false},doc:{path:"/docs",auth:true}} as const satisfies Record<"home"|"docs",{path:string;auth:boolean}>;',
  'export const routes={home:{path:"/",auth:false},docs:{path:"/docs",auth:true}} as const satisfies Record<"home"|"docs",{path:string;auth:boolean}>;',[
   ok('键和字段精确','import {routes} from "./main";const path:"/docs"=routes.docs.path;const auth:false=routes.home.auth;const whole:Record<"home"|"docs",{path:string;auth:boolean}>=routes;'),
   bad('拼错的键不存在','import {routes} from "./main";routes.doc;'),
   bad('字段只读','import {routes} from "./main";routes.docs.auth=true;'),
  ],'固定键 Record 可以在配置声明处发现漏写和拼错。const 断言保留具体路径与布尔字面量；修复应更正数据，而不是扩大目标键集合。','对照要求中的 docs 与初始 doc。｜固定键检查指出了真正的问题。｜修正键名并保留检查。',{
   runtime:[run('声明与实际路由表一致','const {routes}=load("main.js");equal(routes,{home:{path:"/",auth:false},docs:{path:"/docs",auth:true}});')],
  }),
 m(6,9,'复测：上下文可能影响推断','为什么“satisfies 永远完全不影响推断结果”不够准确？',['目标可以提供上下文类型，例如影响元组或字面量推断，但它不把结果简单替换成整个目标类型','因为 satisfies 会执行表达式两次','因为所有 satisfies 都把结果变成 any','因为目标类型会在运行时覆盖值'],'应区分保留表达式信息与完全不提供上下文。satisfies 的目标参与检查和上下文推断，具体结果需要结合表达式分析。','元组目标能帮助数组表达式保留位置。｜上下文影响不等于整体强制换成目标类型。｜避免使用绝对化规则。'),
 t(6,10,'复测：校验插件表并保留函数返回类型','导出 plugins，upper 为 (value:string)=>value.toUpperCase()，length 为 (value:string)=>value.length。检查表满足 Record<string,(value:string)=>string|number>，同时 upper 返回 string、length 返回 number，不要都扩大为联合。',
  'export const plugins:Record<string,(value:string)=>string|number>={upper:value=>value.toUpperCase(),length:value=>value.length};',
  'export const plugins={upper:(value:string)=>value.toUpperCase(),length:(value:string)=>value.length} satisfies Record<string,(value:string)=>string|number>;',[
   ok('具体插件保持各自结果','import {plugins} from "./main";const a:string=plugins.upper("x");const b:number=plugins.length("x");'),
   bad('未知插件不自动存在','import {plugins} from "./main";plugins.missing("x");'),
   bad('插件输入仍受检查','import {plugins} from "./main";plugins.upper(1);'),
  ],'目标的宽字符串索引检查已提供插件的公共能力，表达式类型仍保留实际键与每个函数的具体输出。这比给变量直接写宽 Record 更适合调用具体插件。','不要把变量整体标注为宽字典。｜在对象之后使用 satisfies。｜每个函数继续根据实现推断具体返回。',{
   runtime:[run('两类插件实际行为','const {plugins}=load("main.js");equal(plugins.upper("abc"),"ABC");equal(plugins.length("abc"),3);equal(plugins.length(""),0);')],
  }),
 m(7,1,'Partial 改变哪一层','type Config={network:{host:string;port:number}}; Partial<Config> 允许什么？',['省略 network；若提供 network，其 host 和 port 仍按原类型要求','省略任意深度的字段','自动把所有字段设为 undefined','返回一个复制后的对象'],'Partial 让第一层属性可选，不递归改变嵌套模型，也不生成运行值。深层补丁需要另行设计。','问号加在 Config 的哪些直接属性上？｜network 内部结构没有变化。｜不能省略嵌套必需 port。'),
 m(7,2,'Pick 与 Omit','从 User 中只保留 id、name，Pick<User,"id"|"name"> 与 Omit<User,"secret"> 总是等价吗？',['不一定，User 若还有其他字段，Omit 会继续保留它们','永远等价','只有 Pick 会在运行时删除字段','Omit 总会把全部字段变可选'],'Pick 明确列出保留项，Omit 明确列出排除项。模型新增字段时二者传播方式不同，公开数据白名单通常应慎重选择。','假设 User 新增 email。｜两个表达式分别会保留什么？｜保留清单与排除清单不是同一种规则。'),
 m(7,3,'有限键 Record 的完整性','Record<"small"|"large",number> 是否允许只提供 small？',['不允许，两个指定键都必需','允许，Record 的键默认可选','允许，只要 small 大于零','只有运行时才检查 large'],'有限键 Record 表达每个键对应相同值类型，键默认必需。与 Record<string,number> 的开放字典性质要区分。','键集合只有两个明确成员。｜每个成员都要映射出属性。｜需要可选时再组合 Partial。'),
 t(7,4,'修复错误的部分更新契约','只读 model.ts 提供 Config。导出 Patch=Partial<Config>，实现 merge(base:Config,patch:Patch):Config，浅合并并返回新对象。开启精确可选属性，显式 undefined 不可覆盖未包含 undefined 的字段。',
  {'main.ts':'import type {Config} from "./model";\nexport type Patch=Config;\nexport function merge(base:Config,patch:Patch):Config{return {...base,...patch};}'},
  {'main.ts':'import type {Config} from "./model";\nexport type Patch=Partial<Config>;\nexport function merge(base:Config,patch:Patch):Config{return {...base,...patch};}'},[
   ok('可只更新一个字段','import {Patch,merge} from "./main";const a:Patch={};const b:Patch={retries:0};merge({host:"a",retries:3},b);'),
   bad('字段类型不因可选而改变','import {Patch} from "./main";const p:Patch={retries:"3"};'),
   bad('精确可选不接受显式 undefined','import {Patch} from "./main";const p:Patch={host:undefined};',[2375]),
   {...ok('新增字段也变为可选更新','import {Patch} from "./main";const p:Patch={secure:true};'),supportFiles:{'model.ts':'export type Config={host:string;retries:number;secure:boolean};'}},
  ],'Partial 派生可选更新字段，但保留值类型。精确可选配置让省略和显式 undefined 有区别；实际合并仍由对象展开完成，工具类型本身不会执行它。','更新不应要求完整配置。｜使用 Partial<Config>。｜浅合并需要返回新的对象。',{
   compilerOptions:{exactOptionalPropertyTypes:true},supportFiles:{'model.ts':'export type Config={host:string;retries:number};'},
   runtime:[run('补丁浅合并且不改原对象','const {merge}=load("main.js");const base=Object.freeze({host:"a",retries:3});const next=merge(base,{retries:0});equal(next,{host:"a",retries:0});check(next!==base);equal(base.retries,3);')],
  }),
 m(7,5,'Readonly 是浅层视图','Readonly<{settings:{theme:string}}> 会禁止修改 settings.theme 吗？',['不会，它禁止替换 settings，但内部 theme 仍按原类型可写','会，默认递归全部属性','会，而且运行时也冻结','不会，因为 Readonly 完全不检查赋值'],'Readonly 作用于当前对象属性层级。它是静态只读视图，不是深层不可变保证，也不执行冻结。','被修饰的是 settings 属性。｜嵌套 theme 的声明没有变。｜读取指向的对象仍可能可变。',{stage:'reason'}),
 t(7,6,'设计固定键配置表','导出 Size="small"|"medium"|"large"，Prices=Record<Size,number>。实现 total(prices:Prices,selected:readonly Size[]):number，累加选中尺寸价格，重复尺寸重复计费，空列表为 0。',
  'export type Size="small"|"medium"|"large";\nexport type Prices=Partial<Record<Size,number>>;\nexport function total(prices:Prices,selected:readonly Size[]):number{return selected.reduce((sum,size)=>sum+(prices[size]??0),0);}',
  'export type Size="small"|"medium"|"large";\nexport type Prices=Record<Size,number>;\nexport function total(prices:Prices,selected:readonly Size[]):number{return selected.reduce((sum,size)=>sum+prices[size],0);}',[
   ok('完整价格表','import {Prices,total} from "./main";const p:Prices={small:1,medium:2,large:3};const n:number=total(p,["small"]);'),
   bad('所有尺寸都需定价','import {Prices} from "./main";const p:Prices={small:1,large:3};'),
   bad('价格必须为数字','import {Prices} from "./main";const p:Prices={small:"1",medium:2,large:3};'),
   bad('不能选未知尺寸','import {total} from "./main";total({small:1,medium:2,large:3},["huge"]);'),
  ],'有限键 Record 保证每个尺寸的价格都存在，不能用 Partial 和缺省零掩盖漏配。累加逻辑还需保持重复项语义。','价格表不是可选配置。｜去掉 Partial，使有限键全部必需。｜按 selected 顺序逐项累加。',{
   runtime:[run('重复与空列表','const {total}=load("main.js");const prices={small:1,medium:2,large:3};equal(total(prices,["small","large","small"]),5);equal(total(prices,[]),0);')],
  }),
 m(7,7,'Required 不会填充值','将 Partial<Config> 直接声称为 Required<Config>，是否会自动补上缺失字段？',['不会，Required 只改变类型要求，默认值需要真实构造逻辑','会，数字补 0、字符串补空串','会，从类型名猜默认值','只在开启 strict 时填充'],'Required 把属性变成必需，但不会生成它们的值。把不完整数据断言为完整类型可能让调用方误判。','类型工具是否包含运行表达式？｜缺失字段没有真实来源。｜需要合并默认值或验证完整性。',{stage:'reason'}),
 t(7,8,'迁移：公开视图需要实际筛选','只读 model.ts 提供 User。导出 PublicUser=Pick<User,"id"|"name">；实现 publish(user:User):PublicUser，仅返回 id、name 的新对象。模型新增私有字段后不得出现在公开类型或运行结果里。',
  {'main.ts':'import type {User} from "./model";\nexport type PublicUser=Omit<User,"secret">;\nexport function publish(user:User):PublicUser{return user;}'},
  {'main.ts':'import type {User} from "./model";\nexport type PublicUser=Pick<User,"id"|"name">;\nexport function publish(user:User):PublicUser{return {id:user.id,name:user.name};}'},[
   ok('公开字段完整','import {PublicUser,publish} from "./main";const p:PublicUser={id:"a",name:"Lin"};const result:PublicUser=publish({id:"a",name:"Lin",secret:"x"});'),
   bad('公开类型没有 secret','import {PublicUser} from "./main";declare const p:PublicUser;p.secret;'),
   {...bad('新增内部字段也不进入公开类型','import {PublicUser} from "./main";declare const p:PublicUser;p.internal;'),supportFiles:{'model.ts':'export type User={id:string;name:string;secret:string;internal:boolean};'}},
  ],'白名单 Pick 与运行时显式选字段共同建立公开边界。Omit 只排除已知 secret，新内部字段可能随模型变化被保留下来；类型本身也不删除运行数据。','公开字段应明确列出保留清单。｜用 Pick 而非仅排除当前私有字段。｜返回时真正构造白名单对象。',{
   supportFiles:{'model.ts':'export type User={id:string;name:string;secret:string};'},
   runtime:[run('实际结果只含公开字段','const {publish}=load("main.js");const source=Object.freeze({id:"a",name:"Lin",secret:"x",internal:true});const result=publish(source);equal(result,{id:"a",name:"Lin"});check(result!==source);')],
  }),
 m(7,9,'复测：Exclude 与 NonNullable','Exclude<string|number|undefined,number> 和 NonNullable<string|null|undefined> 分别得到什么？',['string|undefined 与 string','string 与 never','number 与 null','两者都为 unknown'],'Exclude 从联合中排除可赋给指定类型的成员；NonNullable 排除 null 和 undefined。它们操作的是类型候选，不执行值过滤。','分别按工具的排除规则处理联合成员。｜Exclude 这里只去掉 number。｜NonNullable 去掉两种空值。'),
 t(7,10,'复测：从函数派生调用包装','只读 api.ts 导出 calculate。导出 Args=Parameters<typeof calculate>、Result=ReturnType<typeof calculate>；实现 run(...args:Args):Result，原样转发给 calculate。签名变化后参数和返回类型都应更新。',
  {'main.ts':'import {calculate} from "./api";\nexport type Args=[number,number];\nexport type Result=number;\nexport function run(...args:Args):Result{return calculate(...args);}'},
  {'main.ts':'import {calculate} from "./api";\nexport type Args=Parameters<typeof calculate>;\nexport type Result=ReturnType<typeof calculate>;\nexport function run(...args:Args):Result{return calculate(...args);}'},[
   ok('当前参数和结果契约','import {Args,Result,run} from "./main";const args:Args=[2,3];const result:Result=run(...args);const n:number=result;'),
   bad('当前参数类型不可变','import {run} from "./main";run("2",3);'),
   {...ok('签名变化自动跟随','import {Args,Result,run} from "./main";const args:Args=["a",true];const result:Result=run(...args);const s:string=result;'),supportFiles:{'api.ts':'export function calculate(text:string,upper:boolean):string{return upper?text.toUpperCase():text;}'}},
  ],'Parameters 得到参数元组，ReturnType 得到返回类型，组合起来可让包装函数跟随原函数契约。这里处理单个函数签名，重载提取还有额外规则需在进阶题中分析。','从 calculate 的函数类型提取两端。｜Parameters 保留参数位置。｜ReturnType 保留结果，运行时仍需真实转发。',{
   supportFiles:{'api.ts':'export function calculate(a:number,b:number):number{return a+b;}'},
   runtime:[run('参数原样转发','const {run}=load("main.js");equal(run(2,3),5);equal(run(-1,1),0);')],
  }),
 m(8,1,'实体不等于创建参数','User 包含 id、createdAt、name、email，创建表单只允许填写 name、email。直接让表单提交 User 有什么问题？',['要求客户端提供服务端生成字段，也混淆了字段权限','只会降低运行性能，不影响契约','会自动隐藏 id 和 createdAt','TypeScript 会替客户端生成 id'],'实体模型描述完整记录，创建输入描述客户端能提供的数据。共享类型来源不意味着所有边界使用完全相同的字段集合。','谁负责生成 id 和 createdAt？｜创建时它们尚不存在。｜输入契约应只包含可填写字段。'),
 m(8,2,'更新输入为什么不能直接 Partial<Entity>','如果 Entity 有 id、role 等不可由普通用户修改的字段，Partial<Entity> 有何风险？',['它仍允许提交这些字段，只是让它们可选','它会自动把字段标为只读','它禁止一切更新','它会在运行时丢弃敏感字段'],'Partial 只改变必需性，不改变字段是否允许出现在更新请求中。应先挑选可写字段，再将它们变成可选。','问号不代表禁止写入。｜检查可写字段集合是否正确。｜先 Pick 再 Partial。'),
 m(8,3,'派生字段还是复制字段定义','CreateUser 中 name、email 的值类型最好怎样维护？',['从 User 挑选字段，让源字段类型变化能传播','另写一份相同字段并永不更新','全部写成 string 以避免变动','全部写成 any 兼容以后变化'],'从单一模型派生可以减少字段值类型漂移，但仍需独立选择各个边界允许的字段集合。复用结构不等于复用全部权限。','哪些信息应复用，哪些是边界自身的选择？｜值类型来自实体。｜字段范围来自创建需求。'),
 t(8,4,'修复创建接口的服务端字段要求','只读 model.ts 提供 User。导出 CreateUser=Pick<User,"name"|"email">；实现 create(input:CreateUser,id:string,createdAt:number):User，构造完整用户，服务端参数决定 id 和 createdAt。',
  {'main.ts':'import type {User} from "./model";\nexport type CreateUser=User;\nexport function create(input:CreateUser,id:string,createdAt:number):User{return {...input,id,createdAt};}'},
  {'main.ts':'import type {User} from "./model";\nexport type CreateUser=Pick<User,"name"|"email">;\nexport function create(input:CreateUser,id:string,createdAt:number):User{return {name:input.name,email:input.email,id,createdAt};}'},[
   ok('只需提供可填写字段','import {CreateUser,create} from "./main";const input:CreateUser={name:"Lin",email:"a@example.com"};const user=create(input,"u1",1);const id:string=user.id;'),
   bad('创建字段仍然必需','import {CreateUser} from "./main";const input:CreateUser={name:"Lin"};'),
   bad('输入类型不暴露服务端 ID','import {CreateUser} from "./main";declare const input:CreateUser;input.id;'),
   {...ok('源字段类型变化会传播','import {CreateUser} from "./main";const input:CreateUser={name:"Lin",email:{address:"a@example.com"}};'),supportFiles:{'model.ts':'export type User={id:string;createdAt:number;name:string;email:{address:string}};'}},
  ],'创建输入选择允许填写的字段，生成字段由单独的服务端参数提供。显式构造结果也避免已有宽对象夹带其他属性。','不要要求表单提交完整 User。｜Pick 出 name、email。｜返回时使用独立 id、createdAt 参数。',{
   supportFiles:{'model.ts':'export type User={id:string;createdAt:number;name:string;email:string};'},
   runtime:[run('服务端字段不可被输入覆盖','const {create}=load("main.js");const input={name:"Lin",email:"a@example.com",id:"forged",createdAt:999,role:"admin"};equal(create(input,"u1",1),{id:"u1",createdAt:1,name:"Lin",email:"a@example.com"});')],
  }),
 m(8,5,'编译期白名单不代替运行边界','函数参数写成 Pick<User,"name">，是否保证收到的实际对象绝不含 role？',['不保证，结构兼容或外部输入可能携带额外字段，运行更新应只选择允许字段','保证，编译器会删除 role','保证，Pick 自动生成校验器','只在生产环境保证'],'类型视图不清理数据。处理请求时应实际校验并选择允许字段，不能把类型白名单误当成运行时安全过滤。','已有对象可包含更多字段。｜传参不会自动复制或删除。｜实际更新也应使用白名单字段。',{stage:'reason'}),
 t(8,6,'设计安全的用户补丁','只读 model.ts 提供 User。导出 Patch=Partial<Pick<User,"name"|"email">>。实现 update(user:User,patch:Patch):User，返回新对象，仅在对应补丁值不为 undefined 时更新 name、email，其他原字段完整保留。',
  {'main.ts':'import type {User} from "./model";\nexport type Patch=Partial<User>;\nexport function update(user:User,patch:Patch):User{return {...user,...patch};}'},
  {'main.ts':'import type {User} from "./model";\nexport type Patch=Partial<Pick<User,"name"|"email">>;\nexport function update(user:User,patch:Patch):User{return {...user,name:patch.name??user.name,email:patch.email??user.email};}'},[
   ok('允许局部及空补丁','import {Patch} from "./main";const a:Patch={};const b:Patch={name:""};const c:Patch={email:undefined};'),
   bad('补丁不允许 ID 字段','import {Patch} from "./main";const p:Patch={id:"forged"};'),
   bad('补丁不允许角色字段','import {Patch} from "./main";const p:Patch={role:"admin"};'),
   {...bad('新增服务端字段不进入补丁','import {Patch} from "./main";const p:Patch={verified:true};'),supportFiles:{'model.ts':'export type User={id:string;role:string;name:string;email:string;verified:boolean};'}},
  ],'先选择可写字段，再将它们可选化。运行更新同样只读取这两个字段，避免宽对象中的 id、role 或新增字段覆盖原记录。','Partial<User> 范围太宽。｜用 Pick 限定可写集合。｜不要直接展开整个 patch。',{
   supportFiles:{'model.ts':'export type User={id:string;role:string;name:string;email:string};'},
   runtime:[run('静态与运行白名单一致','const {update}=load("main.js");const user=Object.freeze({id:"u1",role:"user",name:"Lin",email:"a",verified:false});const next=update(user,{name:"",email:undefined,id:"forged",role:"admin",verified:true});equal(next,{id:"u1",role:"user",name:"",email:"a",verified:false});check(next!==user);')],
  }),
 m(8,7,'列表视图选择策略','列表只展示 id、title，源实体今后还会增加内部字段。选择 Pick<Entity,"id"|"title"> 有什么维护优势？',['新增无关字段不会自动进入列表视图，同时现有字段类型变化可以传播','保证列表对象在运行时永远只有两个属性','自动减少网络请求字节数','自动生成数据库查询'],'白名单类型控制静态视图的字段范围；数据获取和序列化仍需实际实现。它既避免复制字段定义，也避免无关新字段扩散。','类型选择和实际数据投影分别负责什么？｜Pick 只保留指定字段。｜同名字段的值类型仍来自源实体。',{stage:'reason'}),
 t(8,8,'迁移：批量生成列表摘要','只读 model.ts 提供 Article。导出 Summary=Pick<Article,"id"|"title">；实现 summarize(items:readonly Article[]):Summary[]，按原顺序为每项创建只含 id、title 的新对象。',
  {'main.ts':'import type {Article} from "./model";\nexport type Summary=Omit<Article,"body">;\nexport function summarize(items:readonly Article[]):Summary[]{return [...items];}'},
  {'main.ts':'import type {Article} from "./model";\nexport type Summary=Pick<Article,"id"|"title">;\nexport function summarize(items:readonly Article[]):Summary[]{return items.map(item=>({id:item.id,title:item.title}));}'},[
   ok('摘要类型保留展示字段','import {Summary,summarize} from "./main";const s:Summary={id:"a",title:"TS"};const items:Summary[]=summarize([{id:"a",title:"TS",body:"content"}]);'),
   bad('摘要不提供正文','import {Summary} from "./main";declare const s:Summary;s.body;'),
   {...bad('新增内部字段不会泄露到摘要类型','import {Summary} from "./main";declare const s:Summary;s.internalNote;'),supportFiles:{'model.ts':'export type Article={id:string;title:string;body:string;internalNote:string};'}},
  ],'类型白名单与运行投影相互配合。只复制数组并不会删除元素对象里的正文或私有字段，需要为每项构造摘要。','注意数组复制和元素投影的区别。｜Summary 用 Pick。｜map 中创建只含两个字段的新对象。',{
   supportFiles:{'model.ts':'export type Article={id:string;title:string;body:string};'},
   runtime:[run('每个摘要实际移除内部字段','const {summarize}=load("main.js");const a=Object.freeze({id:"b",title:"B",body:"secret",internalNote:"hidden"});const b=Object.freeze({id:"a",title:"A",body:"text"});const result=summarize(Object.freeze([a,b]));equal(result,[{id:"b",title:"B"},{id:"a",title:"A"}]);check(result[0]!==a&&result[1]!==b);equal(summarize([]),[]);')],
  }),
 m(8,9,'复测：业务规则超出字段类型','CreateUser 里 email:string 是否已经证明邮箱格式有效、账户有权限创建？',['没有，字段类型不能代替格式校验和权限判断','已经证明，Pick 会检查业务规则','只证明权限，不证明格式','只要开启 strict 就全部证明'],'模型类型表达结构和部分状态关系。格式、唯一性、权限等规则仍需相应运行校验和业务流程，不能由普通 string 自动推出。','string 包含任意文本。｜权限依赖调用者和上下文。｜类型结构只是边界的一部分。'),
 t(8,10,'复测：更新必须携带版本但不能修改身份','只读 model.ts 提供 Task。导出 Update={version:Task["version"]}&Partial<Pick<Task,"title"|"done">>。实现 apply(task:Task,input:Update):Task|undefined：版本不相等返回 undefined；相等时仅更新非 undefined 的 title、done，并将 version 加一，id 保持不变。',
  {'main.ts':'import type {Task} from "./model";\nexport type Update=Partial<Task>;\nexport function apply(task:Task,input:Update):Task|undefined{return {...task,...input};}'},
  {'main.ts':'import type {Task} from "./model";\nexport type Update={version:Task["version"]}&Partial<Pick<Task,"title"|"done">>;\nexport function apply(task:Task,input:Update):Task|undefined{if(input.version!==task.version)return undefined;return {...task,title:input.title??task.title,done:input.done??task.done,version:task.version+1};}'},[
   ok('版本必需而更新字段可选','import {Update,apply} from "./main";const input:Update={version:1};const out=apply({id:"a",title:"TS",done:false,version:1},input);'),
   bad('不能省略版本','import {Update} from "./main";const input:Update={title:"new"};'),
   bad('输入不能修改 ID','import {Update} from "./main";const input:Update={version:1,id:"forged"};'),
   bad('完成状态必须为布尔','import {Update} from "./main";const input:Update={version:1,done:"yes"};'),
  ],'更新命令不是简单的 Partial<Entity>：它组合必需的并发版本和可选的可写字段。版本比较与递增必须由运行代码执行，类型只描述需要什么输入。','把必需 version 与可选更新字段分开组合。｜先验证版本，再构造新对象。｜保留 false 和空标题，不要用 || 回退。',{
   supportFiles:{'model.ts':'export type Task={id:string;title:string;done:boolean;version:number};'},
   runtime:[run('版本检查与受限更新','const {apply}=load("main.js");const task=Object.freeze({id:"a",title:"TS",done:true,version:2});equal(apply(task,{version:1,title:"bad"}),undefined);const next=apply(task,{version:2,title:"",done:false,id:"forged"});equal(next,{id:"a",title:"",done:false,version:3});check(next!==task);equal(task.version,2);')],
  }),
];
