import { mc, task, ok, bad } from './author.mjs';
const id=n=>`t08-l${String(n).padStart(2,'0')}`;
const m=(l,n,title,prompt,options,explanation,hints,extra={})=>mc(id(l),n,title,prompt,options,explanation,hints.split('｜'),extra);
const t=(l,n,title,prompt,files,solution,tests,explanation,hints,extra={})=>task(id(l),n,title,prompt,files,solution,tests,explanation,hints.split('｜'),extra);
export const questions=[
 m(1,1,'extends 在条件类型中的含义','type Check<T>=T extends string?"yes":"no" 中 extends 主要检查什么？',['T 是否可赋给 string，而非是否通过 class extends 继承','T 的变量名是否为 string','T 的运行值是否非空','是否已经创建过 String 实例'],'条件类型依据类型可赋值关系选择分支。它不要求类继承，也不执行运行时检测。','这里操作的是类型。｜字符串字面量也能满足 string。｜关注可赋值关系。'),
 m(1,2,'字面量能满足基础类型','type Kind<T>=T extends string?"text":"other"。Kind<"ready"> 是什么？',['"text"','"other"','string','boolean'],'字符串字面量类型可以赋给 string，因此选择真分支。类型更具体并不意味着不属于基础类型。','"ready" 是哪种值的子范围？｜它属于字符串。｜条件选择 text。'),
 m(1,3,'条件类型会生成运行分支吗','声明 type Kind<T>=T extends string?"text":"other" 后，是否会自动在运行时检测传入值？',['不会，类型运算被擦除，运行判断需另写代码','会，自动生成 typeof 检查','会，但只对泛型函数生效','会，把所有非字符串转换为文本'],'条件类型是静态关系计算，不是运行时转换。函数若承诺不同输入返回不同结构，仍要实现实际分支。','type 声明是否保留在 JavaScript 中？｜没有执行函数或判断表达式。｜不能依赖它处理真实数据。'),
 t(1,4,'修复分支方向','导出 Kind<T>，当 T 可赋给 string 时结果为 "text"，否则为 "other"。本题先使用非联合输入，后续小节再讨论联合分布。',
  'export type Kind<T>=T extends string?"other":"text";',
  'export type Kind<T>=T extends string?"text":"other";',[
   ok('文本与非文本分类','import type {Kind} from "./main";const a:Kind<string>="text";const b:Kind<"ready">="text";const c:Kind<number>="other";const d:Kind<{name:string}>="other";'),
   bad('数字不能选择文本分支','import type {Kind} from "./main";const value:Kind<number>="text";'),
   bad('字符串不能选择其他分支','import type {Kind} from "./main";const value:Kind<string>="other";'),
  ],'问号后的类型是真分支，冒号后的类型是假分支。测试包含基础类型、字面量和对象，避免把条件硬编码成某一种固定结果。','先判断 T 是否属于 string。｜满足时返回 text。｜不满足时返回 other。'),
 m(1,5,'真分支提供的结构证据','type Message<T>=T extends {message:unknown}?T["message"]:never 中为什么可以索引 message？',['真分支已经确认 T 满足包含 message 的结构','条件类型可以任意索引任何属性','unknown 会自动创建 message','因为属性名必须叫 message'],'条件检查在真分支提供结构约束，允许安全引用已确认的属性。假分支处理不满足条件的输入。','索引发生在哪个分支？｜真分支知道该字段存在。｜因此可以取得字段类型。',{stage:'reason'}),
 t(1,6,'设计有边界的消息提取','导出 MessageOf<T>：当 T 含必需 message 属性时提取其类型，否则为 never。message 可为任意类型；只有可选 message 的结构不满足必需字段条件。',
  'export type MessageOf<T>=T["message"];',
  'export type MessageOf<T>=T extends {message:unknown}?T["message"]:never;',[
   ok('提取不同消息类型','import type {MessageOf} from "./main";const a:MessageOf<{message:string}>="x";const b:MessageOf<{message:number}>=2;declare const missing:MessageOf<{id:string}>;const n:never=missing;declare const optional:MessageOf<{message?:string}>;const absent:never=optional;'),
   bad('提取结果不允许错误值类型','import type {MessageOf} from "./main";const value:MessageOf<{message:number}>="2";'),
   bad('缺失字段没有可构造结果','import type {MessageOf} from "./main";const value:MessageOf<{id:string}>=undefined;'),
  ],'把约束放在条件内部允许任意 T 参与计算，不满足时得到 never。直接对无约束 T 索引则不合法。必需字段检查也不会把可选属性当成一定存在。','先检查 T 是否具备必需 message。｜在真分支读取 T["message"]。｜其余输入返回 never。'),
 m(1,7,'约束与条件的使用差别','type A<T extends {id:string}>=T["id"] 与 type B<T>=T extends {id:string}?T["id"]:never 对无 id 的类型有何区别？',['A 的类型实参直接违反约束；B 可以计算并得到 never','两者都会在运行时抛错','两者都返回 undefined','B 自动补 id 字段'],'外部约束限制工具允许的输入；内部条件可以接受更广输入并规定不匹配的结果。应该按工具用途选择。','不匹配输入是在入口被拒绝，还是有定义好的分支结果？｜A 限制调用范围。｜B 定义计算失败的类型结果。',{stage:'reason'}),
 t(1,8,'迁移：展开一层数组类型','导出 FlattenOne<T>：T 为可变或只读数组/元组时得到元素类型，否则保留 T。只展开一层，不递归展开嵌套数组。',
  'export type FlattenOne<T>=T extends unknown[]?T[number]:T;',
  'export type FlattenOne<T>=T extends readonly unknown[]?T[number]:T;',[
   ok('可变只读与普通值','import type {FlattenOne} from "./main";const a:FlattenOne<number[]>=1;const b:FlattenOne<readonly string[]>="a";const c:FlattenOne<readonly [1,"x"]>="x";const d:FlattenOne<boolean>=false;const e:FlattenOne<number[][]>=[1,2];'),
   bad('只展开一层','import type {FlattenOne} from "./main";const value:FlattenOne<number[][]>=1;'),
   bad('数组元素类型保留','import type {FlattenOne} from "./main";const value:FlattenOne<readonly number[]>="1";'),
  ],'readonly unknown[] 可以作为两类数组共同的读取能力约束；只检查可变数组会漏掉只读输入。T[number] 提取一层元素，不执行递归。','只读数组不满足可变数组要求。｜使用允许只读的数组约束。｜真分支只索引一次。'),
 m(1,9,'复测：never 是类型结果','一个条件类型对不匹配输入返回 never，是否意味着代码运行到那里一定会抛异常？',['不意味着，never 在这里是类型运算结果，不生成执行路径','意味着自动 throw new Error','意味着函数必定无限循环','意味着运行值为字符串 never'],'never 可以用来表示类型运算中没有可用候选；它不自动创建函数，也不会产生异常处理逻辑。','这里声明的是类型别名。｜没有实际可运行的分支。｜不要把类型结果等同于运行行为。'),
 t(1,10,'复测：保留输入类型的条件包装','导出 Wrapped<T>：T 可赋给 string 时为 {kind:"text";value:T}，否则为 {kind:"other";value:T}。保留具体 T，包括字符串字面量；本题测试非联合输入。',
  'export type Wrapped<T>=T extends string?{kind:"text";value:string}:{kind:"other";value:unknown};',
  'export type Wrapped<T>=T extends string?{kind:"text";value:T}:{kind:"other";value:T};',[
   ok('不同分支保留各自输入','import type {Wrapped} from "./main";const a:Wrapped<"ready">={kind:"text",value:"ready"};const b:Wrapped<number>={kind:"other",value:2};const c:Wrapped<{id:string}>={kind:"other",value:{id:"x"}};'),
   bad('字面量不能被扩大','import type {Wrapped} from "./main";const value:Wrapped<"ready">={kind:"text",value:"other"};'),
   bad('数字分支不能冒充文本载荷','import type {Wrapped} from "./main";const value:Wrapped<number>={kind:"other",value:"2"};'),
   bad('分支标签与输入对应','import type {Wrapped} from "./main";const value:Wrapped<number>={kind:"text",value:2};'),
  ],'条件决定包装结构，T 继续连接原输入与载荷。把真分支写成 string、假分支写成 unknown 会丢失本次调用的具体类型。','分支只决定 kind。｜value 的类型仍使用原 T。｜不要把 T 替换为更宽的约束类型。'),
 m(2,1,'infer 在哪里引入变量','T extends Promise<infer Value>?Value:T 中的 Value 从哪里来？',['从 T 匹配 Promise 结构时推断出来','从运行时 await 的结果读取','必须由调用者额外写第二个类型参数','是一个自动创建的全局类型'],'infer 在条件类型的匹配位置引入局部类型变量，用于表达从结构中提取的部分。它不执行 Promise。','Value 位于被匹配的结构内部。｜匹配成功后可在真分支使用。｜没有运行时读取。'),
 m(2,2,'infer 不需要 any 兜底','从 readonly string[] 提取元素类型，为什么匹配 readonly (infer E)[] 更合适？',['它能匹配只读数组并得到 string，也能接受可变数组','它把数组转换成字符串','它保证数组非空','它自动把元素变成只读对象'],'匹配模式决定接受哪些结构。使用只读数组模式适合只提取元素类型，不要求输入具备可写能力。','提取类型不需要 push 能力。｜只读模式接受更广的数组输入。｜E 对应元素位置。'),
 m(2,3,'infer 变量的范围','type Element<T>=T extends readonly (infer E)[]?E:never 后，能在别处直接把 E 当作全局类型使用吗？',['不能，E 属于该条件匹配的局部推断位置','能，所有 infer 名字都自动导出','能，只要 E 以大写字母开头','不能，因为 infer 只能叫 U'],'infer 引入的类型变量有局部作用范围。外部应使用 Element<某类型>，不能直接引用内部 E。','E 在哪一条类型表达式中声明？｜它不是顶层类型别名。｜通过工具类型取得结果。'),
 t(2,4,'提取可变或只读数组元素','导出 ElementOf<T>，当 T 是可变或只读数组、元组时提取元素类型，否则为 never。使用 infer 或等价类型运算，元组应得到元素联合。',
  'export type ElementOf<T>=T extends (infer E)[]?E:never;',
  'export type ElementOf<T>=T extends readonly (infer E)[]?E:never;',[
   ok('数组和只读元组均支持','import type {ElementOf} from "./main";const a:ElementOf<number[]>=1;const b:ElementOf<readonly string[]>="x";const c:ElementOf<readonly [1,"x"]>=1;const d:ElementOf<readonly [1,"x"]>="x";declare const invalid:ElementOf<boolean>;const n:never=invalid;'),
   bad('元素类型不能扩大','import type {ElementOf} from "./main";const value:ElementOf<readonly number[]>="1";'),
   bad('非数组没有元素结果','import type {ElementOf} from "./main";const value:ElementOf<{length:number}>=1;'),
  ],'infer 从数组元素位置提取 E，readonly 匹配覆盖只读和可变数组。只有 length 的普通对象不等于数组，不能误判。','初始模式只接受可变数组。｜增加 readonly 匹配能力。｜真分支返回推断出的 E。'),
 m(2,5,'函数返回类型不等于函数本身','若 F=(name:string)=>number，匹配 F extends (...args:never[])=>infer R 后，R 是什么？',['number','string','F 本身','never[]'],'推断位置在返回箭头之后，所以提取返回类型。never[] 在这里用于匹配调用签名，不代表实际函数只能接收 never 参数。','观察 infer R 写在哪。｜参数与返回是不同位置。｜R 对应返回结果。',{stage:'reason'}),
 t(2,6,'设计函数返回提取工具','导出 ReturnOf<T>：函数类型提取返回类型，非函数为 never。支持有参数、无参数和返回 Promise 的函数，但只提取一层返回，不执行 Awaited。',
  'export type ReturnOf<T>=T extends ()=>infer R?R:never;',
  'export type ReturnOf<T>=T extends (...args:never[])=>infer R?R:never;',[
   ok('不同参数数量和异步返回','import type {ReturnOf} from "./main";const a:ReturnOf<(name:string)=>number>=1;const b:ReturnOf<()=>string>="x";const c:ReturnOf<(a:number,b:boolean)=>Promise<string>>=Promise.resolve("x");declare const invalid:ReturnOf<{name:string}>;const n:never=invalid;'),
   bad('返回类型不能变成参数类型','import type {ReturnOf} from "./main";const value:ReturnOf<(name:string)=>number>="x";'),
   bad('Promise 不应被自动展开','import type {ReturnOf} from "./main";const value:ReturnOf<()=>Promise<number>>=1;'),
  ],'只匹配 ()=>R 会漏掉要求必需参数的函数。把参数位置写成匹配用的剩余参数，让 infer 聚焦返回位置；返回 Promise 时结果仍是 Promise。','不要要求被匹配函数一定无参数。｜使用可匹配任意参数签名的模式。｜只提取 R，不再递归处理它。'),
 m(2,7,'推断与重载的关系','对重载函数使用条件类型提取返回值时，通常依据哪一个签名推断？',['最后一个调用签名，而不是根据某次假想实参自动选择重载','随机一个签名','第一个签名，永远不会变化','所有运行调用的实际结果'],'类型提取并不执行重载调用解析。常见推断从最后签名获得信息，因此包装重载函数时要谨慎，不能假定保留每组参数返回关系。','此时没有提供调用实参。｜工具只分析函数类型。｜最后签名常是宽泛的兜底。',{stage:'reason'}),
 t(2,8,'迁移：只展开一层 Promise','导出 UnwrapOne<T>：T 为 Promise<V> 时返回 V，否则保留 T。只处理标准 Promise 类型且只展开一层，PromiseLike 不作为本题匹配对象。',
  'export type UnwrapOne<T>=Awaited<T>;',
  'export type UnwrapOne<T>=T extends Promise<infer V>?V:T;',[
   ok('单层展开与原类型保留','import type {UnwrapOne} from "./main";const a:UnwrapOne<Promise<string>>="x";const b:UnwrapOne<number>=2;const c:UnwrapOne<Promise<Promise<number>>>=Promise.resolve(1);declare const thenable:PromiseLike<number>;const d:UnwrapOne<PromiseLike<number>>=thenable;'),
   bad('不递归展开嵌套 Promise','import type {UnwrapOne} from "./main";const value:UnwrapOne<Promise<Promise<number>>>=1;'),
   bad('成功值保留原类型','import type {UnwrapOne} from "./main";const value:UnwrapOne<Promise<number>>="1";'),
  ],'Awaited 更接近递归等待的语义，也处理 PromiseLike，本题明确要求较窄的单层规则。选择工具时要核对语义而非只看名字相近。','仅匹配 Promise<...>。｜infer 捕获里面的一层 V。｜直接返回 V，不继续递归。'),
 m(2,9,'复测：模式匹配不能证明非空数组','T extends readonly [infer Head,...unknown[]] 为什么不会把普通 string[] 当成必有首项的元组？',['普通数组允许为空，不能满足必需首项的结构','string[] 不是数组类型','infer 只能提取数字','只读模式拒绝所有可变输入'],'模式要求至少一个确定元素，普通数组没有这个长度保证。若想处理普通数组，应另行决定是否返回元素类型与 undefined。','元组首项是必需的。｜普通数组可能为 []。｜没有证据就不能保证首项。'),
 t(2,10,'复测：提取非空元组首项','导出 Head<T>，匹配至少一项的只读或可变元组时返回首项类型，否则为 never。空元组和普通数组都不应被当成必有首项。',
  'export type Head<T>=T extends readonly (infer E)[]?E:never;',
  'export type Head<T>=T extends readonly [infer H,...unknown[]]?H:never;',[
   ok('精确首项和边界','import type {Head} from "./main";const a:Head<[string,number]>="x";const b:Head<readonly [1,"x"]>=1;declare const empty:Head<[]>;const n:never=empty;declare const array:Head<string[]>;const m:never=array;'),
   bad('不能取到后续元素类型','import type {Head} from "./main";const value:Head<readonly [1,"x"]>="x";'),
   bad('空元组没有首项','import type {Head} from "./main";const value:Head<[]>=undefined;'),
  ],'数组元素提取会合并所有位置，且不能表达必需首项。使用元组模式将 Head 与剩余部分分开，并让不满足非空形状的输入返回 never。','模式中明确写出第一个位置。｜剩余元素只用于允许后续项。｜返回 H，而不是所有元素的联合。'),
 m(3,1,'何时逐成员计算','type Box<T>=T extends unknown?{value:T}:never，Box<string|number> 如何计算？',['分别处理 string 与 number，再合并成 {value:string}|{value:number}','直接得到 {value:string|number} 且没有成员分配','只处理第一个成员 string','运行时检测当前值再生成类型'],'条件左侧是裸类型参数 T 时，联合实参会分配到各成员进行计算。结构表面相近时仍应理解计算过程及关联差异。','检查 extends 左侧是否直接是 T。｜把联合拆成两个成员分别代入。｜最后合并结果联合。'),
 m(3,2,'元组包裹改变判断单位','type IsText<T>=[T] extends [string]?true:false，IsText<string|number> 是什么？',['false，因为整体联合不能赋给 string','true|false，因为仍然逐成员分配','true，因为存在字符串成员','never'],'元组包裹取消这里的裸类型参数分布行为，让整个联合一次接受可赋值检查。联合里包含数字，所以整体不满足字符串。','左侧不再是裸 T。｜检查整个 string|number。｜存在数字使整体不能赋给 string。'),
 m(3,3,'直接写联合不等于裸参数','type X=(string|number) extends string?1:2，结果是什么？',['2','1|2','1','never'],'分布行为与裸类型参数有关，不是看到任意联合就逐成员计算。此处是完整联合的可赋值判断。','这里有没有参与条件的类型参数？｜直接写的是完整类型表达式。｜整个联合并不满足 string。'),
 t(3,4,'修复逐成员包装','导出 EachArray<T>，把联合的每个成员分别变成数组：EachArray<string|number> 为 string[]|number[]，不能接受混合元素数组；单一输入仍得到该类型数组。',
  'export type EachArray<T>=T[];',
  'export type EachArray<T>=T extends unknown?T[]:never;',[
   ok('每个分支独立成数组','import type {EachArray} from "./main";const a:EachArray<string|number>=["a"];const b:EachArray<string|number>=[1];const c:EachArray<{id:string}>=[{id:"a"}];'),
   bad('混合元素数组不属于任一分支','import type {EachArray} from "./main";const value:EachArray<string|number>=["a",1];'),
   bad('仍需是数组而不是单个值','import type {EachArray} from "./main";const value:EachArray<number>=1;'),
  ],'直接 T[] 会把联合放在元素位置。分布式条件让每个成员先形成自己的数组，再合并为数组类型的联合。','先逐成员分配，再构造数组。｜让条件左侧直接使用 T。｜T extends unknown 可以用于触发分配。'),
 m(3,5,'never 的空联合行为','type Label<T>=T extends string?"text":"other"，Label<never> 为什么是 never？',['分布式条件对空联合没有成员可处理，结果仍为空联合','因为 never 总是进入假分支','因为 string 等于 never','因为条件类型不支持 never 会直接报错'],'never 可视为没有成员的联合。在分布式条件中没有成员产生分支结果，所以不能用这种写法直接判断是否为 never。','此处仍然使用裸 T。｜没有可供分配的成员。｜结果不是简单地选择真分支。',{stage:'reason'}),
 t(3,6,'设计可靠的 never 检测','导出 IsNever<T>，T 为 never 时为 true，否则为 false。需要正确处理 string、unknown、string|number，不允许返回 never 来冒充 true。',
  'export type IsNever<T>=T extends never?true:false;',
  'export type IsNever<T>=[T] extends [never]?true:false;',[
   ok('空联合与其他类型明确区分','import type {IsNever} from "./main";const a:IsNever<never>=true;const b:IsNever<string>=false;const c:IsNever<unknown>=false;const d:IsNever<string|number>=false;'),
   bad('never 检测结果不能为 false','import type {IsNever} from "./main";const value:IsNever<never>=false;'),
   bad('普通类型不能被认为是 never','import type {IsNever} from "./main";const value:IsNever<number>=true;'),
  ],'包裹后对整个 T 判断是否可赋给 never，避免空联合分布导致结果也为 never。正例要求可以实际给 true 赋值，排除把 never 当成成功结果。','问题来自裸 T 触发分布。｜用 [T] 包裹判断整体。｜右侧也用 [never] 对齐结构。'),
 m(3,7,'过滤联合为什么返回 never','type OnlyText<T>=T extends string?T:never 用 never 作为假分支有什么效果？',['不匹配成员从结果联合中消失','不匹配成员被转换成 undefined','所有成员都会导致运行时抛错','never 会作为一个普通对象留在结果里'],'在联合中 T|never 等价于 T，因此逐成员计算时返回 never 可以过滤不需要的候选。这是类型过滤，不是运行数组过滤。','结果会重新组成联合。｜never 不贡献可用成员。｜所以不匹配分支被移除。',{stage:'reason'}),
 t(3,8,'迁移：筛选带标记的事件成员','导出 SelectKind<T,K>，保留联合 T 中可赋给 {kind:K} 的成员，其他成员删除。必须保留对应成员的完整载荷，支持 K 为多个标签的联合。',
  'export type SelectKind<T,K>=[T] extends [{kind:K}]?T:never;',
  'export type SelectKind<T,K>=T extends {kind:K}?T:never;',[
   ok('单标签与多标签筛选','import type {SelectKind} from "./main";type E={kind:"text";text:string}|{kind:"count";count:number}|{kind:"done"};const a:SelectKind<E,"text">={kind:"text",text:"a"};const b:SelectKind<E,"text"|"count">={kind:"count",count:1};'),
   bad('被排除的分支不能出现','import type {SelectKind} from "./main";type E={kind:"text";text:string}|{kind:"count";count:number};const value:SelectKind<E,"text">={kind:"count",count:1};'),
   bad('筛选不删除载荷要求','import type {SelectKind} from "./main";type E={kind:"text";text:string}|{kind:"count";count:number};const value:SelectKind<E,"text">={kind:"text"};'),
  ],'筛选需要每个候选独立接受检查，因此使用裸 T，而不是对整个联合一次判断。保留真分支的 T 可以保持完整载荷。','整体联合通常不全部满足某个标签。｜需要逐个成员检查 kind。｜匹配返回 T，不匹配返回 never。'),
 m(3,9,'复测：联合成员的键','keyof (A|B) 得到共有键；若要得到各成员键的合集，为什么可用 T extends unknown?keyof T:never？',['先按成员分别计算 keyof，再合并键联合','因为 unknown 会自动创建缺失字段','因为 keyof 在任何条件里都返回 string','因为条件类型会执行 Object.keys'],'分布把计算单位从整体联合变成单个成员。每个成员自己的键被提取后，再汇总得到所有键，不代表这些键可在未收窄对象上无条件访问。','先分配，再执行 keyof。｜这与先联合再 keyof 不同。｜合集键仍需结合实际分支使用。'),
 t(3,10,'复测：收集所有联合成员的键','导出 AllKeys<T>，对联合 T 的每个成员取 keyof 后合并。A={id:string;name:string} 与 B={id:string;price:number} 应得到 "id"|"name"|"price"；never 输入得到 never。',
  'export type AllKeys<T>=keyof T;',
  'export type AllKeys<T>=T extends unknown?keyof T:never;',[
   ok('汇总单侧与共同字段','import type {AllKeys} from "./main";type E={id:string;name:string}|{id:string;price:number};const a:AllKeys<E>="id";const b:AllKeys<E>="name";const c:AllKeys<E>="price";declare const empty:AllKeys<never>;const n:never=empty;'),
   bad('不能创造不存在的键','import type {AllKeys} from "./main";const key:AllKeys<{id:string}|{name:string}>="missing";'),
   bad('空联合没有可用键','import type {AllKeys} from "./main";const key:AllKeys<never>="anything";'),
  ],'直接 keyof T 对联合取得共有可用键；条件分布后对各成员独立求键可以得到合集。never 测试也验证该工具保持空联合语义。','把 keyof 放到分布式条件的真分支。｜条件左侧保持裸 T。｜没有成员时仍返回 never。'),
 m(4,1,'映射类型遍历什么','type Flags<T>={[K in keyof T]:boolean} 中 K 表示什么？',['逐个取自 T 属性键集合的类型变量','运行时 for 循环中的字符串值','T 所有属性值的联合','一个固定名为 K 的字段'],'映射类型在类型层遍历键集合，为每个键生成属性类型。它不创建实际对象或执行运行循环。','in 后面提供的是键的类型集合。｜K 每次代表其中一个键。｜生成的是类型结构。'),
 m(4,2,'如何保留每个字段原类型','{[K in keyof T]:T[K]} 为什么比 {[K in keyof T]:T[keyof T]} 更精确？',['前者每个键使用自己的值类型，后者让每个字段都变成所有值类型的联合','前者执行得更快','后者自动删除可选字段','两者永远等价'],'K 是当前字段，keyof T 是全部字段。把当前键换成所有键会破坏字段与值的对应关系。','分别观察 T[K] 和 T[keyof T] 的范围。｜当前键只选一个对应值类型。｜全部键会合并多种值类型。'),
 m(4,3,'修改修饰符的语法','映射类型中的 -readonly 和 -? 分别做什么？',['移除只读修饰与可选修饰','删除 readonly 字段和可选字段','在运行时解除冻结','将所有值设为 undefined'],'映射修饰符改变属性契约，不删除字段也不修改运行对象。字段值类型、可选性和可写性是可分别操作的维度。','减号作用于修饰符。｜属性本身仍然存在。｜不要把类型改写当成运行修改。'),
 t(4,4,'修复字段类型被统一扩大','导出 Copy<T>，按 T 的键生成对应属性，保持每个字段自己的类型，并保留原有可选和只读修饰。',
  'export type Copy<T>={[K in keyof T]:T[keyof T]};',
  'export type Copy<T>={[K in keyof T]:T[K]};',[
   ok('对应字段及可选性保留','import type {Copy} from "./main";const x:Copy<{readonly id:string;count:number;note?:string}>={id:"a",count:2};const id:string=x.id;const count:number=x.count;'),
   bad('数值字段不能接受文本','import type {Copy} from "./main";const x:Copy<{id:string;count:number}>={id:"a",count:"2"};'),
   bad('只读修饰保持','import type {Copy} from "./main";const x:Copy<{readonly id:string}>={id:"a"};x.id="b";'),
  ],'这种基于 keyof T 的映射默认保留修饰符。关键是使用当前 K 对原类型索引，而非每个字段都读取全部属性的联合。','当前属性已经由 K 表示。｜值类型应取 T[K]。｜不额外写修饰符即可保留原修饰。'),
 m(4,5,'只读映射会冻结实例吗','type Frozen<T>={readonly [K in keyof T]:T[K]} 是否会对创建出的对象调用 Object.freeze？',['不会，它只限制通过该类型视图赋值','会，映射时自动生成冻结代码','会，而且递归冻结','只有数组会被自动冻结'],'映射是类型转换，运行对象的创建和冻结属于不同操作。只读类型不能阻止其他可变别名修改同一个对象。','type 声明是否产生运行函数？｜没有 Object.freeze 调用。｜只读约束作用于静态访问。',{stage:'reason'}),
 t(4,6,'设计可编辑视图','导出 Mutable<T>，移除 T 第一层属性的 readonly，保留各字段类型与可选性；不递归修改嵌套对象。',
  'export type Mutable<T>={[K in keyof T]:T[K]};',
  'export type Mutable<T>={-readonly [K in keyof T]:T[K]};',[
   ok('移除只读但保留可选','import type {Mutable} from "./main";const x:Mutable<{readonly id:string;readonly note?:string}>={id:"a"};x.id="b";x.note="n";'),
   bad('字段类型不能改变','import type {Mutable} from "./main";const x:Mutable<{readonly id:string}>={id:"a"};x.id=1;'),
   bad('不会递归取消嵌套只读','import type {Mutable} from "./main";const x:Mutable<{readonly inner:{readonly id:string}}>={inner:{id:"a"}};x.inner.id="b";'),
  ],'使用 -readonly 只移除当前映射层的只读修饰。嵌套类型 T[K] 原样保留，因此内部 readonly 不会自动消失。','负号用于去掉现有修饰。｜可选性不要额外改变。｜内部对象类型继续使用原 T[K]。'),
 m(4,7,'字段值变换与属性保留','type Errors<T>={[K in keyof T]?:string[]} 是否会读取 T 字段的实际值来生成错误信息？',['不会，它只描述可按字段保存错误数组的结构','会，根据值自动校验','会，数字字段自动生成范围错误','会，缺失字段自动填空数组'],'映射类型可以构造错误容器的契约，但真正检测错误、创建对象和填数组都需要运行代码。','这里只声明每个键对应什么类型。｜没有业务校验函数。｜类型结构不等于生成的数据。',{stage:'reason'}),
 t(4,8,'迁移：生成字段校验函数表','导出 Validators<T>，每个原字段必须有一个可写函数属性，函数接受该字段的值类型 T[K] 并返回 boolean。即使原字段可选或只读，校验器表也应必需且可写。',
  'export type Validators<T>={[K in keyof T]:(value:T[keyof T])=>boolean};',
  'export type Validators<T>={-readonly [K in keyof T]-?:(value:T[K])=>boolean};',[
   ok('参数按字段对应且表可编辑','import type {Validators} from "./main";const v:Validators<{readonly name:string;age:number;note?:string}>={name:value=>value.length>0,age:value=>value>=0,note:value=>value===undefined||value.length>0};v.name=value=>value.length>1;'),
   bad('原可选字段也必须提供校验器','import type {Validators} from "./main";const v:Validators<{name:string;note?:string}>={name:value=>true};'),
   bad('每个校验器输入必须匹配对应值','import type {Validators} from "./main";const v:Validators<{age:number}>={age:(value:string)=>value.length>0};'),
   bad('返回值必须为布尔','import type {Validators} from "./main";const v:Validators<{age:number}>={age:value=>value};'),
  ],'映射同时使用 -readonly 和 -? 生成完整可编辑表，再用当前字段的 T[K] 绑定函数参数。原可选字段的读取值仍可能包含 undefined，校验函数需要处理它。','校验器表的可选性不应照搬数据对象。｜移除 readonly 和问号。｜函数输入使用当前 T[K]。'),
 m(4,9,'复测：映射数组也有专门行为','基于 keyof T 的同态只读映射作用于 number[] 时，是否只是一个带数字键的普通对象？',['不是，编译器会保留数组结构并得到只读数组','是，所有数组方法永久消失','是，数组变成字符串','结果一定是 never'],'同态映射对数组和元组有特定处理，会保留容器结构并传播相应修饰。不能把每种映射结果都想成普通对象字面量。','编译器识别数组与元组的结构。｜readonly 映射会作用于容器。｜结果仍有读取数组的方法。'),
 t(4,10,'复测：可选只读快照','导出 Snapshot<T>，将第一层字段全部变为可选且只读，保留字段对应类型；嵌套字段不递归可选化。',
  'export type Snapshot<T>={[K in keyof T]?:T[K]};',
  'export type Snapshot<T>={readonly [K in keyof T]?:T[K]};',[
   ok('所有第一层属性可以省略','import type {Snapshot} from "./main";const a:Snapshot<{id:string;count:number}>={};const b:Snapshot<{id:string;count:number}>={id:"a"};'),
   bad('存在的字段仍然只读','import type {Snapshot} from "./main";const a:Snapshot<{id:string}>={id:"a"};a.id="b";'),
   bad('值类型不扩大','import type {Snapshot} from "./main";const a:Snapshot<{count:number}>={count:"2"};'),
   bad('不会把嵌套必需字段变可选','import type {Snapshot} from "./main";const a:Snapshot<{inner:{id:string}}>={inner:{}};'),
  ],'readonly 和 ? 可以同时添加，而 T[K] 保留字段类型。这里的快照是类型视图，不表示运行时深复制或冻结。','同时添加两个修饰符。｜保持属性值类型为 T[K]。｜不要递归改变内部对象。'),
 m(5,1,'映射中的 as 做什么','{[K in keyof T as NewKey]:T[K]} 中的 as 与运行表达式里的类型断言有什么区别？',['这里指定映射后的属性键，是类型层的键重映射','这里把实际对象属性立即重命名','这里关闭所有类型检查','这里把字段值转换成字符串'],'键重映射中的 as 处于映射类型语法，决定生成的键。它不是对运行值做断言，也不会改写实际对象。','观察 as 位于方括号里的键声明。｜它控制输出属性名。｜没有运行对象参与改名。'),
 m(5,2,'映射到 never 的效果','把某个键重映射为 never，生成结果会怎样？',['该键被移除','该键保留，但值变成 never','键名变成字符串 "never"','所有属性被删除'],'键位置的 never 表示没有输出键，因此用于过滤。它不同于把属性值类型写成 never，后者仍可能保留不可赋值字段。','never 出现在键位置还是值位置？｜这里是键映射。｜没有键意味着不生成属性。'),
 m(5,3,'改名后如何取得原值类型','将 name 重命名为 field_name 时，值类型为何通常仍写 T[K]？',['K 仍是原键，需要从原模型取对应值类型','因为输出键一定也存在于 T','因为所有字段自动变成 string','因为 K 在运行时存有字段值'],'输出名称和源键承担不同角色。as 生成新键，T[K] 沿原键读取值类型，保持字段关系。','原模型里可能没有 field_name。｜K 仍来自 keyof T。｜值类型应从原键读取。'),
 t(5,4,'筛掉字段而不是把值设为 never','导出 WithoutId<T>，移除名为 id 的键，其他字段类型、可选性和只读修饰保留。即使输入没有 id，也应正常保留全部字段。',
  'export type WithoutId<T>={[K in keyof T]:K extends "id"?never:T[K]};',
  'export type WithoutId<T>={[K in keyof T as K extends "id"?never:K]:T[K]};',[
   ok('移除 id 并保留其余结构','import type {WithoutId} from "./main";const a:WithoutId<{id:string;name:string;note?:string}>={name:"Lin"};const b:WithoutId<{count:number}>={count:1};'),
   bad('id 不再是可访问字段','import type {WithoutId} from "./main";declare const value:WithoutId<{id:string;name:string}>;value.id;'),
   bad('保留原只读修饰','import type {WithoutId} from "./main";const value:WithoutId<{id:string;readonly name:string}>={name:"Lin"};value.name="Jia";'),
  ],'要移除属性，需要在键映射位置返回 never。把值改成 never 仍保留原必需 id，会让对象难以构造而不是得到正确视图。','初始代码只改变了属性值。｜把条件移到 as 后面的键位置。｜保留字段值仍用 T[K]。'),
 m(5,5,'字符串模板如何处理非字符串键','给所有字符串键添加前缀时，为何要处理 keyof T 中可能的 number 或 symbol？',['模板键操作需要明确支持范围，不能假定所有键都是字符串','数字键和 symbol 在 TypeScript 中不存在','只要写 as 就自动删除它们','它们会自动保留原值且不改名'],'keyof 可能包含不同种类的属性键。工具要明确是过滤非字符串键、保留它们，还是为数字键制定转换规则。','查看输入是否可能包含 symbol 属性。｜前缀字符串只描述一种命名规则。｜先按键种类限定或分支。',{stage:'reason'}),
 t(5,6,'设计字符串字段前缀视图','导出 Prefixed<T>：只保留字符串键，并将每个键 K 改为 field_K，值类型与原字段对应；保留其可选性与只读修饰。数字键和 symbol 键不进入结果。模板写法 `field_${K}` 表示类型层字符串组合。',
  'export type Prefixed<T>={[K in keyof T as K extends string?`field_${K}`:never]:T[keyof T]};',
  'export type Prefixed<T>={[K in keyof T as K extends string?`field_${K}`:never]:T[K]};',[
   ok('前缀与对应字段类型','import type {Prefixed} from "./main";declare const token:unique symbol;const value:Prefixed<{name:string;age:number;note?:string;0:boolean;[token]:Date}>={field_name:"Lin",field_age:2};const name:string=value.field_name;const age:number=value.field_age;'),
   bad('值不应扩大成全部字段联合','import type {Prefixed} from "./main";const value:Prefixed<{name:string;age:number}>={field_name:2,field_age:2};'),
   bad('数字键被过滤','import type {Prefixed} from "./main";declare const value:Prefixed<{0:string;name:string}>;value.field_0;'),
   bad('原只读修饰保留','import type {Prefixed} from "./main";const value:Prefixed<{readonly id:string}>={field_id:"a"};value.field_id="b";'),
  ],'键位置负责命名和值类型来源的分工不能混淆。T[keyof T] 把全部字段值合并，会允许错误字段值；当前 K 才保留精确对应。','前缀生成逻辑已经正确。｜错误在每个属性的值类型都用了全部键。｜改为 T[K]。'),
 m(5,7,'可选字段的筛选规则','用 T[K] extends string 筛选字符串字段时，name?:string 为什么通常不会入选？',['读取类型含 undefined，整体 string|undefined 不可赋给 string','所有可选字段都无法被映射','问号会把值变成 never','string 类型不能被条件检查'],'应先明确要筛选“必然为字符串”的字段，还是“可能含字符串”的字段。可选属性携带 undefined，两种业务定义会有不同实现。','先计算 T[K] 的实际读取类型。｜它不仅包含 string。｜条件检查的是整体是否满足 string。',{stage:'reason'}),
 t(5,8,'迁移：保留必然为字符串的字段','导出 StringFields<T>，仅保留属性读取类型整体可赋给 string 的字段，保持原类型和修饰符。排除可选字符串、string|number 和其他类型字段。',
  'export type StringFields<T>={[K in keyof T as NonNullable<T[K]> extends string?K:never]:T[K]};',
  'export type StringFields<T>={[K in keyof T as T[K] extends string?K:never]:T[K]};',[
   ok('纯字符串字段保留','import type {StringFields} from "./main";const value:StringFields<{name:string;kind:"user";nick?:string;count:number;mixed:string|number}>={name:"Lin",kind:"user"};const kind:"user"=value.kind;'),
   bad('可选字符串不满足必然条件','import type {StringFields} from "./main";declare const value:StringFields<{name:string;nick?:string}>;value.nick;'),
   bad('混合字段不保留','import type {StringFields} from "./main";declare const value:StringFields<{name:string;mixed:string|number}>;value.mixed;'),
   bad('保留字段的只读性','import type {StringFields} from "./main";const value:StringFields<{readonly name:string}>={name:"Lin"};value.name="Jia";'),
  ],'NonNullable 会先去掉空值，改变题目要求，使可选字符串也通过筛选。本题要检查原始读取类型，不能先清除不确定性。','把“可能是字符串”和“必然是字符串”分开。｜不要提前删除 undefined。｜按原 T[K] 判断并映射键。'),
 m(5,9,'复测：多个源键映射为同名键','如果两个字段都被重映射成同一个键，是否应理解为像对象展开一样后者覆盖前者？',['不应，类型映射可能合并这些来源的值类型，不能按运行覆盖顺序推断','应该，永远只保留最后字段','应该，取字母排序最大的字段','会自动创建两个同名运行属性'],'键重映射不是运行对象赋值。同名输出的值可能汇集成联合，设计工具时应避免无意碰撞或明确说明合并含义。','类型运算没有对象展开的执行顺序。｜多个来源共同贡献输出。｜需要检查碰撞后的类型。'),
 t(5,10,'复测：从事件联合构造载荷表','导出 PayloadMap<E extends {kind:string;payload:unknown}>，每个事件成员的 kind 作为键，对应 payload 作为值。支持同名 kind 的载荷合并为联合；不要将所有载荷混到每个键。',
  'export type PayloadMap<E extends {kind:string;payload:unknown}>={[K in E["kind"]]:E["payload"]};',
  'export type PayloadMap<E extends {kind:string;payload:unknown}>={[Event in E as Event["kind"]]:Event["payload"]};',[
   ok('成员标签与载荷关联','import type {PayloadMap} from "./main";type E={kind:"text";payload:string}|{kind:"count";payload:number};const map:PayloadMap<E>={text:"a",count:1};const text:string=map.text;const count:number=map.count;type Same={kind:"value";payload:string}|{kind:"value";payload:number};const a:PayloadMap<Same>={value:"x"};const b:PayloadMap<Same>={value:1};'),
   bad('字段不能接受其他成员载荷','import type {PayloadMap} from "./main";type E={kind:"text";payload:string}|{kind:"count";payload:number};const map:PayloadMap<E>={text:1,count:2};'),
   bad('每个输出键均需存在','import type {PayloadMap} from "./main";type E={kind:"text";payload:string}|{kind:"count";payload:number};const map:PayloadMap<E>={text:"a"};'),
  ],'映射的输入集合不一定只是属性键，也可以是事件成员，再通过 as 提取合法输出键。使用当前 Event 的 payload 保留关联，同名输出会汇集对应类型。','逐个映射事件成员，而不是先丢掉成员关系。｜as Event["kind"] 生成键。｜值取当前 Event["payload"]。'),
 m(6,1,'模板类型生成什么','type Event=`${"user"|"order"}:${"created"|"deleted"}` 表示什么？',['四种组合字符串的联合','一个运行时字符串拼接函数','只有 "user:created" 与 "order:deleted"','任意 string'],'模板字面量类型在类型层组合候选，每个插槽的联合会产生组合，不执行运行字符串生成。','两个插槽分别有两个候选。｜每个候选都可以与另一位置组合。｜总共四种格式。'),
 m(6,2,'字符串插槽不验证业务内容','type Path=`/users/${string}` 是否保证 ID 非空、用户存在且调用者有权限？',['都不保证，它只描述字符串结构，string 插槽也允许空串','全部保证','只保证用户存在','只保证调用者有权限'],'模板约束只能表达指定的字符串结构。空串属于 string，资源存在性和权限更需要运行信息。','string 插槽允许什么值？｜静态格式不查询数据库。｜业务条件仍需单独验证。'),
 m(6,3,'大小写工具是否运行转换','type Getter<K extends string>=`get${Capitalize<K>}` 会在运行时将对象属性改成 getter 方法吗？',['不会，只生成类型层的属性名格式','会，自动创建方法实现','会，自动调用首字母大写函数','只有生产构建会创建'],'Capitalize 和模板类型负责类型字符串变换，方法对象和函数体仍须实际编写。类型声明不是代码生成器。','是否写了可执行的方法体？｜类型工具会被擦除。｜名称约束与实际实现分开。'),
 t(6,4,'修复事件名称失去约束','导出 EventName<Resource extends string,Action extends string>，结果为 Resource:Action 形式的所有组合，不接受缺少冒号、额外前缀或候选外的名称。',
  'export type EventName<Resource extends string,Action extends string>=string;',
  'export type EventName<Resource extends string,Action extends string>=`${Resource}:${Action}`;',[
   ok('所有合法组合','import type {EventName} from "./main";type E=EventName<"user"|"order","created"|"deleted">;const a:E="user:created";const b:E="user:deleted";const c:E="order:created";const d:E="order:deleted";'),
   bad('未知操作不允许','import type {EventName} from "./main";const e:EventName<"user","created">="user:updated";',[2322,2820]),
   bad('格式分隔符不能省略','import type {EventName} from "./main";const e:EventName<"user","created">="usercreated";',[2322,2820]),
  ],'将两个类型参数放入模板的对应位置，使候选范围和格式同时受限。返回 string 会丢失全部约束。','把冒号作为固定分隔符。｜两侧插入各自类型参数。｜联合自动产生组合。'),
 m(6,5,'组合数量的成本','两个插槽各有 100 个候选时，模板类型最多可能形成多少种组合，为什么需要注意？',['约一万种，过大的联合会影响类型检查与错误信息可读性','只有两百种，所以没有成本','只有一百种，编译器自动去掉另一组','必然只有一种'],'多个独立候选集合产生笛卡尔积，规模可能迅速增长。应按真实需求控制候选范围，而非追求尽可能复杂的类型表达式。','每个左候选要配全部右候选。｜数量按乘法增长。｜大规模生成未必是最易维护的方案。',{stage:'reason'}),
 t(6,6,'设计属性变更事件表','导出 Changes<T>：只处理字符串键 K，生成 `${K}Changed` 属性，其值为接受 T[K]、返回 void 的函数。输出处理器都必需且可写；过滤数字和 symbol 键。',
  'export type Changes<T>={[K in keyof T as K extends string?`${K}Changed`:never]:(value:T[keyof T])=>void};',
  'export type Changes<T>={-readonly [K in keyof T as K extends string?`${K}Changed`:never]-?:(value:T[K])=>void};',[
   ok('事件名与载荷对应','import type {Changes} from "./main";const h:Changes<{readonly name:string;age:number;note?:string}>={nameChanged:value=>value.toUpperCase(),ageChanged:value=>value.toFixed(),noteChanged:value=>{if(value!==undefined)value.toUpperCase();}};h.nameChanged=value=>{};'),
   bad('数值事件不接受文本处理器','import type {Changes} from "./main";const h:Changes<{age:number}>={ageChanged:(value:string)=>{}};'),
   bad('可选字段仍需处理器','import type {Changes} from "./main";const h:Changes<{note?:string}>={};'),
   bad('数字键不生成事件','import type {Changes} from "./main";declare const h:Changes<{0:string;name:string}>;h["0Changed"];',[7053,2339]),
  ],'模板生成名称，当前 K 索引保留载荷类型，修饰符控制输出表完整性。把每个载荷写成所有属性值联合会破坏事件对应关系。','名称来自原字符串键。｜载荷使用当前 T[K]。｜移除只读与可选修饰，使处理器完整可编辑。'),
 m(6,7,'从格式中提取片段','S extends `${infer Name}Changed`?Name:never 中，infer Name 提取哪一部分？',['以 Changed 为后缀时，提取后缀之前的部分','任意字符串最后一个字符','自动查找对象中的 Name 字段','只提取首字母大写部分'],'模板模式可以在条件类型中匹配固定文本与可变片段。它只是结构匹配，是否对应合法模型字段还要进一步约束。','固定的 Changed 位于末尾。｜infer 接收前面的片段。｜匹配成功不代表字段真的存在。',{stage:'reason'}),
 t(6,8,'迁移：从事件名取得对应值类型','导出 EventValue<T,E extends string>：E 匹配 `${K}Changed` 且 K 属于 keyof T 时，返回 T[K]；其他事件名为 never。保留原字段可选读取的 undefined。',
  'export type EventValue<T,E extends string>=E extends `${infer K}Changed`?T[keyof T]:never;',
  'export type EventValue<T,E extends string>=E extends `${infer K}Changed`?K extends keyof T?T[K]:never:never;',[
   ok('不同事件有不同载荷','import type {EventValue} from "./main";type M={name:string;age:number;note?:string};const a:EventValue<M,"nameChanged">="Lin";const b:EventValue<M,"ageChanged">=2;const c:EventValue<M,"noteChanged">=undefined;declare const unknown:EventValue<M,"missingChanged">;const n:never=unknown;'),
   bad('年龄载荷不是文本','import type {EventValue} from "./main";const value:EventValue<{name:string;age:number},"ageChanged">="2";'),
   bad('没有后缀不匹配','import type {EventValue} from "./main";const value:EventValue<{name:string},"name">="Lin";'),
   bad('未知字段没有载荷','import type {EventValue} from "./main";const value:EventValue<{name:string},"otherChanged">="Lin";'),
  ],'先匹配事件格式，再确认提取出的字段属于模型。只有这两层证据都成立才可用 T[K]，不能退回所有字段值的联合。','格式检查和合法键检查是两步。｜infer K 之后还要判断 K extends keyof T。｜匹配失败返回 never。'),
 m(6,9,'复测：普通 string 的范围','为什么一个普通 string 变量不能直接赋给 `${"user"|"order"}:created`？',['它可能含候选之外的文本，必须先验证或保留更精确类型','因为模板类型不能接收变量','因为字符串变量会自动变成数组','只要写成 const 就保证一定匹配'],'string 描述任意文本，目标只接受有限格式。需要实际校验，或从构造过程保留足够精确的信息，不能只看当前示例值。','看变量的静态范围，而非猜测当前内容。｜目标范围更窄。｜需要证据支持收窄。'),
 t(6,10,'复测：生成 getter 接口','导出 Getters<T>：对字符串键 K 生成 `get${Capitalize<K>}`，函数无参数并返回 T[K]；输出全部必需且只读。数字与 symbol 键排除。',
  'export type Getters<T>={[K in keyof T as K extends string?`get${Capitalize<K>}`:never]:()=>T[keyof T]};',
  'export type Getters<T>={readonly [K in keyof T as K extends string?`get${Capitalize<K>}`:never]-?:()=>T[K]};',[
   ok('生成方法名与准确返回','import type {Getters} from "./main";const g:Getters<{name:string;age:number;note?:string}>={getName:()=>"Lin",getAge:()=>2,getNote:()=>undefined};const name:string=g.getName();const age:number=g.getAge();'),
   bad('返回类型与字段对应','import type {Getters} from "./main";const g:Getters<{age:number}>={getAge:()=>"2"};'),
   bad('生成方法属性不可改写','import type {Getters} from "./main";const g:Getters<{age:number}>={getAge:()=>2};g.getAge=()=>3;'),
   bad('可选字段的方法也必需','import type {Getters} from "./main";const g:Getters<{note?:string}>={};'),
  ],'Capitalize 改变类型层字符串首字符，键重映射生成方法名；返回类型仍索引当前原键。只读与必需修饰保证生成接口的使用要求。','方法名在 as 后组合。｜每个方法返回当前 T[K]。｜添加 readonly 并用 -? 移除可选性。'),
 m(7,1,'递归的停止点','type Leaf<T>=T extends readonly (infer U)[]?Leaf<U>:T 中，哪一部分使普通数值类型停止递归？',['不再匹配数组时返回 T','infer 会把所有类型变成 never','readonly 限制最多一层','编译器自动只运行三次'],'递归条件必须有可到达的终止分支。这里每次展开数组一层，非数组直接返回原类型。','观察条件的假分支。｜number 不满足数组条件。｜此时返回自身。'),
 m(7,2,'类型递归和数据遍历','声明递归树类型后，服务端返回的 JSON 是否自动被检查为合法树？',['不会，仍需运行时验证节点及其子节点','会，类型递归会遍历 JSON','只验证根节点就能保证后代合法','JSON.parse 会读取类型别名并验证'],'类型描述结构，不生成验证代码。运行时还要考虑数据大小、深度和循环引用等具体边界。','类型在运行时是否存在？｜网络数据不是类型证明。｜验证需要实际代码。'),
 m(7,3,'递归只读的含义','一个 DeepReadonly 类型让深层属性赋值报错，这是否等于原对象被深度冻结？',['不是，静态只读不等于运行时冻结，其他可写别名仍可能修改对象','是，自动递归调用 Object.freeze','是，所有引用都自动改为只读','只对数组会自动冻结'],'只读类型限制当前类型视角下的操作，不能改变底层对象或其他引用的能力。','区分类型视角和对象行为。｜readonly 不生成冻结代码。｜别名可能仍可写。'),
 t(7,4,'修复数组叶子提取','导出 Leaf<T>，递归展开普通或只读数组，直到非数组叶子；联合输入逐成员处理。',
  'export type Leaf<T>=T extends readonly (infer U)[]?U:T;',
  'export type Leaf<T>=T extends readonly (infer U)[]?Leaf<U>:T;',[
   ok('深层和联合叶子','import type {Leaf} from "./main";const a:Leaf<readonly (readonly number[])[]>=2;const b:Leaf<string[][]|boolean>=true;const c:Leaf<string[][]|boolean>="ok";const d:Leaf<{id:number}>={id:1};'),
   bad('结果不再是数组','import type {Leaf} from "./main";const a:Leaf<number[][]>=[1];'),
   bad('保留叶子的类型','import type {Leaf} from "./main";const a:Leaf<number[][]>="1";'),
  ],'单层展开只得到 U；递归调用 Leaf<U> 才能继续处理更深数组。非数组保持原类型。','先兼容只读数组。｜匹配成功后继续处理元素类型。｜不匹配时返回 T。'),
 m(7,5,'无限递归类型','type Loop<T>=Loop<T> 为什么不能作为有用的类型工具？',['没有结构推进和终止条件，会被编译器拒绝','因为泛型不允许引用自身','因为递归只能用于 class','因为应该改为运行时 while(true)'],'递归别名需要合法结构或条件推进，直接无条件自引用不能产生可用结果。树的子节点引用自身与这种直接循环不同。','没有输入被缩小。｜也没有基础结果。｜合法树结构具有明确成员。'),
 t(7,6,'设计通用树节点','导出 Tree<T>，包含 value:T 和 children:readonly Tree<T>[]。children 属性本身也只读。value 可以赋值；空 children 表示叶节点。',
  'export type Tree<T>={value:T;readonly children:readonly {value:T}[]};',
  'export type Tree<T>={value:T;readonly children:readonly Tree<T>[]};',[
   ok('空树枝与多层节点','import type {Tree} from "./main";const tree:Tree<number>={value:1,children:[{value:2,children:[]}]};tree.value=3;const child:Tree<number>|undefined=tree.children[0];'),
   bad('后代也需要子节点列表','import type {Tree} from "./main";const tree:Tree<number>={value:1,children:[{value:2}]};'),
   bad('禁止添加树枝','import type {Tree} from "./main";declare const tree:Tree<number>;tree.children.push({value:2,children:[]});'),
   bad('禁止替换子节点集合','import type {Tree} from "./main";declare const tree:Tree<number>;tree.children=[];'),
   bad('后代值保持泛型','import type {Tree} from "./main";const tree:Tree<number>={value:1,children:[{value:"2",children:[]}]};'),
  ],'通过递归节点结构约束每一层。readonly 属性防止替换集合，readonly 数组防止通过该引用增删元素；两者作用不同。','子节点仍是同一种 Tree<T>。｜属性和数组分别声明只读。｜叶节点使用空数组。'),
 m(7,7,'限定工具的适用范围','准备编写递归只读工具，为什么应说明是否支持 Date、Map 和函数？',['这些类型有独特操作与结构，简单映射所有 object 未必保留预期语义','所有 object 都完全等价于普通记录','只要递归就自动支持所有内置对象','Date 不能出现在 TypeScript 中'],'递归工具需要明确领域边界。给普通数据记录设计的工具不能无条件宣称对所有对象都正确。','object 覆盖多种对象。｜方法与集合有各自语义。｜先定义支持的数据形状。'),
 t(7,8,'迁移：只读数据视图','输入限定为原始值、普通记录及它们组成的数组或元组。导出 DeepReadonly<T>，让每层属性和数组元素位置只读，保留叶子类型及可选性。不要求支持函数、Date、Map。',
  'export type DeepReadonly<T>={readonly [K in keyof T]:T[K]};',
  'export type DeepReadonly<T>=T extends object?{readonly [K in keyof T]:DeepReadonly<T[K]>}:T;',[
   ok('保持元组和可选叶子','import type {DeepReadonly} from "./main";const a:DeepReadonly<{rows:{name:string}[];meta?:[number,string]}>={rows:[{name:"A"}],meta:[1,"ok"]};const b:DeepReadonly<string>="ok";const name:string=a.rows[0].name;'),
   bad('深层字段只读','import type {DeepReadonly} from "./main";declare const a:DeepReadonly<{inner:{n:number}}>;a.inner.n=2;'),
   bad('数组不可追加','import type {DeepReadonly} from "./main";declare const a:DeepReadonly<{rows:number[]}>;a.rows.push(1);'),
   bad('元组叶子类型保留','import type {DeepReadonly} from "./main";const a:DeepReadonly<[number,string]>=["1","ok"];'),
  ],'递归映射每个当前属性值，使深层结构也受到只读约束；非对象保留原值类型。本题领域限于普通数据，不宣称实现任意对象冻结。','对象分支映射所有键。｜每个值继续调用工具本身。｜非对象直接返回 T。'),
 m(7,9,'复测：递归深度','设计通用类型工具时，为什么需要关心递归深度？',['过深展开可能增加编译成本或触发实例化限制，应缩小领域或限制深度','类型计算完全没有成本','递归深度只影响 JavaScript 调用栈','把错误屏蔽后类型就仍然精确'],'类型运算也消耗编译器资源。限制深度时应明确达到边界后的类型行为，不能默默宣称无限精确。','这里计算发生在编译期间。｜复杂展开需要资源。｜工具契约需要描述停止边界。'),
 t(7,10,'复测：有预算的展开','导出 FlattenWithin<T,B extends readonly unknown[]>。B 是递归预算：预算为空立即返回 T；否则当 T 为数组时展开一层并消耗一个预算元素，非数组保持原样。',
  'export type FlattenWithin<T,B extends readonly unknown[]>=T extends readonly (infer U)[]?FlattenWithin<U,B>:T;',
  'export type FlattenWithin<T,B extends readonly unknown[]>=B extends readonly [unknown,...infer Rest]?T extends readonly (infer U)[]?FlattenWithin<U,Rest>:T:T;',[
   ok('零一多层预算','import type {FlattenWithin} from "./main";const zero:FlattenWithin<number[][],[]>=[[1]];const one:FlattenWithin<number[][],readonly [1]>=[1];const two:FlattenWithin<number[][],[1,1]>=1;const scalar:FlattenWithin<string,[1,1]>="ok";'),
   bad('一层预算不能全部展开','import type {FlattenWithin} from "./main";const a:FlattenWithin<number[][],[1]>=1;'),
   bad('两层预算得到叶子','import type {FlattenWithin} from "./main";const a:FlattenWithin<number[][],[1,1]>=[1];'),
  ],'预算元组每步去掉首元素，形成明确停止条件。到达边界保留剩余结构，调用者可以预期精度与成本。','先判断预算是否非空。｜用剩余 Rest 递归。｜预算为空时不再展开。'),
 m(8,1,'复杂不是目标','一个类型工具可以精确描述十层任意对象路径，但业务只允许更新 title 和 enabled。更合理的起点是什么？',['先明确允许更新的字段与输入契约，只有真实需要时才引入通用深层路径','支持的路径越多越正确','先扩大为 string 路径，再相信调用方','把对象变成 any 可以保持精确检查'],'类型设计应服务实际契约。通用工具可能扩大权限、增加理解成本，并不自动比有限字段模型更符合业务。','先识别业务允许什么。｜额外能力也可能放过错误请求。｜选择足够表达契约的模型。'),
 m(8,2,'诊断性能的证据','项目类型检查变慢，团队怀疑某个递归工具。下一步应该怎么做？',['在相同环境下记录检查数据并缩小复现，再对比替代实现','直接宣布所有条件类型都很慢','把 skipLibCheck 当作修复业务类型的万能开关','删除所有类型测试，只看构建是否结束'],'复杂度判断需要可重复的测量与具体复现。替代方案还应通过语义测试，不能只追求更快而放过错误调用。','先获得可比较的数据。｜缩小到具体使用方式。｜性能和契约都要验证。'),
 m(8,3,'复用 Awaited 的价值','为什么异步结果提取常优先考虑 Awaited，而不是只匹配一次 Promise<infer U>？',['它表达递归等待的语义，并处理 PromiseLike 等等待关系','它能执行请求并拿到服务器数据','它把所有结果转换成 Promise','它保证异步函数永不失败'],'Awaited 是类型层面的等待结果计算。它不能执行异步操作，也不表达永不拒绝的保证；单层 Promise 提取适用于另一个更窄的契约。','先明确需要一层还是等待后的结果。｜PromiseLike 也是相关边界。｜工具没有运行时行为。'),
 t(8,4,'修复异步结果提取','导出 SettledValue<F extends (...args:never[])=>unknown>，得到函数返回值经过等待后的成功值类型。同步返回值也保留；不包含拒绝原因。',
  'export type SettledValue<F extends (...args:never[])=>unknown>=ReturnType<F> extends Promise<infer U>?U:ReturnType<F>;',
  'export type SettledValue<F extends (...args:never[])=>unknown>=Awaited<ReturnType<F>>;',[
   ok('递归等待及 PromiseLike','import type {SettledValue} from "./main";const a:SettledValue<(id:string)=>Promise<Promise<number>>>=1;const b:SettledValue<()=>PromiseLike<{id:string}>>={id:"a"};const c:SettledValue<()=>string>="ok";const d:SettledValue<()=>Promise<number>|null>=null;'),
   bad('等待后不是 Promise','import type {SettledValue} from "./main";const a:SettledValue<()=>Promise<number>>=Promise.resolve(1);'),
   bad('返回叶子类型仍受约束','import type {SettledValue} from "./main";const a:SettledValue<()=>PromiseLike<number>>="1";'),
  ],'ReturnType 提取返回类型，Awaited 表达递归等待后的成功值。组合现有工具比手写不完整的等待规则更清楚；拒绝通道仍需独立建模。','先取函数返回类型。｜再表达等待后的结果。｜组合 Awaited 与 ReturnType。'),
 m(8,5,'简化的验收标准','把复杂类型重写成几个内置工具后，怎样确认没有改变业务约束？',['同时比较合法用法、非法用法、推断结果和必要边界','只要一个示例能编译就等价','只看类型别名变短了多少','只要用到内置工具就不会错'],'语法变短不是等价证明。尤其要检查可选、只读、联合以及输入输出关联，防止简化时丢失原本需要的约束。','成功示例只能覆盖一部分。｜错误调用也必须继续失败。｜关注结构修饰符和推断。'),
 t(8,6,'设计有限范围的补丁','导出 SettingsPatch<T extends {id:string;title:string;enabled:boolean}>：只允许 title 与 enabled 两个字段，均可省略；保留 T 中对应字段的具体值类型。这里按普通结构类型语义检查新对象字面量，不要求精确对象类型。',
  'export type SettingsPatch<T extends {id:string;title:string;enabled:boolean}>=Partial<T>;',
  'export type SettingsPatch<T extends {id:string;title:string;enabled:boolean}>=Partial<Pick<T,"title"|"enabled">>;',[
   ok('补丁允许独立字段或为空','import type {SettingsPatch} from "./main";type S={id:string;title:"draft"|"live";enabled:boolean;secret:string};const a:SettingsPatch<S>={};const b:SettingsPatch<S>={title:"live"};const c:SettingsPatch<S>={enabled:false};'),
   bad('身份不属于补丁','import type {SettingsPatch} from "./main";const a:SettingsPatch<{id:string;title:string;enabled:boolean}>={id:"new"};'),
   bad('后来新增的私有字段也不开放','import type {SettingsPatch} from "./main";const a:SettingsPatch<{id:string;title:string;enabled:boolean;secret:string}>={secret:"x"};'),
   bad('保留具体标题候选','import type {SettingsPatch} from "./main";const a:SettingsPatch<{id:string;title:"draft"|"live";enabled:boolean}>={title:"other"};'),
  ],'白名单 Pick 决定业务范围，Partial 表达补丁可省略字段。无需递归，也避免 Partial<T> 自动开放未来新增的敏感字段。结构类型不等于运行时删掉额外属性。','先选允许的字段。｜再让选中的字段可选。｜不能直接可选化整个模型。',{wrongSolutions:[{'main.ts':'export type SettingsPatch<T extends {id:string;title:string;enabled:boolean}>=Partial<Omit<T,"id">>;'}]}),
 m(8,7,'显示扁平不等于精确','type Simplify<T>={[K in keyof T]:T[K]} 可以让某些提示更易读，它是否保证变量没有额外字段？',['不保证，它不把结构类型系统变成精确对象检查','保证，所有多余字段会被删除','保证，编译器会生成校验器','保证，运行时 Object.keys 只返回声明字段'],'用于展示或映射的别名不执行属性删除，也不改变普通结构可赋值规则。精确输入限制和运行时数据清洗是独立需求。','该声明仍是类型层运算。｜变量的实际属性不会变化。｜结构兼容允许一定的额外信息。'),
 t(8,8,'迁移：用状态联合替代可选字段袋','导出 Outcome<T,E>：成功为 {ok:true;value:T}，失败为 {ok:false;error:E}。不能通过未收窄的对象访问 value/error；本题不要求排除已存变量上的额外字段。',
  'export type Outcome<T,E>={ok:boolean;value?:T;error?:E};',
  'export type Outcome<T,E>={ok:true;value:T}|{ok:false;error:E};',[
   ok('分支提供必需数据','import type {Outcome} from "./main";function read(x:Outcome<number,string>){if(x.ok){const n:number=x.value;return n;}const error:string=x.error;return error;}const a:Outcome<number,string>={ok:false,error:"bad"};'),
   bad('成功不能没有值','import type {Outcome} from "./main";const a:Outcome<number,string>={ok:true};'),
   bad('失败不能没有原因','import type {Outcome} from "./main";const a:Outcome<number,string>={ok:false};'),
   bad('先收窄再读取','import type {Outcome} from "./main";declare const a:Outcome<number,string>;a.value;'),
  ],'简单的可辨识联合可以直接表达状态与数据关系。把每个字段都可选会放过不完整状态，并迫使消费者反复猜测。','成功和失败是两种完整形状。｜让 ok 使用字面量。｜字段在对应分支中必需。'),
 m(8,9,'复测：深层路径范围','某工具只支持普通记录的一层键，需求新增数组下标与可选嵌套路径。最合理的处理是什么？',['重新定义路径、空值和越界契约，再决定扩展工具或采用明确访问函数','扩大返回值为 any 并保留原精确类型宣传','先支持所有字符串，验证以后再说','增加递归层数就自然解决所有问题'],'数组索引、可选节点和失败行为需要明确规则。递归本身不能回答这些业务问题，有限专用 API 也可能更清晰。','先定义错误和缺失值如何处理。｜数组边界不等于普通属性。｜契约比递归层数重要。'),
 t(8,10,'复测：按已知协议取响应数据','服务协议固定为 {data:{items:readonly unknown[]}}。导出 ResponseItem<T extends {data:{items:readonly unknown[]}}> 提取 items 的元素类型；不要递归展开元素内部数组，也不要搜索其他同名字段。',
  'export type ResponseItem<T extends {data:{items:readonly unknown[]}}>=T["data"]["items"];',
  'export type ResponseItem<T extends {data:{items:readonly unknown[]}}>=T["data"]["items"][number];',[
   ok('记录和数组元素保持完整','import type {ResponseItem} from "./main";const a:ResponseItem<{data:{items:readonly {id:string}[]}}>= {id:"a"};const b:ResponseItem<{data:{items:readonly number[][]}}>= [1,2];const c:ResponseItem<{data:{items:readonly ["a",2]}}>=2;'),
   bad('不把元素内部数组展开','import type {ResponseItem} from "./main";const a:ResponseItem<{data:{items:number[][]}}>=1;'),
   bad('不是外层数组','import type {ResponseItem} from "./main";const a:ResponseItem<{data:{items:{id:string}[]}}>=[{id:"a"}];'),
   bad('元素属性类型保留','import type {ResponseItem} from "./main";const a:ResponseItem<{data:{items:{id:string}[]}}>={id:1};'),
  ],'协议路径已经固定，连续索引访问最直接。递归展开会错误地改变数组元素本身的语义；抽象程度应与协议需求一致。','先定位 data.items。｜使用 number 索引提取一层元素。｜不要递归处理元素内容。',{wrongSolutions:[{'main.ts':'type Leaf<T>=T extends readonly (infer U)[]?Leaf<U>:T;export type ResponseItem<T extends {data:{items:readonly unknown[]}}>=Leaf<T["data"]["items"]>;'}]}),
];
