import { mc, task, ok, bad, run } from './author.mjs';
const id=n=>`t09-l${String(n).padStart(2,'0')}`;
const m=(l,n,title,prompt,options,explanation,hints,extra={})=>mc(id(l),n,title,prompt,options,explanation,hints.split('｜'),extra);
const t=(l,n,title,prompt,files,solution,tests,explanation,hints,extra={})=>task(id(l),n,title,prompt,files,solution,tests,explanation,hints.split('｜'),extra);
export const questions=[
 m(1,1,'当前位置不等于声明范围','let value:string|number="ready"; value=42; 紧接着访问 value 时，它的当前控制流类型是什么？',['number，但后续仍可以赋入符合声明类型的 string','永远是 string，因为初始化为字符串','声明类型已永久变成 number','any，因为出现了两种值'],'声明类型规定允许赋入的范围；控制流根据最近赋值判断当前位置的类型。当前收窄不会永久改写声明范围。','区分声明和当前值的证据。｜最近一次赋值是数字。｜后续合法赋值仍受原声明约束。'),
 m(1,2,'分支合流的类型','function f(flag:boolean){let x:string|number;if(flag)x="ok";else x=1;return x} 的返回值类型是什么？',['string | number','string，因为 if 分支先出现','number，因为 else 最后出现','never，因为两条路径不一致'],'控制流合流时，两条可达路径都需要考虑。分支书写顺序不决定运行路径。','分别沿两条路径分析。｜两个分支都能到达 return。｜结果保留两种可能。'),
 m(1,3,'重新赋值会更新证据','在 typeof value === "string" 的分支内执行 value = 12，随后调用 value.toUpperCase() 会怎样？',['报错，赋值后当前值已是 number','通过，外层 if 的证据永远有效','通过并把 12 转为字符串','只能运行时判断，TS 不处理赋值'],'收窄依赖当前位置的控制流。后续赋值提供了新的证据，不能继续沿用已经失效的字符串判断。','沿代码顺序跟踪值。｜赋值发生在方法调用之前。｜number 没有 toUpperCase。'),
 t(1,4,'修复规范化后的检查','实现 readPort(value:string|number):number|null。文本先 trim，空文本返回 null，否则用 Number 转换；数值必须为 1～65535 内的整数。不要使用断言。',
  'export function readPort(value:string|number):number|null {if(typeof value==="string"){if(value.trim()==="")return null;value=Number(value);}return value>0?value:null;}',
  'export function readPort(value:string|number):number|null {if(typeof value==="string"){if(value.trim()==="")return null;value=Number(value);}return Number.isInteger(value)&&value>=1&&value<=65535?value:null;}',[
   ok('数字与文本输入','import {readPort} from "./main";const a:number|null=readPort("8080");const b:number|null=readPort(443);'),
   bad('不接收缺失值','import {readPort} from "./main";readPort(undefined);'),
   bad('调用方仍需考虑失败','import {readPort} from "./main";const a:number=readPort("bad");'),
  ],'文本分支完成转换后，两条路径中的 value 都是 number，但 number 仍包含小数、NaN 和无穷大。类型收窄不能代替业务范围检查。','先单独拒绝空白文本。｜转换后可以统一检查数值。｜整数检查与上下界都需要满足。',{runtime:[run('端口边界与转换','const {readPort}=load("main.js");for(const [input,want] of [[" 8080 ",8080],[1,1],[65535,65535],[0,null],[65536,null],[1.5,null],["",null],["  ",null],["12x",null],[Infinity,null],[NaN,null]])equal(readPort(input),want);')]}),
 m(1,5,'闭包何时读取值','为什么延后执行的回调里，不能仅凭回调创建前对可变属性的一次检查，就假设执行时该属性仍有值？',['回调实际执行前，其他代码可能修改属性，应快照或在执行时重新检查','所有闭包都立即执行','属性一旦收窄便无法再赋值','TS 会自动把所有回调捕获值复制一份'],'闭包通常捕获变量或对象引用，并非自动复制值。需要区分要求使用创建时快照，还是执行时最新状态。','考虑创建和执行之间的时间。｜对象可以被其他引用修改。｜业务决定快照还是重新检查。'),
 t(1,6,'设计创建时快照','实现 makeGreeting(state:{name?:string}):()=>string。创建时 name 存在就保存其原值，回调返回 "Hi "+原值；缺失返回 "Guest"。空字符串也是存在。创建后修改 state 不应影响回调。',
  'export function makeGreeting(state:{name?:string}):()=>string {return ()=>state.name===undefined?"Guest":"Hi "+state.name;}',
  'export function makeGreeting(state:{name?:string}):()=>string {const name=state.name;return ()=>name===undefined?"Guest":"Hi "+name;}',[
   ok('可直接调用延迟函数','import {makeGreeting} from "./main";const a:()=>string=makeGreeting({name:"Lin"});const b:string=makeGreeting({})();'),
   bad('属性必须是文本','import {makeGreeting} from "./main";makeGreeting({name:1});'),
  ],'局部 const 保存读取时的原始字符串或 undefined，回调根据该快照判断。仅把 state 引用赋给 const 不会复制其属性。','明确要求使用创建时的值。｜把属性读入局部变量。｜判断 undefined，不要把空字符串当缺失。',{runtime:[run('快照不随外部属性变化','const {makeGreeting}=load("main.js");const state={name:"Lin"};const greet=makeGreeting(state);state.name="Other";equal(greet(),"Hi Lin");delete state.name;equal(greet(),"Hi Lin");const empty={};const guest=makeGreeting(empty);empty.name="Later";equal(guest(),"Guest");equal(makeGreeting({name:""})(),"Hi ");')],wrongSolutions:[{'main.ts':'export function makeGreeting(state:{name?:string}):()=>string {const name=state.name;return ()=>name?"Hi "+name:"Guest";}'}]}),
 m(1,7,'提前返回后的剩余路径','function f(value:string|null){if(value===null)return 0;return value.length} 为什么后一个 return 可以直接读取 length？',['到达该位置的路径已排除 null','return 会把 null 转为空字符串','所有函数参数默认非空','length 存在于任何值上'],'控制流分析会考虑不可继续到达的路径。null 分支已经返回，后续剩余的是字符串路径。','分析哪些路径能走到最后。｜null 路径已结束。｜剩余值是字符串。'),
 t(1,8,'迁移：执行时读取最新状态','实现 makeLengthReader(state:{text?:string}):()=>number。每次调用回调时读取最新 text；缺失返回 0，否则返回长度。不得使用创建时快照，不修改 state。',
  'export function makeLengthReader(state:{text?:string}):()=>number {const text=state.text;return ()=>text===undefined?0:text.length;}',
  'export function makeLengthReader(state:{text?:string}):()=>number {return ()=>{const text=state.text;if(text===undefined)return 0;return text.length;};}',[
   ok('最新值读取器','import {makeLengthReader} from "./main";const read:()=>number=makeLengthReader({});const n:number=read();'),
   bad('不能传数字属性','import {makeLengthReader} from "./main";makeLengthReader({text:1});'),
  ],'本题与快照题的契约相反：读取必须发生在回调内部。每次先获取当前属性，再检查缺失，可保证当前调用中的使用有证据。','把属性读取放在返回的函数里。｜每次执行都检查本次取得的值。｜提前返回缺失情况。',{runtime:[run('执行时重读与删除','const {makeLengthReader}=load("main.js");const state={text:"a"};const read=makeLengthReader(state);equal(read(),1);state.text="hello";equal(read(),5);delete state.text;equal(read(),0);state.text="";equal(read(),0);state.text="OK";equal(read(),2);equal(state,{text:"OK"});')]}),
 m(1,9,'复测：const 对象属性','const box:{value:string|number}={value:"a"}; box.value=2; const 是否阻止这次属性赋值？',['不会，const 固定变量绑定，属性仍按自己的类型允许赋值','会，所有属性自动深度只读','会，初始化后 value 类型永久是 string','不会，但属性会因此变成 any'],'变量绑定不可重新赋值，不代表对象属性不可修改。属性声明仍允许 string 或 number，赋值会影响后续控制流。','const 限制的是 box 绑定。｜属性有自己的声明类型。｜需要 readonly 才有相应静态写入限制。'),
 t(1,10,'复测：收集首次有效值','实现 firstText(values:readonly (string|null|undefined)[]):string|null。按顺序返回第一个不是 null/undefined 的字符串，包含空字符串；没有则返回 null。不要修改输入。',
  'export function firstText(values:readonly (string|null|undefined)[]):string|null {for(const value of values){if(value)return value;}return null;}',
  'export function firstText(values:readonly (string|null|undefined)[]):string|null {for(const value of values){if(value===null||value===undefined)continue;return value;}return null;}',[
   ok('只读集合及失败结果','import {firstText} from "./main";const a:string|null=firstText([null,undefined,"a"] as const);'),
   bad('数字不是合法候选','import {firstText} from "./main";firstText([1]);'),
   bad('可能没有结果','import {firstText} from "./main";const a:string=firstText([]);'),
  ],'continue 排除了当前循环中缺失的路径，后续 value 是字符串。真值判断则错误排除空字符串，无法满足首次有效值的业务定义。','有效的定义是非空值，不是布尔真。｜排除 null 和 undefined 后继续处理。｜首个有效字符串立刻返回。',{runtime:[run('空文本和顺序不丢失','const {firstText}=load("main.js");equal(firstText([null,"","later"]),"");equal(firstText([undefined,null,"first","second"]),"first");equal(firstText([null,undefined]),null);equal(firstText([]),null);const input=Object.freeze([null,"ok"]);equal(firstText(input),"ok");equal(input,[null,"ok"]);')]}),
 m(2,1,'变量上的额外字段','type User={id:string}; const source={id:"a",secret:"s"}; const user:User=source; 赋值后 source.secret 会怎样？',['仍然存在，类型标注没有删除属性','被编译器从 source 删除','运行时变成 undefined','赋值一定报错，因为多了 secret'],'结构兼容允许源对象提供更多信息。目标类型只改变通过该引用可直接访问的静态成员，不会转换对象。','检查是否执行了删除或新建对象。｜这里只有类型标注。｜运行时仍是同一个引用。'),
 m(2,2,'新字面量的额外检查','为什么 const user:{id:string}={id:"a",secret:"s"} 可能报错，而先保存对象再赋值可以通过？',['新对象字面量会受到额外属性检查，普通变量赋值主要按结构兼容判断','变量赋值永远不检查任何类型','编译器随机选择报错位置','先保存会自动移除 secret'],'额外属性检查帮助发现新字面量中的拼写或配置错误，但它不是全局精确对象语义。已有变量仍需满足目标的必需字段和字段类型。','区分新字面量和已有变量。｜两种情况都检查必需结构。｜额外检查不是运行清洗。'),
 m(2,3,'satisfies 也不是清洗','const source={id:"a",secret:"s"}; const value=source satisfies {id:string}; value.secret 是否仍可访问？',['可以，已有变量的检查不会删除其具体字段','不可以，satisfies 总会缩成目标类型','运行时会删除，但编辑器暂时还能看到','secret 会自动变成 never'],'satisfies 检查可赋值关系，不生成投影代码。对于这里的已有变量，结果保留其已有类型与对象值。','表达式输入是已有变量。｜检查不是转换。｜原类型含有 secret。'),
 t(2,4,'修复公开数据投影','实现 toPublic(source:{id:string;name:string;secret:string}):{id:string;name:string}。返回只含 id、name 的新对象，不修改源对象，也不复制额外字段。',
  'export function toPublic(source:{id:string;name:string;secret:string}):{id:string;name:string}{return source;}',
  'export function toPublic(source:{id:string;name:string;secret:string}):{id:string;name:string}{return {id:source.id,name:source.name};}',[
   ok('公开视图的字段','import {toPublic} from "./main";const user=toPublic({id:"a",name:"Lin",secret:"s"});const id:string=user.id;'),
   bad('公开返回类型不暴露 secret','import {toPublic} from "./main";toPublic({id:"a",name:"Lin",secret:"s"}).secret;'),
  ],'返回类型不会删除私有数据，直接返回 source 可以通过类型检查却违反业务。显式构造白名单字段才能完成投影。','必须创建新对象。｜逐项列出公开字段。｜不要展开全部 source。',{runtime:[run('只输出公开字段且不改源','const {toPublic}=load("main.js");const source=Object.freeze({id:"a",name:"Lin",secret:"s",token:"hidden"});const result=toPublic(source);equal(result,{id:"a",name:"Lin"});check(result!==source);equal(source.secret,"s");equal(source.token,"hidden");')],wrongSolutions:[{'main.ts':'export function toPublic(source:{id:string;name:string;secret:string}):{id:string;name:string}{return {...source};}'}]}),
 m(2,5,'精确检查能看到什么','一个基于 keyof Actual 的额外键检查工具，能发现运行时存在但已被宽类型标注隐藏的所有字段吗？',['不能，它只能使用静态类型中仍然可见的信息','能，keyof 会遍历运行时对象','能，只要加上泛型约束','能，类型擦除后信息反而更多'],'当具体对象先被赋给较窄的静态视图后，类型运算无法恢复隐藏的运行时信息。安全输出仍需实际投影或验证。','keyof 操作类型，不读取对象。｜已丢失的信息无法凭空恢复。｜静态辅助不是运行时保证。'),
 t(2,6,'设计静态额外键检查','导出 Exact<Shape,Actual>：Actual 可赋给 Shape，且 keyof Actual 没有 Shape 之外的键时返回 Actual，否则返回 never。本题输入为普通非联合对象类型，仅检查第一层静态键。',
  'export type Exact<Shape,Actual>=Actual extends Shape?Actual:never;',
  'export type Exact<Shape,Actual>=Actual extends Shape?Exclude<keyof Actual,keyof Shape> extends never?Actual:never:never;',[
   ok('合法形状保留具体类型','import type {Exact} from "./main";const a:Exact<{id:string;name?:string},{id:"a"}>={id:"a"};const id:"a"=a.id;const b:Exact<{id:string},{id:string}>={id:"b"};'),
   bad('已有变量也发现可见额外键','import type {Exact} from "./main";const source={id:"a",secret:"s"};const value:Exact<{id:string},typeof source>=source;'),
   bad('字段类型仍需兼容','import type {Exact} from "./main";const value:Exact<{id:string},{id:number}>={id:1};'),
   bad('必需字段不可缺失','import type {Exact} from "./main";const value:Exact<{id:string},{}>={};'),
  ],'先检查结构兼容，再计算 Actual 中超出 Shape 的键。明确限制普通非联合输入和浅层语义，避免把此工具描述成所有场景的完美精确对象类型。','两项条件都要成立。｜Exclude 可以计算额外键。｜没有额外键时结果为 never，检查这个结果后保留 Actual。'),
 m(2,7,'嵌套对象也需要边界','公开返回 {profile:source.profile}，但 profile 中存在内部备注。只给返回值标注 {profile:{name:string}} 是否足够移除备注？',['不够，嵌套对象仍是原引用，需要在对应层投影','足够，嵌套类型标注会自动递归删除','足够，只要最外层对象是新建的','备注会在 JSON.stringify 时自动被 TS 忽略'],'浅层新建对象不代表深层清理。序列化读取实际对象字段，不读取 TypeScript 类型声明。','检查 profile 是否复制并筛选。｜新外壳可包含旧引用。｜序列化面对实际属性。'),
 t(2,8,'迁移：嵌套公开视图','实现 exportProfile(source:{id:string;profile:{name:string;internalNote:string}}):{id:string;profile:{name:string}}。返回两层新对象，仅保留公开字段，源对象不能被修改。',
  'export function exportProfile(source:{id:string;profile:{name:string;internalNote:string}}):{id:string;profile:{name:string}} {return {id:source.id,profile:source.profile};}',
  'export function exportProfile(source:{id:string;profile:{name:string;internalNote:string}}):{id:string;profile:{name:string}} {return {id:source.id,profile:{name:source.profile.name}};}',[
   ok('保留公开结构','import {exportProfile} from "./main";const a=exportProfile({id:"a",profile:{name:"Lin",internalNote:"private"}});const name:string=a.profile.name;'),
   bad('类型也不能暴露嵌套私有字段','import {exportProfile} from "./main";exportProfile({id:"a",profile:{name:"Lin",internalNote:"private"}}).profile.internalNote;'),
  ],'每一层需要公开的结构都显式重建。仅限制返回类型或复制外壳，仍可能把嵌套的内部数据带出去。','外层保留 id 和 profile。｜profile 内只保留 name。｜测试还会检查嵌套引用是否独立。',{runtime:[run('嵌套投影与引用隔离','const {exportProfile}=load("main.js");const source={id:"a",profile:{name:"Lin",internalNote:"private",token:"x"},secret:"s"};const out=exportProfile(source);equal(out,{id:"a",profile:{name:"Lin"}});check(out!==source);check(out.profile!==source.profile);out.profile.name="Other";equal(source.profile.name,"Lin");equal(source.profile.internalNote,"private");')]}),
 m(2,9,'复测：索引签名改变契约','把配置类型改成 {url:string;[key:string]:unknown}，是否仍能依靠额外属性检查发现所有拼错的可选配置字段？',['不能，字符串索引签名明确允许任意其他字符串键','能，unknown 会拒绝全部额外字段','能，索引签名只影响数组','不能，因为 url 也不再必需'],'索引签名开放其他键；必需的 url 仍需满足，但其他拼错键可能被允许。应根据业务选择开放字典还是有限键配置。','索引签名表达允许什么。｜unknown 限制读取使用，不禁止键存在。｜必需字段的约束仍保留。'),
 t(2,10,'复测：显式检查可枚举键','实现 hasOnlyKeys(value:object,allowed:readonly string[]):boolean：检查 Object.keys(value) 返回的每一个键都在 allowed 中。忽略继承键、symbol 和不可枚举键；不验证值类型或必需字段。',
  'export function hasOnlyKeys(value:object,allowed:readonly string[]):boolean{return allowed.every(key=>Object.keys(value).includes(key));}',
  'export function hasOnlyKeys(value:object,allowed:readonly string[]):boolean{return Object.keys(value).every(key=>allowed.includes(key));}',[
   ok('允许列表可以只读','import {hasOnlyKeys} from "./main";const a:boolean=hasOnlyKeys({id:"a"},["id","name"] as const);'),
   bad('拒绝非对象输入','import {hasOnlyKeys} from "./main";hasOnlyKeys(null,[]);'),
  ],'应遍历实际出现的键，判断是否全部被允许；遍历允许列表检查存在性是另一种要求。本函数只验证指定范围的键，不应被当成完整数据校验器。','谁的键必须是子集？｜实际键应包含在允许列表。｜空对象没有违反允许键范围。',{runtime:[run('实际键子集及作用范围','const {hasOnlyKeys}=load("main.js");equal(hasOnlyKeys({id:"a"},["id","name"]),true);equal(hasOnlyKeys({id:"a",extra:1},["id"]),false);equal(hasOnlyKeys({},["id"]),true);const v=Object.create({inherited:1});v.id="a";v[Symbol("hidden")]=1;Object.defineProperty(v,"hidden",{value:1,enumerable:false});equal(hasOnlyKeys(v,["id"]),true);')]}),
 m(3,1,'回调替换的方向','严格函数参数检查下，需要 (value:string|number)=>void 的位置，能直接放入只能处理 string 的回调吗？',['不能，调用方有权传入 number，窄回调无法履行契约','能，因为 string 属于联合类型','能，因为 void 会忽略参数类型','只要目前调用只传 string 就自动合法'],'判断方向要从调用方允许传什么出发。候选函数必须处理所有被允许的输入，不能要求更窄前提。','目标可能传数字。｜候选函数是否能处理数字？｜返回 void 不取消参数约束。'),
 m(3,2,'更宽参数可以替换','需要 (value:string)=>void 时，接收 unknown 并在内部安全处理的函数能否替代？',['可以，它能接受包括 string 在内的输入','不能，参数名称必须相同','不能，unknown 比 string 宽','可以，但 TS 自动把 unknown 断言成 string'],'接收范围更宽的函数可以满足较窄的调用契约。unknown 在函数内部仍需检查，不会被自动断言。','目标调用只会给字符串。｜unknown 参数允许接收字符串。｜函数内部检查仍由实现负责。'),
 m(3,3,'忽略额外参数','数组回调可以只声明 value 而不声明 index，主要原因是什么？',['函数可以忽略调用方提供的额外参数','数组不会传 index','少写参数会让 value 变成 any','所有参数都自动成为可选参数'],'候选函数少使用参数通常是安全的；相反，要求调用方不保证提供的额外必需参数可能不安全。','实际调用可以提供更多参数。｜函数可以不使用它们。｜不要反向要求额外必需参数。'),
 t(3,4,'修复通用渲染器','实现 renderAll(values:readonly (string|number)[],render:(value:string|number)=>string):string[]。按顺序把每个原值交给 render 一次，返回对应结果；允许 render 接收更宽输入，不应允许只接收 string。',
  'export function renderAll(values:readonly (string|number)[],render:(value:string)=>string):string[]{return values.map(value=>render(String(value)));}',
  'export function renderAll(values:readonly (string|number)[],render:(value:string|number)=>string):string[]{return values.map(value=>render(value));}',[
   ok('通用和更宽回调','import {renderAll} from "./main";const a:string[]=renderAll([1,"a"],value=>String(value));renderAll([1],(value:unknown)=>String(value));'),
   bad('不能只支持文本','import {renderAll} from "./main";renderAll([1],(value:string)=>value.toUpperCase());'),
   bad('不能要求额外必需参数','import {renderAll} from "./main";renderAll([1],(value:string|number,index:number)=>String(index));'),
  ],'参数类型应表达实际会传入的所有原值。把数字转换成文本改变了业务行为，不能靠这种转换掩盖错误的回调契约。','输入包含两类值。｜回调也必须接收这两类。｜不要转换原值后再调用。',{runtime:[run('保持原值与调用顺序','const {renderAll}=load("main.js");const seen=[];equal(renderAll([2,"a",0],value=>{seen.push(value);return typeof value+":"+value;}),["number:2","string:a","number:0"]);equal(seen,[2,"a",0]);equal(renderAll([],()=>{throw Error("不应调用");}),[]);')]}),
 m(3,5,'方法签名的例外','在 strictFunctionTypes 下，接口的 method(value:T):void 与 property:(value:T)=>void 有什么重要差异？',['方法签名的参数检查存在双向兼容例外，函数属性通常按严格方向检查','两种写法所有情况下完全相同','函数属性不检查任何参数','方法签名自动生成运行时参数校验'],'方法形式在参数兼容检查中有特殊规则。涉及安全回调容器时，要明确使用的声明形式，不能把所有函数位置一概而论。','观察冒号位于成员名后还是参数后。｜strictFunctionTypes 对方法有例外。｜例外不等于运行时安全。'),
 t(3,6,'设计严格处理器容器','导出 Consumer<T>，包含函数属性 accept:(value:T)=>void。严格模式下 Consumer<string> 不应赋给 Consumer<string|number>；能够接收 unknown 的处理器可以用于 string。',
  'export interface Consumer<T>{accept(value:T):void}',
  'export interface Consumer<T>{accept:(value:T)=>void}',[
   ok('宽输入处理器可用于窄调用','import type {Consumer} from "./main";const broad:Consumer<unknown>={accept:value=>{}};const text:Consumer<string>=broad;text.accept("ok");'),
   bad('窄处理器不可冒充通用处理器','import type {Consumer} from "./main";const text:Consumer<string>={accept:value=>{value.toUpperCase();}};const all:Consumer<string|number>=text;'),
   bad('实际调用遵守输入范围','import type {Consumer} from "./main";declare const text:Consumer<string>;text.accept(1);'),
  ],'函数属性使参数接受严格方向检查。方法签名在这里可能允许不安全的替换，所以声明样式是本题契约的一部分。','不要使用方法成员简写。｜属性值本身是函数类型。｜写成 accept: (value:T)=>void。'),
 m(3,7,'返回类型的替换方向','目标函数返回 {id:string}，候选函数返回 {id:string;name:string}，为什么通常可以替代？',['候选提供了调用方所需的全部返回结构，还提供更多信息','返回类型永远不检查','只要属性多就可以忽略 id 类型','函数返回时自动删除 name'],'返回值应满足调用方期望的结构。额外字段通常不妨碍结构兼容，但缺少 id 或 id 类型不符仍不合法。','调用方需要从结果读取 id。｜候选结果满足这个要求。｜额外信息不代表运行时删除。'),
 t(3,8,'迁移：给窄回调增加真实守卫','实现 onText(callback:(text:string)=>void):(value:string|number)=>void。返回通用回调，文本原样交给 callback 一次，数字忽略；不能强制断言或把数字转成文本。',
  'export function onText(callback:(text:string)=>void):(value:string|number)=>void{return value=>callback(String(value));}',
  'export function onText(callback:(text:string)=>void):(value:string|number)=>void{return value=>{if(typeof value==="string")callback(value);};}',[
   ok('适配后接收整个联合','import {onText} from "./main";const handler:(value:string|number)=>void=onText(text=>{text.toUpperCase();});handler(2);handler("ok");'),
   bad('传入的回调需要能处理文本','import {onText} from "./main";onText((value:number)=>{});'),
  ],'适配器接收完整输入范围，再用运行判断保证窄回调只收到文本。它改变的是实际处理流程，而不是通过断言隐藏不安全调用。','返回函数必须接收完整联合。｜只在 typeof 为 string 时调用。｜数字路径不做转换也不调用。',{runtime:[run('只分发文本且保留空文本','const {onText}=load("main.js");const seen=[];const handler=onText(value=>seen.push(value));handler(1);handler("a");handler(0);handler("");equal(seen,["a",""]);')]}),
 m(3,9,'复测：可选回调参数','把回调声明成 (index?:number)=>void，是否适合表达“调用方每次都提供 index，但回调可以不用它”？',['不适合，可选表示调用方允许省略，回调实现必须考虑 undefined；不用参数可直接少声明','适合，可选只表示不用时不报错','适合，可选参数永远是 number','无所谓，函数参数没有类型检查'],'可选参数表达调用契约中的缺失可能，不是提示实现者可以忽略。若调用方保证提供数字，应声明 index:number，回调仍可选择不使用参数。','可选决定调用时能否省略。｜实现者必须接受所有合法调用。｜忽略参数不需要把它声明为可选。'),
 t(3,10,'复测：保证索引的访问器','实现 visit(values:readonly string[],callback:(value:string,index:number)=>void):void。每个值按顺序访问一次，索引从 0 开始；允许只使用 value 的回调。',
  'export function visit(values:readonly string[],callback:(value:string,index?:number)=>void):void{values.forEach((value,index)=>callback(value,index));}',
  'export function visit(values:readonly string[],callback:(value:string,index:number)=>void):void{values.forEach((value,index)=>callback(value,index));}',[
   ok('索引可直接当数字使用','import {visit} from "./main";visit(["a"],(value,index)=>{const n:number=index;});visit(["a"],value=>{value.toUpperCase();});'),
   bad('不能只接收特定索引','import {visit} from "./main";visit(["a"],(value:string,index:0)=>{});'),
  ],'调用方保证每次给出数字索引，声明就应反映保证。回调可以少声明参数，但声明了的参数不能要求比契约更窄的值。','去掉索引的问号。｜forEach 提供从零开始的索引。｜少用参数仍是合法替换。',{runtime:[run('值和索引严格对应','const {visit}=load("main.js");const calls=[];visit(["x","y","x"],(value,index)=>calls.push([value,index]));equal(calls,[["x",0],["y",1],["x",2]]);visit([],()=>{throw Error("空集合不调用");});')]}),
 m(4,1,'可选与必需 undefined','{name?:string} 与 {name:string|undefined} 的关键区别是什么？',['前者允许省略 name，后者要求存在 name 键，即使值可为 undefined','二者任何配置下完全等价','后者不允许读取 name','前者只能赋空字符串'],'可选性表达属性可缺失，值联合表达值域。读取时都可能遇到 undefined，不代表对象构造要求相同。','先检查空对象能否满足。｜后者的属性没有问号。｜值域与存在性分别考虑。'),
 m(4,2,'精确可选属性的写入','开启 exactOptionalPropertyTypes 时，声明 {name?:string}，哪种构造符合要求？',['{} 或 {name:"Lin"}，但不能直接 {name:undefined}','只能 {name:undefined}','必须总是提供 name','任何值均可，因为 name 可选'],'精确可选属性区分缺失与显式 undefined。需要允许显式 undefined 时，应把它写进属性值联合。','可省略不等于允许每种值。｜存在时需要符合 string。｜undefined 需要显式列入值域。'),
 m(4,3,'读取仍可能缺失','开启 exactOptionalPropertyTypes 后，读取 {name?:string} 的 name 是否自动得到 string？',['不是，未证明存在时读取仍是 string|undefined','是，开启后所有属性都必需','是，缺失时自动补空字符串','不是，读取结果永远是 undefined'],'该配置调整可选属性的写入语义，不自动补值。读取缺失属性仍可能产生 undefined。','对象仍可以是空对象。｜读取缺失字段是什么？｜配置不会生成默认值。'),
 t(4,4,'修复省略字段的构造','本题开启 exactOptionalPropertyTypes。实现 makeOptions(label:string|undefined):{label?:string}。undefined 时返回没有 label 自有属性的对象，否则保留原字符串，包含空字符串。',
  'export function makeOptions(label:string|undefined):{label?:string}{return {label};}',
  'export function makeOptions(label:string|undefined):{label?:string}{return label===undefined?{}:{label};}',[
   ok('构造与读取','import {makeOptions} from "./main";const a:{label?:string}=makeOptions(undefined);const b:string|undefined=makeOptions("x").label;'),
   bad('不接受 null','import {makeOptions} from "./main";makeOptions(null);'),
  ],'若需要省略，就创建不含该键的对象；写入 undefined 是另一种状态。判断时也不能丢弃合法的空字符串。','区分两种返回结构。｜undefined 分支返回空对象。｜其他分支保留 label。',{compilerOptions:{exactOptionalPropertyTypes:true},runtime:[run('省略与空文本','const {makeOptions}=load("main.js");const empty=makeOptions(undefined);check(!Object.hasOwn(empty,"label"));equal(makeOptions(""),{label:""});equal(makeOptions("ok"),{label:"ok"});')]}),
 m(4,5,'展开补丁的陷阱','未开启精确可选属性配置时，{...current,...{name:undefined}} 会怎样处理已有 name？',['用显式 undefined 覆盖已有值，不会自动忽略这个字段','保留原值，因为 undefined 等于字段缺失','删除 name 键','把 name 改为空字符串'],'对象展开复制实际存在的可枚举属性，包括值为 undefined 的属性。是否忽略 undefined 必须由补丁的业务规则决定。','补丁中 name 键实际存在。｜后面的同名属性覆盖前面的。｜展开没有自动忽略规则。'),
 t(4,6,'设计三态补丁','开启精确可选属性。实现 applyName(current:{name:string},patch:{name?:string|null}):{name:string}：省略 name 保持原值；null 清空为 ""；字符串替换，包含空字符串。返回新对象，不修改参数。',
  'export function applyName(current:{name:string},patch:{name?:string|null}):{name:string}{return {name:patch.name||current.name};}',
  'export function applyName(current:{name:string},patch:{name?:string|null}):{name:string}{return {name:patch.name===undefined?current.name:patch.name===null?"":patch.name};}',[
   ok('三态输入','import {applyName} from "./main";applyName({name:"a"},{});applyName({name:"a"},{name:null});const a:{name:string}=applyName({name:"a"},{name:"b"});'),
   bad('显式 undefined 不属于协议','import {applyName} from "./main";applyName({name:"a"},{name:undefined});',[2379,2345]),
  ],'省略、清空和赋新值分别使用不同状态表达。使用 || 会把空字符串和 null 混为不更新，违反补丁语义。','先处理缺失。｜再单独处理 null。｜字符串不应做真值过滤。',{compilerOptions:{exactOptionalPropertyTypes:true},runtime:[run('三态语义及不变性','const {applyName}=load("main.js");const current=Object.freeze({name:"old"});equal(applyName(current,{}),{name:"old"});equal(applyName(current,{name:null}),{name:""});equal(applyName(current,{name:""}),{name:""});equal(applyName(current,{name:"new"}),{name:"new"});check(applyName(current,{})!==current);equal(current,{name:"old"});')]}),
 m(4,7,'delete 与赋 undefined','对允许可选字段的普通对象，delete obj.name 与 obj.name=undefined 的运行时区别是什么？',['delete 移除自有属性，赋 undefined 通常仍保留键；后者是否允许还受静态配置影响','没有区别，Object.keys 总是一样','赋 undefined 自动调用 delete','delete 只修改类型不修改对象'],'属性是否存在能通过自有属性检查观察。静态赋值许可和运行时删除语义需要分别讨论。','观察 Object.hasOwn 的结果。｜赋值一般不会删除键。｜精确可选配置可能拒绝该赋值。'),
 t(4,8,'迁移：明确删除可选属性','开启精确可选属性。实现 clearNickname<T extends {nickname?:string}>(value:T):Omit<T,"nickname">：返回移除 nickname 的新对象，保留其他自有可枚举字段，不修改原对象。',
  'export function clearNickname<T extends {nickname?:string}>(value:T):Omit<T,"nickname">{return {...value,nickname:undefined};}',
  'export function clearNickname<T extends {nickname?:string}>(value:T):Omit<T,"nickname">{const {nickname,...rest}=value;return rest;}',[
   ok('其他字段类型保留','import {clearNickname} from "./main";const result=clearNickname({nickname:"n",id:1,active:true});const id:number=result.id;const active:boolean=result.active;'),
   bad('返回类型不含 nickname','import {clearNickname} from "./main";clearNickname({nickname:"n",id:1}).nickname;'),
  ],'Omit 只改变静态视图，必须实际执行对象拆分才能移除键。把 nickname 赋为 undefined 并未删除这个自有属性。','解构取出 nickname。｜剩余属性组成新对象。｜返回 rest，不要重新添加该键。',{compilerOptions:{exactOptionalPropertyTypes:true},runtime:[run('真实删除而不是留 undefined','const {clearNickname}=load("main.js");const source=Object.freeze({nickname:"n",id:1,active:true});const result=clearNickname(source);equal(result,{id:1,active:true});check(!Object.hasOwn(result,"nickname"));check(result!==source);equal(source.nickname,"n");equal(clearNickname({}),{});')]}),
 m(4,9,'复测：允许显式 undefined','开启精确可选属性时，若协议确实需要“省略、文本、显式 undefined”三种写入，应该如何声明？',['name?:string|undefined','name:string','name?:never','name:undefined'],'问号允许省略，显式联合 undefined 允许存在但值为 undefined。是否在业务上区分两种状态，需要用属性存在检查实现。','先表达可以省略。｜再表达存在时的值域。｜问号与 undefined 可以同时需要。'),
 t(4,10,'复测：保留属性存在性','开启精确可选属性。实现 describe(value:{name?:string|undefined}):"missing"|"undefined"|"text"。没有自有 name 返回 missing；自有值为 undefined 返回 undefined；自有文本返回 text。继承的 name 不算自有字段。',
  'export function describe(value:{name?:string|undefined}):"missing"|"undefined"|"text"{return value.name===undefined?"missing":"text";}',
  'export function describe(value:{name?:string|undefined}):"missing"|"undefined"|"text"{if(!Object.hasOwn(value,"name"))return "missing";return value.name===undefined?"undefined":"text";}',[
   ok('显式 undefined 是合法输入','import {describe} from "./main";const a:"missing"|"undefined"|"text"=describe({name:undefined});describe({});describe({name:""});'),
   bad('null 不在值域','import {describe} from "./main";describe({name:null});'),
  ],'仅比较读取值无法区分缺失与显式 undefined。先检查自有属性存在性，再检查值；in 还会看到继承属性，不符合本题要求。','先判断 Object.hasOwn。｜存在后才区分 undefined 和文本。｜空字符串仍属于文本。',{compilerOptions:{exactOptionalPropertyTypes:true},runtime:[run('区分自有缺失和显式空值','const {describe}=load("main.js");equal(describe({}),"missing");equal(describe({name:undefined}),"undefined");equal(describe({name:""}),"text");equal(describe({name:"ok"}),"text");equal(describe(Object.create({name:"inherited"})),"missing");')]}),
 m(5,1,'断言不会转换值','const value:unknown="42"; const count=value as number; count 在运行时是什么？',['仍是字符串 "42"，断言没有执行数值转换','数字 42','NaN','undefined'],'as 告诉检查器按指定类型看待表达式，编译后不会产生转换步骤。需要转换时必须调用相应运行逻辑并验证结果。','观察有没有调用 Number。｜类型语法会被擦除。｜原始值不会因此改变。'),
 m(5,2,'非空断言没有后备值','对可能为 undefined 的查找结果使用 result!.name，查找失败时会怎样？',['运行时仍可能抛错，! 不会创建对象或提供默认值','自动创建 name 为空的对象','返回字符串 undefined','自动跳过整条表达式'],'非空断言仅移除静态空值疑虑，不改变实际值。要定义缺失时返回、抛错或默认值的真实行为。','! 是类型操作。｜实际结果仍可能 undefined。｜访问不存在对象的属性仍会失败。'),
 m(5,3,'双重断言的代价','value as unknown as Target 能通过某些不兼容断言，这意味着什么？',['人为绕过了静态兼容检查，并未证明值满足 Target','完成了深度校验','会生成 Target 的实例','一定比类型守卫安全'],'双重断言可以隐藏不兼容关系。它不提供运行时证据，也不应该替代外部数据校验。','检查过程中并没有读取字段。｜unknown 不是校验函数。｜编译许可不等于事实成立。'),
 t(5,4,'修复查找结果的缺失路径','实现 findName(users:readonly {id:string;name:string}[],id:string):string|null。返回首个匹配用户的 name；无匹配返回 null，不使用非空断言。',
  'export function findName(users:readonly {id:string;name:string}[],id:string):string|null{return users.find(user=>user.id===id)!.name;}',
  'export function findName(users:readonly {id:string;name:string}[],id:string):string|null{const user=users.find(user=>user.id===id);return user===undefined?null:user.name;}',[
   ok('显式失败结果','import {findName} from "./main";const result:string|null=findName([],"a");'),
   bad('调用方需要处理缺失','import {findName} from "./main";const result:string=findName([],"a");'),
  ],'先保存并检查查找结果，才能证明读取属性安全。返回 null 明确告诉调用方未找到；空姓名仍是合法结果。','find 可能返回 undefined。｜先判断对象是否存在。｜存在时保留原 name。',{runtime:[run('缺失与首个匹配','const {findName}=load("main.js");equal(findName([],"a"),null);equal(findName([{id:"a",name:""}],"a"),"");equal(findName([{id:"a",name:"first"},{id:"a",name:"second"}],"a"),"first");equal(findName([{id:"b",name:"B"}],"a"),null);')]}),
 m(5,5,'什么时候可以考虑断言','在确实需要类型断言时，什么证据最有意义？',['有明确的外部契约或实际检查，并说明检查器无法表达的关系','编辑器没有报错','变量名看起来像目标类型','线上暂时没收到错误反馈'],'断言把部分证明责任交给开发者。应尽量局部化并有可验证依据；没有报错或变量名都不是数据结构的证明。','先说明为什么事实成立。｜区分证据与愿望。｜把无法表达的边界控制在局部。'),
 t(5,6,'设计真实的断言函数','实现 assertText(value:unknown):asserts value is string。字符串直接返回，其他值抛出 Error，消息为 "Expected text"。空字符串合法，不使用 as 或非空断言。',
  'export function assertText(value:unknown):asserts value is string {}',
  'export function assertText(value:unknown):asserts value is string {if(typeof value!=="string")throw new Error("Expected text");}',[
   ok('检查后可以使用字符串','import {assertText} from "./main";let value:unknown="ok";assertText(value);const text:string=value;value.toUpperCase();'),
   bad('检查前仍不可当字符串','import {assertText} from "./main";let value:unknown=1;const text:string=value;'),
  ],'asserts 签名是静态承诺，编译器不会证明函数体真的完成检查。必须通过运行测试验证错误值会被拒绝；空函数也可能编译通过。','非字符串必须结束正常路径。｜抛出指定错误。｜字符串路径正常返回。',{runtime:[run('断言承诺有实际检查','const {assertText}=load("main.js");assertText("");assertText("ok");for(const value of [1,null,undefined,{},[],true]){let caught=false;try{assertText(value);}catch(error){caught=true;equal(error.message,"Expected text");}check(caught,"必须拒绝非字符串");}')]}),
 m(5,7,'satisfies 不是运行校验','为什么不能依赖 satisfies 验证从网络得到的未知对象？',['它执行静态可赋值检查，不生成对远端值的运行检查','它只支持数字','它能校验但只能在生产环境生效','它会自动发起第二次请求'],'外部数据需要实际检查。satisfies 适合检查本地表达式的静态契约，不会把不可信数据自动变成可靠模型。','操作发生在编译期间。｜网络返回是在运行期间。｜需要检查字段和值。'),
 t(5,8,'迁移：安全读取计数','实现 readCount(value:unknown):number|null。只接受有限且非负的整数 number，其他返回 null；不做字符串转换。不得使用断言。',
  'export function readCount(value:unknown):number|null{return value as number;}',
  'export function readCount(value:unknown):number|null{return typeof value==="number"&&Number.isFinite(value)&&Number.isInteger(value)&&value>=0?value:null;}',[
   ok('边界输入保持 unknown','import {readCount} from "./main";const result:number|null=readCount({count:1});readCount("1");'),
   bad('结果不保证成功','import {readCount} from "./main";const result:number=readCount("1");'),
  ],'typeof 提供数值类型证据，业务检查再排除 NaN、无穷、小数和负数。as number 不会完成这些步骤，也不会转换文本。','先检查真实类型。｜再检查有限整数及非负范围。｜失败返回 null。',{runtime:[run('拒绝伪装数字和无效数值','const {readCount}=load("main.js");equal(readCount(0),0);equal(readCount(8),8);for(const value of ["8",-1,1.5,NaN,Infinity,-Infinity,null,undefined,{},true])equal(readCount(value),null);')]}),
 m(5,9,'复测：断言与类型守卫承诺','一个返回 true 的函数被声明为 value is User，为什么仍可能有漏洞？',['检查器依赖谓词承诺，函数体可能没有正确验证全部必需字段','谓词一定被编译器自动证明','所有返回 true 的函数都会验证 User','只有 as 才可能不安全，谓词不可能出错'],'谓词与 asserts 声明也需要可信实现。运行时反例测试应覆盖每个必需字段及其值类型，不能只看签名。','声明表达承诺。｜实现可能与承诺不一致。｜用反例验证实现。'),
 t(5,10,'复测：验证后执行操作','实现 upperText(value:unknown):string|null。仅原始字符串返回 toUpperCase() 结果，其他值返回 null；不能通过 String(value) 强制转换，也不能使用断言。',
  'export function upperText(value:unknown):string|null{return String(value).toUpperCase();}',
  'export function upperText(value:unknown):string|null{if(typeof value!=="string")return null;return value.toUpperCase();}',[
   ok('明确未知输入和失败结果','import {upperText} from "./main";const result:string|null=upperText(undefined);'),
   bad('调用方不可忽略失败','import {upperText} from "./main";const result:string=upperText(1);'),
  ],'转换与验证解决不同问题。本题要求拒绝非字符串，使用 String 会把本应拒绝的输入转换成文本；真实检查后才能按契约调用方法。','不要把所有值先转字符串。｜typeof 成功后才调用方法。｜其他路径返回 null。',{runtime:[run('接受文本并拒绝可转换对象','const {upperText}=load("main.js");equal(upperText("hello"),"HELLO");equal(upperText(""),"");for(const value of [1,null,undefined,true,[],{toString(){throw Error("不应转换");}}])equal(upperText(value),null);')]}),
 m(6,1,'unknown 的边界作用','为什么将外部输入先接收为 unknown 比直接声明为业务对象更合适？',['它要求使用前提供检查证据，避免把未验证的数据当成可靠模型','它会自动拒绝所有错误数据','它会自动解析 JSON','它让所有属性访问都不再检查'],'unknown 保留不确定性，并限制未经检查的操作。它本身不是校验器，真实检查仍由程序实现。','输入声明不是数据证明。｜unknown 限制直接使用。｜需要检查后建立模型。'),
 m(6,2,'对象检查的第一步','typeof value === "object" 后，为什么不能立即读取任意字段？',['还要处理 null，并证明目标属性存在及值类型','所有 object 都有所有字段','object 自动排除 null','字段会在读取时被自动创建'],'JavaScript 的 typeof null 是 object。排除 null 后，还需确认属性及其值满足目标契约。','先考虑 null。｜再考虑缺失属性。｜存在也不表示类型正确。'),
 m(6,3,'数组检查的局限','Array.isArray(value) 成功后，能否直接认定这是 string[]？',['不能，仍需逐个检查元素，空数组是否允许也由契约决定','能，JavaScript 数组只能装字符串','能，只要第一个元素是字符串','不能，因为数组永远不能收窄'],'容器形状和元素形状是不同的证据。检查第一个元素会遗漏后续不合法值，混合数组必须考虑。','数组可以混合多种值。｜逐项验证才覆盖所有元素。｜先明确空数组的规则。'),
 t(6,4,'修复用户对象读取','实现 readUser(value:unknown):{id:string;active:boolean}|null。接受非 null、非数组对象，要求自有 id 为非空字符串、自有 active 为 boolean；返回只含这两个字段的新对象，否则 null。不要求处理会抛错的 getter 或 Proxy。',
  'export function readUser(value:unknown):{id:string;active:boolean}|null {if(typeof value==="object"&&value!==null&&"id" in value&&"active" in value&&typeof value.id==="string"&&typeof value.active==="boolean")return {id:value.id,active:value.active};return null;}',
  'export function readUser(value:unknown):{id:string;active:boolean}|null {if(typeof value!=="object"||value===null||Array.isArray(value))return null;if(!Object.hasOwn(value,"id")||!Object.hasOwn(value,"active")||!("id" in value)||!("active" in value))return null;if(typeof value.id!=="string"||value.id.length===0||typeof value.active!=="boolean")return null;return {id:value.id,active:value.active};}',[
   ok('未知输入与明确结果','import {readUser} from "./main";const a:{id:string;active:boolean}|null=readUser({id:"a",active:false});readUser(null);'),
   bad('不能直接忽略失败','import {readUser} from "./main";const a:{id:string;active:boolean}=readUser({});'),
  ],'对象、字段存在性、字段类型和业务范围都需要证据。自有属性要求不能只用 in 判断；返回新对象同时隔离额外字段。','先拒绝 null 和数组。｜检查自有键，再检查字段值。｜非空 id 与布尔值都满足才构造结果。',{runtime:[run('对象边界与字段所有权','const {readUser}=load("main.js");const input={id:"a",active:false,secret:"s"};const out=readUser(input);equal(out,{id:"a",active:false});check(out!==input);for(const value of [null,undefined,1,{},[],{id:"",active:true},{id:"a",active:1},{id:1,active:true},Object.create({id:"a",active:true}),Object.assign([],{id:"a",active:true})])equal(readUser(value),null);')]}),
 m(6,5,'JSON 语法正确不代表模型正确','JSON.parse 没有抛错，可以说明什么？',['文本符合 JSON 语法，但结果可能是 null、数字、数组或不符合业务的对象','一定得到业务需要的对象','所有字段都满足声明接口','只要 JSON 有花括号就无需验证'],'解析解决文本语法问题，模型验证检查解析值的结构和值域。两个步骤需要分别处理失败。','JSON 允许多种顶层值。｜解析不认识业务接口。｜仍需检查结果。'),
 t(6,6,'设计全部有效才成功的文本列表读取器','实现 readTags(value:unknown):string[]|null。仅接受数组，所有元素必须是非空字符串；空数组合法。返回新数组，不转换或丢弃错误元素。',
  'export function readTags(value:unknown):string[]|null {if(!Array.isArray(value))return null;return value.filter((item):item is string=>typeof item==="string"&&item.length>0);}',
  'export function readTags(value:unknown):string[]|null {if(!Array.isArray(value))return null;const tags:string[]=[];for(const item of value){if(typeof item!=="string"||item.length===0)return null;tags.push(item);}return tags;}',[
   ok('输入不可信且失败显式','import {readTags} from "./main";const result:string[]|null=readTags(["a"]);readTags({});'),
   bad('不能忽略失败','import {readTags} from "./main";const result:string[]=readTags(null);'),
  ],'过滤会悄悄丢失错误元素，而本题要求整个输入失败。逐项检查并构建新数组，既保持顺序和重复项，也不污染原输入。','不是过滤合法子集。｜任意不合格项都返回 null。｜全部通过后返回新数组。',{runtime:[run('混合输入整体拒绝','const {readTags}=load("main.js");const input=Object.freeze(["a","a","b"]);const result=readTags(input);equal(result,["a","a","b"]);check(result!==input);equal(readTags([]),[]);for(const value of [null,"a",{},["a",2],["a",""]])equal(readTags(value),null);')]}),
 m(6,7,'catch 的值也可能未知','为什么处理 catch(error) 时不能假定 error 一定是 Error 实例？',['JavaScript 可以抛出任意值，应先检查再读取 message','throw 只能抛 Error','catch 会自动把字符串包装成 Error','TS 会自动补齐 message 字段'],'抛出的值可能来自业务代码或外部库，字符串、null 等都可能出现。异常边界同样需要收窄。','throw 的运行语义允许任意值。｜先证明 Error 实例。｜其他情况提供明确后备行为。'),
 t(6,8,'迁移：区分解析失败与模型失败','实现 parseEnabled(text:string):{ok:true;value:boolean}|{ok:false;reason:"syntax"|"shape"}。JSON 解析异常返回 syntax；解析成功但不是 boolean 返回 shape；boolean 原样返回。',
  'export function parseEnabled(text:string):{ok:true;value:boolean}|{ok:false;reason:"syntax"|"shape"}{try{const value:unknown=JSON.parse(text);return {ok:true,value:Boolean(value)};}catch{return {ok:false,reason:"syntax"};}}',
  'export function parseEnabled(text:string):{ok:true;value:boolean}|{ok:false;reason:"syntax"|"shape"}{let value:unknown;try{value=JSON.parse(text);}catch{return {ok:false,reason:"syntax"};}if(typeof value!=="boolean")return {ok:false,reason:"shape"};return {ok:true,value};}',[
   ok('按结果标签读取','import {parseEnabled} from "./main";const result=parseEnabled("true");if(result.ok){const v:boolean=result.value;}else{const r:"syntax"|"shape"=result.reason;}'),
   bad('输入必须为文本','import {parseEnabled} from "./main";parseEnabled(true);'),
  ],'把 JSON.parse 的结果接入 unknown，再用真实类型检查建立 boolean 证据。Boolean 转换会让许多错误结构伪装成合法值。','解析异常单独处理。｜成功后检查 typeof。｜false 也是合法结果。',{runtime:[run('区分语法与结构失败','const {parseEnabled}=load("main.js");equal(parseEnabled("true"),{ok:true,value:true});equal(parseEnabled("false"),{ok:true,value:false});equal(parseEnabled("{"),{ok:false,reason:"syntax"});for(const text of ["null","0","1","{}","[]",JSON.stringify("false")])equal(parseEnabled(text),{ok:false,reason:"shape"});')]}),
 m(6,9,'复测：类型守卫的检查粒度','校验 {id:string;roles:string[]} 时，只检查 id 是字符串且 roles 是数组，遗漏了什么？',['roles 中每个元素的类型','对象变量名','JSON 字段的排列顺序','接口在源码中的行号'],'数组容器检查不证明元素类型。验证器必须覆盖目标类型承诺中的每一部分，业务限制还可能要求非空或候选范围。','把目标结构逐层展开。｜数组还有元素契约。｜不能只验证容器。'),
 t(6,10,'复测：未知错误转成稳定消息','实现 errorMessage(error:unknown):string。Error 实例返回其 message，原始字符串原样返回，其他值返回 "Unknown error"。不要对其他值执行 String 转换。',
  'export function errorMessage(error:unknown):string{return String(error);}',
  'export function errorMessage(error:unknown):string{if(error instanceof Error)return error.message;if(typeof error==="string")return error;return "Unknown error";}',[
   ok('接受所有未知值','import {errorMessage} from "./main";const message:string=errorMessage(null);errorMessage(new Error("bad"));'),
   bad('返回是文本而非错误对象','import {errorMessage} from "./main";const result:Error=errorMessage("bad");'),
  ],'按明确允许的两种情况读取消息，其余使用固定后备文本。未知对象上的转换也可能执行自定义方法，不能把它当成无条件安全的读取。','先检查 Error 实例。｜再检查原始字符串。｜其余直接固定文本。',{runtime:[run('错误和非错误抛出值','const {errorMessage}=load("main.js");equal(errorMessage(new Error("bad")),"bad");equal(errorMessage(""),"");equal(errorMessage("text"),"text");for(const value of [null,undefined,1,{message:"pretend"},{toString(){throw Error("不应转换");}}])equal(errorMessage(value),"Unknown error");')]}),
 m(7,1,'声明文件的信任边界','库的 .d.ts 声明返回 string，但实际 JavaScript 返回 null，使用方通过编译能证明什么？',['使用方符合声明的契约，不能证明库运行实现与声明一致','证明运行时绝不返回 null','编译器会自动修正库的返回值','声明文件在运行时验证每次调用'],'声明文件描述约定，不执行验证。错误声明会让检查器建立错误前提，需要实现测试或边界校验确认。','检查器能看到的是声明。｜运行实现可能与声明不一致。｜类型检查不是库行为证明。'),
 m(7,2,'any 的传播','把外部结果声明为 any 后，为什么错误属性访问可能不再报错？',['any 放宽了相关检查，并可能继续传播到后续表达式','编译器已经验证所有属性','any 表示值一定符合任何接口','所有访问会自动返回安全默认值'],'any 能隐藏本应暴露的不确定性。边界处改用 unknown 并校验，才能让后续类型保证建立在证据上。','any 不是所有结构的证明。｜检查被放宽不代表安全。｜关注后续结果是否继续丢失约束。'),
 m(7,3,'泛型解析器的空承诺','function parse<T>(text:string):T 若只返回 JSON.parse(text)，问题是什么？',['调用者可任意指定 T，但实现没有验证解析值满足 T','泛型会自动按 T 校验 JSON','JSON.parse 会读取 T 的字段','只要解析没抛错就完全安全'],'类型参数不能在运行时直接读取。把解析值声明成任意 T 是未经验证的承诺；可通过传入真正的解码函数建立关系。','T 在运行时不存在。｜JSON 语法不等于业务模型。｜需要与 T 对应的实际解码器。'),
 t(7,4,'修复任意泛型解析承诺','实现 decodeJson<T>(text:string,decode:(value:unknown)=>T):T。先解析 JSON，再把解析结果交给 decode 一次并返回其结果；语法错误和解码错误原样传播。',
  'export function decodeJson<T>(text:string,decode:(value:unknown)=>T):T{return JSON.parse(text);}',
  'export function decodeJson<T>(text:string,decode:(value:unknown)=>T):T{const value:unknown=JSON.parse(text);return decode(value);}',[
   ok('结果来自解码器','import {decodeJson} from "./main";const result:number=decodeJson("1",value=>{if(typeof value!=="number")throw Error("bad");return value+1;});'),
   bad('返回值不能由调用方随意改变','import {decodeJson} from "./main";const result:string=decodeJson("1",()=>1);'),
   bad('解码器必须接受未知输入','import {decodeJson} from "./main";decodeJson("1",(value:string)=>value);'),
  ],'T 与解码器的实际返回值建立联系，解析后的未知值不能直接冒充 T。语法和业务失败由各自步骤自然抛出。','把解析结果先保存在 unknown。｜调用 decode 并返回它的结果。｜不要吞掉任何一步的错误。',{runtime:[run('解码真实执行且错误传播','const {decodeJson}=load("main.js");let count=0;equal(decodeJson("2",value=>{count++;return value+3;}),5);equal(count,1);const sentinel={reason:"invalid"};let caught;try{decodeJson("null",()=>{throw sentinel;});}catch(error){caught=error;}check(caught===sentinel);let called=false;let syntax=false;try{decodeJson("{",()=>{called=true;return 1;});}catch{syntax=true;}check(syntax);check(!called);')]}),
 m(7,5,'void 回调与异步遗漏','一个 API 接受 ()=>void，传入 async 回调能够通过编译，是否说明 API 会等待它？',['不能，void 上下文可以忽略返回值，API 必须实际等待 Promise 才有等待行为','说明 API 自动 await','说明 async 函数变成同步','说明 Promise 不可能拒绝'],'类型允许忽略返回值，不会生成等待流程。异步 API 应明确返回值和错误传播契约，并在实现中实际 await。','void 常表示调用方忽略返回值。｜允许赋值不改变运行步骤。｜检查 API 是否使用返回的 Promise。'),
 t(7,6,'设计等待完成后提交的流程','实现 runThenCommit(work:()=>Promise<void>,commit:()=>void):Promise<void>。先调用 work，成功完成后调用 commit 一次；work 同步抛出或 Promise 拒绝时不提交，错误原样传播。',
  'export async function runThenCommit(work:()=>Promise<void>,commit:()=>void):Promise<void>{work();commit();}',
  'export async function runThenCommit(work:()=>Promise<void>,commit:()=>void):Promise<void>{await work();commit();}',[
   ok('异步契约','import {runThenCommit} from "./main";const result:Promise<void>=runThenCommit(async()=>{},()=>{});'),
   bad('工作函数需要 Promise','import {runThenCommit} from "./main";runThenCommit(()=>{},()=>{});'),
  ],'标记 async 只保证外层返回 Promise，不自动等待函数体中所有异步调用。显式 await 建立工作完成与提交之间的顺序。','必须使用 work 的返回值。｜等待成功后再提交。｜不捕获或吞掉失败。',{runtime:[run('等待完成及拒绝传播','const {runThenCommit}=load("main.js");const events=[];let release;const gate=new Promise(resolve=>{release=resolve;});const pending=runThenCommit(async()=>{events.push("start");await gate;events.push("done");},()=>events.push("commit"));equal(events,["start"]);release();await pending;equal(events,["start","done","commit"]);const sentinel={reason:"fail"};let commits=0;let caught;try{await runThenCommit(()=>Promise.reject(sentinel),()=>commits++);}catch(error){caught=error;}check(caught===sentinel);equal(commits,0);caught=undefined;try{await runThenCommit(()=>{throw sentinel;},()=>commits++);}catch(error){caught=error;}check(caught===sentinel);equal(commits,0);')]}),
 m(7,7,'索引类型不是存在证明','默认未开启 noUncheckedIndexedAccess 时，number[] 的 values[100] 可能被视为 number，为什么仍需关注越界？',['数组类型不保证该索引存在，运行时可能得到 undefined','数组会自动补齐到 101 项','TypeScript 会在访问前检查长度','数字数组不允许为空'],'某些默认静态规则偏向便利，不代表运行时存在性保证。严格索引配置能暴露更多风险，业务边界也需要实际处理。','类型描述元素，不保证长度。｜空数组也满足 number[]。｜运行结果可能缺失。'),
 t(7,8,'迁移：安全取得索引值','实现 atIndex<T>(values:readonly T[],index:number):T|undefined。只接受非负整数索引且小于 length，否则返回 undefined；有效索引读取原值，不允许负数倒数语义。',
  'export function atIndex<T>(values:readonly T[],index:number):T|undefined{return values.at(index);}',
  'export function atIndex<T>(values:readonly T[],index:number):T|undefined{if(!Number.isInteger(index)||index<0||index>=values.length)return undefined;return values[index];}',[
   ok('元素类型和失败可能保留','import {atIndex} from "./main";const result:number|undefined=atIndex([1,2],0);const text:string|undefined=atIndex(["a"],4);'),
   bad('不能忽略未命中','import {atIndex} from "./main";const result:number=atIndex([1],3);'),
  ],'Array.at 接受负数并会处理非整数索引，语义与本题不一致。类型兼容不足以证明业务行为一致，需明确验证索引范围。','先验证整数。｜检查非负及上界。｜最后读取原索引。',{runtime:[run('整数范围和原值引用','const {atIndex}=load("main.js");const value={id:1};check(atIndex([value],0)===value);for(const index of [-1,0.5,1,NaN,Infinity])equal(atIndex([value],index),undefined);equal(atIndex([],0),undefined);equal(atIndex(["a","b"],1),"b");')]}),
 m(7,9,'复测：测试与类型的分工','一个金额计算函数接受 number 并返回 number，类型检查能否证明舍入和折扣规则正确？',['不能，类型限制输入输出结构，业务规则还需要运行测试','能，number 自动符合全部业务规则','能，只要没有 any','不能，所以类型检查完全没有价值'],'类型检查和行为验证覆盖不同方面。测试边界、顺序、错误传播等行为，与类型正反例配合才更完整。','数字类型不描述全部计算规则。｜同类型实现可以产生不同结果。｜两类证据互相补充。'),
 t(7,10,'复测：结果必须来自实际映射','实现 mapResult<T,U>(value:T,transform:(value:T)=>U):U。调用 transform 恰好一次，传入原值，返回其实际结果，异常原样传播。',
  'export function mapResult<T,U>(value:T,transform:(value:T)=>U):U{transform(value);return transform(value);}',
  'export function mapResult<T,U>(value:T,transform:(value:T)=>U):U{return transform(value);}',[
   ok('输入输出类型关联','import {mapResult} from "./main";const result:string=mapResult(1,n=>String(n));'),
   bad('回调参数必须匹配输入','import {mapResult} from "./main";mapResult(1,(value:string)=>value);'),
  ],'重复执行回调仍能满足同样的类型签名，却可能重复产生副作用。次数、原值引用和异常传播需要行为测试验证。','类型签名没有限制调用次数。｜直接返回唯一一次调用结果。｜不要提前试调用。',{runtime:[run('次数引用与异常原样传播','const {mapResult}=load("main.js");const input={id:1};const output={ok:true};let calls=0;check(mapResult(input,value=>{calls++;check(value===input);return output;})===output);equal(calls,1);const sentinel={bad:true};let caught;try{mapResult(1,()=>{throw sentinel;});}catch(error){caught=error;}check(caught===sentinel);')]}),
];
