import { mc, task, ok, bad, run } from './author.mjs';
const id=n=>`t10-l${String(n).padStart(2,'0')}`;
const m=(l,n,title,prompt,options,explanation,hints,extra={})=>mc(id(l),n,title,prompt,options,explanation,hints.split('｜'),extra);
const t=(l,n,title,prompt,files,solution,tests,explanation,hints,extra={})=>task(id(l),n,title,prompt,files,solution,tests,explanation,hints.split('｜'),extra);
export const questions=[
 m(1,1,'类的两个侧面','声明 class User 后，类型位置的 User 与 typeof User 通常分别表示什么？',['实例类型与类构造函数值的类型','都只表示实例类型','都只表示字符串类名','前者是构造函数，后者是实例'],'类声明同时提供运行时构造函数和实例类型名字。typeof User 从值侧取得构造函数及静态成员的类型。','先区分 new 出来的对象与类本身。｜User 类型描述实例。｜typeof 查询值侧类型。'),
 m(1,2,'静态成员属于谁','class Counter {static total=0; value=0} 中，如何分别访问 total 与 value？',['Counter.total 与 new Counter().value','new Counter().total 与 Counter.value','两者只能通过 Counter 访问','两者只能通过实例访问'],'static 成员位于类构造函数一侧，实例字段位于每个对象上。访问方式反映不同的成员归属。','static 说明成员归属。｜value 没有 static。｜实例由 new 创建。'),
 m(1,3,'派生构造函数的顺序','在派生类构造函数中，为什么通常必须先调用 super(...) 再访问 this？',['父类构造过程需要先建立派生实例的 this','super 只是可选的格式化函数','调用 super 会把对象变成字符串','TS 会自动跳过所有未初始化字段'],'派生类初始化遵循 JavaScript 的构造规则。需要通过父类构造初始化，再访问当前实例。','继承类需要父类构造步骤。｜此时 this 尚未完成建立。｜super 先于 this 使用。'),
 t(1,4,'修复独立的实例状态','实现 Counter：构造参数 start:number 初始化实例 value:number；add(amount:number):number 累加并返回当前值。多个实例互不影响。',
  'export class Counter {static value=0;constructor(start:number){Counter.value=start;}add(amount:number):number{return Counter.value+=amount;}}',
  'export class Counter {value:number;constructor(start:number){this.value=start;}add(amount:number):number{return this.value+=amount;}}',[
   ok('实例字段及方法','import {Counter} from "./main";const counter=new Counter(2);const current:number=counter.value;const next:number=counter.add(3);'),
   bad('数值参数受约束','import {Counter} from "./main";new Counter("2");'),
   bad('实例值不是类静态值','import {Counter} from "./main";Counter.value;'),
  ],'实例状态必须保存在 this 上，static 状态会被所有实例共享。构造和更新都应针对当前对象。','把 value 放到实例。｜构造函数写 this.value。｜add 更新同一实例字段。',{runtime:[run('实例独立且保留初始值','const {Counter}=load("main.js");const a=new Counter(2);const b=new Counter(10);equal(a.add(3),5);equal(b.value,10);equal(b.add(-2),8);equal(a.value,5);')]}),
 m(1,5,'override 的保证范围','override 标记最主要帮助检查什么？',['该成员确实覆盖基类已有成员，并接受相关类型兼容检查；不证明业务行为正确','自动调用基类实现','自动复制所有父类状态','证明子类所有运行行为都正确'],'override 可以暴露重命名后不再对应的成员，但执行内容、调用次数等仍需测试验证。','它检查继承成员关系。｜不是自动 super 调用。｜类型关系和实际行为分别验证。'),
 t(1,6,'设计保留父类行为的扩展','导出 Greeter 和 LoudGreeter。Greeter 构造 name:string，greet():string 返回 "Hello, "+name；LoudGreeter extends Greeter，覆盖 greet，把 super.greet() 的结果转为大写。',
  'export class Greeter {constructor(public name:string){}greet():string{return "Hello, "+this.name;}}export class LoudGreeter extends Greeter {override greet():string{return this.name.toUpperCase();}}',
  'export class Greeter {constructor(public name:string){}greet():string{return "Hello, "+this.name;}}export class LoudGreeter extends Greeter {override greet():string{return super.greet().toUpperCase();}}',[
   ok('子类可以作为基类使用','import {Greeter,LoudGreeter} from "./main";const value:Greeter=new LoudGreeter("Lin");const text:string=value.greet();'),
   bad('构造参数仍然必需','import {LoudGreeter} from "./main";new LoudGreeter();'),
  ],'super.greet() 复用父类完整结果，再进行扩展。仅处理 name 会遗漏父类格式，也无法跟随父类实现变化。','父类负责问候格式。｜覆盖方法先取得父类结果。｜再执行大写转换。',{runtime:[run('复用父类并保持实例关系','const {Greeter,LoudGreeter}=load("main.js");const loud=new LoudGreeter("Lin");equal(loud.greet(),"HELLO, LIN");check(loud instanceof Greeter);equal(new Greeter("Lin").greet(),"Hello, Lin");Greeter.prototype.greet=function(){return "Welcome "+this.name;};equal(loud.greet(),"WELCOME LIN");')]}),
 m(1,7,'父类构造中调用可覆盖方法','为什么基类构造函数中调用子类可覆盖的方法可能有初始化风险？',['子类字段可能还没初始化，覆盖方法却已被调用','覆盖方法永远不会被调用','所有子类字段在父类构造前都已经初始化','TypeScript 会自动等待字段初始化'],'构造期间的动态分派可能进入依赖子类字段的逻辑。设计时应避免依赖尚未建立的状态，而不能仅凭方法类型正确就认为安全。','考虑父类构造与子类字段的先后。｜覆盖方法可能读取子类字段。｜声明存在不等于此时已初始化。'),
 t(1,8,'迁移：派生类完成初始化','导出 Point 和 LabeledPoint。Point(x:number,y:number) 提供实例 x、y 和 sum():number；LabeledPoint(x,y,label:string) 继承 Point 并保存 label，describe():string 返回 label+":"+sum()。',
  'export class Point {constructor(public x:number,public y:number){}sum():number{return this.x+this.y;}}export class LabeledPoint extends Point {constructor(x:number,y:number,public label:string){super(0,0);}describe():string{return this.label+":"+this.sum();}}',
  'export class Point {constructor(public x:number,public y:number){}sum():number{return this.x+this.y;}}export class LabeledPoint extends Point {constructor(x:number,y:number,public label:string){super(x,y);}describe():string{return this.label+":"+this.sum();}}',[
   ok('保留父类能力并新增标签','import {Point,LabeledPoint} from "./main";const p=new LabeledPoint(1,2,"A");const base:Point=p;const label:string=p.label;const text:string=p.describe();'),
   bad('标签参数不能遗漏','import {LabeledPoint} from "./main";new LabeledPoint(1,2);'),
  ],'子类必须把真实构造参数传给 super，不能仅满足参数类型却丢弃数据。继承的方法随后才能使用正确状态。','父类负责坐标初始化。｜把 x、y 原样传入 super。｜describe 使用继承的 sum。',{runtime:[run('父子字段及后续变化','const {Point,LabeledPoint}=load("main.js");const p=new LabeledPoint(2,3,"A");check(p instanceof Point);equal(p.describe(),"A:5");equal([p.x,p.y,p.label],[2,3,"A"]);p.x=7;equal(p.describe(),"A:10");equal(new LabeledPoint(-2,2,"").describe(),":0");')]}),
 m(1,9,'复测：实例方法不是自动绑定','把实例方法保存为普通变量后调用，是否会自动保留原实例的 this？',['通常不会，需要按业务使用绑定、包装回调或实例箭头函数','会，类方法始终自动绑定','会，只有对象字面量方法不绑定','方法会自动变成静态函数'],'方法调用时的接收者影响 this。类型注解不自动生成绑定操作，回调传递时应注意调用方式。','观察调用表达式是否仍有实例接收者。｜保存函数不等于绑定。｜需要实际绑定或闭包。'),
 t(1,10,'复测：静态工厂与实例结果','导出 Temperature，构造 celsius:number 并保存实例 celsius；实例 toFahrenheit():number 按 C*9/5+32 转换；静态 fromFahrenheit(value:number):Temperature 按 (F-32)*5/9 创建新实例。',
  'export class Temperature {constructor(public celsius:number){}toFahrenheit():number{return this.celsius*9/5+32;}static fromFahrenheit(value:number):Temperature{return new Temperature(value);}}',
  'export class Temperature {constructor(public celsius:number){}toFahrenheit():number{return this.celsius*9/5+32;}static fromFahrenheit(value:number):Temperature{return new Temperature((value-32)*5/9);}}',[
   ok('类工厂返回实例','import {Temperature} from "./main";const value:Temperature=Temperature.fromFahrenheit(32);const n:number=value.toFahrenheit();'),
   bad('静态工厂不属于实例','import {Temperature} from "./main";new Temperature(0).fromFahrenheit(32);',[2576]),
   bad('实例转换不属于类本身','import {Temperature} from "./main";Temperature.toFahrenheit();'),
  ],'静态工厂在类侧创建实例；实例方法读取该对象保存的摄氏温度。类型检查约束成员归属，运行测试检查转换公式与真实实例。','工厂先把华氏转摄氏。｜用 new 创建 Temperature。｜实例方法做反向转换。',{runtime:[run('静态构造与温标往返','const {Temperature}=load("main.js");const freezing=Temperature.fromFahrenheit(32);check(freezing instanceof Temperature);equal(freezing.celsius,0);equal(Temperature.fromFahrenheit(212).celsius,100);equal(new Temperature(-40).toFahrenheit(),-40);check(freezing!==Temperature.fromFahrenheit(32));')]}),
 m(2,1,'private 的检查层次','TypeScript 的 private secret:string 与 JavaScript 的 #secret 有什么关键差异？',['private 主要限制类型检查层面的访问，#secret 还具有 JavaScript 运行时私有语义','二者都会自动加密字段','private 比 #secret 更能阻止运行时访问','二者都只是命名约定'],'TS private 不等于 JavaScript 私有槽位。# 字段由运行时约束，不能通过普通字符串属性索引读取同一个私有值。','区分类型语法与运行机制。｜普通属性和私有槽位不同。｜它们都不是加密存储。'),
 m(2,2,'protected 的访问范围','一个 protected 实例成员通常允许在哪里使用？',['声明类及其派生类内部，在相关访问规则内使用','任意调用方只要知道名字','只有构造函数内','只能通过类构造函数静态访问'],'protected 为继承实现开放成员，同时限制外部直接访问。它仍属于 TypeScript 的访问控制，不自动提供运行时隐私。','考虑子类是否需要复用。｜外部访问与内部继承访问不同。｜不等同于 static。'),
 m(2,3,'readonly 不会深冻结','readonly items:string[] 的直接效果是什么？',['不能重新给 items 赋值，但数组本身仍可通过该引用 push','不能 push，也不能修改任何嵌套对象','自动调用 Object.freeze','只有数组长度不可修改'],'readonly 修饰属性绑定，不递归改变属性值。若还要禁止通过此视图修改数组，应使用 readonly string[]，运行冻结仍是另一回事。','问的是属性修饰符。｜数组类型本身仍可变。｜两个层次的只读需要分别声明。'),
 t(2,4,'修复只读身份与可编辑名称','导出 Profile，构造 id:string、name:string。id 是公开只读实例属性，name 可编辑；rename(name:string):void 更新名称，不改变 id。',
  'export class Profile {constructor(public id:string,public name:string){}rename(name:string):void{this.name=name;}}',
  'export class Profile {constructor(public readonly id:string,public name:string){}rename(name:string):void{this.name=name;}}',[
   ok('身份可读名称可写','import {Profile} from "./main";const p=new Profile("a","Lin");const id:string=p.id;p.name="Other";p.rename("Next");'),
   bad('身份不可重新赋值','import {Profile} from "./main";const p=new Profile("a","Lin");p.id="b";',[2540]),
  ],'readonly 表达身份在这个类型视图下不可改写；构造函数负责初始赋值。名称继续可编辑，不必把整个实例一律标成只读。','给 id 添加 readonly。｜保留 public 读取。｜rename 只更新 name。',{runtime:[run('重命名保留身份和实例独立性','const {Profile}=load("main.js");const a=new Profile("a","Lin");const b=new Profile("b","Other");a.rename("New");equal([a.id,a.name,b.id,b.name],["a","New","b","Other"]);')]}),
 m(2,5,'只读视图与可变别名','const source={count:1}; const view:Readonly<typeof source>=source; source.count=2; view.count 是什么？',['2，只读视图不会复制或冻结原对象','1，Readonly 自动创建副本','undefined','赋给 source.count 必然报错'],'readonly 限制通过特定视图写入，其他可写引用仍能改变同一对象。如果需要稳定快照，要实际复制相应层级的数据。','view 和 source 指向同一个对象。｜只读约束不自动复制。｜从任一引用读取都能观察更新。'),
 t(2,6,'设计只供子类使用的计数能力','导出 BaseCounter 与 StepCounter。BaseCounter 提供 protected count=0、公开 read():number；StepCounter extends BaseCounter，公开 step():number 把 count 加 2 并返回。外部不能直接访问 count。',
  'export class BaseCounter {count=0;read():number{return this.count;}}export class StepCounter extends BaseCounter {step():number{return this.count+=2;}}',
  'export class BaseCounter {protected count=0;read():number{return this.count;}}export class StepCounter extends BaseCounter {step():number{return this.count+=2;}}',[
   ok('子类可通过受保护成员扩展','import {BaseCounter,StepCounter} from "./main";class Triple extends BaseCounter{step(){return this.count+=3;}}const a:number=new Triple().step();const b:number=new StepCounter().read();'),
   bad('外部不能直接读取内部计数','import {StepCounter} from "./main";new StepCounter().count;',[2445]),
  ],'protected 保留子类实现所需的访问，而 public read 暴露受控读取接口。改成 private 会同时阻止本题要求的子类扩展。','子类需要访问所以不是 private。｜外部不应直接访问所以不是 public。｜使用 protected。',{runtime:[run('继承状态更新','const {BaseCounter,StepCounter}=load("main.js");const a=new StepCounter();const b=new StepCounter();check(a instanceof BaseCounter);equal(a.step(),2);equal(a.step(),4);equal(a.read(),4);equal(b.read(),0);')]}),
 m(2,7,'私有字段与普通同名属性','对象内部使用 #secret 时，给该对象增加普通的 secret 属性能否替换同一个私有槽位？',['不能，普通字符串属性和 #secret 是不同的存储位置','能，去掉 # 后名称相同就等价','能，只要属性值类型一致','不能，因为 JavaScript 禁止增加任何新属性'],'#secret 不是普通字符串键。添加 secret 或名为 #secret 的字符串键，不会改写类内部的私有槽位。','语法中的 # 有运行语义。｜字符串键是另一套属性访问。｜同样的文字不意味着同一存储。'),
 t(2,8,'迁移：运行时私有状态','导出 Vault，使用 #secret:string 存储构造参数。公开 reveal():string 返回真实私有值，replace(value:string):void 更新它。普通 secret 或字符串键 "#secret" 不应影响真实值。',
  'export class Vault {constructor(private secret:string){}reveal():string{return this.secret;}replace(value:string):void{this.secret=value;}}',
  'export class Vault {#secret:string;constructor(secret:string){this.#secret=secret;}reveal():string{return this.#secret;}replace(value:string):void{this.#secret=value;}}',[
   ok('公开方法操作私有值','import {Vault} from "./main";const v=new Vault("a");const value:string=v.reveal();v.replace("b");'),
   bad('没有公开 secret 属性','import {Vault} from "./main";new Vault("a").secret;',[2339,2341,2551]),
  ],'private 参数属性仍使用普通属性存储，不能满足本题运行时私有要求。# 字段通过语言私有槽位保存，并由类内部方法访问。','显式声明 #secret。｜构造函数写入 this.#secret。｜两个公开方法只操作这个槽位。',{runtime:[run('普通属性无法覆盖私有槽位','const {Vault}=load("main.js");const v=new Vault("original");check(!Object.keys(v).includes("secret"));v.secret="fake";v["#secret"]="also fake";equal(v.reveal(),"original");v.replace("updated");equal(v.reveal(),"updated");equal(v.secret,"fake");equal(new Vault("other").reveal(),"other");')]}),
 m(2,9,'复测：可维护的封装','把内部数组通过只读返回类型直接返回，是否能保证调用方拥有不随内部变化的快照？',['不能，只读类型不创建副本，内部修改仍可被调用方观察','能，只读返回值自动复制数组','能，返回后内部数组也被冻结','不能，所以 readonly 完全没有价值'],'只读视图限制调用方的静态写操作；稳定快照还要求实际复制。需要清楚说明接口返回的是实时视图还是独立快照。','先区分视图和快照。｜返回类型不改变对象引用。｜需要副本才能隔离数组结构变化。'),
 t(2,10,'复测：独立只读快照','导出 LogBook。内部保存字符串记录，add(text:string):void 追加；snapshot():readonly string[] 返回新的数组副本，之后 add 不影响此前快照，调用方不能按声明直接 push。',
  'export class LogBook {private entries:string[]=[];add(text:string):void{this.entries.push(text);}snapshot():readonly string[]{return this.entries;}}',
  'export class LogBook {private entries:string[]=[];add(text:string):void{this.entries.push(text);}snapshot():readonly string[]{return [...this.entries];}}',[
   ok('快照可读','import {LogBook} from "./main";const log=new LogBook();log.add("a");const values:readonly string[]=log.snapshot();values.map(value=>value.toUpperCase());'),
   bad('声明不允许调用方追加','import {LogBook} from "./main";new LogBook().snapshot().push("x");',[2339]),
   bad('内部数组不公开','import {LogBook} from "./main";new LogBook().entries;',[2341,2339]),
  ],'返回副本保证数组结构独立，readonly 限制正常 TS 调用方的写操作。这里元素是字符串，不涉及对象元素的深层复制，也不承诺冻结快照。','snapshot 创建新数组。｜返回类型继续只读。｜内部 entries 由 add 维护。',{runtime:[run('快照不随内部追加变化','const {LogBook}=load("main.js");const log=new LogBook();log.add("a");const old=log.snapshot();log.add("b");equal(old,["a"]);equal(log.snapshot(),["a","b"]);check(old!==log.snapshot());try{old.push("outside");}catch{}equal(log.snapshot(),["a","b"]);equal(new LogBook().snapshot(),[]);')]}),
 m(3,1,'implements 不会提供实现','class Store implements Reader 中，implements Reader 会自动生成 Reader 的方法体吗？',['不会，它检查实例是否满足契约，方法仍需实际实现','会，从接口复制方法体','会，所有方法默认返回 null','只要方法名相同就不再检查类型'],'接口描述结构，没有可供复制的运行方法体。implements 验证兼容关系，不是代码生成或继承实现。','接口是否包含运行代码？｜检查与提供实现不同。｜类仍需实现所需成员。'),
 m(3,2,'接口不自动标注类方法参数','interface Reader{read(key:string):string}，class Store implements Reader{read(key){return key}} 在严格模式下有什么问题？',['key 仍可能报隐式 any，implements 不为该方法提供参数上下文标注','没有问题，key 自动是 string','key 自动是 Reader','必须把接口改为抽象类才允许参数'],'implements 检查最终实例结构，不把接口参数注解自动填入类方法。需要给方法明确参数类型或提供其他真实上下文。','观察类方法自己的参数声明。｜implements 不是上下文赋值。｜给 key 标注 string。'),
 m(3,3,'抽象类可以包含什么','抽象类相较于只有接口声明，可以提供什么？',['共享状态、构造逻辑和已实现方法，同时要求子类补齐抽象成员','只能包含抽象方法，不能有方法体','允许直接 new 任何未完成实现','自动生成所有子类'],'抽象类可同时表达实现复用与待完成契约。它本身不能直接实例化；具体子类必须满足抽象成员要求。','抽象不等于所有成员都无实现。｜共享行为可以有方法体。｜具体实例由完整子类创建。'),
 t(3,4,'修复接口实现的运行行为','导出接口 Formatter，包含 format(value:number):string；导出 PrefixFormatter implements Formatter，构造 prefix:string，format 返回 prefix+String(value)。',
  'export interface Formatter{format(value:number):string}export class PrefixFormatter implements Formatter{constructor(public prefix:string){}format(value:number):string{return String(value);}}',
  'export interface Formatter{format(value:number):string}export class PrefixFormatter implements Formatter{constructor(public prefix:string){}format(value:number):string{return this.prefix+String(value);}}',[
   ok('实例可作为接口使用','import {PrefixFormatter} from "./main";import type {Formatter} from "./main";const f:Formatter=new PrefixFormatter("#");const text:string=f.format(2);'),
   bad('实例方法参数有类型','import {PrefixFormatter} from "./main";new PrefixFormatter("#").format("2");'),
  ],'接口验证输入输出结构，但不能证明前缀拼接行为。具体实现必须使用构造状态，运行测试负责验证这一部分。','接口规定方法签名。｜类保存 prefix。｜返回 prefix 加上数值文本。',{runtime:[run('接口满足但业务也正确','const {PrefixFormatter}=load("main.js");equal(new PrefixFormatter("#").format(2),"#2");equal(new PrefixFormatter("").format(-1),"-1");equal(new PrefixFormatter("USD ").format(0),"USD 0");')]}),
 m(3,5,'implements 检查哪一侧','为什么不能只用 class C implements Factory 来证明 C 的静态构造签名满足 new(name:string)=>Instance？',['implements 主要检查实例侧，构造函数侧应把类值赋给构造签名等方式检查','因为类不能有构造参数','因为接口不能描述构造签名','因为 typeof 永远只能用于原始值'],'类的实例结构和构造函数值是不同侧面。工厂参数的 new 签名应接收类值并检查其构造能力。','区分类值和实例。｜implements 面向实例结构。｜new 签名描述类值的能力。'),
 t(3,6,'设计抽象模板流程','导出 abstract class TextJob：抽象 transform(text:string):string，具体 run(text:string):string 返回 "["+this.transform(text)+"]"。导出 TrimJob extends TextJob，transform 去除两端空白，复用父类 run。',
  'export abstract class TextJob{abstract transform(text:string):string;run(text:string):string{return "["+text+"]";}}export class TrimJob extends TextJob{transform(text:string):string{return text.trim();}}',
  'export abstract class TextJob{abstract transform(text:string):string;run(text:string):string{return "["+this.transform(text)+"]";}}export class TrimJob extends TextJob{transform(text:string):string{return text.trim();}}',[
   ok('子类补齐扩展点','import {TextJob,TrimJob} from "./main";const job:TextJob=new TrimJob();const text:string=job.run(" a ");class UpperJob extends TextJob{transform(text:string){return text.toUpperCase();}}new UpperJob().run("a");'),
   bad('抽象类不可直接实例化','import {TextJob} from "./main";new TextJob();',[2511]),
   bad('具体子类不能遗漏抽象方法','import {TextJob} from "./main";class EmptyJob extends TextJob{}',[2515]),
  ],'父类负责共享流程，通过 this.transform 调用子类提供的扩展点。仅声明抽象方法而不在流程中使用，仍可能编译但失去设计目的。','run 调用抽象扩展点。｜子类实现 transform。｜括号格式由父类统一负责。',{runtime:[run('共享流程使用子类实现','const {TextJob,TrimJob}=load("main.js");const job=new TrimJob();check(job instanceof TextJob);equal(job.run(" a "),"[a]");equal(job.run("  "),"[]");class UpperJob extends TextJob{transform(text){return text.toUpperCase();}}equal(new UpperJob().run("hello"),"[HELLO]");')]}),
 m(3,7,'接口的可选成员不会自动出现','interface Option{debug?:boolean}，class Plain implements Option{} 会自动拥有可访问的 debug 属性吗？',['不会，implements 不向类自身类型添加未声明成员','会，debug 默认 false','会，debug 默认 undefined 且必然存在','不会，因为接口不允许可选属性'],'类符合可选成员契约，不代表该成员被添加进类类型或运行对象。要通过类实例读取该成员，需要在类中声明实现，或使用相应接口视图。','可选成员可以完全不提供。｜检查通过不会生成成员。｜类自身结构仍由声明决定。'),
 t(3,8,'迁移：检查并使用构造函数契约','导出接口 Named{name:string}；实现 createNamed<T extends Named>(Ctor:new(name:string)=>T,name:string):T，使用 Ctor 创建并返回实例，保留具体子类能力。',
  'export interface Named{name:string}export function createNamed<T extends Named>(Ctor:new(name:string)=>T,name:string):T{return new Ctor("");}',
  'export interface Named{name:string}export function createNamed<T extends Named>(Ctor:new(name:string)=>T,name:string):T{return new Ctor(name);}',[
   ok('构造后保留具体类型','import {createNamed} from "./main";class User{constructor(public name:string){}greet(){return this.name;}}const u=createNamed(User,"Lin");const text:string=u.greet();'),
   bad('构造参数类型必须兼容','import {createNamed} from "./main";class Wrong{constructor(public name:number){}}createNamed(Wrong,"Lin");'),
   bad('实例必须具有 name','import {createNamed} from "./main";class Wrong{constructor(name:string){}}createNamed(Wrong,"Lin");'),
  ],'构造签名检查传入类值的能力，泛型 T 保留其具体实例类型。正确签名之外还要传递真实参数，而不是替换成占位内容。','参数 Ctor 是可 new 的值。｜构造时传入 name。｜返回类型保留 T。',{runtime:[run('真实构造与参数传递','const {createNamed}=load("main.js");let calls=0;class User{constructor(name){calls++;this.name=name;}greet(){return "Hi "+this.name;}}const u=createNamed(User,"Lin");check(u instanceof User);equal(u.greet(),"Hi Lin");equal(calls,1);check(createNamed(User,"Other")!==u);')]}),
 m(3,9,'复测：结构契约不要求显式 implements','函数接收 {read():string}，一个未写 implements 但具有兼容 read 方法的对象通常能传入吗？',['能，结构兼容主要检查成员是否满足要求','不能，必须声明同名接口','只能传类实例，普通对象不行','能，但方法不会实际执行'],'公开结构的兼容通常不要求显式继承关系。implements 有利于在类声明处检查契约，但不是所有结构赋值的前提。','目标描述需要的能力。｜检查对象是否具备该能力。｜显式 implements 不是唯一证据。'),
 t(3,10,'复测：通过接口协作','导出接口 TextSource{read():string} 与 TextSink{write(text:string):void}；实现 transfer(source:TextSource,sink:TextSink):void，读取一次并把同一文本写入一次。不要求参数继承某个基类。',
  'export interface TextSource{read():string}export interface TextSink{write(text:string):void}export function transfer(source:TextSource,sink:TextSink):void{source.read();sink.write(source.read());}',
  'export interface TextSource{read():string}export interface TextSink{write(text:string):void}export function transfer(source:TextSource,sink:TextSink):void{const text=source.read();sink.write(text);}',[
   ok('普通对象也可协作','import {transfer} from "./main";transfer({read:()=>"a"},{write:text=>{const s:string=text;}});'),
   bad('源返回类型必须为文本','import {transfer} from "./main";transfer({read:()=>1},{write:text=>{}});'),
   bad('目标必须实现 write','import {transfer} from "./main";transfer({read:()=>"a"},{});'),
  ],'接口让不同对象按能力协作，不要求共享继承体系。读取次数等行为约束仍需由实现和运行测试保证。','只执行一次 read。｜保存实际返回值。｜再写入一次。',{runtime:[run('一次读取一次写入且顺序正确','const {transfer}=load("main.js");const events=[];let reads=0;transfer({read(){events.push("read");return "value"+(++reads);}},{write(text){events.push(text);}});equal(events,["read","value1"]);equal(reads,1);const sentinel={failed:true};let written=false;let caught;try{transfer({read(){throw sentinel;}},{write(){written=true;}});}catch(error){caught=error;}check(caught===sentinel);check(!written);')]}),
 m(4,1,'联合类型有没有运行对象','type Status="idle"|"running" 会自动生成可供 Object.values(Status) 使用的运行对象吗？',['不会，类型别名被擦除，需要另外提供运行值','会，自动生成数组','会，自动生成数字枚举','只在严格模式下生成'],'字面量联合描述静态候选值，不提供枚举对象。需要在运行时遍历时，可另外定义常量对象或元组。','type 是类型声明。｜Object.values 需要运行值。｜两者不是同一层。'),
 m(4,2,'数字枚举的反向映射','普通 enum Code{Ready=1,Done=2} 的运行对象中，Code[1] 通常是什么？',['"Ready"','1','"Done"','undefined，因为所有枚举都没有反向映射'],'普通数字枚举生成名称到数值及数值到名称的映射。遍历整个枚举对象时需要留意这两类值。','这里是普通数字枚举。｜存在数值到成员名的映射。｜1 对应 Ready。'),
 m(4,3,'字符串枚举不同','普通 enum State{Idle="idle",Busy="busy"} 是否自动生成 "idle" 到 "Idle" 的反向映射？',['不会，字符串枚举不自动生成这种反向映射','会，所有枚举都生成双向映射','只有 Idle 会生成','会，但需要先调用一次枚举'],'字符串枚举的输出规则与数字枚举不同。不能把数字枚举的反向映射结论套用到所有枚举。','成员值是字符串。｜不要套用数字枚举规则。｜需要反查时自行建立逻辑。'),
 t(4,4,'修复外部字符串到枚举的解析','导出普通字符串枚举 Mode{Read="read",Write="write"}。实现 parseMode(value:unknown):Mode|null，仅接受这两个原始字符串并返回对应成员，否则 null。不使用断言。',
  'export enum Mode{Read="read",Write="write"}export function parseMode(value:unknown):Mode|null{return value===Mode.Write?Mode.Write:Mode.Read;}',
  'export enum Mode{Read="read",Write="write"}export function parseMode(value:unknown):Mode|null{if(value===Mode.Read)return Mode.Read;if(value===Mode.Write)return Mode.Write;return null;}',[
   ok('返回枚举或失败','import {Mode,parseMode} from "./main";const mode:Mode|null=parseMode("read");const member:Mode=Mode.Write;'),
   bad('普通文本不直接等于枚举类型','import {Mode} from "./main";const mode:Mode="read";'),
  ],'枚举为内部值提供命名，外部输入仍需验证。不能把所有未知输入悄悄降级为某个合法成员，除非业务明确规定默认值。','分别匹配两个合法值。｜匹配后返回对应枚举成员。｜其他值返回 null。',{runtime:[run('只接纳协议中的两个值','const {Mode,parseMode}=load("main.js");equal([Mode.Read,Mode.Write],["read","write"]);equal(parseMode("read"),Mode.Read);equal(parseMode("write"),Mode.Write);for(const value of ["Read","WRITE","",null,1,{},undefined])equal(parseMode(value),null);')]}),
 m(4,5,'枚举名称与值','enum Mode{Read="read",Write="write"}，keyof typeof Mode 表达什么？',['成员名联合 "Read"|"Write"','成员值联合 "read"|"write"','任意 string','数字 0|1'],'typeof Mode 获取枚举运行对象类型，keyof 提取其成员名。名字与实际协议值可能不同，应根据需求选择。','先观察对象属性名。｜Read 是名字，read 是值。｜keyof 取键。'),
 t(4,6,'设计可遍历的常量状态表','导出 const Status={Idle:"idle",Running:"running",Done:"done"}，使用 as const；导出 StatusValue 为其值联合，并实现 isStatus(value:unknown):value is StatusValue，只识别三个值。',
  'export const Status={Idle:"idle",Running:"running",Done:"done"};export type StatusValue=typeof Status[keyof typeof Status];export function isStatus(value:unknown):value is StatusValue{return typeof value==="string";}',
  'export const Status={Idle:"idle",Running:"running",Done:"done"} as const;export type StatusValue=typeof Status[keyof typeof Status];export function isStatus(value:unknown):value is StatusValue{return value===Status.Idle||value===Status.Running||value===Status.Done;}',[
   ok('常量与值联合保持关联','import {Status,isStatus} from "./main";import type {StatusValue} from "./main";const a:StatusValue="idle";const precise:"running"=Status.Running;let raw:unknown="done";if(isStatus(raw)){const value:StatusValue=raw;}'),
   bad('联合不应扩大到所有文本','import type {StatusValue} from "./main";const a:StatusValue="other";'),
   bad('键名不是协议值','import type {StatusValue} from "./main";const a:StatusValue="Idle";',[2322,2820]),
  ],'as const 保留对象属性的字面量值，再通过索引访问取得候选联合。类型谓词仍需真实检查，不能只确认它是任意字符串。','先保留值的字面量类型。｜值联合来自 typeof Status 的索引访问。｜运行检查逐个匹配允许值。',{runtime:[run('运行表与守卫一致','const {Status,isStatus}=load("main.js");equal(Object.values(Status),["idle","running","done"]);for(const value of Object.values(Status))equal(isStatus(value),true);for(const value of ["other","Idle",1,null,undefined,{}])equal(isStatus(value),false);')]}),
 m(4,7,'const enum 的工具链边界','为什么共享库使用 const enum 前，需要确认编译与发布方式？',['成员可能被内联，输出和使用方式受编译选项及工具链影响，不能假定始终存在普通运行对象','const enum 永远生成可遍历对象','const enum 能自动同步不同版本的数值','因为 const enum 只能保存字符串'],'const enum 的内联和保留行为涉及编译配置与消费方工具链。需要运行对象时，普通枚举或常量对象通常更容易明确契约。','先确认运行对象是否会保留。｜发布方和使用方可能分别编译。｜不要把编译期成员当作必然存在的对象。'),
 t(4,8,'迁移：数字枚举只列数值','导出普通数字枚举 Level{Low=1,Medium=3,High=5}。实现 levels():Level[]，按 Low、Medium、High 顺序返回三项数值，不包含反向映射中的成员名，每次返回新数组。',
  'export enum Level{Low=1,Medium=3,High=5}export function levels():Level[]{return [Level.Low,Level.Medium];}',
  'export enum Level{Low=1,Medium=3,High=5}export function levels():Level[]{return [Level.Low,Level.Medium,Level.High];}',[
   ok('返回明确枚举成员','import {Level,levels} from "./main";const values:Level[]=levels();const low:Level=Level.Low;'),
   bad('成员名不是数值枚举成员','import {Level} from "./main";const value:Level="Low";'),
  ],'数字枚举运行对象包含反向映射，因此不能无条件把 Object.values 的所有值都当成员数值。明确列出业务顺序能避免混入名称和依赖对象枚举顺序。','本题要求固定业务顺序。｜列出三个枚举成员。｜每次创建新的数组。',{runtime:[run('数值枚举映射与成员列表','const {Level,levels}=load("main.js");equal(Level[1],"Low");equal(Level[3],"Medium");equal(Level[5],"High");equal(levels(),[1,3,5]);const first=levels();check(first!==levels());first.pop();equal(levels(),[1,3,5]);')]}),
 m(4,9,'复测：如何选择表示方式','仅需约束内部状态文本且不需运行对象时，哪种方案通常最直接？',['字面量联合；若以后需要遍历，再提供关联的运行常量','必须使用数字枚举','必须使用类继承','用 any 可以同时得到完整约束'],'根据运行需求选择表示方式。字面量联合提供静态候选约束，运行遍历需要另有值；枚举并不是所有状态表示的必选项。','明确是否需要运行时对象。｜仅静态候选时联合已能表达。｜按实际需求增加运行值。'),
 t(4,10,'复测：完整的状态标签表','导出 type State="idle"|"loading"|"done"；导出 labels:Record<State,string>，值分别为 "待机"、"加载中"、"完成"。实现 labelOf(state:State):string 返回对应标签，禁止其他状态。',
  'export type State="idle"|"loading"|"done";export const labels:Record<State,string>={idle:"待机",loading:"加载中",done:"完成"};export function labelOf(state:State):string{return labels.idle;}',
  'export type State="idle"|"loading"|"done";export const labels:Record<State,string>={idle:"待机",loading:"加载中",done:"完成"};export function labelOf(state:State):string{return labels[state];}',[
   ok('全部状态都有标签','import {labels,labelOf} from "./main";import type {State} from "./main";const all:Record<State,string>=labels;const text:string=labelOf("loading");'),
   bad('未知状态不能调用','import {labelOf} from "./main";labelOf("failed");'),
   bad('类型表不能遗漏状态','import type {State} from "./main";const incomplete:Record<State,string>={idle:"a",loading:"b"};'),
  ],'Record 把有限状态集合与完整标签表关联起来。类型保证每个状态有字段，但具体查询仍需使用实际 state，不能始终返回固定标签。','用 State 作为 Record 的键集合。｜按 state 索引。｜测试会逐一查询不同状态。',{runtime:[run('每个状态返回对应文本','const {labels,labelOf}=load("main.js");equal(labels,{idle:"待机",loading:"加载中",done:"完成"});equal(labelOf("idle"),"待机");equal(labelOf("loading"),"加载中");equal(labelOf("done"),"完成");')]}),
 m(5,1,'接口同名声明','同一模块内两次声明 interface Config，分别包含 host:string 和 port:number，结果通常是什么？',['合并为同时需要 host 与 port 的接口','后一个完全覆盖前一个','只能保留第一个','自动变成 host 或 port 的联合'],'兼容的同名接口声明会合并成员。它不是运行时对象覆盖，也不是任选一种形状的联合。','两个声明描述同一个接口。｜不同成员会汇集。｜必需成员仍然必需。'),
 m(5,2,'同名属性冲突','同名接口分别声明 value:string 和 value:number，会自动合成 value:string|number 吗？',['不会，重复非函数成员的类型需要一致，否则报冲突','会，总是自动联合','会，自动选择更宽类型','不会，只静默保留最后一个'],'声明合并要求重复属性兼容于规定的同一类型要求，不是将冲突自动修复成联合。需要统一契约或使用不同结构。','属性重复不是两种候选。｜编译器不会擅自改变契约。｜应解决声明冲突。'),
 m(5,3,'类型别名不能随意重开','type Config={host:string} 之后再声明同名 type Config={port:number}，是否像接口一样合并？',['不会，类型别名重复声明会报错','会，与 interface 完全相同','会，但只合并可选属性','会，在运行时才合并'],'类型别名与接口声明的扩展机制不同。需要组合别名时应显式使用交叉等结构，不能依赖同名重开。','区分 type 与 interface。｜别名需要唯一标识。｜组合应显式表达。'),
 t(5,4,'修复合并后的完整配置','保留两个导出 Config 接口声明，分别为 {host:string} 与 {port:number}。实现 makeConfig(host:string,port:number):Config，返回同时含两个字段的对象。',
  'export interface Config{host:string}export interface Config{port:number}export function makeConfig(host:string,port:number):Config{return {host};}',
  'export interface Config{host:string}export interface Config{port:number}export function makeConfig(host:string,port:number):Config{return {host,port};}',[
   ok('合并成员都可用','import {makeConfig} from "./main";import type {Config} from "./main";const c:Config=makeConfig("localhost",8080);const host:string=c.host;const port:number=c.port;'),
   bad('不能遗漏后合并的字段','import type {Config} from "./main";const c:Config={host:"localhost"};'),
   bad('不能遗漏原字段','import type {Config} from "./main";const c:Config={port:80};'),
  ],'两个接口声明合并为一个包含全部成员的契约。实现函数必须满足合并后的整体结构，而不是只看其中一个声明。','合并后有两个必需字段。｜构造结果同时提供它们。｜保留各自字段类型。',{runtime:[run('合并声明对应真实字段','const {makeConfig}=load("main.js");equal(makeConfig("localhost",8080),{host:"localhost",port:8080});equal(makeConfig("",0),{host:"",port:0});')]}),
 m(5,5,'声明不等于补丁实现','通过模块扩展给类增加 label():string 的类型声明后，运行时是否自动出现 label 方法？',['不会，还需实际安装对应方法，并确保该实现被加载','会，编译器根据返回类型生成方法','会，默认返回空字符串','只有浏览器会自动生成'],'模块扩展补充检查器对已有模块的认识，不会凭空产生方法体。缺少实现或加载顺序错误，仍会导致运行失败。','声明描述接口。｜方法体需要实际代码。｜扩展文件也必须执行。'),
 t(5,6,'设计合并的调用重载','通过两个同名导出接口 Convert 声明合并调用签名：(value:string):number 与 (value:number):string。这里只设计类型，不实现运行函数；不同输入必须得到对应返回类型。',
  'export interface Convert{(value:string|number):string|number}',
  'export interface Convert{(value:string):number}export interface Convert{(value:number):string}',[
   ok('重载保留输入输出对应','import type {Convert} from "./main";declare const convert:Convert;const n:number=convert("12");const s:string=convert(12);'),
   bad('拒绝其他输入','import type {Convert} from "./main";declare const convert:Convert;convert(true);',[2769,2345]),
   bad('文本输入不返回文本','import type {Convert} from "./main";declare const convert:Convert;const result:string=convert("12");'),
  ],'函数成员或调用签名可以形成重载集合，保留具体输入与返回的对应关系。单一联合签名会把结果扩大成联合，表达能力不同。','每个声明提供一个调用签名。｜两个接口使用同一个名字。｜不要改成单一联合返回。'),
 m(5,7,'模块标识必须对应','declare module "./box" 的扩展为什么要与实际导入指向同一个模块？',['扩展绑定到被解析的模块，指向不同模块不能补充预期类型','模块名只用于显示，可以随意写','扩展自动作用于所有同名类','声明会自动重命名磁盘文件'],'模块扩展依赖模块身份与解析。仅类名相同不足以让另一个模块自动获得该扩展。','目标是模块中的声明。｜路径需要指向同一个模块。｜不是全局按类名匹配。'),
 t(5,8,'迁移：补齐模块扩展的运行实现','只读 box.ts 导出 Box，其构造参数为 value:string。main.ts 扩展 ./box 中的 Box 接口，增加 label():string，并在 Box.prototype 安装方法，返回 "["+当前 this.value+"]"。main.ts 重新导出 Box。',
  'import {Box} from "./box";declare module "./box"{interface Box{label():string}}export {Box};',
  'import {Box} from "./box";declare module "./box"{interface Box{label():string}}Box.prototype.label=function():string{return "["+this.value+"]";};export {Box};',[
   ok('扩展原模块类型','import "./main";import {Box} from "./box";const box=new Box("a");const text:string=box.label();'),
   bad('方法参数仍受约束','import {Box} from "./main";new Box("a").label(1);',[2554]),
  ],'declare module 扩展类型，prototype 赋值提供真实行为，两者缺一不可。方法使用动态 this 读取当前实例，而不是捕获某个固定对象。','先声明扩展接口。｜再把函数赋给 Box.prototype.label。｜用普通函数读取 this.value。',{rules:{allowAmbient:true},supportFiles:{'box.ts':'export class Box{constructor(public value:string){}}'},runtime:[run('原类原型得到真实行为','const Original=load("box.js").Box;const before=new Original("before");const {Box}=load("main.js");check(Box===Original);equal(before.label(),"[before]");const box=new Box("a");equal(box.label(),"[a]");box.value="b";equal(box.label(),"[b]");equal(new Box("other").label(),"[other]");')]}),
 m(5,9,'复测：函数与命名空间合并','函数后面声明同名 namespace 并导出一个常量，通常可以表达什么？',['可调用函数附带命名的静态属性','函数自动变成不能调用的对象','只添加类型，不可能提供运行值','所有局部变量自动成为公开属性'],'函数与后续命名空间可以合并，导出的值成员成为运行时可访问属性。这里需要实际导出值，不能把纯类型成员当运行属性。','函数仍有调用能力。｜namespace 的导出值可以附着其上。｜注意声明顺序与 export。'),
 t(5,10,'复测：可调用函数附带版本','导出函数 format(value:number):string，返回 "#"+value；在其后用同名 namespace format 导出 const version="1.0"。调用与读取 format.version 都应可用。',
  'export function format(value:number):string{return "#"+value;}export namespace format{export const version=1;}',
  'export function format(value:number):string{return "#"+value;}export namespace format{export const version="1.0";}',[
   ok('调用与静态属性并存','import {format} from "./main";const text:string=format(2);const version:"1.0"=format.version;'),
   bad('函数参数不因合并而放宽','import {format} from "./main";format("2");'),
  ],'函数提供调用行为，后续同名命名空间提供附加导出值。类型和运行测试同时检查函数仍可调用、版本属性真实存在且值正确。','先声明函数。｜后声明同名 namespace。｜版本是字符串字面量常量。',{rules:{allowAmbient:true},runtime:[run('函数与附加属性同时存在','const {format}=load("main.js");equal(format(2),"#2");equal(format(-1),"#-1");equal(format.version,"1.0");')]}),
 m(6,1,'先确认装饰器模式','阅读装饰器代码时，为什么要先确认 experimentalDecorators 配置？',['旧版实验装饰器与标准装饰器的调用协议和能力不同，不能直接混用','它只决定是否显示编辑器颜色','开启后所有装饰器自动更安全','两种模式永远完全相同'],'装饰器需要结合固定编译版本和模式理解。本节默认使用标准装饰器，旧版对照题会显式开启 experimentalDecorators。','配置影响语义而不只是提示。｜先识别当前模式。｜再查看对应的参数与返回协议。'),
 m(6,2,'标准方法装饰器收到什么','标准实例方法装饰器通常接收哪些主要参数？',['原方法值与描述该成员的 context 对象','目标实例、属性名、属性描述符三个参数','只有属性名字符串','只有已经调用得到的返回值'],'标准方法装饰器可以检查 context，并返回替代方法。旧版三参数方法装饰器是另一种协议。','区分标准模式和旧实验模式。｜此时不是普通方法调用。｜收到方法值与上下文。'),
 m(6,3,'装饰器包装保留什么','返回替代方法时，为什么需要关注 this、参数、返回值和异常？',['包装应保持原调用契约，不能意外丢失接收者、重复调用或吞掉结果','装饰器会自动修复所有包装错误','替代方法不能返回值','this 总是指向装饰器函数本身'],'类型签名和运行行为都必须保持。普通函数配合 call/apply 可把当前接收者传给原方法；箭头捕获的 this 可能不是调用实例。','包装函数何时执行？｜接收者来自方法调用。｜显式转发并返回结果。'),
 t(6,4,'修复保留接收者的方法包装','标准装饰器模式。导出 upper 装饰器，适用于一个 string 参数、string 返回的方法；调用原方法恰好一次，保留 this，返回结果的大写。导出 Greeter(prefix:string)，其 @upper greet(name:string) 原实现为 prefix+name。',
  'export function upper<This>(value:(this:This,name:string)=>string,context:ClassMethodDecoratorContext<This,(this:This,name:string)=>string>){return function(this:This,name:string):string{return name.toUpperCase();};}export class Greeter{constructor(public prefix:string){}@upper greet(name:string):string{return this.prefix+name;}}',
  'export function upper<This>(value:(this:This,name:string)=>string,context:ClassMethodDecoratorContext<This,(this:This,name:string)=>string>){return function(this:This,name:string):string{return value.call(this,name).toUpperCase();};}export class Greeter{constructor(public prefix:string){}@upper greet(name:string):string{return this.prefix+name;}}',[
   ok('保留方法参数和结果','import {Greeter,upper} from "./main";const text:string=new Greeter("Hi ").greet("Lin");class Other{@upper run(value:string):string{return value;}}'),
   bad('参数仍要求文本','import {Greeter} from "./main";new Greeter("Hi ").greet(1);'),
  ],'装饰器替换方法后仍须转发接收者和参数。直接处理输入会遗漏原方法行为，多个实例也应读取各自状态。','使用普通包装函数取得调用时 this。｜value.call(this,name) 执行原方法。｜对返回文本转大写。',{compilerOptions:{experimentalDecorators:false},runtime:[run('装饰后读取各自实例状态','const {Greeter,upper}=load("main.js");equal(new Greeter("Hi ").greet("Lin"),"HI LIN");equal(new Greeter("Bye ").greet("Tom"),"BYE TOM");let calls=0;const wrapped=upper(function(name){calls++;return this.prefix+name;},{});equal(wrapped.call({prefix:"x"},"y"),"XY");equal(calls,1);const sentinel={bad:true};let caught;try{upper(function(){throw sentinel;},{}).call({},"a");}catch(error){caught=error;}check(caught===sentinel);')]}),
 m(6,5,'装饰器执行时间','标准方法装饰器的函数体与它返回的包装方法，通常分别在何时执行？',['装饰应用阶段执行装饰器，实际方法调用时执行包装方法','二者只在每次 new 时同时执行','二者都只在编译期间执行，不产生运行行为','包装方法在声明前已执行完'],'装饰器参与类定义相关的运行过程；返回的函数是后续调用的方法。不要把装饰应用次数误认为业务方法调用次数。','区分定义类和调用方法。｜返回函数尚未执行其方法体。｜实例调用才进入包装逻辑。'),
 t(6,6,'设计通用调用通知装饰器','标准模式。导出 before(notify:()=>void)，返回泛型方法装饰器，支持任意 This、Args extends unknown[]、Result。每次调用先 notify 一次，再按原 this 和参数调用原方法一次，原样返回结果，不强制 async。',
  'export function before(notify:()=>void){return function<This,Args extends unknown[],Result>(value:(this:This,...args:Args)=>Result,context:ClassMethodDecoratorContext<This,(this:This,...args:Args)=>Result>){return function(this:This,...args:Args):Result{notify();notify();return value.apply(this,args);};};}',
  'export function before(notify:()=>void){return function<This,Args extends unknown[],Result>(value:(this:This,...args:Args)=>Result,context:ClassMethodDecoratorContext<This,(this:This,...args:Args)=>Result>){return function(this:This,...args:Args):Result{notify();return value.apply(this,args);};};}',[
   ok('保留不同方法签名','import {before} from "./main";class Service{@before(()=>{})sum(a:number,b:number):number{return a+b;}@before(()=>{})async name():Promise<string>{return "a";}}const n:number=new Service().sum(1,2);const p:Promise<string>=new Service().name();'),
   bad('包装后参数不放宽','import {before} from "./main";class Service{@before(()=>{})sum(a:number):number{return a;}}new Service().sum("1");'),
  ],'泛型保留原方法的 this、参数元组和结果。不要随意声明 async，否则同步返回会变为 Promise，异步返回的引用也可能改变。','用 Args 元组转发完整参数。｜notify 只执行一次。｜直接返回 value.apply 的结果。',{compilerOptions:{experimentalDecorators:false},runtime:[run('通知顺序和返回引用','const {before}=load("main.js");const events=[];const result={ok:true};const wrapped=before(()=>events.push("before"))(function(a,b){events.push([this.id,a,b]);return result;},{});check(wrapped.call({id:"x"},1,2)===result);equal(events,["before",["x",1,2]]);const promise=Promise.resolve(3);const asyncWrapped=before(()=>{})(()=>promise,{});check(asyncWrapped()===promise);equal(await asyncWrapped(),3);')]}),
 m(6,7,'字段装饰器的返回值','标准字段装饰器返回初始化函数时，该函数的用途是什么？',['接收字段初始值并返回该实例应保存的初始化值','替代整个类的构造函数','自动生成所有字段的 getter','只用于修改接口声明'],'字段初始化函数影响实例初始化时的字段值。它与方法装饰器返回替代方法是不同的协议，不能混为一谈。','装饰目标是字段。｜返回函数处理初始值。｜最终值保存到该实例字段。'),
 t(6,8,'迁移：字段初始化清理','标准模式。导出 trimField<This>(value:undefined,context:ClassFieldDecoratorContext<This,string>)，返回字段初始化函数，把初始字符串 trim 后保存。导出 Form，@trimField name="  Lin  "。',
  'export function trimField<This>(value:undefined,context:ClassFieldDecoratorContext<This,string>){return function(this:This,initial:string):string{return initial;};}export class Form{@trimField name="  Lin  ";}',
  'export function trimField<This>(value:undefined,context:ClassFieldDecoratorContext<This,string>){return function(this:This,initial:string):string{return initial.trim();};}export class Form{@trimField name="  Lin  ";}',[
   ok('字符串字段保持字符串类型','import {Form,trimField} from "./main";const value:string=new Form().name;class Other{@trimField title=" x ";}const title:string=new Other().title;'),
   bad('不适用于数字字段','import {trimField} from "./main";class Wrong{@trimField count=1;}',[1240,1270]),
  ],'字段装饰器接收 undefined 作为字段值位置参数，通过返回初始化函数处理每个实例的初始值。它不会持续拦截之后的普通赋值。','返回初始化函数。｜函数接收 initial:string。｜返回 initial.trim()。',{compilerOptions:{experimentalDecorators:false},runtime:[run('初始化处理与后续赋值','const {Form,trimField}=load("main.js");const a=new Form();const b=new Form();equal(a.name,"Lin");equal(b.name,"Lin");a.name=" later ";equal(a.name," later ");equal(b.name,"Lin");const init=trimField(undefined,{});equal(init.call({},"  "),"");equal(init.call({}," x "),"x");')]}),
 m(6,9,'复测：参数装饰器模式','标准装饰器模式下，能否直接使用旧版 experimentalDecorators 的参数装饰器写法？',['不能直接照搬，标准装饰器不提供旧版参数装饰器协议','能，两种模式只是名称不同','能，但必须把参数改为 any','能，编译器会自动转换旧版协议'],'旧实验模式和标准模式并非完全兼容。迁移时需要检查使用的装饰目标、签名和工具链，而不是只切换一个选项。','本题明确标准模式。｜旧版支持的目标不一定有对应协议。｜不能机械搬运。'),
 t(6,10,'复测：旧版方法描述符对照','本题显式开启 experimentalDecorators，使用旧版方法装饰器。导出 locked(target:object,key:string|symbol,descriptor:PropertyDescriptor):void，将 writable 设为 false。导出 Tool，其 @locked run():string 返回 "ok"。不要混入标准 context 签名。',
  'export function locked(target:object,key:string|symbol,descriptor:PropertyDescriptor):void{descriptor.writable=true;}export class Tool{@locked run():string{return "ok";}}',
  'export function locked(target:object,key:string|symbol,descriptor:PropertyDescriptor):void{descriptor.writable=false;}export class Tool{@locked run():string{return "ok";}}',[
   ok('旧模式方法仍可调用','import {Tool,locked} from "./main";const value:string=new Tool().run();const decorator:(target:object,key:string|symbol,descriptor:PropertyDescriptor)=>void=locked;'),
   bad('方法仍无参数','import {Tool} from "./main";new Tool().run(1);',[2554]),
  ],'旧版方法装饰器接收目标、成员键和属性描述符，可以修改描述符。此题专门对照旧协议，不能把它当成标准装饰器的调用形式。','本题配置与前面不同。｜第三个参数是描述符。｜设置 writable=false。',{compilerOptions:{experimentalDecorators:true},runtime:[run('旧版描述符确实修改','const {Tool}=load("main.js");equal(new Tool().run(),"ok");const descriptor=Object.getOwnPropertyDescriptor(Tool.prototype,"run");equal(descriptor.writable,false);equal(typeof descriptor.value,"function");')]}),
 m(7,1,'namespace 与模块的区别','namespace 与 ES 模块最重要的组织差异是什么？',['namespace 通过命名空间声明组织名字，ES 模块通过文件的 import/export 建立边界和依赖','namespace 会自动从网络加载同名文件','ES 模块不能导出类型','二者只是同一个语法的不同拼写'],'二者都能组织代码，但作用域、加载和输出机制不同。迁移前应确认文件如何被编译和加载，不能只删除外层声明。','关注文件之间如何建立依赖。｜namespace 不自动加载文件。｜模块依赖由 import/export 表达。'),
 m(7,2,'命名空间内部的 export','namespace Tools{function helper(){} export function run(){helper();}} 中，外部能否直接调用 Tools.helper？',['不能，helper 未导出，只供该声明内部使用','能，所有命名空间成员自动公开','能，只要 run 调用过一次','不能，因为命名空间不能包含函数'],'命名空间内的 export 决定哪些成员能通过命名空间访问。内部辅助函数可被导出函数使用，但不会因此自动公开。','观察 helper 有没有 export。｜被调用不等于被导出。｜run 的可见性与 helper 不同。'),
 m(7,3,'两个模块里的同名空间','a.ts 与 b.ts 各自是 ES 模块，并各自导出 namespace Tools，它们会自动成为一个全局 Tools 吗？',['不会，模块作用域使它们成为各自导出的名字','会，所有同名 namespace 都全局合并','会，导入任意一个就获得全部成员','只有文件名相同才会合并'],'命名空间合并需要正确的声明作用域。同名不代表跨独立模块自动共享一个对象，必须明确导入和组合。','先确定声明所在作用域。｜模块不是同一个全局脚本。｜名字相同不代表模块身份相同。'),
 t(7,4,'修复命名空间公共入口','导出 namespace TextTools。内部不导出 clean(text:string)，返回 trim 后文本；导出 label(text:string)，返回 "["+clean(text)+"]"。外部只能通过 TextTools.label 使用，不暴露 clean。',
  'export namespace TextTools{export function clean(text:string):string{return text.trim();}export function label(text:string):string{return "["+clean(text)+"]";}}',
  'export namespace TextTools{function clean(text:string):string{return text.trim();}export function label(text:string):string{return "["+clean(text)+"]";}}',[
   ok('公共方法可用','import {TextTools} from "./main";const text:string=TextTools.label(" a ");'),
   bad('内部辅助方法不公开','import {TextTools} from "./main";TextTools.clean("a");',[2339]),
   bad('公开参数仍受检查','import {TextTools} from "./main";TextTools.label(1);'),
  ],'内部函数不加 export，外部入口继续通过闭包使用它。移除导出改变公共面，不应破坏原功能。','clean 只在声明内部使用。｜保留 label 的 export。｜外部通过命名空间访问 label。',{rules:{allowAmbient:true},runtime:[run('公共行为与内部可见性','const {TextTools}=load("main.js");equal(TextTools.label(" a "),"[a]");equal(TextTools.label("  "),"[]");check(!Object.hasOwn(TextTools,"clean"));')]}),
 m(7,5,'重开的声明能访问哪些成员','同一作用域内重开 namespace Tools，第二个声明能直接使用第一个声明中未导出的局部变量吗？',['不能仅凭合并访问未导出局部成员，共享成员需要适当导出','能，合并会把所有局部变量变成公共变量','能，运行时先执行就自动可见','不能，命名空间绝对不允许重开'],'导出成员参与可见的合并结果，而每个声明中的非导出局部仍有作用域边界。合并不等于把所有内部实现拼成一个无边界块。','检查成员是否导出。｜同名合并保留局部边界。｜需要共享的契约应明确表达。'),
 t(7,6,'设计可共享的命名空间配置','在同一文件中保留两段导出 namespace Limits：第一段 export const max=10；第二段导出 accepts(value:number):boolean，只接受 0～max 的整数。两段共同形成 Limits 公共对象。',
  'export namespace Limits{export const max=10;}export namespace Limits{export function accepts(value:number):boolean{return value<=max;}}',
  'export namespace Limits{export const max=10;}export namespace Limits{export function accepts(value:number):boolean{return Number.isInteger(value)&&value>=0&&value<=max;}}',[
   ok('两段声明共同可见','import {Limits} from "./main";const max:10=Limits.max;const valid:boolean=Limits.accepts(2);'),
   bad('不能传字符串','import {Limits} from "./main";Limits.accepts("2");'),
  ],'导出的 max 能在合并命名空间的其他声明中使用。业务检查仍需包含整数和下界，不能只看上界。','引用共享的 max。｜整数与非负都要满足。｜保留两段 namespace 声明。',{rules:{allowAmbient:true},runtime:[run('合并对象和边界行为','const {Limits}=load("main.js");equal(Limits.max,10);for(const n of [0,5,10])equal(Limits.accepts(n),true);for(const n of [-1,0.5,11,NaN,Infinity])equal(Limits.accepts(n),false);')]}),
 m(7,7,'引用路径不是运行加载器','历史脚本中的三斜线 reference path 是否应被当成浏览器的运行时 import？',['不应，它提供编译依赖信息，实际输出和加载顺序仍要由构建与宿主安排','应该，它会自动发起网络请求','应该，浏览器原生执行 reference 指令','不应，因为它会删除被引用文件'],'类型引用或编译依赖不等于运行时加载指令。维护旧脚本时要检查输出组合与页面脚本顺序，迁移模块时应建立真实导入。','编译器读取注释指令。｜浏览器不会因此自动加载脚本。｜关注输出与宿主加载方式。'),
 t(7,8,'迁移：去掉多余的命名空间包装','把 text.ts 中 TextTools.label 迁移为该文件的具名导出 label(text:string):string，行为仍为 "["+trim 后文本+"]"。main.ts 导入 label 并导出 formatAll(values:readonly string[]):string[]，按顺序格式化。内部 clean 不导出。',
  {'text.ts':'export namespace TextTools{function clean(text:string){return text.trim();}export function label(text:string):string{return "["+clean(text)+"]";}}','main.ts':'import {TextTools} from "./text";export function formatAll(values:readonly string[]):string[]{return values.map(TextTools.label);}'},
  {'text.ts':'function clean(text:string):string{return text.trim();}export function label(text:string):string{return "["+clean(text)+"]";}','main.ts':'import {label} from "./text";export function formatAll(values:readonly string[]):string[]{return values.map(label);}'},[
   ok('模块具名入口可直接导入','import {label} from "./text";import {formatAll} from "./main";const text:string=label(" a ");const values:string[]=formatAll(["b"]);'),
   bad('内部函数仍不导出','import {clean} from "./text";clean("a");',[2305,2459]),
   bad('迁移不放宽数据类型','import {formatAll} from "./main";formatAll([1]);'),
  ],'文件本身已有模块边界，可以直接导出公共方法，消费者相应改用具名导入。迁移同时保持内部辅助函数私有与原运行行为。','将 label 提到文件模块层并导出。｜clean 留在模块内部。｜main.ts 更新导入和调用。',{rules:{allowAmbient:true},runtime:[run('两个模块保持格式行为','const {label}=load("text.js");const {formatAll}=load("main.js");equal(label(" a "),"[a]");equal(formatAll([" x ","", " y"]),["[x]","[]","[y]"]);equal(formatAll([]),[]);')]}),
 m(7,9,'复测：环境声明不会创建全局对象','declare namespace LegacyApi{function start():void} 是否保证浏览器里已经有 LegacyApi 对象？',['不保证，环境声明只描述外部值，必须实际加载提供它的脚本','保证，declare 会生成完整对象','保证，调用时自动下载实现','保证，命名空间默认存在于 window'],'环境声明可以让检查器认识宿主或库，但不提供运行实现。没有加载对应库时，调用仍可能失败。','declare 的作用是描述。｜运行对象需要实际来源。｜检查通过不能替代脚本加载。'),
 t(7,10,'复测：为旧调用保留兼容入口','只读 core.ts 导出 add(a:number,b:number):number。main.ts 导出 namespace LegacyMath，其 add 使用 core 的真实 add，并额外导出现代具名 add。两条入口应引用同一函数，不重复维护算法。',
  'import {add as coreAdd} from "./core";export const add=coreAdd;export namespace LegacyMath{export function add(a:number,b:number):number{return a+b;}}',
  'import {add as coreAdd} from "./core";export const add=coreAdd;export namespace LegacyMath{export const add=coreAdd;}',[
   ok('新旧入口同样可调用','import {LegacyMath,add} from "./main";const a:number=LegacyMath.add(1,2);const b:number=add(1,2);'),
   bad('兼容入口保留参数约束','import {LegacyMath} from "./main";LegacyMath.add("1",2);'),
  ],'兼容层只暴露原实现，避免维护两套可能漂移的算法。命名空间入口与现代模块入口共享同一函数引用，逐步迁移调用方时行为一致。','导入 core 的函数值。｜两个入口都引用它。｜不再定义新的计算函数。',{rules:{allowAmbient:true},supportFiles:{'core.ts':'export function add(a:number,b:number):number{return a+b;}'},runtime:[run('兼容入口没有复制实现','const core=load("core.js");const {add,LegacyMath}=load("main.js");check(add===core.add);check(LegacyMath.add===core.add);equal(add(2,3),5);equal(LegacyMath.add(-1,1),0);')]}),
];
