import { mc, task, ok, bad, run } from './author.mjs';
const id=n=>`t11-l${String(n).padStart(2,'0')}`;
const m=(l,n,title,prompt,options,explanation,hints,extra={})=>mc(id(l),n,title,prompt,options,explanation,hints.split('｜'),extra);
const t=(l,n,title,prompt,files,solution,tests,explanation,hints,extra={})=>task(id(l),n,title,prompt,files,solution,tests,explanation,hints.split('｜'),extra);
export const questions=[
 m(1,1,'默认与具名不是同一入口','文件只声明 export default function format(){}，另一个文件应如何直接导入该默认函数？',['import format from "./formatter"，本地名字可以自行选择','import {format} from "./formatter"，必定可用','不需要 import，函数自动进入全局','import type format 后即可调用'],'默认导出与同名具名导出是不同入口。函数声明的名字不自动增加一个同名具名导出。','观察 export 后有没有 default。｜默认导入不用花括号。｜本地绑定名称可变化。'),
 m(1,2,'模块边界','两个独立模块各自声明未导出的 const cache，会因为同名而自动共享吗？',['不会，各自处于模块作用域，需要明确导出和导入来共享','会，名字相同就指向同一值','会，只有 const 可以共享','不会，因为模块禁止声明同名变量'],'模块边界隔离局部名字。共享状态需要有清晰归属并通过模块接口访问，不能仅依赖变量名一致。','先看变量属于哪个文件模块。｜未导出名字对外不可见。｜共享依赖需要显式表达。'),
 m(1,3,'export 星号的边界','export * from "./formatter" 会自动重新导出该模块的 default 吗？',['不会，默认导出需要显式转发','会，星号总包含 default','只有默认函数名字为 default 才会','会，但消费者必须用 type 导入'],'星号重导出不包含 default。需要兼容统一入口时，可使用 export {default as format} 等显式形式。','default 有独立规则。｜不能只凭星号猜测覆盖全部入口。｜默认值可以显式命名后转发。'),
 t(1,4,'修复默认与具名导入','只读 formatter.ts 默认导出 format(value:number):string，具名导出 prefix。main.ts 导出 describe(value:number):string，调用 format 并在结果后拼接 " ("+prefix+")"。',
  'import {format,prefix} from "./formatter";export function describe(value:number):string{return format(value)+" ("+prefix+")";}',
  'import format,{prefix} from "./formatter";export function describe(value:number):string{return format(value)+" ("+prefix+")";}',[
   ok('模块连接保留签名','import {describe} from "./main";const text:string=describe(2);'),
   bad('入口参数不能放宽','import {describe} from "./main";describe("2");'),
  ],'默认函数用默认导入，prefix 用具名导入。同一条 import 可以同时接收两类导出，但位置不同。','format 是默认导出。｜prefix 是具名导出。｜组合默认绑定和花括号绑定。',{supportFiles:{'formatter.ts':'export const prefix="ID";export default function format(value:number):string{return prefix+":"+value;}'},runtime:[run('使用真实依赖结果','const {describe}=load("main.js");equal(describe(2),"ID:2 (ID)");equal(describe(0),"ID:0 (ID)");')]}),
 m(1,5,'重新导出不创建本地变量','只写 export {format} from "./formatter"，是否同时在当前文件创建可直接调用的本地 format 绑定？',['不会；当前文件也要调用时，应另行导入或先导入再导出','会，重导出与导入完全等价','会，但只能在文件最后一行调用','不会，因为重导出不能提供运行值'],'重导出连接公共接口，不一定建立供当前模块内部使用的本地名字。对外转发与内部消费是两个需求。','观察有没有本地 import 声明。｜转发不是本地变量声明。｜需要调用时明确导入。'),
 t(1,6,'设计统一导出入口','只读 model.ts 导出接口 User 和 createUser(id:string):User；只读 formatter.ts 默认导出 label(user:User):string。编辑 main.ts，让消费者能从 ./main 导入类型 User、函数 createUser 和具名函数 label。转发真实函数，不重复实现。',
  'export * from "./model";export * from "./formatter";',
  'export type {User} from "./model";export {createUser} from "./model";export {default as label} from "./formatter";',[
   ok('统一入口同时提供值和类型','import {createUser,label} from "./main";import type {User} from "./main";const user:User=createUser("a");const text:string=label(user);'),
   bad('转发保留源函数约束','import {createUser} from "./main";createUser(1);'),
   bad('用户字段仍必需','import type {User} from "./main";const user:User={};'),
  ],'显式转发默认值为具名 label，避免星号遗漏默认导出。公共入口可同时组织值和类型，但类型导出不提供运行对象。','User 使用类型导出。｜createUser 使用具名重导出。｜默认 label 需要 default as label。',{supportFiles:{'model.ts':'export interface User{id:string}export function createUser(id:string):User{return {id};}','formatter.ts':'import type {User} from "./model";export default function label(user:User):string{return "User:"+user.id;}'},runtime:[run('公共入口转发原实现','const api=load("main.js");const model=load("model.js");const formatter=load("formatter.js");check(api.createUser===model.createUser);check(api.label===formatter.default);equal(api.label(api.createUser("a")),"User:a");')]}),
 m(1,7,'导入绑定与状态更新','模块导出 let count 并提供 increment() 修改它。消费者通过导入的 count 读取，与 const snapshot=count 有何区别？',['导入绑定反映导出端更新，普通局部数值快照保留读取时的值','两者都会自动成为快照','两者都允许消费者直接给导入绑定赋值','两者永远指向相同的可变数值对象'],'ES 模块导入是对导出绑定的关联，读取可以观察导出方更新。将当前原始值赋给普通局部常量，则保存当时的值。','区分绑定和读取结果。｜number 是原始值。｜复制一次不等于持续读取。'),
 t(1,8,'迁移：读取共享模块的最新状态','只读 state.ts 导出 count=0 和 increment()。main.ts 导出 current():number，每次返回最新 count；导出 advance():number，调用 increment 恰好一次并返回最新 count。',
  'import {count,increment} from "./state";const initial=count;export function current():number{return initial;}export function advance():number{increment();return initial;}',
  'import {count,increment} from "./state";export function current():number{return count;}export function advance():number{increment();return count;}',[
   ok('公开函数保留数值契约','import {current,advance} from "./main";const a:number=current();const b:number=advance();'),
   bad('读取函数不接收参数','import {current} from "./main";current(1);',[2554]),
  ],'需要最新状态时应在函数执行中读取导入绑定，不能只在模块初始化时复制一次数值。状态的实际归属仍在 state 模块。','不要保存初始化快照。｜current 内读取 count。｜advance 先修改再读取。',{supportFiles:{'state.ts':'export let count=0;export function increment():void{count++;}'},runtime:[run('多个消费者观察同一状态','const state=load("state.js");const api=load("main.js");equal(api.current(),0);equal(api.advance(),1);state.increment();equal(api.current(),2);equal(api.advance(),3);equal(state.count,3);')]}),
 m(1,9,'复测：命名空间导入','import * as math from "./math" 的 math 在使用上是什么？',['用于访问该模块导出成员的命名空间对象，不是自动可调用的默认函数','始终是默认导出的函数本身','包含模块所有未导出局部变量','只在类型位置存在'],'命名空间导入聚合模块导出成员。调用具名函数应访问 math.add 等成员，不能把整个模块对象当函数调用。','星号导入表示导出集合。｜访问其成员。｜默认函数也不等于集合本身。'),
 t(1,10,'复测：消除同名导入冲突','只读 text.ts 导出 format(value:string):string，包裹方括号；number.ts 导出 format(value:number):string，添加 #。main.ts 导出 summary(name:string,id:number):string，输出两个 format 结果用空格连接。用别名区分导入，复用原函数。',
  'import {format} from "./text";import {format as formatNumber} from "./number";export function summary(name:string,id:number):string{return format(name)+" "+format(String(id));}',
  'import {format as formatText} from "./text";import {format as formatNumber} from "./number";export function summary(name:string,id:number):string{return formatText(name)+" "+formatNumber(id);}',[
   ok('组合入口签名明确','import {summary} from "./main";const result:string=summary("Lin",1);'),
   bad('顺序和参数类型不互换','import {summary} from "./main";summary(1,"Lin");'),
  ],'本地别名区分两个模块的同名导出，原模块的导出名称与函数实现不变。不要用转换把错误函数的参数凑到可编译。','分别命名文本和数值格式化器。｜每个值传给对应函数。｜用一个空格连接结果。',{supportFiles:{'text.ts':'export function format(value:string):string{return "["+value+"]";}','number.ts':'export function format(value:number):string{return "#"+value;}'},runtime:[run('两个依赖各自完成职责','const {summary}=load("main.js");equal(summary("Lin",2),"[Lin] #2");equal(summary("",0),"[] #0");equal(summary("A",-3),"[A] #-3");')]}),
 m(2,1,'类型导入的输出','import type {User} from "./model" 仅用于类型位置时，编译后的 JavaScript 是否需要保留这条导入？',['这条类型导入会被擦除，不因它执行 model 模块','必须保留并执行 model','自动生成 User 构造函数','把 model 的全部内容内联进来'],'import type 明确声明仅用于类型关系，输出时被移除。若模块还有必须执行的副作用，应另行建立运行依赖。','类型声明不需要运行值。｜这条语法明确指定 type。｜副作用需要单独考虑。'),
 m(2,2,'类既可以是类型也可以是值','什么时候可以对类使用 import type？',['只在实例类型等类型位置引用，不需要 new、extends 或 instanceof 等运行操作时','任何时候都可以，new 会自动补回导入','只有类没有构造函数时','只有类没有方法时'],'类同时有类型侧和运行值侧。类型导入只保留类型用途，不能在运行位置使用被擦除的构造函数。','先判断用途发生在哪一层。｜new 需要实际构造函数。｜纯注解不需要运行值。'),
 m(2,3,'verbatimModuleSyntax 的提醒','开启 verbatimModuleSyntax 后，为什么纯接口导入应显式写 type？',['该配置强调按导入语法保留值导入，纯类型应明确标注以免混淆','它让所有接口都生成运行对象','它只影响代码缩进','它会自动校验服务器返回的数据'],'类型用途与值用途需要在导入语法中清楚表达。该配置并不替代模块运行环境配置，也不生成接口实现。','看导入名是否真的有运行值。｜纯接口没有运行实体。｜用 type 表达擦除意图。'),
 t(2,4,'修复纯类型依赖','本题开启 verbatimModuleSyntax。只读 model.ts 导出接口 User，并有可观察的初始化副作用。main.ts 仅需 User 类型，实现 userName(user:User):string 返回 name；加载 main 不应执行 model。',
  'import {User} from "./model";export function userName(user:User):string{return user.name;}',
  'import type {User} from "./model";export function userName(user:User):string{return user.name;}',[
   ok('类型约束仍然生效','import {userName} from "./main";const value:string=userName({name:"Lin"});'),
   bad('缺失字段仍被拒绝','import {userName} from "./main";userName({});'),
  ],'接口只用于注解，用 import type 保留静态依赖并去掉运行依赖。模型模块的副作用不会因这条纯类型导入执行。','User 不是运行构造函数。｜将导入标记为 type。｜函数仍使用 User 注解。',{compilerOptions:{verbatimModuleSyntax:true},supportFiles:{'state.ts':'export let loads=0;export function mark():void{loads++;}','model.ts':'import {mark} from "./state";mark();export interface User{name:string}'},runtime:[run('纯类型导入不触发初始化','const state=load("state.js");equal(state.loads,0);const {userName}=load("main.js");equal(userName({name:"Lin"}),"Lin");equal(state.loads,0);')]}),
 m(2,5,'type 修饰与副作用','模块负责注册插件，而消费者只保留 import type {Plugin}，为什么注册可能没有发生？',['类型导入被擦除，没有形成执行注册模块的运行依赖','Plugin 接口自动注销插件','注册只在类型检查时运行','所有模块副作用都被禁止'],'副作用需要实际执行模块。需要注册时，应明确保留副作用导入或调用初始化函数，不能依赖被擦除的类型引用。','检查 JavaScript 是否还有依赖。｜没有加载就没有注册。｜显式表达运行需求。'),
 t(2,6,'设计需要构造的类导入','只读 user.ts 导出 class User(name:string)，实例 greet():string 返回 "Hi "+name。main.ts 实现 createGreeting(name:string):string，实际 new User 并调用 greet。',
  'import type {User} from "./user";export function createGreeting(name:string):string{return new User(name).greet();}',
  'import {User} from "./user";export function createGreeting(name:string):string{return new User(name).greet();}',[
   ok('运行入口返回文本','import {createGreeting} from "./main";const text:string=createGreeting("Lin");'),
   bad('参数保留文本约束','import {createGreeting} from "./main";createGreeting(1);'),
  ],'new User 是运行时操作，必须导入类值。仅因为 User 也能出现在类型位置，并不意味着所有用途都可以写成类型导入。','查看 User 的使用位置。｜new 需要实际值。｜去掉导入中的 type。',{supportFiles:{'user.ts':'export class User{constructor(public name:string){}greet():string{return "Hi "+this.name;}}'},runtime:[run('类值实际可构造','const {createGreeting}=load("main.js");equal(createGreeting("Lin"),"Hi Lin");equal(createGreeting(""),"Hi ");')]}),
 m(2,7,'混合类型和值的导入','模块同时导出接口 User 和函数 createUser，可怎样清楚表达两种用途？',['import {type User,createUser} from "./model"','import type {User,createUser} 后直接调用 createUser','只导入 User 就会自动获得 createUser','必须把它们改成相同名字'],'内联 type 修饰符可与值导入共用一条声明。需要执行的函数仍是值导入，不能把整个导入声明都标成 type 后调用。','User 是纯类型。｜createUser 是需要调用的值。｜分别标注用途。'),
 t(2,8,'迁移：类型与初始化都保留','只读 plugin.ts 导出接口 Plugin{name:string}，并向 registry.ts 注册 "core"。main.ts 导出 activeName():string|undefined，读取 registry.first()；同时导出插件类型 Plugin。加载 main 必须触发插件注册一次。',
  'import type {Plugin} from "./plugin";import {first} from "./registry";export type {Plugin};export function activeName():string|undefined{return first();}',
  'import type {Plugin} from "./plugin";import "./plugin";import {first} from "./registry";export type {Plugin};export function activeName():string|undefined{return first();}',[
   ok('运行与类型公共面同时可用','import {activeName} from "./main";import type {Plugin} from "./main";const plugin:Plugin={name:"x"};const name:string|undefined=activeName();'),
   bad('插件形状不可丢失','import type {Plugin} from "./main";const plugin:Plugin={};'),
  ],'类型导入与副作用导入表达两个独立需求：前者用于检查和导出契约，后者确保注册代码执行。不能指望接口引用触发初始化。','保留 Plugin 的类型用途。｜添加显式副作用导入。｜状态读取仍通过 registry。',{supportFiles:{'registry.ts':'const names:string[]=[];export function register(name:string):void{names.push(name);}export function first():string|undefined{return names[0];}export function count():number{return names.length;}','plugin.ts':'import {register} from "./registry";register("core");export interface Plugin{name:string}'},runtime:[run('初始化执行一次且可被观察','const registry=load("registry.js");equal(registry.count(),0);const api=load("main.js");equal(api.activeName(),"core");equal(registry.count(),1);load("main.js");equal(registry.count(),1);')]}),
 m(2,9,'复测：typeof 的类型查询','类型位置的 typeof createUser 查询函数类型，是否等于运行时调用 createUser？',['不等于，它查询静态类型，不执行函数','等于，会创建一个默认用户','等于，但只调用一次','不等于，它只能返回字符串 "function"'],'类型查询 typeof 与运行表达式 typeof 需要区分。类型查询取得已有值声明的类型，不执行该函数。','观察 typeof 所在的语法位置。｜这里是类型表达式。｜查询不等于调用。'),
 t(2,10,'复测：只转发公共类型','开启 verbatimModuleSyntax。只读 contract.ts 导出接口 Request{id:string} 和类型别名 Result={ok:boolean}。main.ts 只转发这两种类型；不得新增同名运行对象，加载 main 的导出对象中不应出现 Request 或 Result。',
  'export {Request,Result} from "./contract";',
  'export type {Request,Result} from "./contract";',[
   ok('调用方获得公共类型','import type {Request,Result} from "./main";const request:Request={id:"a"};const result:Result={ok:true};'),
   bad('类型仍检查字段','import type {Request} from "./main";const request:Request={id:1};'),
   bad('类型不能当运行对象','import {Request} from "./main";console.log(Request);',[1484,2693]),
  ],'type 重导出保留静态公共接口但不制造运行值。开启该配置后应显式标注类型出口，避免生成不存在的值转发。','两个名称都是纯类型。｜使用 export type。｜消费者也按类型使用。',{compilerOptions:{verbatimModuleSyntax:true},supportFiles:{'contract.ts':'export interface Request{id:string}export type Result={ok:boolean};'},runtime:[run('没有伪造类型运行值','const api=load("main.js");check(!Object.hasOwn(api,"Request"));check(!Object.hasOwn(api,"Result"));')]}),
 m(3,1,'解析模式选择依据','选择 moduleResolution 时，主要应该依据什么？',['代码实际由什么运行环境或打包工具解析模块，而不是只挑能消除报错的选项','哪一个名字最短','所有项目都固定使用同一模式','只根据编辑器主题选择'],'解析模式模拟目标环境的查找规则。通过检查不保证目标加载器接受相同路径，配置应与实际构建和运行方式匹配。','先明确谁最终加载模块。｜不同宿主规则可能不同。｜不能只为消除红线改配置。'),
 m(3,2,'相对路径从哪里算','src/views/page.ts 中 import "../shared"，路径通常相对于哪里解析？',['当前导入文件 src/views/page.ts 所在目录','永远相对于仓库根目录','相对于浏览器当前网址','相对于用户主目录'],'相对模块说明符以导入它的文件位置为起点。移动文件后需要重新检查路径关系，不能假定都从项目根出发。','查看 import 所在文件。｜.. 返回该目录的上一级。｜再定位目标文件。'),
 m(3,3,'类型解析与运行解析','为什么 TypeScript 已找到模块类型，运行时仍可能提示找不到模块？',['类型解析和运行加载是不同步骤，别名、扩展名、输出文件或加载器规则可能不一致','类型检查通过就不可能发生这种情况','因为所有声明文件都会自动执行','因为模块导出只能在编辑器使用'],'检查器找到声明或源码，只证明静态查找成功。运行时还需要存在的输出文件及加载器可识别的说明符。','先分开静态与运行两步。｜声明不提供执行实现。｜检查实际输出和加载规则。'),
 t(3,4,'修复嵌套文件的相对路径','编辑 views/page.ts：从同级目录之外的 shared/title.ts 导入 title，并导出 render(name:string):string，返回 title(name)。main.ts 已转发 render。修正相对于 views/page.ts 的路径，不复制 title 实现。',
  {'views/page.ts':'import {title} from "./shared/title";export function render(name:string):string{return title(name);}'},
  {'views/page.ts':'import {title} from "../shared/title";export function render(name:string):string{return title(name);}'},[
   ok('入口可跨目录导入','import {render} from "./main";const text:string=render("Lin");'),
   bad('入口签名保留','import {render} from "./main";render(1);'),
  ],'page.ts 在 views 目录中，应先通过 .. 回到项目层，再进入 shared。./shared 会寻找 views/shared，位置不同。','把当前文件目录作为起点。｜返回上一级再进入 shared。｜路径为 ../shared/title。',{supportFiles:{'main.ts':'export {render} from "./views/page";','shared/title.ts':'export function title(name:string):string{return "Title:"+name;}'},runtime:[run('嵌套导入实际加载','const {render}=load("main.js");equal(render("Lin"),"Title:Lin");equal(render(""),"Title:");')]}),
 m(3,5,'源码为何可能导入 .js','TypeScript 源码写 import {value} from "./dep.js"，而项目中对应源码是 dep.ts，这一定错误吗？',['不一定，支持相应扩展替换的解析规则可找到 dep.ts，说明符也能对应输出的 dep.js','一定错误，只能写 .ts','一定错误，TypeScript 不支持 .js 字符串','一定正确，任何运行环境都会补齐所有文件'],'源码类型查找可以按规则替换扩展名，但最终运行仍取决于输出和宿主规则。不能把某种模式的成功泛化到所有配置。','区分导入说明符和类型查找候选。｜输出可能是 .js。｜仍需明确当前解析环境。'),
 t(3,6,'设计对应输出文件的导入','当前课程使用 ESNext/Bundler 类型检查，运行练习由本地模块加载器执行生成的 .js。main.ts 应通过 "./format.js" 导入 format，导出 show(value:number):string 返回 format(value)。只读源码文件为 format.ts。',
  'import {format} from "./formatting.js";export function show(value:number):string{return format(value);}',
  'import {format} from "./format.js";export function show(value:number):string{return format(value);}',[
   ok('js 说明符找到 ts 源码','import {show} from "./main";const text:string=show(2);'),
   bad('依赖签名仍检查输入','import {show} from "./main";show("2");'),
  ],'这里 format.js 说明符可在静态阶段找到 format.ts，并在输出后指向 format.js。错误的文件名 formatting 不会因为扩展替换而自动修正。','目标源码叫 format.ts。｜说明符对应输出 format.js。｜文件基名必须一致。',{supportFiles:{'format.ts':'export function format(value:number):string{return "n="+value;}'},runtime:[run('生成文件可按 js 路径加载','const {show}=load("main.js");equal(show(2),"n=2");equal(show(-1),"n=-1");')]}),
 m(3,7,'paths 不负责什么','tsconfig 中配置 paths 别名后，它是否自动把输出 JavaScript 的别名替换成相对路径？',['不会，paths 帮助类型解析，运行端需要对应支持或改用可加载路径','会，总会改写所有输出字符串','会，并自动安装依赖包','会，但只替换注释中的路径'],'paths 不是通用输出重写器。打包器或运行加载器需要单独理解别名，否则可能类型检查成功但运行失败。','观察配置作用于哪一步。｜解析不是输出重写。｜运行加载器也要支持该名字。'),
 t(3,8,'迁移：去除运行器不认识的别名','本题已配置 @shared/* 指向 shared/*，所以初始代码能通过类型解析。但练习运行器只支持相对本地路径。修复 main.ts 的导入，export double(value:number):number 调用 shared/math.ts 的 times(value,2)，不要复制算法。',
  'import {times} from "@shared/math";export function double(value:number):number{return times(value,2);}',
  'import {times} from "./shared/math";export function double(value:number):number{return times(value,2);}',[
   ok('保留函数契约','import {double} from "./main";const value:number=double(3);'),
   bad('错误输入仍被拒绝','import {double} from "./main";double("3");'),
  ],'别名在静态检查中成功不表示运行器能加载它。本题明确不修改加载器，改成等价的相对依赖即可连接实际输出文件。','运行器不理解 @shared。｜目标文件是 shared/math.ts。｜main.ts 位于根目录，使用 ./shared/math。',{compilerOptions:{baseUrl:'.',paths:{'@shared/*':['shared/*']}},supportFiles:{'shared/math.ts':'export function times(value:number,factor:number):number{return value*factor;}'},runtime:[run('类型可解析也必须运行可加载','const {double}=load("main.js");equal(double(3),6);equal(double(-2),-4);equal(double(0),0);')]}),
 m(3,9,'复测：定位模块找不到','遇到 Cannot find module，较合理的排查顺序是什么？',['核对说明符、实际文件和大小写，再检查当前解析模式、包声明入口等配置','立即给所有模块声明 any','删除所有 import','只关闭 strict 即可修复路径'],'模块定位问题应从实际依赖与环境规则查起。放宽类型不能创建不存在的文件，随意声明也可能掩盖运行问题。','先找具体目标文件。｜确认当前规则如何查找。｜不要用类型兜底代替路径修复。'),
 t(3,10,'复测：同名文件的不同身份','users/model.ts 与 orders/model.ts 都导出接口 Item，分别为 {name:string} 与 {total:number}。main.ts 导出 describe(user:UserItem,order:OrderItem):string，返回 user.name+":"+order.total；类型别名导入必须来自对应目录。',
  'import type {Item as UserItem} from "./users/model";import type {Item as OrderItem} from "./users/model";export function describe(user:UserItem,order:OrderItem):string{return user.name+":"+order.total;}',
  'import type {Item as UserItem} from "./users/model";import type {Item as OrderItem} from "./orders/model";export function describe(user:UserItem,order:OrderItem):string{return user.name+":"+order.total;}',[
   ok('同名类型来自正确模块','import {describe} from "./main";const value:string=describe({name:"Lin"},{total:2});'),
   bad('订单不能替代用户','import {describe} from "./main";describe({total:2},{total:2});'),
   bad('用户不能替代订单','import {describe} from "./main";describe({name:"Lin"},{name:"Other"});'),
  ],'同样的导出名字可以属于完全不同的模块。别名解决本地命名冲突，但只有正确的模块路径才能取得正确契约。','先确认每个 Item 的定义文件。｜UserItem 来自 users。｜OrderItem 来自 orders。',{supportFiles:{'users/model.ts':'export interface Item{name:string}','orders/model.ts':'export interface Item{total:number}'},runtime:[run('正确模型协作','const {describe}=load("main.js");equal(describe({name:"Lin"},{total:2}),"Lin:2");equal(describe({name:""},{total:0}),":0");')]}),
 m(4,1,'声明文件提供什么','一个 .d.ts 文件的主要作用是什么？',['描述已有代码的类型契约，不提供对应运行实现','替代 JavaScript 执行所有业务','在运行时验证每次函数调用','自动下载被声明的库'],'声明文件为检查器描述外部代码。执行时仍需真实 JavaScript 或宿主实现，声明本身不生成函数体。','区分描述和实现。｜.d.ts 面向检查器。｜运行值要有真实来源。'),
 m(4,2,'错误声明造成的后果','声明写函数返回 string，实际实现返回 undefined，调用方通过编译说明什么？',['调用符合声明，不证明运行结果符合声明','运行值自动变成空字符串','编译器会修改第三方实现','错误声明不会影响调用方'],'类型检查依赖声明中的前提。声明不准确会把错误信息传播给使用方，因此要依据真实 API 并验证边界。','检查器相信了什么？｜真实函数可以违背声明。｜应核对实际返回。'),
 m(4,3,'declare 不创建值','declare const client:{send():void} 是否会在 JavaScript 中创建 client 对象？',['不会，必须由运行环境或其他代码提供它','会，send 默认是空函数','会，但只在开发环境创建','会，声明自动成为 JSON 对象'],'declare 表示已有外部值的契约，不分配运行对象。没有实际来源时，即使类型检查通过也可能运行失败。','没有对象创建表达式。｜声明表达存在的假设。｜运行环境需要兑现假设。'),
 t(4,4,'修复函数返回声明','只读 vendor.js 导出 lengthOf(text)，实际返回字符串长度 number。编辑 vendor.d.ts，准确声明该具名函数：参数 string，返回 number。真实实现不可修改。',
  {'vendor.d.ts':'export function lengthOf(text:string):string;'},
  {'vendor.d.ts':'export function lengthOf(text:string):number;'},[
   ok('实际返回是数值','import {lengthOf} from "./vendor";const size:number=lengthOf("abc");'),
   bad('拒绝错误输入','import {lengthOf} from "./vendor";lengthOf(1);'),
   bad('不能把结果当文本','import {lengthOf} from "./vendor";const size:string=lengthOf("abc");'),
  ],'声明应反映现有 JavaScript，而不是为调用方想要的类型编造返回值。正例、反例和真实调用共同验证输入输出契约。','查看实现的 return。｜length 是数值。｜声明无函数体，只写签名。',{compilerOptions:{skipLibCheck:false},supportFiles:{'vendor.js':'export function lengthOf(text){return text.length;}'},runtime:[run('执行真实 JavaScript','const {lengthOf}=load("vendor.js");equal(lengthOf("abc"),3);equal(lengthOf(""),0);')]}),
 m(4,5,'失败分支需要声明','一个 find 函数未找到时返回 undefined，声明中省掉 undefined 有什么风险？',['调用方可能直接使用不存在的结果，静态检查却无法提醒','没有风险，编译器自动补齐全部失败分支','undefined 会自动被包装为对象','只影响编辑器颜色'],'外部声明不依靠函数体推断，漏掉失败状态会形成虚假保证。声明应覆盖合法调用产生的全部结果。','声明文件不分析外部业务实现。｜未找到也是正常结果之一。｜类型应保留这个可能。'),
 t(4,6,'设计包含查找失败的声明','vendor.js 导出 findUser(id)，id 为 "a" 时返回 {id:"a",name:"Lin"}，其他文本返回 undefined。vendor.d.ts 导出 User 接口和 findUser(id:string):User|undefined。',
  {'vendor.d.ts':'export interface User{id:string;name:string}export function findUser(id:string):User;'},
  {'vendor.d.ts':'export interface User{id:string;name:string}export function findUser(id:string):User|undefined;'},[
   ok('检查后可读取模型','import {findUser} from "./vendor";import type {User} from "./vendor";const result:User|undefined=findUser("a");if(result){const name:string=result.name;}'),
   bad('调用方不能忽略失败','import {findUser} from "./vendor";import type {User} from "./vendor";const result:User=findUser("missing");'),
   bad('查找键必须是文本','import {findUser} from "./vendor";findUser(1);'),
  ],'声明需要表达未命中的真实分支。省略 undefined 会使错误使用看起来合法，但不能改变运行结果。','User 描述成功模型。｜函数结果还包括未命中。｜返回类型添加 undefined。',{compilerOptions:{skipLibCheck:false},supportFiles:{'vendor.js':'export function findUser(id){return id==="a"?{id:"a",name:"Lin"}:undefined;}'},runtime:[run('真实实现包含未命中','const {findUser}=load("vendor.js");equal(findUser("a"),{id:"a",name:"Lin"});equal(findUser("missing"),undefined);')]}),
 m(4,7,'类型入口与运行入口','包配置中的类型声明入口，是否能替代 JavaScript 运行入口？',['不能，类型入口让检查器找声明，运行入口仍需可执行实现','可以，所有 .d.ts 都可直接执行','可以，只要文件名相同','不能，因为第三方包不能提供声明'],'声明入口与运行入口服务不同阶段。需要同时检查声明是否可找到、实现是否存在，以及两者描述的 API 是否一致。','两个入口面向不同消费者。｜检查器和运行加载器不同。｜类型文件不是运行替代品。'),
 t(4,8,'迁移：声明真实默认导出','vendor.js 默认导出 parse(text)，空字符串返回 null，其他字符串返回 {value:text}。编辑 vendor.d.ts，提供对应默认函数签名，不要虚构具名 parse 出口。',
  {'vendor.d.ts':'export function parse(text:string):{value:string}|null;'},
  {'vendor.d.ts':'export default function parse(text:string):{value:string}|null;'},[
   ok('调用真实默认入口','import parse from "./vendor";const result:{value:string}|null=parse("a");'),
   bad('默认函数输入仍检查','import parse from "./vendor";parse(1);'),
   bad('不虚构具名函数出口','import {parse} from "./vendor";parse("a");',[2614,2305]),
  ],'声明不仅要描述参数返回，还要匹配实际导出形状。默认函数在 JavaScript 中通过 default 出口提供，不能随意写成具名导出。','观察实现的 export default。｜声明也应有 default。｜保留空文本的 null 结果。',{compilerOptions:{skipLibCheck:false},supportFiles:{'vendor.js':'export default function parse(text){return text===""?null:{value:text};}'},runtime:[run('运行默认导出形状','const vendor=load("vendor.js");equal(vendor.default("a"),{value:"a"});equal(vendor.default(""),null);check(!Object.hasOwn(vendor,"parse"));')]}),
 m(4,9,'复测：宽泛补充声明','为了消除报错而把整个第三方模块声明成 any，主要代价是什么？',['绕开了参数和返回约束，后续错误更难被发现','得到更准确的类型推断','自动修复了第三方库实现','运行时校验反而更严格'],'宽泛声明可能短暂隐藏缺失类型的问题，却不建立正确契约。应逐步描述实际使用的 API，并用正反例验证。','不报错不等于声明准确。｜any 会继续传播。｜需要与真实 API 对齐。'),
 t(4,10,'复测：异步 API 声明','vendor.js 导出 async function count(text)，返回文本长度。编辑 vendor.d.ts，声明 count(text:string):Promise<number>，不能把等待后的数字误写为同步返回值。',
  {'vendor.d.ts':'export function count(text:string):number;'},
  {'vendor.d.ts':'export function count(text:string):Promise<number>;'},[
   ok('等待前后类型区分','import {count} from "./vendor";const pending:Promise<number>=count("a");async function use(){const value:number=await count("a");return value;}'),
   bad('不能把 Promise 当同步数值','import {count} from "./vendor";const value:number=count("a");'),
   bad('参数仍然是文本','import {count} from "./vendor";count(1);'),
  ],'声明文件描述调用立即返回的值。async 函数立即返回 Promise，await 后才得到成功值；两者不能混淆。','先看函数是否 async。｜调用返回 Promise。｜成功值为 number。',{compilerOptions:{skipLibCheck:false},supportFiles:{'vendor.js':'export async function count(text){return text.length;}'},runtime:[run('实际调用返回可等待结果','const {count}=load("vendor.js");const pending=count("abc");equal(typeof pending.then,"function");equal(await pending,3);equal(await count(""),0);')]}),
 m(5,1,'编写声明的起点','为已有 JavaScript 库编写声明时，首先应确认什么？',['实际导出形状、合法输入、返回值和失败行为','先为所有函数添加任意泛型 T','先把全部返回值写成 void','只根据函数名称猜测类型'],'声明服务真实 API，需要依据实现、使用说明和可验证行为。漂亮的类型不能代替对已有契约的理解。','先观察实际可调用入口。｜检查不同输入路径。｜再表达输入输出关系。'),
 m(5,2,'什么时候需要重载','函数对 string 返回 string[]，对 readonly string[] 返回 string。只写联合参数和联合返回会丢失什么？',['具体输入与对应返回值之间的关联','函数的所有运行实现','JavaScript 的字符串能力','文件的导出名称'],'联合返回让每个调用都面对多个候选。若 API 有明确分支对应关系，可用重载保留更准确的调用结果。','单个调用传入哪种值？｜应当得到对应结果。｜重载可分开描述契约。'),
 m(5,3,'泛型要有真实关系','声明 createStore<T> 时，T 最有用的作用是什么？',['关联初始元素、后续写入和读出值，避免各处退化为 unknown 或任意类型','允许读出调用者随意指定的任何值','自动执行运行时 schema 校验','让所有 store 共用同一数组'],'泛型表达输入输出之间真实可保持的关系。它不创造数据，也不提供运行验证，应与库的实际存储行为一致。','寻找哪些位置使用同一种元素。｜写入和读取必须关联。｜泛型不是运行时检查。'),
 t(5,4,'修复重载声明的对应关系','只读 vendor.js 的 convert：字符串按逗号拆分为 string[]；字符串数组用逗号连接为 string。vendor.d.ts 声明这两个重载，数组参数支持 readonly string[]。本题不要求开放联合变量调用。',
  {'vendor.d.ts':'export function convert(value:string|readonly string[]):string|string[];'},
  {'vendor.d.ts':'export function convert(value:string):string[];export function convert(value:readonly string[]):string;'},[
   ok('精确匹配两个返回分支','import {convert} from "./vendor";const parts:string[]=convert("a,b");const text:string=convert(["a","b"] as const);'),
   bad('拒绝不支持的输入','import {convert} from "./vendor";convert(1);',[2769,2345]),
   bad('文本分支不是文本返回','import {convert} from "./vendor";const text:string=convert("a,b");'),
  ],'两条重载分别描述实际分支。只读数组参数允许调用方提供只读输入，因为实现只是连接，并不修改数组。','字符串输入返回数组。｜数组输入返回字符串。｜写两条同名函数声明。',{compilerOptions:{skipLibCheck:false},supportFiles:{'vendor.js':'export function convert(value){return typeof value==="string"?value.split(","):value.join(",");}'},runtime:[run('实际分支与只读输入','const {convert}=load("vendor.js");equal(convert("a,b"),["a","b"]);equal(convert(Object.freeze(["a","b"])),"a,b");equal(convert([]),"");')]}),
 m(5,5,'返回清理函数不能遗漏','on(callback) 返回用于退订的函数，把声明写成 on(callback):void 会带来什么问题？',['调用方失去获取和调用退订函数的类型信息','运行时退订函数会自动消失','自动变成一次性订阅','任何回调都将禁止执行'],'声明应保留 API 的生命周期能力。void 可能掩盖可使用的返回值，导致调用方无法按正常类型方式完成清理。','观察调用结果的用途。｜退订是公共契约的一部分。｜返回类型要描述函数。'),
 t(5,6,'设计泛型存储声明','vendor.js 导出 createStore(initial)，复制数组并返回 add(value) 与 first()。vendor.d.ts 导出 Store<T>，add(value:T):void、first():T|undefined；createStore<T>(initial:readonly T[]):Store<T>。',
  {'vendor.d.ts':'export interface Store<T>{add(value:unknown):void;first():T|undefined}export function createStore<T>(initial:readonly T[]):Store<T>;'},
  {'vendor.d.ts':'export interface Store<T>{add(value:T):void;first():T|undefined}export function createStore<T>(initial:readonly T[]):Store<T>;'},[
   ok('元素关系与空存储','import {createStore} from "./vendor";const store=createStore([1,2]);store.add(3);const first:number|undefined=store.first();const empty=createStore<string>([]);empty.add("a");createStore([1,2] as const);'),
   bad('不能写入其他元素类型','import {createStore} from "./vendor";createStore([1,2]).add("x");'),
   bad('空存储读出仍可能缺失','import {createStore} from "./vendor";const first:number=createStore<number>([]).first();'),
  ],'同一个 T 贯穿初始集合、add 与 first。把写入放宽为 unknown 会允许与读出承诺矛盾的数据进入存储。','add 与初始数组共享元素 T。｜first 保留空集合可能。｜工厂返回 Store<T>。',{compilerOptions:{skipLibCheck:false},supportFiles:{'vendor.js':'export function createStore(initial){const values=[...initial];return {add(value){values.push(value);},first(){return values[0];}};}'},runtime:[run('复制初始集合与实例独立','const {createStore}=load("vendor.js");const initial=[1];const store=createStore(initial);initial[0]=9;equal(store.first(),1);const empty=createStore([]);equal(empty.first(),undefined);empty.add("a");equal(empty.first(),"a");equal(store.first(),1);')]}),
 m(5,7,'回调参数可选性的依据','库保证每次回调都传 value:number，声明 callback(value?:number) 是否更友好？',['不是，它错误表示可能不传值，迫使使用方处理 undefined','是，可选只是说明可以不使用参数','是，可选会自动验证值','无所谓，回调参数不参与检查'],'声明应反映库实际调用方式。回调可忽略额外参数，不需要把库保证提供的参数标成可选。','看库每次实际传什么。｜可选表示允许缺失。｜不使用参数与参数缺失不同。'),
 t(5,8,'迁移：完整的订阅生命周期声明','vendor.js 导出 on(callback) 和 emit(value)。回调每次收到 number；on 返回无参数退订函数，emit 接收 number 并返回 void。编写 vendor.d.ts，保留这些约束。',
  {'vendor.d.ts':'export function on(callback:(value:number)=>void):void;export function emit(value:number):void;'},
  {'vendor.d.ts':'export function on(callback:(value:number)=>void):()=>void;export function emit(value:number):void;'},[
   ok('上下文参数和清理能力','import {on,emit} from "./vendor";const off:()=>void=on(value=>{const n:number=value;});emit(1);off();on(()=>{});'),
   bad('回调不能只接受字符串','import {on} from "./vendor";on((value:string)=>{});'),
   bad('事件值必须是数字','import {emit} from "./vendor";emit("1");'),
  ],'不仅描述注册入口，还要描述返回的清理能力。数字回调参数必需，但调用方仍能提供不使用该参数的函数。','on 返回函数。｜该函数无参数且返回 void。｜回调接收 number。',{compilerOptions:{skipLibCheck:false},supportFiles:{'vendor.js':'const listeners=new Set();export function on(callback){listeners.add(callback);return ()=>{listeners.delete(callback);};}export function emit(value){for(const callback of listeners)callback(value);}'},runtime:[run('订阅退订和重复清理','const {on,emit}=load("vendor.js");const seen=[];const off=on(value=>seen.push(value));emit(1);emit(2);off();off();emit(3);equal(seen,[1,2]);')]}),
 m(5,9,'复测：可调用对象不只是函数签名','库默认导出的函数还有 version 属性，声明时需要注意什么？',['同时描述调用签名和属性，保持真实默认导出形状','只要写成 object 就保留了调用能力','函数在 JavaScript 中不能有属性','version 必须声明成全局变量'],'JavaScript 函数也是对象。声明可用带调用签名的对象类型，或合适的函数与命名空间合并来表达附加属性。','函数可被调用也可拥有属性。｜两部分都属于公共 API。｜导出形状仍需匹配。'),
 t(5,10,'复测：声明带版本的默认函数','vendor.js 默认导出 tag(text)，返回 "["+text+"]"，并有 version 值 "1.0"。vendor.d.ts 描述默认可调用对象：(text:string)=>string，同时具有 version:"1.0"。',
  {'vendor.d.ts':'declare const tag:(text:string)=>string;export default tag;'},
  {'vendor.d.ts':'declare const tag:{(text:string):string;version:"1.0"};export default tag;'},[
   ok('调用与属性同时可用','import tag from "./vendor";const text:string=tag("a");const version:"1.0"=tag.version;'),
   bad('参数不能任意类型','import tag from "./vendor";tag(1);'),
   bad('版本不能误认为数字','import tag from "./vendor";const version:number=tag.version;'),
  ],'可调用对象类型同时列出调用签名和属性，默认导出该声明值。只有函数类型会遗漏 version，只有属性对象则会丢失调用能力。','用对象类型中的调用签名。｜同时添加 version 属性。｜保留 export default。',{compilerOptions:{skipLibCheck:false},supportFiles:{'vendor.js':'function tag(text){return "["+text+"]";}tag.version="1.0";export default tag;'},runtime:[run('真实默认函数带版本','const tag=load("vendor.js").default;equal(tag("a"),"[a]");equal(tag(""),"[]");equal(tag.version,"1.0");')]}),
 m(6,1,'先找库自带类型','使用第三方包前，发现它已经提供匹配当前版本的声明，通常应先做什么？',['确认解析确实使用这些声明，而不是无条件再安装另一套类型','立刻为该包全部声明 any','同时安装所有历史版本的 @types','删除库自带声明'],'类型来源可能已经包含在库中。先确认实际版本和解析入口，避免重复或过时的声明引入冲突。','先检查包提供的内容。｜版本应与实现相符。｜不必盲目叠加类型来源。'),
 m(6,2,'@types 的职责','@types 类型包是否通常提供原库的业务 JavaScript 实现？',['它主要提供类型声明，业务实现仍由对应库提供','会自动替代原库全部运行代码','只用于 CSS 样式','安装后不再需要原库'],'类型包与运行包承担不同职责。需要确认版本兼容，不能把安装类型声明等同于安装业务实现。','名称中的 types 指向什么？｜运行函数仍需实际代码。｜两套版本要能对应。'),
 m(6,3,'types 配置不是所有导入的开关','tsconfig 中 types:[] 是否意味着显式 import 的包永远不能使用它的声明？',['不是，它限制自动纳入的全局类型包；显式模块导入仍会进行相应类型解析','是，所有第三方类型都永久禁用','是，只能用 any','不是，因为它会自动安装缺少的包'],'自动引入全局类型与显式导入模块的查找是不同机制。应针对具体解析路径诊断，不把 types 当作所有声明的总开关。','区分全局自动纳入和模块导入。｜import 仍然需要解析目标。｜配置不会安装依赖。'),
 t(6,4,'修复自带类型的入口','虚拟包 measure 的实际 size(text) 接收 string 并返回 number。包内 legacy.d.ts 是旧版 number 到 string，current.d.ts 是当前正确契约。只编辑 package.json，让 types 指向 current.d.ts，保留 name 与 version。',
  {'node_modules/measure/package.json':'{"name":"measure","version":"2.0.0","types":"legacy.d.ts"}'},
  {'node_modules/measure/package.json':'{"name":"measure","version":"2.0.0","types":"current.d.ts"}'},[
   ok('裸模块导入取得当前声明','import {size} from "measure";const result:number=size("abc");'),
   bad('旧版参数不再合法','import {size} from "measure";size(3);'),
   bad('当前返回不能当文本','import {size} from "measure";const result:string=size("abc");'),
  ],'同一个包中声明文件存在不代表解析器选中了正确入口。types 应指向与实际版本匹配的声明，而不是在消费者处强行断言。','检查 package.json 的 types。｜当前契约位于 current.d.ts。｜只更改该路径。',{supportFiles:{'node_modules/measure/legacy.d.ts':'export function size(value:number):string;','node_modules/measure/current.d.ts':'export function size(value:string):number;','node_modules/measure/index.js':'export function size(value){return value.length;}'},runtime:[run('真实版本行为','const {size}=load("node_modules/measure/index.js");equal(size("abc"),3);equal(size(""),0);')]}),
 m(6,5,'本地补充声明的边界','给没有类型的模块补写 declare module "legacy-lib" 时，应避免什么？',['为了消除报错而虚构不存在的导出或过度放宽参数','核对库的实际 API','添加错误用法测试','把补充声明纳入项目'],'补充声明仍是对真实代码的承诺。它能解决类型缺失，但不应该掩盖缺少实现或错误调用。','声明必须描述已有功能。｜名字写进声明不代表功能出现。｜需要正确约束。'),
 t(6,6,'设计 @types 中的函数声明','虚拟运行包 legacy-math 只有 index.js，其 scale(value,factor) 要求两个 number 并返回乘积。编辑 node_modules/@types/legacy-math/index.d.ts，导出准确函数声明，factor 不能省略。',
  {'node_modules/@types/legacy-math/index.d.ts':'export function scale(value:number,factor?:number):number;'},
  {'node_modules/@types/legacy-math/index.d.ts':'export function scale(value:number,factor:number):number;'},[
   ok('从类型包解析函数','import {scale} from "legacy-math";const result:number=scale(2,3);'),
   bad('因子必须提供','import {scale} from "legacy-math";scale(2);',[2554]),
   bad('因子不是文本','import {scale} from "legacy-math";scale(2,"3");'),
  ],'运行库无自带声明时，解析可以从对应 @types 包获得模块契约。声明的必需参数应反映真实调用要求，不能随意加问号。','类型包路径对应运行包名称。｜写具名 scale 导出。｜两个参数都为必需 number。',{supportFiles:{'node_modules/legacy-math/index.js':'export function scale(value,factor){return value*factor;}'},runtime:[run('实际库提供运算实现','const {scale}=load("node_modules/legacy-math/index.js");equal(scale(2,3),6);equal(scale(-2,4),-8);')]}),
 m(6,7,'版本不匹配的排查','升级运行库后类型提示仍显示旧 API，合理的第一步是什么？',['查看实际加载的声明路径及类型包版本，再核对它们与运行库是否匹配','立即把所有结果断言为新接口','只重命名局部变量','默认所有 .d.ts 都永远兼容未来版本'],'声明可能来自库自身、独立包或本地覆盖。只有确认当前来源，才能判断是版本错配、入口错误还是实现与声明不一致。','先找正在生效的声明。｜确认其版本和入口。｜不要靠断言掩盖差异。'),
 t(6,8,'迁移：补充无类型模块','虚拟 legacy-text 包导出 join(values,separator)，values 为 readonly string[]，separator 可省略，默认逗号，返回 string。编辑 local.d.ts，使用 declare module "legacy-text" 精确声明。此文件不添加顶层 export {}，作为环境模块声明。',
  {'local.d.ts':'declare module "legacy-text" {export function join(values:readonly string[],separator:string):string;}'},
  {'local.d.ts':'declare module "legacy-text" {export function join(values:readonly string[],separator?:string):string;}'},[
   ok('声明可供模块导入使用','import {join} from "legacy-text";const a:string=join(["a","b"] as const);const b:string=join(["a","b"],"-");'),
   bad('数组元素必须为文本','import {join} from "legacy-text";join([1]);'),
   bad('分隔符不能为数字','import {join} from "legacy-text";join(["a"],1);'),
  ],'环境模块声明给指定包名提供缺失契约；这里文件没有顶层导入导出，因此是声明模块而不是对已有模块做增强。可选参数对应实际默认值。','模块名与 import 完全一致。｜separator 可省略。｜返回 string，数组允许只读输入。',{rules:{allowAmbient:true},supportFiles:{'node_modules/legacy-text/index.js':'export function join(values,separator=","){return values.join(separator);}'},runtime:[run('真实可选参数行为','const {join}=load("node_modules/legacy-text/index.js");equal(join(Object.freeze(["a","b"])),"a,b");equal(join(["a","b"],"-"),"a-b");equal(join([]),"");')]}),
 m(6,9,'复测：skipLibCheck 的限度','skipLibCheck 可以代替安装缺失的运行包或保证声明与实现一致吗？',['不能，它跳过部分声明文件检查，不会提供缺失代码或验证实现','可以，它会生成缺失实现','可以，它会自动修复所有声明','可以，但只在手机浏览器生效'],'跳过声明检查是检查范围选择，不是依赖安装或运行校验。它可能减少某些诊断，但不能让错误契约变正确。','选项作用于检查过程。｜不会修改真实库行为。｜缺失依赖仍需处理。'),
 t(6,10,'复测：使用当前版本的响应模型','catalog 包当前自带 SearchResult={items:readonly string[];total:number}。main.ts 导入该类型并实现 count(result:SearchResult):number 返回 total。不要按旧版数组结果读取 length，也不要自己重新声明旧模型。',
  'import type {SearchResult} from "catalog";export function count(result:SearchResult):number{return result.length;}',
  'import type {SearchResult} from "catalog";export function count(result:SearchResult):number{return result.total;}',[
   ok('使用包的当前模型','import {count} from "./main";const result:number=count({items:["a"],total:10});'),
   bad('旧版数组结果不再合法','import {count} from "./main";count(["a"]);'),
   bad('总数类型不放宽','import {count} from "./main";count({items:[],total:"10"});'),
  ],'消费者需要跟随已安装版本的真实契约调整。总数可能大于当前页 items.length，更不能把整个结果对象当数组。','通过包名导入当前 SearchResult。｜响应对象包含 total。｜返回总数而不是当前页长度。',{supportFiles:{'node_modules/catalog/package.json':'{"name":"catalog","version":"2.0.0","types":"index.d.ts"}','node_modules/catalog/index.d.ts':'export interface SearchResult{items:readonly string[];total:number}'},runtime:[run('总数与当前页长度不同','const {count}=load("main.js");equal(count({items:["a"],total:10}),10);equal(count({items:[],total:0}),0);')]}),
 m(7,1,'lib 提供的是什么','在编译配置中加入 DOM 类型库，会在 Node 或 Worker 中自动创建 document 吗？',['不会，lib 提供声明，实际 API 由运行环境提供','会，自动安装完整浏览器','会，只缺少 CSS','会，但只在严格模式下'],'类型库让检查器认识名字和接口，不是运行时实现。浏览器窗口、Worker 与服务器环境提供的全局能力不同。','声明和实现分开考虑。｜document 需要真实 DOM 环境。｜lib 不安装运行能力。'),
 m(7,2,'Node 类型的来源','在没有 Node 类型声明的项目中，process 报找不到名字，能否靠添加 DOM 类型库解决？',['不能，DOM 与 Node 环境契约不同，应确认目标环境及对应类型来源','可以，DOM 包含所有服务器全局','可以，process 会变成 window','不必处理，所有未知全局默认安全'],'不同类型库描述不同宿主。应按实际运行环境选择声明，而不是把所有类型无差别加入以消除报错。','process 属于哪类宿主？｜DOM 不描述全部 Node 能力。｜类型选择需匹配运行环境。'),
 m(7,3,'模块中的全局增强','一个含 export {} 的 .d.ts 文件要扩展全局声明，通常应怎样组织？',['使用 declare global 包裹全局成员，保留文件的模块身份','直接把所有成员 export 出去就等于全局','删除所有类型字段','用 console.log 创建全局类型'],'模块内的导出名字不自动成为全局名字。declare global 明确把指定声明加入全局范围，但仍不创建运行值。','模块导出与全局作用域不同。｜需要明确的全局增强块。｜声明不执行初始化。'),
 t(7,4,'修复可选宿主配置的全局声明','编辑 env.d.ts，声明 globalThis.APP_META 为 {version:string}|undefined。文件保持模块身份并使用 declare global。只读 main.ts 的 readVersion() 已实现缺失时返回 "unknown"，宿主在运行时提供实际值。',
  {'env.d.ts':'export const APP_META:{version:string}|undefined;'},
  {'env.d.ts':'export {};declare global{var APP_META:{version:string}|undefined;}'},[
   ok('全局配置可缺失','import {readVersion} from "./main";globalThis.APP_META=undefined;globalThis.APP_META={version:"1.0"};const text:string=readVersion();'),
   bad('版本字段仍检查类型','import "./main";globalThis.APP_META={version:1};'),
  ],'export const 只声明模块导出，不会增强 globalThis。使用全局 var 声明描述宿主属性，同时用 undefined 表达它可能尚未提供。','保留 export {} 使文件为模块。｜在 declare global 内声明 var。｜类型必须包含 undefined。',{rules:{allowAmbient:true},supportFiles:{'main.ts':'export function readVersion():string{return globalThis.APP_META?.version??"unknown";}'},runtime:[run('声明不初始化而宿主值可变化','globalThis.APP_META=undefined;const {readVersion}=load("main.js");equal(readVersion(),"unknown");globalThis.APP_META={version:"2.0"};equal(readVersion(),"2.0");globalThis.APP_META=undefined;equal(readVersion(),"unknown");')]}),
 m(7,5,'全局对象不存在时','为什么服务器端模块顶层直接读取 window.location 可能在被导入时就失败？',['模块顶层代码会执行，而该运行环境可能没有 window','类型检查会阻止所有模块加载','window 在任何 JavaScript 环境都存在','只有调用导出函数时才会执行全部顶层代码'],'模块加载会执行顶层逻辑。把浏览器依赖放到真正有能力的调用边界，或通过显式参数注入，可以减少环境耦合。','先考虑模块初始化时间。｜宿主可能没有 window。｜类型存在不保证全局值存在。'),
 t(7,6,'设计不依赖 DOM 的存储接口','本题仅启用 ES2022 类型库。导出接口 TextStorage{setItem(key:string,value:string):void}，实现 save(storage:TextStorage,key:string,value:string):void，调用传入 storage 的 setItem 一次。不能读取浏览器 localStorage。',
  'export interface TextStorage{setItem(key:string,value:string):void}export function save(storage:TextStorage,key:string,value:string):void{localStorage.setItem(key,value);}',
  'export interface TextStorage{setItem(key:string,value:string):void}export function save(storage:TextStorage,key:string,value:string):void{storage.setItem(key,value);}',[
   ok('任何兼容适配器都可使用','import {save} from "./main";save({setItem(key,value){const k:string=key;const v:string=value;}},"a","b");'),
   bad('适配器必须实现所需能力','import {save} from "./main";save({},"a","b");'),
   bad('不把值放宽为任意类型','import {save} from "./main";save({setItem(){}},"a",1);'),
  ],'依赖明确的最小接口，核心逻辑就不需要 DOM 全局。浏览器或其他宿主可以分别提供适配器，测试也能注入可观察实现。','使用函数参数中的 storage。｜只调用所需 setItem。｜不要引入浏览器全局。',{compilerOptions:{lib:['ES2022']},runtime:[run('通过注入能力保存数据','const {save}=load("main.js");const events=[];const storage={setItem(key,value){check(this===storage);events.push([key,value]);}};save(storage,"name","Lin");equal(events,[["name","Lin"]]);')]}),
 m(7,7,'全局声明中的可选能力','某宿主有时提供 bridge，有时不提供，声明直接保证 bridge 总存在有什么风险？',['调用方可能跳过缺失检查，运行时却访问不存在的值','声明会强制宿主自动创建 bridge','没有风险，全局声明永远比实现可靠','只影响接口名称'],'全局声明同样需要反映实际存在性。条件能力应通过联合 undefined、能力检测或显式依赖表达，不能凭空承诺。','检查是否所有宿主都提供它。｜声明应保留缺失可能。｜使用前建立存在证据。'),
 t(7,8,'迁移：检测宿主桥接能力','只读 env.d.ts 声明 globalThis.hostBridge 为 {send(text:string):void}|undefined。实现 notify(text:string):boolean：缺失返回 false；存在时发送一次原文本并返回 true，异常不吞掉。',
  'export function notify(text:string):boolean{globalThis.hostBridge!.send(text);return true;}',
  'export function notify(text:string):boolean{const bridge=globalThis.hostBridge;if(bridge===undefined)return false;bridge.send(text);return true;}',[
   ok('能力缺失属于正常情况','import {notify} from "./main";globalThis.hostBridge=undefined;const ok:boolean=notify("a");'),
   bad('发送文本必须为字符串','import {notify} from "./main";notify(1);'),
  ],'类型断言不会创建桥接对象。先读取当前能力并判断，再通过该对象调用方法，保留方法接收者和真实异常。','保存本次读取到的 bridge。｜缺失时直接返回 false。｜存在时调用 send 一次。',{supportFiles:{'env.d.ts':'export {};declare global{var hostBridge:{send(text:string):void}|undefined;}'},runtime:[run('能力可用性与错误传播','const {notify}=load("main.js");globalThis.hostBridge=undefined;equal(notify("a"),false);const seen=[];const bridge={send(text){check(this===bridge);seen.push(text);}};globalThis.hostBridge=bridge;equal(notify(""),true);equal(seen,[""]);const sentinel={failed:true};globalThis.hostBridge={send(){throw sentinel;}};let caught;try{notify("x");}catch(error){caught=error;}check(caught===sentinel);globalThis.hostBridge=undefined;')]}),
 m(7,9,'复测：Worker 不是窗口','浏览器 Worker 中是否可以因为类型库包含 DOM，就直接假设 document 可用？',['不可以，Worker 与窗口的实际全局能力不同','可以，所有浏览器线程共享同一个 document 变量','可以，编译器会跨线程转发所有操作','不可以，因为 Worker 完全不能执行 JavaScript'],'Worker 是独立执行环境，不提供窗口 DOM 的同样接口。应确认宿主能力及通信方式，类型库不能改变运行边界。','浏览器内也有不同宿主。｜窗口和 Worker 不是同一个全局。｜检查真实可用能力。'),
 t(7,10,'复测：在缺少 DOM 时安全调用','本题提供 DOM 声明，但运行测试可能没有 document。实现 pageTitle():string|null：document 不存在时返回 null，否则读取其 title。不能在模块顶层提前读取 document。',
  'export function pageTitle():string|null{return document.title;}',
  'export function pageTitle():string|null{return typeof document==="undefined"?null:document.title;}',[
   ok('返回明确的无 DOM 结果','import {pageTitle} from "./main";const title:string|null=pageTitle();'),
   bad('调用方不能忽略缺失','import {pageTitle} from "./main";const title:string=pageTitle();'),
  ],'DOM 声明允许静态引用 document，但调用时仍需检测宿主是否提供它。typeof 可安全判断未定义名字，检查应在实际调用边界执行。','先判断 typeof document。｜缺失返回 null。｜存在再读取 title。',{runtime:[run('有无 DOM 能力分别处理','delete globalThis.document;const {pageTitle}=load("main.js");equal(pageTitle(),null);globalThis.document={title:"Example"};equal(pageTitle(),"Example");globalThis.document.title="";equal(pageTitle(),"");delete globalThis.document;equal(pageTitle(),null);')]}),
 m(8,1,'共享模型放在哪里','多个模块使用同一业务契约时，把它放在明确的共享契约模块有什么好处？',['减少重复定义漂移，让消费者依赖同一类型来源','保证运行时数据自动合法','自动消除所有循环依赖','让所有业务字段都必须公开'],'共享类型有助于统一静态契约，但不替代运行校验，也不能自动解决架构中的所有依赖问题。','关注类型的唯一维护位置。｜不要把共享等同于全局。｜运行验证仍有独立职责。'),
 m(8,2,'公共入口不应无差别扩张','库的入口文件为什么不一定适合对所有内部文件使用 export *？',['可能意外公开内部能力或引入同名冲突，应明确公共导出面','因为 export * 永远无法编译','因为它会自动删除默认导出函数的实现','因为所有类型都必须全局声明'],'公共导出会成为消费者可依赖的契约。显式选择导出成员，有助于保持边界和减少内部改动的外部影响。','先定义承诺给消费者什么。｜内部功能不一定需要公开。｜星号可能扩大公共面。'),
 m(8,3,'类型依赖与运行循环','把仅用于注解的导入改为 import type，能保证所有循环依赖都消失吗？',['不能，它可移除相应运行依赖，但真正的值依赖和初始化顺序仍需分析','能，任何循环都自动变直线','不能，因为类型导入仍会执行全部模块','能，并自动重排所有顶层语句'],'类型边可以不进入运行图，但真实运行值的相互依赖仍然存在。组织共享契约时应避免无意依赖业务初始化代码。','区分类型图和运行依赖图。｜只移除纯类型产生的边。｜值依赖仍需要实际设计。'),
 t(8,4,'修复重复维护的共享模型','只读 contracts.ts 导出 User。main.ts 导出类型 PublicUser，应直接关联 User，而非复制其字段；identity(user:PublicUser):PublicUser 原样返回输入。模型新增字段后，PublicUser 必须同步。',
  'export interface PublicUser{id:string;name:string}export function identity(user:PublicUser):PublicUser{return user;}',
  'import type {User} from "./contracts";export type PublicUser=User;export function identity(user:PublicUser):PublicUser{return user;}',[
   ok('当前契约可用','import {identity} from "./main";import type {PublicUser} from "./main";const user:PublicUser={id:"a",name:"Lin"};identity(user);'),
   {...ok('契约新增字段自动传播','import type {PublicUser} from "./main";const user:PublicUser={id:"a",name:"Lin",active:true};const active:boolean=user.active;'),supportFiles:{'contracts.ts':'export interface User{id:string;name:string;active:boolean}'}},
   bad('字段类型仍受约束','import type {PublicUser} from "./main";const user:PublicUser={id:1,name:"Lin"};'),
  ],'别名或重导出使 PublicUser 跟随唯一契约来源。复制当前字段可能暂时可用，却会在模型演进后与真实契约脱节。','导入 User 类型。｜PublicUser 关联该类型。｜不要再次列出字段。',{supportFiles:{'contracts.ts':'export interface User{id:string;name:string}'},runtime:[run('契约传递不改变对象','const {identity}=load("main.js");const user={id:"a",name:"Lin",active:true};check(identity(user)===user);')]}),
 m(8,5,'公开 DTO 与内部模型','内部用户增加 token 字段时，公开 DTO 用白名单 Pick 相比排除已知秘密字段的 Omit 有什么优势？',['新增内部字段不会自动进入公开白名单','自动在运行时删除 token','让所有字段变成只读','保证任何网络返回都合法'],'白名单使公开字段集合显式稳定。它仍是类型层约束，实际输出对象还需要按白名单构造。','新增字段是否默认进入结果？｜Pick 只选指定键。｜不要忽略运行时投影。'),
 t(8,6,'设计公共导出白名单','只读 client.ts 导出 Options、createClient 和内部 internalReset。main.ts 仅对外提供 Options 类型与 createClient 函数；不得公开 internalReset，createClient 保持原函数引用。',
  'export * from "./client";',
  'export type {Options} from "./client";export {createClient} from "./client";',[
   ok('公共类型与工厂可用','import {createClient} from "./main";import type {Options} from "./main";const options:Options={endpoint:"/api"};const client=createClient(options);const endpoint:string=client.endpoint;'),
   bad('内部入口不暴露','import {internalReset} from "./main";internalReset();',[2305,2459]),
   bad('公开契约仍检查参数','import {createClient} from "./main";createClient({endpoint:1});'),
  ],'公共入口明确转发承诺给外部的成员。将内部函数保留在内部模块，不意味着要删除实现；只需要避免从公共入口暴露它。','替换无差别 export *。｜类型和值分别显式导出。｜不重复实现工厂函数。',{supportFiles:{'client.ts':'export interface Options{endpoint:string}export function createClient(options:Options){return {endpoint:options.endpoint};}export function internalReset():void{}'},runtime:[run('公共出口保持边界','const api=load("main.js");const internal=load("client.js");check(api.createClient===internal.createClient);check(!Object.hasOwn(api,"internalReset"));equal(api.createClient({endpoint:"/api"}),{endpoint:"/api"});')]}),
 m(8,7,'公共类型的依赖方向','一个纯共享契约文件从业务启动模块读取运行值来定义默认配置，可能带来什么问题？',['消费者使用契约时可能卷入业务初始化依赖，应区分纯类型和运行配置','所有 interface 会自动变成 class','所有循环都会被编译器自动修复','任何类型都不能引用别的文件'],'共享层应有清楚职责。纯类型、公共常量与业务初始化可以分别组织，减少不必要的运行加载和依赖循环。','契约文件是否实际执行代码？｜消费者会加载哪些依赖？｜把初始化责任放在明确位置。'),
 t(8,8,'迁移：公开模型与实际输出一致','只读 model.ts 导出内部 User。main.ts 导出 PublicUser=Pick<User,"id"|"name">，实现 toPublic(user:User):PublicUser，仅构造 id、name 的新对象。新增内部字段也不能进入公开类型或输出。',
  'import type {User} from "./model";export type PublicUser=Omit<User,"password">;export function toPublic(user:User):PublicUser{const {password,...rest}=user;return rest;}',
  'import type {User} from "./model";export type PublicUser=Pick<User,"id"|"name">;export function toPublic(user:User):PublicUser{return {id:user.id,name:user.name};}',[
   ok('公开字段可用','import {toPublic} from "./main";const user=toPublic({id:"a",name:"Lin",password:"secret"});const name:string=user.name;'),
   bad('密码不进入公开类型','import type {PublicUser} from "./main";declare const user:PublicUser;user.password;'),
   {...bad('新内部字段不进入公共契约','import type {PublicUser} from "./main";declare const user:PublicUser;user.token;'),supportFiles:{'model.ts':'export interface User{id:string;name:string;password:string;token:string}'}},
  ],'类型白名单与实际投影需要一致。只删除 password 的黑名单实现会在新增 token 时泄露字段，不能仅依赖旧模型中的已知秘密。','类型只选 id 和 name。｜返回对象也只写这两个字段。｜不要把剩余字段整体展开。',{supportFiles:{'model.ts':'export interface User{id:string;name:string;password:string}'},runtime:[run('新增内部字段也不输出','const {toPublic}=load("main.js");const user=Object.freeze({id:"a",name:"Lin",password:"secret",token:"future"});const out=toPublic(user);equal(out,{id:"a",name:"Lin"});check(out!==user);equal(user.token,"future");')]}),
 m(8,9,'复测：适配器类型漂移','包装器把依赖函数的返回类型复制成固定 string|null，有什么维护风险？',['依赖返回契约变化时，包装器可能不同步；可按需求从原契约派生','能自动兼容所有未来返回类型','会在运行时删除 null','只要函数名相同就永远一致'],'包装器若承诺透传依赖结果，类型应保留这种关系。若公共 API 有意保持稳定，则需要真实转换层，不能只是继续使用旧注解。','先判断透传还是转换。｜透传契约应随来源变化。｜稳定契约需要实现适配。'),
 t(8,10,'复测：派生最小解析端口','只读 parser.ts 导出 Parser 接口，含 parse(text:string):string|null 和 reset():void。main.ts 导出 ParserPort=Pick<Parser,"parse">，实现 runParser(parser:ParserPort,text:string):ReturnType<ParserPort["parse"]>，透传结果并保留接收者。',
  'import type {Parser} from "./parser";export type ParserPort={parse(text:string):string|null};export function runParser(parser:ParserPort,text:string):string|null{return parser.parse(text);}',
  'import type {Parser} from "./parser";export type ParserPort=Pick<Parser,"parse">;export function runParser(parser:ParserPort,text:string):ReturnType<ParserPort["parse"]>{return parser.parse(text);}',[
   ok('只要求所需方法','import {runParser} from "./main";const result:string|null=runParser({parse:text=>text||null},"a");'),
   {...ok('来源返回类型变化时同步','import {runParser} from "./main";const result:number|null=runParser({parse:text=>text.length},"a");'),supportFiles:{'parser.ts':'export interface Parser{parse(text:string):number|null;reset():void}'}},
   bad('输入参数仍然受约束','import {runParser} from "./main";runParser({parse:text=>text},1);'),
  ],'Pick 定义最小依赖能力，ReturnType 关联真实返回契约。包装器实际透传，类型也应跟随来源；不必要求未使用的 reset。','端口从 Parser 派生。｜返回从 parse 的函数类型提取。｜通过 parser.parse 调用以保留 this。',{supportFiles:{'parser.ts':'export interface Parser{parse(text:string):string|null;reset():void}'},runtime:[run('透传结果并保留接收者','const {runParser}=load("main.js");const parser={prefix:"x",parse(text){check(this===parser);return text?this.prefix+text:null;}};equal(runParser(parser,"a"),"xa");equal(runParser(parser,""),null);')]}),
];
