import { mc, task, ok, bad } from './author.mjs';
const id=n=>`t13-l${String(n).padStart(2,'0')}`;
const m=(l,n,title,prompt,options,explanation,hints,extra={})=>mc(id(l),n,title,prompt,options,explanation,hints.split('｜'),extra);
const t=(l,n,title,prompt,files,solution,tests,explanation,hints,extra={})=>task(id(l),n,title,prompt,files,solution,tests,explanation,hints.split('｜'),{...(l<=2?{runtimeEnvironment:'dom'}:{}),...extra});
const productParser=`export type Product={id:number;title:string;price:number;tags:readonly string[]};
export type ParseResult={ok:true;value:Product}|{ok:false;issues:string[]};
function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==="object"&&value!==null&&!Array.isArray(value);}
export function parseProduct(raw:unknown):ParseResult{
 if(!isRecord(raw))return {ok:false,issues:["object"]};
 const id=typeof raw.id==="number"&&Number.isSafeInteger(raw.id)&&raw.id>0?raw.id:undefined;
 const title=typeof raw.title==="string"&&raw.title.trim()!==""?raw.title.trim():undefined;
 const price=typeof raw.price==="number"&&Number.isFinite(raw.price)&&raw.price>=0?raw.price:undefined;
 const tags=Array.isArray(raw.tags)&&raw.tags.every((tag:unknown)=>typeof tag==="string"&&tag.trim()!=="")?raw.tags.map((tag:string)=>tag.trim()):undefined;
 const issues:string[]=[];
 if(id===undefined)issues.push("id");if(title===undefined)issues.push("title");if(price===undefined)issues.push("price");if(tags===undefined)issues.push("tags");
 if(id===undefined||title===undefined||price===undefined||tags===undefined)return {ok:false,issues};
 return {ok:true,value:{id,title,price,tags}};
}`;
export const questions=[
 m(1,1,'查询结果的两个不确定性','querySelector(".field") 返回后直接访问 value，通常需要先解决什么？',['是否找到元素，以及它是否确实是具有所需能力的元素类型','只要选择器看起来像表单就一定安全','只需要把返回值断言为 input','DOM lib 会在运行时自动验证类型'],'选择器字符串不一定证明实际标签种类，查询也可能没有匹配。需要真实检查存在性和元素类型。','可能没有匹配。｜匹配也可能是 div。｜检查真实对象类型。'),
 m(1,2,'非空断言会做什么','把 querySelector 的结果写成 el!，能否保证页面一定存在该元素？',['不能，它不会增加运行时存在性检查','能，编译器会创建元素','能，查询会自动重试到成功','不能，因为它会删除页面元素'],'非空断言只是改变静态检查对表达式的理解。页面结构变化或查询时机错误仍可能导致空值。','断言是否产生运行代码？｜页面可能变化。｜需要明确缺失时的行为。'),
 m(1,3,'泛型查询的承诺','querySelector<HTMLInputElement>(".field") 是否自动拒绝实际匹配到的 div？',['不会，泛型参数不能代替对实际元素的运行验证','会，浏览器读取 TypeScript 泛型','会，自动把 div 转换为 input','会，没有输入框就抛编译错误'],'显式泛型提供静态类型信息，不会修改 DOM 查询的实际结果。无法保证标签时应使用运行检查。','泛型是否保留到 JavaScript？｜选择器可以匹配多个标签种类。｜用实际类型守卫验证。'),
 t(1,4,'修复可能不存在的文本节点','实现 readText(root:ParentNode,selector:string):string|null。返回首个匹配元素的 textContent；没有匹配返回 null，空文本必须保留为空字符串。选择器保证合法，不修改 DOM。',
 'export function readText(root:ParentNode,selector:string):string|null{return root.querySelector(selector).textContent;}',
 'export function readText(root:ParentNode,selector:string):string|null{const element=root.querySelector(selector);return element===null?null:element.textContent;}',[
 ok('调用者处理缺失','import {readText} from "./main";const value:string|null=readText(document,".label");'),
 bad('不能假定永远有文本','import {readText} from "./main";const value:string=readText(document,".label");'),
 ],'查询结果可能为 null，真实分支处理让类型和行为同时安全。不能用 || null 把合法空文本错误地变成缺失。','先保存查询结果。｜没有匹配时单独返回 null。｜空字符串与缺失不同。',{runtime:[{name:'缺失、空文本及限定查询范围',code:'const {readText}=load("main.js");document.body.innerHTML="<div class=label>outside</div><section><span class=label></span><b>hello</b></section>";const root=document.querySelector("section");equal(readText(root,".missing"),null);equal(readText(root,".label"),"");equal(readText(root,"b"),"hello");equal(readText(document,".label"),"outside");'}]}),
 m(1,5,'类型守卫与元素属性','为什么先判断 element instanceof HTMLInputElement 比检查一个任意对象上是否存在 value 更符合“只接收输入框”的要求？',['它验证实际元素类别，textarea 等有 value 的对象仍不符合输入框要求','它会自动提交表单','它能绕过所有空值检查','它能证明输入文本一定合法'],'能力检查和类别要求需要区分。输入框类别正确后，其值的业务合法性仍需要另外验证。','textarea 也有 value。｜题目是否要求某种具体元素？｜类型正确不等于值有效。'),
 t(1,6,'安全读取真正的输入框','实现 readInput(root:ParentNode,selector:string):string|undefined。只有首个匹配元素是 HTMLInputElement 才返回当前 value；缺失或其他标签返回 undefined。保留空串和空格，不修改元素。',
 'export function readInput(root:ParentNode,selector:string):string|undefined{return root.querySelector(selector).value;}',
 'export function readInput(root:ParentNode,selector:string):string|undefined{const element=root.querySelector(selector);return element instanceof HTMLInputElement?element.value:undefined;}',[
 ok('公开缺失契约','import {readInput} from "./main";const value:string|undefined=readInput(document,".field");'),
 bad('调用者不能忽略缺失','import {readInput} from "./main";const value:string=readInput(document,".field");'),
 ],'instanceof 同时排除 null 和其他元素类型。返回当前 value 而不是最初的 value 属性，才能反映用户输入后的状态。','不能凭类名假定标签。｜使用 HTMLInputElement 守卫。｜读取属性 value 的当前值。',{runtime:[{name:'真实类别与当前输入值',code:'const {readInput}=load("main.js");document.body.innerHTML="<input id=a value=initial><textarea id=b>text</textarea><div id=c></div>";const input=document.querySelector("#a");input.value=" changed ";equal(readInput(document,"#a")," changed ");input.value="";equal(readInput(document,"#a"),"");equal(readInput(document,"#b"),undefined);equal(readInput(document,"#c"),undefined);equal(readInput(document,"#missing"),undefined);'}]}),
 m(1,7,'首次找到之后是否永远存在','某次查询成功后，另一次重新查询仍返回可空类型，为什么合理？',['DOM 可能变化，每次查询都是新的结果，需要按当前结果处理','TypeScript 忘记了所有变量','只要查询过一次所有后续查询都应非空','因为浏览器不支持稳定选择器'],'保存的元素引用和新的查询结果不同。移除节点后，旧引用仍可能存在，但新查询可能找不到它。','查询之间可能发生什么？｜旧引用不等于新结果。｜按当前操作所需证据处理。'),
 t(1,8,'迁移：只更新真正的按钮','实现 setButtonText(root:ParentNode,selector:string,text:string):boolean。仅当首个匹配元素是 HTMLButtonElement 时更新 textContent 并返回 true；其他情况返回 false，DOM 保持原样。不要把文本作为 HTML 插入。',
 'export function setButtonText(root:ParentNode,selector:string,text:string):boolean{const element=root.querySelector(selector);element.textContent=text;return true;}',
 'export function setButtonText(root:ParentNode,selector:string,text:string):boolean{const element=root.querySelector(selector);if(!(element instanceof HTMLButtonElement))return false;element.textContent=text;return true;}',[
 ok('明确成功状态','import {setButtonText} from "./main";const changed:boolean=setButtonText(document,"button","Save");'),
 bad('文本参数有类型约束','import {setButtonText} from "./main";setButtonText(document,"button",3);'),
 ],'先验证类别再修改，失败分支不产生副作用。textContent 表达纯文本需求，innerHTML 会把用户文本解释为标记，不满足本题要求。','查询为空也要返回 false。｜只允许按钮类别。｜使用 textContent 保留纯文本语义。',{runtime:[{name:'精确修改与文本语义',code:'const {setButtonText}=load("main.js");document.body.innerHTML="<button id=a>old</button><div id=b>keep</div><input id=c type=button value=keep>";equal(setButtonText(document,"#missing","x"),false);equal(setButtonText(document,"#b","x"),false);equal(document.querySelector("#b").textContent,"keep");equal(setButtonText(document,"#c","x"),false);equal(setButtonText(document,"#a","<b>Save</b>"),true);equal(document.querySelector("#a").textContent,"<b>Save</b>");equal(document.querySelector("#a b"),null);'}]}),
 m(1,9,'复测：输入框类型不是数据校验','确认元素是 HTMLInputElement 后，Number(element.value) 是否一定得到业务上可接受的数字？',['不一定，空串、非法文本、无限值等仍需按需求处理','一定，输入框只允许数值','一定，类型检查会验证用户输入','不一定，但加 number 断言即可修复'],'DOM 类型约束属性接口，不保证输入内容符合业务要求。应明确空白、格式和数值范围的策略。','value 的静态类型是什么？｜Number 对空串如何处理？｜类别验证后还要验证数据。'),
 t(1,10,'复测：从输入框取得有限数字','实现 readFinite(root:ParentNode,selector:string):number|undefined。首个匹配必须是 input；其 value 去除首尾空格后非空，且 Number 转换结果有限才返回数字，否则 undefined。允许 0、负数和小数，不修改输入。',
 'export function readFinite(root:ParentNode,selector:string):number|undefined{return 0;}',
 'export function readFinite(root:ParentNode,selector:string):number|undefined{const element=root.querySelector(selector);if(!(element instanceof HTMLInputElement))return undefined;const text=element.value.trim();if(text==="")return undefined;const value=Number(text);return Number.isFinite(value)?value:undefined;}',[
 ok('有限数字或缺失','import {readFinite} from "./main";const value:number|undefined=readFinite(document,"input");'),
 bad('不能假定所有输入都有效','import {readFinite} from "./main";const value:number=readFinite(document,"input");'),
 ],'此题组合元素类别、空白判断和数值有效性。不能把 0 当作失败，也不能用 parseFloat 接受 12x 这样的不完整数字文本。','先确认真实输入框。｜空白不能按 0 处理。｜完整 Number 转换后检查有限性。',{runtime:[{name:'类别与数值边界',code:'const {readFinite}=load("main.js");document.body.innerHTML="<input id=a><textarea id=b>3</textarea>";const input=document.querySelector("#a");for(const [text,expected] of [["0",0],[" -2.5 ",-2.5],["12",12],["",undefined],["  ",undefined],["12x",undefined],["Infinity",undefined],["NaN",undefined]]){input.value=text;equal(readFinite(document,"#a"),expected);equal(input.value,text);}equal(readFinite(document,"#b"),undefined);equal(readFinite(document,"#missing"),undefined);'}]}),
 m(2,1,'target 与 currentTarget','在 form 上监听冒泡的 input 事件，用户编辑其中的 input，回调执行时两者通常分别是什么？',['target 是触发事件的 input，currentTarget 是当前监听的 form','两者一定都是 form','target 是 form，currentTarget 是 input','两者一定都是 input'],'事件来源与当前执行监听器的位置不同。事件委托通常检查 target；已知直接绑定元素时也可以使用闭包中的明确引用。','谁触发事件？｜监听器绑定在哪里？｜区分来源与监听位置。'),
 m(2,2,'为什么 EventTarget 没有 value','回调参数为 Event 时，event.target 不能直接读取 value 的主要原因是什么？',['目标可能为空，也可能是其他 EventTarget，需要验证实际类别','所有事件目标都没有 value','只要事件名是 input，TypeScript 就一定推断出 HTMLInputElement','只需检查事件是否冒泡便能证明目标类型'],'事件名称本身不足以证明所有触发者的具体元素类别。可用实际元素检查，或在直接绑定场景使用已验证的元素引用。','EventTarget 是较宽的接口。｜空值与元素类别都要处理。｜选择真实守卫或明确引用。'),
 m(2,3,'取消提交与停止传播','希望接管可取消的 submit 事件、阻止默认提交，同时仍允许其他监听器观察事件，应该怎么做？',['调用 preventDefault，不因这个需求额外调用 stopPropagation','只调用 stopPropagation 即可阻止默认提交','返回 false 总能阻止 addEventListener 的默认行为','只能同时取消默认行为和事件传播'],'默认行为和传播是两个维度。addEventListener 回调返回 false 不等于取消默认行为；事件还必须支持取消。','需求是默认行为还是传播？｜使用对应 API。｜注意事件的 cancelable 属性。'),
 t(2,4,'读取事件中的真实输入值','实现 inputValue(event:Event):string|undefined。仅当 event.target 是 HTMLInputElement 时返回其当前 value；尚未派发的事件、其他标签均返回 undefined。不能断言目标必然为 input。',
 'export function inputValue(event:Event):string|undefined{return event.target.value;}',
 'export function inputValue(event:Event):string|undefined{const target=event.target;return target instanceof HTMLInputElement?target.value:undefined;}',[
 ok('返回可能缺失','import {inputValue} from "./main";const value:string|undefined=inputValue(new Event("input"));'),
 bad('不能忽略目标缺失','import {inputValue} from "./main";const value:string=inputValue(new Event("input"));'),
 ],'对 EventTarget 做真实类别检查，才能在类型和运行行为上安全读取 value。空目标不能依靠非空断言解决。','先取出 target。｜使用输入框类别守卫。｜未派发事件也必须安全处理。',{runtime:[{name:'空目标与冒泡目标类别',code:'const {inputValue}=load("main.js");equal(inputValue(new Event("input")),undefined);document.body.innerHTML="<section><input><textarea></textarea></section>";const root=document.querySelector("section"),input=root.querySelector("input"),textarea=root.querySelector("textarea");const values=[];root.addEventListener("input",event=>values.push(inputValue(event)));input.value=" now ";input.dispatchEvent(new Event("input",{bubbles:true}));input.value="";input.dispatchEvent(new Event("input",{bubbles:true}));textarea.dispatchEvent(new Event("input",{bubbles:true}));root.dispatchEvent(new Event("input"));equal(values,[" now ","",undefined,undefined]);'}]}),
 m(2,5,'移除监听器为什么没生效','注册时传入 ()=>save()，清理时又传入另一个 ()=>save()，为什么通常移除不了？',['两个箭头函数是不同函数对象，清理需要匹配注册时的回调及 capture 设置','removeEventListener 只能移除具名函数','所有箭头函数都不能被移除','移除监听器必须先派发一次事件'],'内容相同不代表函数引用相同。保留注册用的函数引用，并保持 capture 匹配，才能准确移除对应监听器。','比较函数对象而非函数文本。｜保存 handler 引用。｜清理选项也需要匹配。'),
 t(2,6,'设计可清理的输入监听','实现 watchInput(input:HTMLInputElement,onValue:(value:string)=>void):()=>void。每次 input 事件恰好回调一次当前 value，不在绑定时回调；返回清理函数，只移除本次绑定，重复清理安全。',
 'export function watchInput(input:HTMLInputElement,onValue:(value:string)=>void):()=>void{input.addEventListener("input",()=>onValue(input.value));return ()=>{};}',
 'export function watchInput(input:HTMLInputElement,onValue:(value:string)=>void):()=>void{const handler=()=>onValue(input.value);input.addEventListener("input",handler);return ()=>input.removeEventListener("input",handler);}',[
 ok('清理函数与值契约','import {watchInput} from "./main";const cleanup:()=>void=watchInput(document.createElement("input"),(value:string)=>{});'),
 bad('不能绑定无 value 的元素','import {watchInput} from "./main";watchInput(document.createElement("div"),()=>{});'),
 ],'直接绑定已知输入框时，闭包中的元素引用比断言事件目标更简单。保存 handler 以便只移除当前订阅，不能清掉其他订阅者。','为当前绑定创建独立 handler。｜回调执行时读取当前 value。｜返回使用同一 handler 的清理函数。',{runtime:[{name:'独立订阅、当前值与重复清理',code:'const {watchInput}=load("main.js");const input=document.createElement("input"),a=[],b=[];const offA=watchInput(input,v=>a.push(v));const offB=watchInput(input,v=>b.push(v));equal(a,[]);equal(b,[]);input.value="first";input.dispatchEvent(new Event("input"));offA();offA();input.value="";input.dispatchEvent(new Event("input"));equal(a,["first"]);equal(b,["first",""]);offB();input.value="last";input.dispatchEvent(new Event("input"));equal(b,["first",""]);'}]}),
 m(2,7,'异步回调里的 currentTarget','监听器执行时要在稍后的异步逻辑继续操作绑定元素，更稳妥的方式是什么？',['在同步回调期间取得并验证元素引用，或使用明确绑定的闭包引用','总是在 await 后重新读取 event.currentTarget 并非空断言','用 event.target 替代 currentTarget 就必然是同一个元素','把 Event 类型改成 MouseEvent 就能延长 currentTarget 生命周期'],'currentTarget 与当前事件派发过程有关。需要异步使用时，应保存确切元素引用，不把稍后读取事件属性当作同等证据。','异步执行时派发可能已结束。｜保存需要的对象引用。｜来源元素和绑定元素仍需区分。'),
 t(2,8,'迁移：接管表单提交','实现 bindTitleForm(form:HTMLFormElement,onTitle:(title:string)=>void):()=>void。每次 submit 先 preventDefault；查询本表单内 input[name=title]，仅在真实输入框当前值 trim 后非空时回调一次。返回清理函数，不停止传播，不修改输入。',
 'export function bindTitleForm(form:HTMLFormElement,onTitle:(title:string)=>void):()=>void{const handler=(event:Event)=>{};form.addEventListener("submit",handler);return ()=>form.removeEventListener("submit",handler);}',
 'export function bindTitleForm(form:HTMLFormElement,onTitle:(title:string)=>void):()=>void{const handler=(event:Event)=>{event.preventDefault();const input=form.querySelector("input[name=title]");if(!(input instanceof HTMLInputElement))return;const title=input.value.trim();if(title!=="")onTitle(title);};form.addEventListener("submit",handler);return ()=>form.removeEventListener("submit",handler);}',[
 ok('表单绑定契约','import {bindTitleForm} from "./main";const cleanup:()=>void=bindTitleForm(document.createElement("form"),(title:string)=>{});'),
 bad('回调不能要求数值标题','import {bindTitleForm} from "./main";bindTitleForm(document.createElement("form"),(title:number)=>{});'),
 ],'先阻止默认提交，再验证表单数据。清理后不再取消事件或调用业务回调；本题派发合成事件验证逻辑，不执行浏览器页面导航。','preventDefault 应对每次绑定期间的 submit 执行。｜查询限制在当前表单内部。｜只传递非空的修剪后文本。',{runtime:[{name:'取消默认行为、传播与清理',code:'const {bindTitleForm}=load("main.js");document.body.innerHTML="<input name=title value=outside><section><form><input name=title></form></section>";const form=document.querySelector("form"),input=form.querySelector("input"),titles=[];let bubbled=0;document.querySelector("section").addEventListener("submit",()=>bubbled++);const off=bindTitleForm(form,title=>titles.push(title));input.value="  task  ";const first=new Event("submit",{bubbles:true,cancelable:true});form.dispatchEvent(first);equal(first.defaultPrevented,true);equal(titles,["task"]);equal(input.value,"  task  ");input.value=" ";const blank=new Event("submit",{bubbles:true,cancelable:true});form.dispatchEvent(blank);equal(blank.defaultPrevented,true);equal(titles,["task"]);input.remove();const missing=new Event("submit",{bubbles:true,cancelable:true});form.dispatchEvent(missing);equal(missing.defaultPrevented,true);equal(bubbled,3);off();off();const last=new Event("submit",{bubbles:true,cancelable:true});form.dispatchEvent(last);equal(last.defaultPrevented,false);equal(titles,["task"]);'}]}),
 m(2,9,'复测：事件委托与动态元素','列表容器会不断新增输入框，希望统一处理其冒泡 input 事件，应如何设计？',['在容器监听并验证 event.target，避免只绑定初始化时查询到的输入框','仅给初始 NodeList 绑定，后来新增元素会自动继承监听器','把容器断言为 HTMLInputElement 后读取 value','每次事件都给所有元素再添加一个监听器'],'容器监听可以接收后加入后代的冒泡事件，但仍需检查目标类型与业务标记。重复添加监听器可能造成重复回调。','新增元素是否存在于初始查询结果？｜事件能否冒泡到稳定容器？｜每次检查实际触发目标。'),
 t(2,10,'复测：动态输入事件委托','实现 delegateFields(root:HTMLElement,onValue:(field:string,value:string)=>void):()=>void。在 root 监听 input；仅处理真实 HTMLInputElement 且 data-field 是非空字符串的目标，原样传递标记与当前 value。支持绑定后新增的输入框，清理后不再回调。',
 'export function delegateFields(root:HTMLElement,onValue:(field:string,value:string)=>void):()=>void{return ()=>{};}',
 'export function delegateFields(root:HTMLElement,onValue:(field:string,value:string)=>void):()=>void{const handler=(event:Event)=>{const input=event.target;if(!(input instanceof HTMLInputElement))return;const field=input.getAttribute("data-field");if(field===null||field==="")return;onValue(field,input.value);};root.addEventListener("input",handler);return ()=>root.removeEventListener("input",handler);}',[
 ok('委托接口','import {delegateFields} from "./main";const cleanup:()=>void=delegateFields(document.body,(field:string,value:string)=>{});'),
 bad('字段值仍是文本','import {delegateFields} from "./main";delegateFields(document.body,(field:string,value:number)=>{});'),
 ],'把监听器放在稳定容器，通过目标守卫处理动态后代。不能使用容器的属性代替触发输入框，也不能只扫描绑定时已有元素。','监听容器的冒泡事件。｜验证目标是输入框且标记非空。｜保留 handler 供清理。',{runtime:[{name:'动态后代、过滤和清理',code:'const {delegateFields}=load("main.js");document.body.innerHTML="<section></section>";const root=document.querySelector("section"),values=[];const off=delegateFields(root,(field,value)=>values.push([field,value]));root.innerHTML="<input data-field=title><textarea data-field=note></textarea><input data-field><input>";const inputs=root.querySelectorAll("input");inputs[0].value="new";inputs[0].dispatchEvent(new Event("input",{bubbles:true}));inputs[0].value="";inputs[0].dispatchEvent(new Event("input",{bubbles:true}));root.querySelector("textarea").dispatchEvent(new Event("input",{bubbles:true}));inputs[1].dispatchEvent(new Event("input",{bubbles:true}));inputs[2].dispatchEvent(new Event("input",{bubbles:true}));root.dispatchEvent(new Event("input"));equal(values,[["title","new"],["title",""]]);off();off();inputs[0].dispatchEvent(new Event("input",{bubbles:true}));equal(values.length,2);'}]}),

 m(3,1,'fetch 完成与 HTTP 成功','请求 Promise 已兑现，但响应状态为 404，应该如何理解？',['已收到响应，不代表 HTTP 成功，应检查 ok 或具体状态','Promise 兑现说明状态一定是 2xx','404 必然让 fetch 的 Promise 拒绝','只要响应能解析为 JSON 就应视为成功'],'请求完成、HTTP 状态符合要求和响应数据有效是不同层次。业务逻辑需要分别处理，而不是只依赖 Promise 是否兑现。','是否收到响应是一层。｜HTTP 状态是另一层。｜最后才是内容是否可信。'),
 m(3,2,'返回类型不是远端校验','把获取 JSON 的函数标注为 Promise<User>，但实现没有检查字段，问题是什么？',['类型承诺缺少运行时证据，服务端返回错误结构时仍可能被当作 User','TypeScript 会自动发送 User 的字段校验规则','浏览器会根据返回标注过滤 JSON','只要接口 URL 固定，返回结构就不可能变化'],'外部数据不由本地类型系统控制。应在边界接为 unknown 并通过真实校验建立可信类型。','标注会被服务端读取吗？｜运行输入可能与预期不同。｜承诺需要验证支持。'),
 m(3,3,'JSON 解析失败属于哪一层','响应为 200，但 json() 因内容不是合法 JSON 而拒绝，这能说明什么？',['HTTP 成功，但响应解码失败，仍不能取得业务数据','网络连接一定从未建立','响应状态一定被浏览器改成 500','这是编译时类型错误，不会发生在运行时'],'HTTP 层成功不能保证内容可解码。解码成功之后还要验证业务结构和约束。','状态和正文格式各自独立。｜json() 也返回 Promise。｜解码与结构校验分开考虑。'),
 t(3,4,'先检查 HTTP 再读取正文','实现 readJson(request:Request,url:string):Promise<unknown>。Request 类型由只读 transport.ts 提供，代表注入的请求函数。仅调用一次；ok 为 false 时抛 Error 且不调用 json；成功返回 json 的结果。请求或解析拒绝原样传播。测试不访问真实网络。',
 'import type {Request} from "./transport";export async function readJson(request:Request,url:string):Promise<unknown>{const response=await request(url);return response.json();}',
 'import type {Request} from "./transport";export async function readJson(request:Request,url:string):Promise<unknown>{const response=await request(url);if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json();}',[
 ok('未知数据边界','import {readJson} from "./main";import type {Request} from "./transport";declare const request:Request;const value:Promise<unknown>=readJson(request,"/api");'),
 bad('不能直接承诺业务结构','import {readJson} from "./main";import type {Request} from "./transport";declare const request:Request;const value:Promise<{id:number}>=readJson(request,"/api");'),
 ],'先确认 HTTP 状态，再调用响应方法读取正文。unknown 保留外部数据的不确定性，调用者必须进一步验证。','先等待响应。｜失败状态不能进入 json。｜保持网络和解析拒绝的原始对象。',{runtimeEnvironment:undefined,supportFiles:{'transport.ts':'export interface Reply{ok:boolean;status:number;json():Promise<unknown>}export type Request=(url:string)=>Promise<Reply>;'},runtime:[{name:'请求参数、HTTP 失败及正文调用次数',code:'const {readJson}=load("main.js");let urls=[],calls=0;equal(await readJson(async url=>{urls.push(url);return {ok:true,status:200,json:async()=>{calls++;return {id:1};}};},"/users"),{id:1});equal(urls,["/users"]);equal(calls,1);let error;try{await readJson(async()=>({ok:false,status:404,json:async()=>{calls++;return {};}}),"/missing");}catch(e){error=e;}check(error&&error.name==="Error");equal(calls,1);'},{name:'拒绝保持来源',code:'const {readJson}=load("main.js");const network={kind:"network"},decode={kind:"decode"};for(const [request,failure] of [[async()=>{throw network;},network],[async()=>({ok:true,status:200,json:async()=>{throw decode;}}),decode]]){let caught;try{await readJson(request,"/api");}catch(e){caught=e;}check(caught===failure);}'}]}),
 m(3,5,'unknown 进入对象检查','验证远端对象时，为什么 typeof value === "object" 之后通常还要处理 null？',['JavaScript 中 typeof null 也是 object，直接访问字段仍可能失败','null 自动拥有所有可选字段','unknown 会自动排除 null','只有数组需要排除 null'],'真实守卫必须符合 JavaScript 运行行为。对象、null、数组和具体字段还需按目标契约分别处理。','typeof null 的结果是什么？｜字段读取需要真实对象。｜按需求继续校验属性。'),
 t(3,6,'为 User 承诺提供证据','实现 loadUser(request:Request,url:string):Promise<User>。User={id:number;name:string}；HTTP 失败、结构不合法都抛 Error。JSON 必须是非 null 非数组对象，id 是正安全整数，name 是 trim 后非空字符串。返回只含 id 与修剪后 name 的新对象。',
 'import type {Request} from "./transport";export interface User{id:number;name:string}export async function loadUser(request:Request,url:string):Promise<User>{const response=await request(url);return {id:1,name:"guest"};}',
 'import type {Request} from "./transport";export interface User{id:number;name:string}export async function loadUser(request:Request,url:string):Promise<User>{const response=await request(url);if(!response.ok)throw new Error("HTTP failure");const value:unknown=await response.json();if(typeof value!=="object"||value===null||Array.isArray(value)||!("id" in value)||typeof value.id!=="number"||!Number.isSafeInteger(value.id)||value.id<=0||!("name" in value)||typeof value.name!=="string"||value.name.trim()==="")throw new Error("Invalid user");return {id:value.id,name:value.name.trim()};}',[
 ok('验证后的公开契约','import {loadUser} from "./main";import type {User} from "./main";import type {Request} from "./transport";declare const request:Request;const user:Promise<User>=loadUser(request,"/user");'),
 bad('公开模型不接受文本 id','import type {User} from "./main";const user:User={id:"1",name:"A"};'),
 ],'Promise<User> 的可信度来自实际验证。重新构造公开对象还能避免把额外字段直接传播到应用中，且不修改响应对象。','外部值先保持 unknown。｜逐项检查对象和业务范围。｜只投影公开字段。',{runtimeEnvironment:undefined,supportFiles:{'transport.ts':'export interface Reply{ok:boolean;status:number;json():Promise<unknown>}export type Request=(url:string)=>Promise<Reply>;'},runtime:[{name:'验证、投影且不修改输入',code:'const {loadUser}=load("main.js");const input=Object.freeze({id:7,name:"  Ada  ",secret:"hidden"});let urls=[];const user=await loadUser(async url=>{urls.push(url);return {ok:true,status:200,json:async()=>input};},"/user/7");equal(user,{id:7,name:"Ada"});check(user!==input);equal(input.name,"  Ada  ");equal(urls,["/user/7"]);'},{name:'拒绝结构和业务脏数据',code:'const {loadUser}=load("main.js");for(const input of [null,[],"x",{}, {id:0,name:"a"},{id:1.5,name:"a"},{id:Infinity,name:"a"},{id:Number.MAX_SAFE_INTEGER+1,name:"a"},{id:1,name:" "},{id:1,name:3},{id:"1",name:"a"}]){let caught;try{await loadUser(async()=>({ok:true,status:200,json:async()=>input}),"/user");}catch(e){caught=e;}check(caught&&caught.name==="Error");}let calls=0,caught;try{await loadUser(async()=>({ok:false,status:500,json:async()=>{calls++;return {id:1,name:"a"};}}),"/user");}catch(e){caught=e;}check(caught);equal(calls,0);'}]}),
 m(3,7,'一个 catch 的分类风险','把请求、HTTP 检查、JSON 解析和结构验证都包在同一个 catch 中，并一律显示“网络断开”，主要问题是什么？',['会把不同阶段的失败误归类，应按失败阶段保留可用信息','这样能证明所有失败都来自网络','这样会让 HTTP 错误自动恢复','只要 catch 接受 unknown 就一定分类正确'],'错误变量的类型安全和错误分类的正确性是两件事。可以统一兜底，但不要向用户或日志提供错误的原因判断。','catch 覆盖了哪些步骤？｜其中是否都属于传输失败？｜分阶段构建错误结果。'),
 t(3,8,'迁移：区分失败阶段','实现 loadTitle(request:Request,url:string):Promise<Result>。Result 为只读 types.ts 提供的联合：成功含 title；请求拒绝为 network，HTTP 非成功为 http，JSON 拒绝或不是 trim 后非空字符串为 data。成功返回修剪文本，HTTP 失败不读取正文。',
 'import type {Request,Result} from "./types";export async function loadTitle(request:Request,url:string):Promise<Result>{return {ok:false,kind:"network"};}',
 'import type {Request,Result} from "./types";export async function loadTitle(request:Request,url:string):Promise<Result>{let response;try{response=await request(url);}catch{return {ok:false,kind:"network"};}if(!response.ok)return {ok:false,kind:"http"};let value:unknown;try{value=await response.json();}catch{return {ok:false,kind:"data"};}if(typeof value!=="string"||value.trim()==="")return {ok:false,kind:"data"};return {ok:true,title:value.trim()};}',[
 ok('成功分支具有标题','import {loadTitle} from "./main";import type {Request} from "./types";declare const request:Request;async function use(){const result=await loadTitle(request,"/title");if(result.ok){const title:string=result.title;}}'),
 bad('失败分支不能直接读标题','import type {Result} from "./types";declare const result:Result;const title:string=result.title;'),
 ],'将请求、HTTP 状态和正文处理分成清晰阶段，才能返回真实失败类别。结果联合要求调用者先分支判断再访问成功数据。','只把 request 拒绝归为 network。｜状态失败提前返回 http。｜解码与内容不合法统一为 data。',{runtimeEnvironment:undefined,supportFiles:{'types.ts':'export interface Reply{ok:boolean;status:number;json():Promise<unknown>}export type Request=(url:string)=>Promise<Reply>;export type Result={ok:true;title:string}|{ok:false;kind:"network"|"http"|"data"};'},runtime:[{name:'四种路径不混淆',code:'const {loadTitle}=load("main.js");equal(await loadTitle(async()=>{throw Error("offline");},"/title"),{ok:false,kind:"network"});let calls=0;equal(await loadTitle(async()=>({ok:false,status:503,json:async()=>{calls++;return "x";}}),"/title"),{ok:false,kind:"http"});equal(calls,0);equal(await loadTitle(async()=>({ok:true,status:200,json:async()=>{throw Error("bad json");}}),"/title"),{ok:false,kind:"data"});for(const value of [null,3,{},"","  "]){equal(await loadTitle(async()=>({ok:true,status:200,json:async()=>value}),"/title"),{ok:false,kind:"data"});}let url;equal(await loadTitle(async value=>{url=value;return {ok:true,status:200,json:async()=>"  title  "};},"/title"),{ok:true,title:"title"});equal(url,"/title");'}]}),
 m(3,9,'复测：204 与 JSON','接口明确用 204 表示无内容，客户端仍无条件调用 json()，可能发生什么？',['因为没有可解析正文而失败，应按接口协议处理无内容状态','204 会自动提供一个空对象','json() 在 204 下必然返回 null','TypeScript 会自动省略这次方法调用'],'客户端要遵守具体协议，不能假定每个成功响应都有 JSON。无内容与内容为 null 也不是同一件事。','没有正文与正文是 null 有何区别？｜先按状态决定是否读取。｜用结果模型保留差异。'),
 t(3,10,'复测：显式处理无内容响应','实现 loadOptional(request:Request,url:string):Promise<Result>。HTTP 非成功抛 Error；成功且 status=204 返回 {kind:"empty"} 并不读 json；其他成功响应解析后返回 {kind:"value",value}，包括 value 为 null。类型由只读 types.ts 提供。',
 'import type {Request,Result} from "./types";export async function loadOptional(request:Request,url:string):Promise<Result>{const response=await request(url);return {kind:"value",value:await response.json()};}',
 'import type {Request,Result} from "./types";export async function loadOptional(request:Request,url:string):Promise<Result>{const response=await request(url);if(!response.ok)throw new Error("HTTP failure");if(response.status===204)return {kind:"empty"};return {kind:"value",value:await response.json()};}',[
 ok('区分内容分支','import {loadOptional} from "./main";import type {Request} from "./types";declare const request:Request;async function use(){const result=await loadOptional(request,"/item");if(result.kind==="value"){const value:unknown=result.value;}}'),
 bad('无内容分支没有 value','import type {Result} from "./types";declare const result:Result;if(result.kind==="empty"){const value=result.value;}'),
 ],'先处理 HTTP 状态，再按接口协议判断是否有正文。unknown 内容与无内容用不同分支表示，避免把有效 JSON null 当作缺失。','204 分支应在 json 前返回。｜其他成功状态才读取正文。｜保留内容为 null 的 value 分支。',{runtimeEnvironment:undefined,supportFiles:{'types.ts':'export interface Reply{ok:boolean;status:number;json():Promise<unknown>}export type Request=(url:string)=>Promise<Reply>;export type Result={kind:"empty"}|{kind:"value";value:unknown};'},runtime:[{name:'无内容不读正文，null 仍为内容',code:'const {loadOptional}=load("main.js");let calls=0;equal(await loadOptional(async()=>({ok:true,status:204,json:async()=>{calls++;throw Error("empty");}}),"/item"),{kind:"empty"});equal(calls,0);equal(await loadOptional(async()=>({ok:true,status:200,json:async()=>{calls++;return null;}}),"/item"),{kind:"value",value:null});equal(calls,1);let error;try{await loadOptional(async()=>({ok:false,status:404,json:async()=>{calls++;return {};}}),"/item");}catch(e){error=e;}check(error&&error.name==="Error");equal(calls,1);'},{name:'请求与解析拒绝不被吞掉',code:'const {loadOptional}=load("main.js");const failure={reason:"failed"};for(const request of [async()=>{throw failure;},async()=>({ok:true,status:200,json:async()=>{throw failure;}})]){let caught;try{await loadOptional(request,"/item");}catch(e){caught=e;}check(caught===failure);}'}]}),

 m(4,1,'外部 JSON 的类型边界','JSON.parse 的结果准备传入业务层，哪种处理更能保护业务类型？',['先作为 unknown，逐项验证后构造业务对象','直接把结果断言为业务接口','只判断 typeof value 是 object 即可','把返回类型标成接口会在运行时校验'],'静态类型无法约束远端或存储里的真实内容。进入业务层前需要运行校验，并明确失败如何表示。','输入来自程序外部。｜标注会产生验证代码吗？｜unknown 迫使检查。'),
 m(4,2,'对象判断的漏洞','typeof value === "object" 后立即读取字段，还漏了什么重要情况？',['null 也是 object，数组也是 object，均可能不符合目标记录结构','所有对象都没有属性','typeof 会自动把数组变成 null','只要对象有属性就证明全部字段合法'],'先排除不符合协议的整体形状，再检查每个字段和业务约束。','考虑 null。｜考虑数组。｜最后再看字段。'),
 m(4,3,'类型谓词能否替代逻辑','定义 function isUser(x:unknown):x is User，但函数总是返回 true，会发生什么？',['调用处会获得错误的静态信任，运行时脏数据仍在','TypeScript 会自动重写函数体','运行时自动检查接口每个字段','函数返回 true 但类型永远不能缩窄'],'类型谓词把证据责任交给实现者。谓词必须真实检验形状，否则只是制造不可靠的承诺。','返回类型是承诺。｜函数体是否提供证据？｜脏数据仍会进入业务。'),
 t(4,4,'验证记录对象边界','实现 isRecord(value:unknown):value is Record<string,unknown>。仅非 null 且非数组的对象返回 true；函数、原始值均返回 false。此题不校验记录的具体字段。',
 'export function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==="object";}',
 'export function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==="object"&&value!==null&&!Array.isArray(value);}',[
 ok('守卫后字段仍保持未知','import {isRecord} from "./main";declare const raw:unknown;if(isRecord(raw)){const id:unknown=raw.id;}'),
 bad('守卫不能凭空保证字段类型','import {isRecord} from "./main";declare const raw:unknown;if(isRecord(raw)){const id:number=raw.id;}'),
 ],'只证明整体是记录形状，不宣称字段已校验。null 和数组都需要显式排除；函数虽然可带属性，本题契约仍排除。','typeof null 的结果要单独处理。｜数组也符合 object。｜字段维持 unknown。',{runtimeEnvironment:undefined,runtime:[{name:'记录与非记录边界',code:'const {isRecord}=load("main.js");for(const value of [{},Object.freeze({id:1}),new Date(0),Object.create(null)])equal(isRecord(value),true);for(const value of [null,[],[1],()=>1,"x",0,false,undefined])equal(isRecord(value),false);'}]}),
 m(4,5,'规范化是否可以改变输入','解析函数把 title.trim() 后作为业务值，怎样避免修改共享的只读输入？',['验证后构造新对象，保留原输入及其原始字段','直接给原对象的 title 赋值','在类型上写 Readonly 就会自动阻止运行修改','把对象断言为另一个接口再修改'],'外部对象可能被其他代码共享或冻结。规范化应创建可信的输出，运行测试可验证输入不变。','原数据可能被冻结。｜类型只读不是运行时冻结。｜投影为新对象。'),
 t(4,6,'设计商品数据解析器','实现 parseProduct(raw:unknown):ParseResult。Product 有正安全整数 id、修剪后非空 title、有限且非负 price、每项修剪后非空的字符串 tags。对象不能为 null/数组；成功返回新对象，仅含公开四字段；失败返回字段名 issues，按 id/title/price/tags 顺序，整体形状错用 object。不可修改输入。',
 'export type Product={id:number;title:string;price:number;tags:readonly string[]};export type ParseResult={ok:true;value:Product}|{ok:false;issues:string[]};export function parseProduct(raw:unknown):ParseResult{return {ok:true,value:{id:1,title:"item",price:0,tags:[]}};}',
 productParser,[
 ok('分支后字段可信','import {parseProduct} from "./main";const result=parseProduct({});if(result.ok){const id:number=result.value.id;const tags:readonly string[]=result.value.tags;}'),
 bad('成功分支 id 不是文本','import {parseProduct} from "./main";const result=parseProduct({});if(result.ok){const id:string=result.value.id;}'),
 bad('失败分支没有可信商品','import {parseProduct} from "./main";const result=parseProduct({});if(!result.ok){const product=result.value;}'),
 ],'逐字段确认类型与业务范围，失败返回可定位的字段；成功投影为新对象。类型联合保证调用者先区分结果，再读取可信数据。','先验证整体记录。｜分别计算四个字段是否合格。｜收集问题后再构造新商品。',{runtimeEnvironment:undefined,runtime:[{name:'合法值被规范化且不修改输入',code:'const {parseProduct}=load("main.js");const raw=Object.freeze({id:7,title:"  Book  ",price:0,tags:Object.freeze([" a ","b"]),secret:"x"});const result=parseProduct(raw);check(result.ok);equal(result.value,{id:7,title:"Book",price:0,tags:["a","b"]});check(result.value!==raw);check(result.value.tags!==raw.tags);equal(raw.title,"  Book  ");'},{name:'全部字段错误按顺序报告',code:'const {parseProduct}=load("main.js");for(const raw of [null,[],"x"]){equal(parseProduct(raw),{ok:false,issues:["object"]});}const failures=[{raw:{},issues:["id","title","price","tags"]},{raw:{id:0,title:" ",price:-1,tags:[""]},issues:["id","title","price","tags"]},{raw:{id:1.5,title:"ok",price:Infinity,tags:["a"]},issues:["id","price"]},{raw:{id:1,title:"ok",price:1,tags:["a",3]},issues:["tags"]}];for(const item of failures)equal(parseProduct(item.raw),{ok:false,issues:item.issues});'}]}),
 m(4,7,'数组整体解析策略','要求批量导入“全部有效才接受”，有一条无效时应该如何设计返回值？',['返回失败并指出无效条目的位置，不暴露部分成功列表为完整数据','跳过错误条目后仍标记完整成功','把无效条目断言成合法类型','只验证数组第一条记录'],'全有或全无是明确的业务契约。解析器应积累或定位错误，而非悄悄丢弃或伪造记录。','批量接口承诺什么？｜有错误时可以产生完整成功吗？｜保留条目位置。'),
 t(4,8,'迁移：解析区分创建和删除事件','只读 types.ts 定义 EventData 为 created(id:string,title:string) 或 deleted(id:string,reason:string)。实现 parseEvent(raw:unknown):EventData|null。非数组记录且 type/id 合法，created 要非空 title，deleted 要非空 reason；字符串去首尾空格，输出新对象且只含对应字段，其他一律 null。',
 'import type {EventData} from "./types";export function parseEvent(raw:unknown):EventData|null{return null;}',
 'import type {EventData} from "./types";export function parseEvent(raw:unknown):EventData|null{if(typeof raw!=="object"||raw===null||Array.isArray(raw)||!("type" in raw)||!("id" in raw)||typeof raw.id!=="string"||raw.id.trim()==="")return null;const id=raw.id.trim();if(raw.type==="created"){if(!("title" in raw)||typeof raw.title!=="string"||raw.title.trim()==="")return null;return {type:"created",id,title:raw.title.trim()};}if(raw.type==="deleted"){if(!("reason" in raw)||typeof raw.reason!=="string"||raw.reason.trim()==="")return null;return {type:"deleted",id,reason:raw.reason.trim()};}return null;}',[
 ok('两类分支可分别读取','import {parseEvent} from "./main";const value=parseEvent({});if(value?.type==="created"){const title:string=value.title;}else if(value?.type==="deleted"){const reason:string=value.reason;}'),
 bad('删除分支没有创建标题','import type {EventData} from "./types";declare const event:EventData;if(event.type==="deleted"){const title=event.title;}'),
 ],'判别字段确定需要验证的载荷。只读联合描述目标契约，真正的解析逻辑负责建立证据；返回新对象防止额外字段泄露。','先处理整体形状和共同 id。｜type 决定 title 或 reason。｜未知 type 返回 null。',{runtimeEnvironment:undefined,supportFiles:{'types.ts':'export type EventData={type:"created";id:string;title:string}|{type:"deleted";id:string;reason:string};'},runtime:[{name:'两种事件规范化与字段白名单',code:'const {parseEvent}=load("main.js");const created=Object.freeze({type:"created",id:" a ",title:" New ",secret:1});equal(parseEvent(created),{type:"created",id:"a",title:"New"});equal(created.id," a ");equal(parseEvent({type:"deleted",id:"a",reason:"  stale ",title:"ignored"}),{type:"deleted",id:"a",reason:"stale"});'},{name:'拒绝分支错误和空值',code:'const {parseEvent}=load("main.js");for(const value of [null,[],{}, {type:"updated",id:"a"},{type:"created",id:"a"},{type:"deleted",id:"a"},{type:"created",id:" ",title:"x"},{type:"deleted",id:"a",reason:" "},{type:"created",id:1,title:"x"}])equal(parseEvent(value),null);'}]}),
 m(4,9,'复测：字段名称正确仍不够','一个对象有 id、price 等必需键，是否足以把它当作 Product？',['不足，还要检查字段类型、取值范围和数组成员','足够，键存在就是完整验证','足够，TS 会自动过滤非法取值','只要 JSON 能解析就足够'],'存在性只是验证的一层。业务约束可能包括整数边界、非负数、字符串内容和集合元素合法性。','键存在但值可能是什么？｜需要哪些业务范围？｜数组内部还需检查。'),
 t(4,10,'复测：批量导入全有或全无','只读 parser.ts 提供 parseProduct 和 Product。实现 parseProducts(raw:unknown):ImportResult：输入必须是数组；逐项解析，全部成功返回全新的 Product[]；存在错误则仅返回问题列表，格式为 index:field，按输入顺序与每项字段顺序；非数组返回 object。不得丢弃错误项或修改输入。',
 'import {parseProduct} from "./parser";import type {Product} from "./parser";export type ImportResult={ok:true;items:Product[]}|{ok:false;issues:string[]};export function parseProducts(raw:unknown):ImportResult{return {ok:true,items:[]};}',
 'import {parseProduct} from "./parser";import type {Product} from "./parser";export type ImportResult={ok:true;items:Product[]}|{ok:false;issues:string[]};export function parseProducts(raw:unknown):ImportResult{if(!Array.isArray(raw))return {ok:false,issues:["object"]};const items:Product[]=[],issues:string[]=[];raw.forEach((entry:unknown,index:number)=>{const result=parseProduct(entry);if(result.ok)items.push(result.value);else issues.push(...result.issues.map(field=>`${index}:${field}`));});return issues.length?{ok:false,issues}:{ok:true,items};}',[
 ok('分支后获得可信列表','import {parseProducts} from "./main";const result=parseProducts([]);if(result.ok){const items:readonly import("./parser").Product[]=result.items;}'),
 bad('失败分支没有完整列表','import {parseProducts} from "./main";const result=parseProducts([]);if(!result.ok){const items=result.items;}'),
 ],'批量结果复用单项验证，但只有所有条目都可信才返回列表。错误用 index:field 指明来源，避免用静默过滤伪造完整导入成功。','先验证整体数组。｜逐项调用现成解析器。｜累计带索引的问题，最后决定分支。',{runtimeEnvironment:undefined,supportFiles:{'parser.ts':productParser},runtime:[{name:'空数组与完整可信导入',code:'const {parseProducts}=load("main.js");equal(parseProducts([]),{ok:true,items:[]});const raw=Object.freeze([Object.freeze({id:1,title:" A ",price:0,tags:Object.freeze([" x "])}),Object.freeze({id:2,title:"B",price:2,tags:Object.freeze([])})]);const result=parseProducts(raw);equal(result,{ok:true,items:[{id:1,title:"A",price:0,tags:["x"]},{id:2,title:"B",price:2,tags:[]}]});check(result.items!==raw);'},{name:'不静默丢弃错误条目',code:'const {parseProducts}=load("main.js");equal(parseProducts({}),{ok:false,issues:["object"]});const result=parseProducts([{id:1,title:"ok",price:1,tags:[]},{id:0,title:" ",price:-1,tags:[""]},{id:2,title:"ok",price:1,tags:[]},{id:3,title:"ok",price:Infinity,tags:["x"]}]);equal(result,{ok:false,issues:["1:id","1:title","1:price","1:tags","3:price"]});'}]}),

 m(5,1,'不改扩展名如何开始检查','旧项目仍以 .js 为主，希望逐步引入 TypeScript 检查，哪组设置直接相关？',['allowJs 允许纳入 JS，checkJs 对 JS 报类型错误，JSDoc 可以补充契约','只改 target，JS 就会自动变 TS','只开启 declaration 就能验证全部 JS','只把文件命名为 index.js 就会默认严格检查'],'JS 检查可以逐步开启。要明确项目文件范围、检查选项和实际注释，不能把允许读取 JS 等同于一定报告其错误。','先允许 JS 进入程序。｜再选择是否报告 JS 中的类型问题。｜注释辅助表达接口。'),
 m(5,2,'JSDoc 会影响什么','给 JS 函数写 @param {number}，调用者可获得什么，运行时又不会发生什么？',['静态检查能使用参数契约，注释不会自动把字符串转换成数字','浏览器自动校验并转换所有实参','注释只能影响运行速度','编译器会把 JS 文件删除'],'JSDoc 是可参与检查的声明，不是输入解析代码。运行边界仍需要实际转换和校验。','类型信息给检查器用。｜运行时值仍原样传递。｜行为必须由函数实现。'),
 m(5,3,'只允许 JS 与检查 JS','allowJs:true、checkJs:false 的配置是否等同于旧 JS 已通过严格检查？',['不等同，JS 可参与项目，但部分 JS 自身错误不会被报告','等同，allowJs 自动强制 checkJs','等同，所有注释都是运行时校验','不等同，因为 JS 文件完全不会被纳入项目'],'必须区分文件纳入与对其报告错误。题目会通过替换只读 JS 中的错误，验证 checkJs 确实生效。','两个选项职责不同。｜JS 是否被读取？｜JS 自身错误是否被报告？'),
 t(5,4,'让已有 JS 错误真正参与检查','只编辑 tsconfig，保持 main.js 为唯一项目入口、allowJs:true、noEmit:true。启用 JS 本身的检查。测试会把只读 main.js 的 count:number 声明值改成文本；配置必须报告该错误。',
 {'tsconfig.json':'{"compilerOptions":{"allowJs":true,"checkJs":false,"noEmit":true},"files":["main.js"]}'},
 {'tsconfig.json':'{"compilerOptions":{"allowJs":true,"checkJs":true,"noEmit":true},"files":["main.js"]}'},[
 ok('读取已声明数值','import {count} from "./main";const n:number=count;'),
 bad('数值不接受文本使用','import {count} from "./main";const text:string=count;'),
 ],'配置应把 JS 纳入项目并对其错误报告诊断。反例替换只读实现后，单纯允许 JS 而不检查仍会失败。','保留 allowJs 及 main.js 入口。｜启用 checkJs。｜验证错误 JS 是否出现诊断。',{project:{configFile:'tsconfig.json',rootFiles:['main.js']},supportFiles:{'main.js':'/** @type {number} */ export const count=2;'},emissionTests:[{name:'只检查而不写出',files:[]},{name:'JS 自身类型错误被发现',supportFiles:{'main.js':'/** @type {number} */ export const count="bad";'},diagnosticCodes:[2322],files:[]}]}),
 m(5,5,'JSDoc 与实现不一致','注释写 @returns {number}，函数在非法输入时返回 undefined，最该做什么？',['核对需求，修正注释或实现并验证非法输入分支','给所有调用者增加 number 断言','只关闭 checkJs','把 undefined 文本改名为 number'],'注释必须与真实行为一致。让检查消失但保留错误契约会使调用者误用返回值。','真实函数有哪些返回路径？｜调用者应该处理什么？｜检查和运行验证都需要一致。'),
 t(5,6,'为 JS 解析函数写可信 JSDoc','编辑 main.js，保留 JS 语法。实现 parsePort(text)：仅十进制数字文本表示的 1 到 65535 整数返回 number，其他返回 null。使用 JSDoc 标明 string 参数和 number|null 结果，不能只靠注释伪造行为。',
 '/** @param {string} text @returns {number} */ export function parsePort(text){return Number(text);}',
 '/** @param {string} text @returns {number|null} */ export function parsePort(text){if(!/^[0-9]+$/.test(text))return null;const port=Number(text);return Number.isSafeInteger(port)&&port>=1&&port<=65535?port:null;}',[
 ok('返回需处理失败','import {parsePort} from "./main";const port:number|null=parsePort("80");'),
 bad('调用者不能假定永远有效','import {parsePort} from "./main";const port:number=parsePort("bad");'),
 bad('参数只接受文本','import {parsePort} from "./main";parsePort(80);'),
 ],'JSDoc 明确静态契约，函数体实际验证完整数字文本与端口范围。直接 Number 转换会把空串当成 0，也可能接受不符合协议的表示。','先验证整个文本格式。｜再检查数字的整数与范围。｜JSDoc 同时表达成功和失败。',{compilerOptions:{allowJs:true,checkJs:true},runtime:[{name:'端口边界和非法文本',code:'const {parsePort}=load("main.js");for(const [text,result] of [["1",1],["65535",65535],["80",80],["0",null],["65536",null],["",null],[" 80",null],["80x",null],["-1",null],["1.5",null],["1e2",null]])equal(parsePort(text),result);'}]}),
 m(5,7,'从 unknown 建立 JS 边界','JSDoc 里的 @param {unknown} 对迁移代码有什么实际帮助？',['迫使实现先验证外部值，再访问需要的字段','运行时自动冻结参数','让 JSON.parse 不可能失败','等同于 any，可直接调用所有方法'],'unknown 仍需要运行时证据。JS 文件也可用 JSDoc 表达不可信输入，逐步把检查加到边界。','外部数据类型未受控制。｜unknown 下能直接访问 id 吗？｜真实校验后才返回可信模型。'),
 t(5,8,'迁移：在 JS 中验证外部任务','继续使用 main.js。用 JSDoc 定义 Task={id:string,done:boolean}，readTask(raw:unknown):Task|null。输入须为非数组记录，id 修剪后非空、done 必须 boolean；返回仅含 id 和 done 的新对象，否则 null。',
 '/** @typedef {{id:string,done:boolean}} Task */\n/** @param {unknown} raw @returns {Task|null} */\nexport function readTask(raw){return null;}',
 '/** @typedef {{id:string,done:boolean}} Task */\n/** @param {unknown} raw @returns {Task|null} */\nexport function readTask(raw){if(typeof raw!=="object"||raw===null||Array.isArray(raw)||!("id" in raw)||typeof raw.id!=="string"||raw.id.trim()===""||!("done" in raw)||typeof raw.done!=="boolean")return null;return {id:raw.id.trim(),done:raw.done};}',[
 ok('可信任务可被使用','import {readTask} from "./main";const task:import("./main").Task|null=readTask({id:"a",done:false});'),
 bad('调用者不能假定总成功','import {readTask} from "./main";const task:import("./main").Task=readTask({});'),
 ],'JSDoc 表达 JS 模块的边界契约，运行代码逐项验证。只给返回值写 Task 而不验证 raw 会把不可信输入直接带入业务层。','先排除 null/数组。｜id 和 done 分别检查。｜成功时只返回两个公开字段。',{compilerOptions:{allowJs:true,checkJs:true},runtime:[{name:'合法记录投影与输入保持',code:'const {readTask}=load("main.js");const raw=Object.freeze({id:" a ",done:false,secret:"hidden"});const result=readTask(raw);equal(result,{id:"a",done:false});check(result!==raw);equal(raw.id," a ");'},{name:'脏数据被拒绝',code:'const {readTask}=load("main.js");for(const raw of [null,[],{}, {id:"",done:true},{id:" ",done:true},{id:1,done:true},{id:"a",done:"false"},{id:"a"}])equal(readTask(raw),null);'}]}),
 m(5,9,'复测：只让 TS 调用者通过','TS 调用文件类型检查通过，能否据此判断被导入 JS 的实现内部也被检查过？',['不能，需确认 checkJs 及 JS 文件范围，调用契约通过不等于实现无错','能，TS 自动检查所有 JS 内部','能，只要 JS 文件有一条 JSDoc','不能，因为 TS 永远无法读取 JS 声明'],'项目中的 TS 调用测试和 JS 自身检查相互补充。尤其要确认检查选项、文件入口和实际实现行为。','调用侧和实现侧是两个位置。｜当前 checkJs 是否开启？｜运行边界还需测试。'),
 t(5,10,'复测：配置和 JS 实现一起修复','同时编辑 tsconfig.json 与 legacy.js。只检查 legacy.js，开启 allowJs/checkJs、严格检查与 noEmit。parseId(text:string):number|null 仅接受正安全整数的十进制文本；JSDoc 需如实声明，运行行为也要符合。不能只改配置或只改 JS。',
 {'tsconfig.json':'{"compilerOptions":{"allowJs":true,"checkJs":false,"strict":true,"noEmit":true},"files":["legacy.js"]}','legacy.js':'/** @param {string} text @returns {number} */ export function parseId(text){return Number(text);}'},
 {'tsconfig.json':'{"compilerOptions":{"allowJs":true,"checkJs":true,"strict":true,"noEmit":true},"files":["legacy.js"]}','legacy.js':'/** @param {string} text @returns {number|null} */ export function parseId(text){if(!/^[0-9]+$/.test(text))return null;const value=Number(text);return Number.isSafeInteger(value)&&value>0?value:null;}'},[
 ok('公开结果处理失败','import {parseId} from "./legacy";const id:number|null=parseId("2");'),
 bad('无效输入可能失败','import {parseId} from "./legacy";const id:number=parseId("bad");'),
 bad('严格空值检查也保留','const value:number=undefined;'),
 ],'配置决定是否真实检查 JS，注释和代码共同定义对外契约。类型反例、实际配置与运行边界均参与判断，单独改一处不足以完成任务。','配置开启 checkJs。｜注释承认无效输入可能失败。｜实现完整文本与安全整数验证。',{project:{configFile:'tsconfig.json',rootFiles:['legacy.js'],requiredOptions:{checkJs:true,allowJs:true,strict:true}},emissionTests:[{name:'保持只检查流程',files:[]}],runtime:[{name:'有效与无效编号',code:'const {parseId}=load("legacy.js");for(const [text,result] of [["1",1],["007",7],["9007199254740991",9007199254740991],["0",null],["",null],["1x",null],["-1",null],["1.5",null],["9007199254740992",null]])equal(parseId(text),result);'}]}),

 m(6,1,'逐步迁移的起点','现有 JS 项目准备迁移到 TS，先稳定什么最有利于发现迁移回归？',['对外接口及关键行为测试，再逐步迁移模块','先把所有 .js 批量改名为 .ts','先给全部边界值加断言','先删除旧测试避免报错'],'迁移应保留业务契约。类型检查能发现接口不匹配，行为测试能发现同类型下的逻辑变化。','哪些使用方依赖接口？｜哪些行为仅靠类型看不出来？｜先建立可比证据。'),
 m(6,2,'模块边界','从 JS 模块迁移时，为什么先选边界清楚的模块较易控制风险？',['依赖和公开接口更容易核对，可在新旧实现之间比较结果','因为边界清楚就不需要测试','因为 JS 与 TS 永远不能互相导入','因为只要模块小就不会有运行错误'],'清楚的输入输出让迁移任务可验证。跨越外部数据或多方依赖时，更需明确兼容策略。','先看调用者范围。｜定义可观察行为。｜跨边界的类型承诺要有验证。'),
 m(6,3,'同类型不同结果','把 JS 搜索函数迁成 TS 后，签名仍是 string[]=>string[]，却改了空白查询行为，编译器会怎样？',['类型可能仍通过，因此还要比较原有行为或按新需求修改测试','类型系统会自动发现所有结果集变化','会把原有 JS 行为注入新函数','改名为 .ts 后运行结果必然完全相同'],'静态契约通常不表示所有业务细节。迁移测试要覆盖空白、大小写、顺序、引用等使用方关心的行为。','返回类型足以表示结果内容吗？｜空白查询的结果可不同。｜测试真实行为。'),
 t(6,4,'迁移搜索函数并保持行为','只编辑 main.ts，实现 search(items:readonly Item[],term:string):Item[]。与只读 legacy.js 一致：term 先 trim 并转小写，按 title 不区分大小写包含搜索；保留原顺序和各项原引用，返回新数组，不修改输入。Item 从只读 model.ts 导入。',
 'import type {Item} from "./model";export function search(items:readonly Item[],term:string):Item[]{return [];}',
 'import type {Item} from "./model";export function search(items:readonly Item[],term:string):Item[]{const query=term.trim().toLowerCase();return items.filter(item=>item.title.toLowerCase().includes(query));}',[
 ok('公开搜索输入输出','import {search} from "./main";import type {Item} from "./model";const items:readonly Item[]=[{id:"a",title:"Alpha"}];const result:Item[]=search(items,"a");'),
 bad('条目类型仍完整','import {search} from "./main";search([{id:"a"}],"a");'),
 ],'类型检查守住 Item 契约，运行测试与旧 JS 实现对比结果、顺序和对象引用。空白查询需保留所有项，而不是被当作缺失或报错。','先读旧实现确定规则。｜filter 自然返回新数组且保留条目引用。｜trim 与大小写处理顺序要一致。',{compilerOptions:{allowJs:true,checkJs:true},supportFiles:{'model.ts':'export interface Item{id:string;title:string}','legacy.js':'/** @param {readonly {id:string,title:string}[]} items @param {string} term */ export function search(items,term){const query=term.trim().toLowerCase();return items.filter(item=>item.title.toLowerCase().includes(query));}'},runtime:[{name:'对照旧实现、保留顺序与引用',code:'const fresh=load("main.js").search,old=load("legacy.js").search;const a=Object.freeze({id:"a",title:"Alpha"}),b=Object.freeze({id:"b",title:"BETA"}),c=Object.freeze({id:"c",title:"alphabet"});const items=Object.freeze([a,b,c]);for(const term of ["a"," AL ","","  ","z","beta"]){const actual=fresh(items,term),expected=old(items,term);equal(actual,expected);check(actual!==items);actual.forEach(item=>check(items.includes(item)));}equal(fresh(items,"a").map(item=>item.id),["a","b","c"]);'}]}),
 m(6,5,'JS 依赖的返回值仍需审视','新 TS 模块导入旧 JS 函数，编译通过后为什么还应检查其真实返回值？',['旧函数可能缺少可信声明或返回不符合契约，适配层应验证边界','JS 一旦被 TS 导入就会自动产生运行时校验','把返回值写成 Item 就会修改旧函数','TS 不能调用 JS 函数'],'逐步迁移常需要适配旧模块。先以实际返回为准校验，再向新模块提供可信类型。','旧模块的契约从何而来？｜运行值谁负责检查？｜适配层可隔离不可信结果。'),
 t(6,6,'给旧 JS 模块增加可信适配层','只编辑 main.ts。只读 legacy.js 的 getLegacyItem(id) 可能返回脏数据。实现 loadItem(id:number):Item|null：只接受正安全整数 id；仅当结果是非数组记录，id 与请求相同、label 为 trim 后非空字符串时返回新 {id,label}；否则 null。旧模块不可改。',
 'import {getLegacyItem} from "./legacy";import type {Item} from "./model";export function loadItem(id:number):Item|null{return getLegacyItem(id);}',
 'import {getLegacyItem} from "./legacy";import type {Item} from "./model";export function loadItem(id:number):Item|null{if(!Number.isSafeInteger(id)||id<=0)return null;const raw:unknown=getLegacyItem(id);if(typeof raw!=="object"||raw===null||Array.isArray(raw)||!("id" in raw)||raw.id!==id||!("label" in raw)||typeof raw.label!=="string"||raw.label.trim()==="")return null;return {id,label:raw.label.trim()};}',[
 ok('公开模型可用','import {loadItem} from "./main";import type {Item} from "./model";const item:Item|null=loadItem(1);'),
 bad('调用者必须处理缺失','import {loadItem} from "./main";import type {Item} from "./model";const item:Item=loadItem(99);'),
 ],'适配层把旧 JS 的不可信输出局限在边界内。即使源码的推断看似有帮助，也要验证返回对象和与请求匹配的 id，再构造公开模型。','先拒绝非法请求 id。｜把旧返回当 unknown 验证。｜只投影公开字段。',{compilerOptions:{allowJs:true},supportFiles:{'model.ts':'export interface Item{id:number;label:string}','legacy.js':'export function getLegacyItem(id){if(id===1)return {id:1,label:"  One  ",secret:"internal"};if(id===2)return {id:2,label:" Two "};if(id===3)return {id:"3",label:"bad"};if(id===4)return {id:4,label:" "};return null;}'},runtime:[{name:'旧模块合法结果变成新模型',code:'const {loadItem}=load("main.js");equal(loadItem(1),{id:1,label:"One"});equal(loadItem(2),{id:2,label:"Two"});for(const id of [0,-1,1.5,3,4,5,Number.MAX_SAFE_INTEGER+1])equal(loadItem(id),null);'},{name:'适配后不泄露旧实现内部字段',code:'const {loadItem}=load("main.js"),old=load("legacy.js");const item=loadItem(1),original=old.getLegacyItem(1);check(item!==original);equal(Object.keys(item).sort(),["id","label"]);'}]}),
 m(6,7,'路径别名与迁移','为了让 TS 能解析旧 JS，配置了 paths 后，能否据此断言运行器也认识同一别名？',['不能，还需核对真实加载流程或在运行器中配置映射','能，paths 会重写所有生成导入','能，只要目录里存在 tsconfig','不能，因为 TypeScript 无法解析 JS'],'迁移中的静态路径映射与运行时模块解析应保持一致。题目里的适配模块使用真实相对路径，以便运行测试也能加载。','编译器与运行器是同一个系统吗？｜查看生成说明符。｜确认两边的路径规则。'),
 t(6,8,'迁移时保留旧路径并引入新实现','实现 formatAmount(mode:"legacy"|"modern",amount:number):string。legacy 模式调用只读 legacy.js 的 format(amount)，保持其原始输出；modern 模式返回 USD 加空格和两位小数。非有限数抛 RangeError。不要修改旧模块。',
 'import {format} from "./legacy";export function formatAmount(mode:"legacy"|"modern",amount:number):string{return format(amount);}',
 'import {format} from "./legacy";export function formatAmount(mode:"legacy"|"modern",amount:number):string{if(!Number.isFinite(amount))throw new RangeError("invalid amount");return mode==="legacy"?format(amount):`USD ${amount.toFixed(2)}`;}',[
 ok('两种模式有效','import {formatAmount} from "./main";const text:string=formatAmount("legacy",1);formatAmount("modern",2);'),
 bad('未知模式不可调用','import {formatAmount} from "./main";formatAmount("other",1);'),
 ],'新旧实现共存时要明确选择规则。legacy 继续复用原模块，modern 提供新格式；共同数值边界需在调用前检查。','先检查 amount。｜legacy 委托旧模块。｜modern 使用新格式。',{compilerOptions:{allowJs:true,checkJs:true},supportFiles:{'legacy.js':'/** @param {number} amount */ export function format(amount){return "$"+amount.toFixed(2);}'},runtime:[{name:'新旧模式和非法数值',code:'const {formatAmount}=load("main.js"),old=load("legacy.js");for(const n of [0,-2.5,1.234,12]){equal(formatAmount("legacy",n),old.format(n));equal(formatAmount("modern",n),"USD "+n.toFixed(2));}for(const n of [NaN,Infinity,-Infinity]){let error;try{formatAmount("legacy",n);}catch(e){error=e;}check(error&&error.name==="RangeError");}'}]}),
 m(6,9,'复测：切换实现后的验证','接口类型没有改变，把业务调用从旧实现切到新实现后，还需重点验证什么？',['边界值、异常、调用次数及对外可观察结果','只检查返回类型名称','仅确认文件扩展名变化','仅确认 IDE 能跳转源码'],'类型相同不意味着行为相同。迁移期间应重点比较旧契约和新行为，特别是失败路径及副作用。','切换会改变哪些运行结果？｜失败和边界值容易遗漏。｜回归测试覆盖调用路径。'),
 t(6,10,'复测：可切换的适配入口','实现 createGateway(legacy:(raw:string)=>unknown,modern:(raw:string)=>unknown,useModern:boolean):(raw:string)=>Result。每次仅调用被选中函数一次；其结果必须是非数组记录、id 为正安全整数，才返回 {ok:true,id}，否则 {ok:false,reason:"invalid"}。只读 model.ts 定义 Result，禁止把原对象原样返回。',
 'import type {Result} from "./model";export function createGateway(legacy:(raw:string)=>unknown,modern:(raw:string)=>unknown,useModern:boolean):(raw:string)=>Result{return raw=>({ok:false,reason:"invalid"});}',
 'import type {Result} from "./model";export function createGateway(legacy:(raw:string)=>unknown,modern:(raw:string)=>unknown,useModern:boolean):(raw:string)=>Result{return raw=>{const value=(useModern?modern:legacy)(raw);if(typeof value!=="object"||value===null||Array.isArray(value)||!("id" in value)||typeof value.id!=="number"||!Number.isSafeInteger(value.id)||value.id<=0)return {ok:false,reason:"invalid"};return {ok:true,id:value.id};};}',[
 ok('结果联合可分支使用','import {createGateway} from "./main";const read=createGateway(()=>({id:1}),()=>({id:2}),true);const result=read("x");if(result.ok){const id:number=result.id;}'),
 bad('失败分支没有 id','import type {Result} from "./model";declare const result:Result;if(!result.ok){const id=result.id;}'),
 ],'切换入口保留统一契约，同时只执行所选实现。返回值从 unknown 校验并投影；错误路径不应泄露部分数据，也不能调用两个实现做比较而产生副作用。','先依据开关选择一个函数。｜调用一次并验证返回对象。｜只输出通过校验的 id。',{supportFiles:{'model.ts':'export type Result={ok:true;id:number}|{ok:false;reason:"invalid"};'},runtime:[{name:'只调用选中的实现且保留输入',code:'const {createGateway}=load("main.js");const calls=[];const legacy=raw=>{calls.push(["legacy",raw]);return {id:1,secret:"old"};};const modern=raw=>{calls.push(["modern",raw]);return {id:2,secret:"new"};};equal(createGateway(legacy,modern,false)("a"),{ok:true,id:1});equal(createGateway(legacy,modern,true)("b"),{ok:true,id:2});equal(calls,[["legacy","a"],["modern","b"]]);'},{name:'拒绝脏结果而不泄漏对象',code:'const {createGateway}=load("main.js");for(const result of [null,[],{}, {id:"1"},{id:0},{id:1.5},{id:Infinity},{id:Number.MAX_SAFE_INTEGER+1}])equal(createGateway(()=>result,()=>null,false)("x"),{ok:false,reason:"invalid"});const original=Object.freeze({id:3,secret:1});const valid=createGateway(()=>original,()=>null,false)("x");equal(valid,{ok:true,id:3});check(valid!==original);'}]}),

 m(7,1,'any 为什么会扩散','从第三方函数拿到 any 并直接读取深层属性，后续检查可能发生什么？',['错误操作可能继续通过静态检查，应在边界收回为 unknown 并验证','any 会自动为每个字段建立运行时校验','只影响当前这一行，绝不影响返回值','any 与 unknown 在字段访问上完全相同'],'any 容易沿函数返回和对象属性传播。优先在输入边界转换成 unknown，再提供有证据的业务类型。','深层字段真的被检查了吗？｜返回值会继续传播什么类型？｜用 unknown 建立验证边界。'),
 m(7,2,'断言不能代替解析','把 JSON.parse(text) as Account 后，哪些事实仍需要确认？',['JSON 是否可解析、字段是否存在及其业务值是否有效','断言已完成所有运行检查','服务端会读取 Account 并保证返回','断言已把数字字符串转换为数字'],'断言只影响静态视图，不检查外部文本。应通过可失败的解析函数建立可信 Account。','类型信息是否留在 JavaScript？｜非法文本会怎样？｜字段约束谁来验证？'),
 m(7,3,'先收紧哪一个 any','项目里有多个 any，优先处理哪个通常更有收益？',['跨模块传播或接收外部数据的边界，并配套调用与行为测试','任意选一个变量名最长的','只处理测试文件里的 any','只改成另一种宽泛断言即可'],'边界处的宽类型影响更多调用者。逐步收紧时保留行为测试，避免只在类型上改了签名而运行不变。','哪些值会传播到其他模块？｜哪类数据最不可信？｜先隔离来源。'),
 t(7,4,'修复深层属性上的 any','实现 accountName(raw:unknown):string|null。只有非数组记录含 profile，profile 也是非数组记录，name 为 trim 后非空字符串时返回规范化名称；其他输入返回 null。不修改原对象。当前实现用 any 无条件读取，需真正建立检查。',
 'export function accountName(raw:any):string{return raw.profile.name;}',
 'export function accountName(raw:unknown):string|null{if(typeof raw!=="object"||raw===null||Array.isArray(raw)||!("profile" in raw))return null;const profile=raw.profile;if(typeof profile!=="object"||profile===null||Array.isArray(profile)||!("name" in profile)||typeof profile.name!=="string")return null;const name=profile.name.trim();return name===""?null:name;}',[
 ok('返回可能失败的名称','import {accountName} from "./main";const name:string|null=accountName({profile:{name:"a"}});'),
 bad('调用者不能忽略缺失','import {accountName} from "./main";const name:string=accountName({});'),
 ],'用 unknown 和实际分支验证替换 any 的无条件读取。返回类型承认无法取得有效名称，不能用断言或非空断言跳过校验。','先确认外层对象与 profile。｜name 必须是字符串。｜修剪后再判断非空。',{runtime:[{name:'嵌套记录与规范化',code:'const {accountName}=load("main.js");const raw=Object.freeze({profile:Object.freeze({name:"  Ada  ",secret:1})});equal(accountName(raw),"Ada");equal(raw.profile.name,"  Ada  ");for(const value of [null,[],{}, {profile:null},{profile:[]},{profile:{}},{profile:{name:" "}},{profile:{name:1}}])equal(accountName(value),null);'}]}),
 m(7,5,'何时允许类型断言','去掉随意的 as，并不代表任何断言都不能使用。更合理的判断标准是什么？',['断言有清楚且经维护的外部证据，范围尽量局部；外部未知数据仍应运行校验','只要断言能让编译器通过就正确','所有非空断言都会新增运行守卫','所有 TS 项目必须一律使用 any'],'断言有合法用途，但不能替代对不可信运行输入的验证。课程练习默认要求通过模型与检查解决边界问题。','断言的依据是什么？｜输入来源是否可信？｜是否能用真实守卫表达？'),
 t(7,6,'把松散解析器隔离在边界','只读 parser.ts 的 parseLoose(text) 返回未经验证的 JSON。实现 readTags(text:string):readonly string[]|null：解析错误返回 null；只有数组且每项是 trim 后非空字符串才成功；去重并保留首次出现顺序，返回新数组。不能把解析结果断言成字符串数组。',
 'import {parseLoose} from "./parser";export function readTags(text:string):readonly string[]{return parseLoose(text) as string[];}',
 'import {parseLoose} from "./parser";export function readTags(text:string):readonly string[]|null{let raw:unknown;try{raw=parseLoose(text);}catch{return null;}if(!Array.isArray(raw))return null;const tags:string[]=[],seen=new Set<string>();for(const value of raw){if(typeof value!=="string"||value.trim()==="")return null;const tag=value.trim();if(!seen.has(tag)){seen.add(tag);tags.push(tag);}}return tags;}',[
 ok('返回可能缺失的只读标签','import {readTags} from "./main";const tags:readonly string[]|null=readTags("[]");'),
 bad('调用者不能假定总是数组','import {readTags} from "./main";const tags:readonly string[]=readTags("bad");'),
 ],'把宽泛解析结果限制在局部 unknown 变量，逐项检查后再返回可信标签。先验证完整输入，再规范化、去重；遇到坏项不应返回部分成功。','JSON 解析会抛错。｜数组成员仍然未知。｜验证后按首次出现顺序去重。',{supportFiles:{'parser.ts':'export function parseLoose(text:string){return JSON.parse(text);}'},runtime:[{name:'规范化、去重和全有或全无',code:'const {readTags}=load("main.js");equal(readTags("[]"),[]);equal(readTags(`[" a ","b","a","b"]`),["a","b"]);for(const text of ["{bad","null","{}",`["a",1]`,`["a","  "]`])equal(readTags(text),null);'}]}),
 m(7,7,'非空断言的失败方式','element!.textContent! 通过检查后，页面还可能怎样失败？',['没有匹配元素时仍会在运行时访问 null，断言不创建兜底分支','两个感叹号自动重试 DOM 查询','表达式会自动创建缺失元素','类型检查通过说明选择器永不失效'],'非空断言不会改变查询结果。应按需求为缺失、空文本制定真实处理路径。','选择器可能匹配不到。｜编译后的代码有没有分支？｜补上兜底逻辑。'),
 t(7,8,'迁移：去掉 DOM 非空断言','实现 primaryText(root:ParentNode):string。读取首个 .primary 元素的 textContent；缺失或 textContent 为 null 时返回 "untitled"，合法空文本必须原样返回空字符串。不修改 DOM，不使用非空断言。',
 'export function primaryText(root:ParentNode):string{return root.querySelector(".primary")!.textContent!;}',
 'export function primaryText(root:ParentNode):string{const element=root.querySelector(".primary");return element?.textContent??"untitled";}',[
 ok('总能得到文本','import {primaryText} from "./main";const text:string=primaryText(document);'),
 bad('根对象必须能查询','import {primaryText} from "./main";primaryText(1);'),
 ],'真实的可选访问和空值合并对应两个失败情况。用 ?? 而不是 ||，才能保留合法空字符串。','先处理没有匹配的元素。｜textContent 自身可能可空。｜空字符串不是缺失。',{runtimeEnvironment:'dom',runtime:[{name:'缺失、空文本和限定范围',code:'const {primaryText}=load("main.js");document.body.innerHTML="<div class=primary>outside</div><section><span class=primary></span></section>";const root=document.querySelector("section");equal(primaryText(root),"");equal(primaryText(document),"outside");root.querySelector(".primary").remove();equal(primaryText(root),"untitled");'}]}),
 m(7,9,'复测：签名变严格后的下一步','将外部数据入口从 any 改成 unknown 并完成类型检查，为什么仍需要旧调用方和异常测试？',['收紧类型后，调用者的处理路径和真实解析行为都可能需要同步调整','unknown 会自动把所有旧输入变成有效对象','类型检查通过就证明异常文案和运行结果不变','只需删除旧测试即可避免回归'],'类型收紧提供更可靠的静态契约，迁移仍需验证实际异常、空值和成功值。','调用者以前可能如何假定结果？｜运行异常谁来处理？｜保留行为证据。'),
 t(7,10,'复测：从 JSON 文本构造账户','只读 model.ts 定义 Account{id:number;name:string}。实现 parseAccount(text:string):Account|null：JSON 解析失败返回 null；对象不能是 null/数组；id 是正安全整数，name 为 trim 后非空字符串；成功返回仅含 id/name 的新对象。不用 any、类型断言或非空断言。',
 'import type {Account} from "./model";export function parseAccount(text:string):Account{return JSON.parse(text) as Account;}',
 'import type {Account} from "./model";export function parseAccount(text:string):Account|null{let raw:unknown;try{raw=JSON.parse(text);}catch{return null;}if(typeof raw!=="object"||raw===null||Array.isArray(raw)||!("id" in raw)||typeof raw.id!=="number"||!Number.isSafeInteger(raw.id)||raw.id<=0||!("name" in raw)||typeof raw.name!=="string"||raw.name.trim()==="")return null;return {id:raw.id,name:raw.name.trim()};}',[
 ok('可信账户或缺失','import {parseAccount} from "./main";import type {Account} from "./model";const account:Account|null=parseAccount("{}");'),
 bad('不能假定 JSON 都有效','import {parseAccount} from "./main";import type {Account} from "./model";const account:Account=parseAccount("{}");'),
 ],'JSON.parse 的返回值先收进 unknown，再按账户业务契约验证。返回新对象避免把额外字段带入内部；错误文本、错误形状和业务值都返回 null。','先捕获解析失败。｜验证对象、id 和 name。｜最后投影为新 Account。',{supportFiles:{'model.ts':'export interface Account{id:number;name:string}'},runtime:[{name:'合法账户与公开字段',code:'const {parseAccount}=load("main.js");equal(parseAccount(`{"id":7,"name":"  Ada  ","secret":1}`),{id:7,name:"Ada"});'},{name:'非法 JSON 与业务值',code:'const {parseAccount}=load("main.js");for(const text of ["{bad","null","[]","{}",`{"id":0,"name":"a"}`,`{"id":1.5,"name":"a"}`,`{"id":1,"name":" "}`,`{"id":"1","name":"a"}`,`{"id":9007199254740992,"name":"a"}`])equal(parseAccount(text),null);'}]}),

];

for(const id of ['t13-l05-q06','t13-l05-q08']){const q=questions.find(item=>item.id===id);q.files={'main.js':q.files['main.ts']};q.solution={'main.js':q.solution['main.ts']};}

questions.find(q=>q.id==='t13-l01-q06').wrongSolutions=[{'main.ts':'export function readInput(root:ParentNode,selector:string):string|undefined{const element=root.querySelector(selector);return element instanceof HTMLInputElement?(element.getAttribute("value")??""):undefined;}'}];

for(const [id,from,to] of [
 ['t13-l02-q06','input.removeEventListener("input",handler)','input.removeEventListener("input",()=>onValue(input.value))'],
 ['t13-l02-q08','event.preventDefault();',''],
 ['t13-l03-q08','kind:"data"','kind:"network"'],
 ['t13-l03-q10','if(response.status===204)return {kind:"empty"};',''],
]) {
 const question=questions.find(q=>q.id===id);
 question.wrongSolutions=[{'main.ts':question.solution['main.ts'].replaceAll(from,to)}];
}

const jsCombined=questions.find(q=>q.id==='t13-l05-q10');
jsCombined.wrongSolutions=[
 {...jsCombined.solution,'tsconfig.json':jsCombined.files['tsconfig.json']},
 {...jsCombined.files,'tsconfig.json':jsCombined.solution['tsconfig.json']},
];
