import { mc, task, ok, bad } from './author.mjs';
const id=n=>`t14-l${String(n).padStart(2,'0')}`;
const m=(l,n,title,prompt,options,explanation,hints,extra={})=>mc(id(l),n,title,prompt,options,explanation,hints.split('｜'),extra);
const t=(l,n,title,prompt,files,solution,tests,explanation,hints,extra={})=>task(id(l),n,title,prompt,files,solution,tests,explanation,hints.split('｜'),extra);
const taskModel=`export interface TaskBase{readonly id:string;readonly title:string;readonly tags:readonly string[]}
export type OpenTask=TaskBase&{readonly state:"open";readonly completedAt?:never};
export type DoneTask=TaskBase&{readonly state:"done";readonly completedAt:number};
export type Task=OpenTask|DoneTask;`;
const recordParser=`import type {Task} from "./model";
export type ParseResult={ok:true;task:Task}|{ok:false;field:"id"|"title"|"tags"|"state"|"completedAt"};
export function validateTask(raw:unknown):ParseResult{
 if(typeof raw!=="object"||raw===null||Array.isArray(raw))return {ok:false,field:"id"};
 if(!("id" in raw)||typeof raw.id!=="string"||raw.id.trim()==="")return {ok:false,field:"id"};
 if(!("title" in raw)||typeof raw.title!=="string"||raw.title.trim()==="")return {ok:false,field:"title"};
 if(!("tags" in raw)||!Array.isArray(raw.tags)||!raw.tags.every((v:unknown)=>typeof v==="string"&&v.trim()!==""))return {ok:false,field:"tags"};
 if(!("state" in raw))return {ok:false,field:"state"};
 const tags=[...new Set(raw.tags.map((v:string)=>v.trim()))];const base={id:raw.id.trim(),title:raw.title.trim(),tags};
 if(raw.state==="open")return Object.hasOwn(raw,"completedAt")?{ok:false,field:"completedAt"}:{ok:true,task:{...base,state:"open"}};
 if(raw.state!=="done")return {ok:false,field:"state"};
 if(!("completedAt" in raw)||typeof raw.completedAt!=="number"||!Number.isSafeInteger(raw.completedAt)||raw.completedAt<0)return {ok:false,field:"completedAt"};
 return {ok:true,task:{...base,state:"done",completedAt:raw.completedAt}};
}`;
const importList=`import {validateTask} from "./validator";import type {Task} from "./model";
export type ImportResult={ok:true;tasks:Task[]}|{ok:false;errors:{index:number;field:string}[]};
export function importTaskList(raw:unknown):ImportResult{
 if(!Array.isArray(raw))return {ok:false,errors:[{index:-1,field:"items"}]};
 const tasks:Task[]=[],errors:{index:number;field:string}[]=[],ids=new Set<string>();
 raw.forEach((entry:unknown,index:number)=>{const result=validateTask(entry);if(!result.ok){errors.push({index,field:result.field});return;}if(ids.has(result.task.id)){errors.push({index,field:"id"});return;}ids.add(result.task.id);tasks.push(result.task);});
 return errors.length?{ok:false,errors}:{ok:true,tasks};
}`;
const extendedTaskModel=`export interface TaskBase{readonly id:string;readonly title:string;readonly tags:readonly string[]}
export type OpenTask=TaskBase&{readonly state:"open";readonly completedAt?:never;readonly archivedAt?:never};
export type DoneTask=TaskBase&{readonly state:"done";readonly completedAt:number;readonly archivedAt?:never};
export type ArchivedTask=TaskBase&{readonly state:"archived";readonly archivedAt:number;readonly completedAt?:never};
export type Task=OpenTask|DoneTask|ArchivedTask;`;
const archiveService=`import type {OpenTask,ArchivedTask} from "./model";
export function archiveTask(task:OpenTask,at:number):ArchivedTask{
 if(!Number.isSafeInteger(at)||at<0)throw new RangeError("invalid archive time");
 return {id:task.id,title:task.title,tags:[...task.tags],state:"archived",archivedAt:at};
}`;
const taskView=`import type {Task} from "./model";
export function label(task:Task):string{
 switch(task.state){
  case "open":return "待办:"+task.title;
  case "done":return "完成:"+task.title+"@"+task.completedAt;
  case "archived":return "归档:"+task.title+"@"+task.archivedAt;
  default:{const impossible:never=task;return impossible;}
 }
}`;
const extendedParser=`import type {Task} from "./model";
export function parseTask(raw:unknown):Task|null{
 if(typeof raw!=="object"||raw===null||Array.isArray(raw)||!("id" in raw)||typeof raw.id!=="string"||raw.id.trim()===""||!("title" in raw)||typeof raw.title!=="string"||raw.title.trim()===""||!("tags" in raw)||!Array.isArray(raw.tags)||!raw.tags.every((tag:unknown)=>typeof tag==="string"&&tag.trim()!=="")||!("state" in raw))return null;
 const base={id:raw.id.trim(),title:raw.title.trim(),tags:[...new Set(raw.tags.map((tag:string)=>tag.trim()))]};
 if(raw.state==="open")return Object.hasOwn(raw,"completedAt")||Object.hasOwn(raw,"archivedAt")?null:{...base,state:"open"};
 if(raw.state==="done"){if(Object.hasOwn(raw,"archivedAt")||!("completedAt" in raw)||typeof raw.completedAt!=="number"||!Number.isSafeInteger(raw.completedAt)||raw.completedAt<0)return null;return {...base,state:"done",completedAt:raw.completedAt};}
 if(raw.state==="archived"){if(Object.hasOwn(raw,"completedAt")||!("archivedAt" in raw)||typeof raw.archivedAt!=="number"||!Number.isSafeInteger(raw.archivedAt)||raw.archivedAt<0)return null;return {...base,state:"archived",archivedAt:raw.archivedAt};}
 return null;
}`;
export const questions=[
 m(1,1,'先建模合法状态','任务有待办和完成两种状态，只有完成任务存在完成时间，哪种类型设计能更好表达？',['以 state 为判别字段建立联合，并使完成时间只属于完成分支','一个接口里 state:string、completedAt?:number 已足以禁止所有非法组合','只把 completedAt 改名即可','把每个任务都强制写成 any'],'可辨识联合让状态和字段之间形成关联。运行时还需要验证外部数据是否真的符合这一契约。','关注状态与字段的关联。｜可选字段并不能表示只有完成态才允许时间。｜分支联合更明确。'),
 m(1,2,'readonly 的真实作用','把任务接口的 title 与 tags 标为 readonly，就能保证什么？',['阻止受检查的代码直接改写这些字段，但不等于运行时冻结对象与数组','浏览器自动冻结输入','从网络收到的对象自动通过校验','同一对象在任何 JS 中都不可能修改'],'readonly 是静态契约。函数仍需避免实际修改输入，运行测试可以用冻结对象来验证。','静态与运行时分开。｜tags 指向的数组也要考虑。｜用行为测试确认。'),
 m(1,3,'对象已有变量时的非法状态','open 状态对象先存入变量，再赋给 Task；如果它含 completedAt:number，怎样让模型仍尽量拒绝？',['在 open 分支用 completedAt?:never 排除数值字段','只依赖对象字面量额外属性检查','把 completedAt 设成 any','只让 done 分支定义 state:string'],'仅不在 open 分支声明属性，结构赋值时可能允许来源变量的额外属性。可用 never 明确禁止数值完成时间。','变量赋值不同于新鲜字面量检查。｜明确表示该字段在 open 时不得取数值。｜运行输入仍需验证。'),
 t(1,4,'定义项目的任务联合','编辑 main.ts，导出 TaskBase、OpenTask、DoneTask、Task。共同字段 id/title 为 string，tags 为 readonly string[]，均只读；open 分支 state:"open" 且拒绝数值 completedAt；done 分支 state:"done" 且必须有 number completedAt。',
 'export type Task={id:string;title:string;state:string};',taskModel,[
 ok('两种合法任务可用','import type {Task,OpenTask,DoneTask} from "./main";const open:OpenTask={id:"a",title:"A",tags:[],state:"open"};const done:DoneTask={id:"b",title:"B",tags:[],state:"done",completedAt:0};const values:readonly Task[]=[open,done];'),
 bad('完成状态需要时间','import type {Task} from "./main";const task:Task={id:"a",title:"A",tags:[],state:"done"};'),
 bad('待办状态不能拥有数值完成时间','import type {Task} from "./main";const task:Task={id:"a",title:"A",tags:[],state:"open",completedAt:1};'),
 bad('保存到变量后仍拒绝非法组合','import type {Task} from "./main";const mixed={id:"a",title:"A",tags:[],state:"open" as const,completedAt:1};const task:Task=mixed;'),
 bad('标题不可直接改写','import type {Task} from "./main";declare const task:Task;task.title="changed";'),
 bad('标签列表不可直接 push','import type {Task} from "./main";declare const task:Task;task.tags.push("x");'),
 ],'Task 由两种合法分支组成。completedAt?:never 可以阻止把带数值完成时间的已有变量作为 open 任务；只读字段限制受检查代码的直接修改。','先定义共同字段。｜两个分支用字面量状态。｜open 排除完成时间，done 强制要求它。'),
 m(1,5,'类型模型之外的业务约束','类型里 id:string，是否已经确保用户输入的 id 非空且没有首尾空格？',['没有，这需要创建或解析函数在运行时处理','有，string 自动排除空白','有，只读修饰符会修剪字符串','有，联合类型能解析所有 JSON'],'普通 string 类型不表示非空或格式规则。公共业务函数要明确验证并规范化运行输入。','静态类型覆盖哪些值？｜空串也是 string。｜创建函数建立业务约束。'),
 t(1,6,'创建规范的待办任务','只读 model.ts 定义 OpenTask。实现 createTask(id:string,title:string,tags:readonly string[]):OpenTask。id/title 修剪后非空，所有标签修剪后非空，否则抛 RangeError；标签按修剪后的文本去重并保留首次顺序。返回新对象和新标签数组，state 为 open，输入不得改变。',
 'import type {OpenTask} from "./model";export function createTask(id:string,title:string,tags:readonly string[]):OpenTask{return {id,title,tags,state:"open"};}',
 'import type {OpenTask} from "./model";export function createTask(id:string,title:string,tags:readonly string[]):OpenTask{const cleanId=id.trim(),cleanTitle=title.trim();if(cleanId===""||cleanTitle==="")throw new RangeError("invalid task");const cleanTags:string[]=[],seen=new Set<string>();for(const value of tags){const tag=value.trim();if(tag==="")throw new RangeError("invalid tag");if(!seen.has(tag)){seen.add(tag);cleanTags.push(tag);}}return {id:cleanId,title:cleanTitle,tags:cleanTags,state:"open"};}',[
 ok('返回待办任务','import {createTask} from "./main";import type {OpenTask} from "./model";const task:OpenTask=createTask("a","A",[]);'),
 bad('调用者仍需传入文本标题','import {createTask} from "./main";createTask("a",1,[]);'),
 ],'创建函数把普通字符串转成符合业务规则的待办任务。新对象和新标签数组确保规范化不会修改共享输入。','先修剪 id/title 并验证。｜逐项验证并去重标签。｜返回新的 open 对象。',{supportFiles:{'model.ts':taskModel},runtime:[{name:'规范化、去重与不修改输入',code:'const {createTask}=load("main.js");const tags=Object.freeze([" web ","ts","web"]);const task=createTask(" a "," Write ",tags);equal(task,{id:"a",title:"Write",tags:["web","ts"],state:"open"});check(task.tags!==tags);equal(tags,[" web ","ts","web"]);equal(createTask("b","B",[]).tags,[]);'},{name:'空白字段拒绝',code:'const {createTask}=load("main.js");for(const args of [[" ","A",[]],["a"," ",[]],["a","A",["x"," "]]]){let error;try{createTask(...args);}catch(e){error=e;}check(error&&error.name==="RangeError");}'}]}),
 m(1,7,'完成任务时的对象身份','把待办任务转换为完成任务时，怎样处理共享输入比较稳妥？',['构造新完成对象并保留原任务，按约定复制需要独立拥有的标签数组','直接给只读输入加 completedAt','只改 state 不记录时间','类型断言会自动生成完成对象'],'状态转换既要满足目标类型，也要满足不改写输入的行为契约。运行测试可检查冻结对象和输出引用。','readonly 限制直接改写。｜新状态还需要完成时间。｜是否共享可变数组要明确。'),
 t(1,8,'迁移：完成任务而不修改输入','实现 completeTask(task:OpenTask,at:number):DoneTask。at 必须为非负安全整数，否则抛 RangeError；返回新对象，保留 id/title，复制标签到新数组，state 为 done，completedAt=at。原任务不修改。',
 'import type {OpenTask,DoneTask} from "./model";export function completeTask(task:OpenTask,at:number):DoneTask{return {...task,state:"done",completedAt:at};}',
 'import type {OpenTask,DoneTask} from "./model";export function completeTask(task:OpenTask,at:number):DoneTask{if(!Number.isSafeInteger(at)||at<0)throw new RangeError("invalid completion time");return {id:task.id,title:task.title,tags:[...task.tags],state:"done",completedAt:at};}',[
 ok('状态转换返回完成任务','import {completeTask} from "./main";import type {OpenTask,DoneTask} from "./model";declare const task:OpenTask;const done:DoneTask=completeTask(task,0);'),
 bad('完成态不能作为待办输入','import {completeTask} from "./main";import type {DoneTask} from "./model";declare const task:DoneTask;completeTask(task,1);'),
 ],'有效完成时间和对象独立性都要验证。只展开 task 虽生成新外层对象，仍会与原任务共享标签数组，未满足本题约定。','先验证 at。｜创建新对象而不改原任务。｜标签数组也要复制。',{supportFiles:{'model.ts':taskModel},runtime:[{name:'完成态与原任务独立',code:'const {completeTask}=load("main.js");const tags=Object.freeze(["a"]),task=Object.freeze({id:"a",title:"A",tags,state:"open"});const done=completeTask(task,0);equal(done,{id:"a",title:"A",tags:["a"],state:"done",completedAt:0});check(done!==task);check(done.tags!==tags);equal(task,{id:"a",title:"A",tags:["a"],state:"open"});'},{name:'非法时间拒绝',code:'const {completeTask}=load("main.js"),task={id:"a",title:"A",tags:[],state:"open"};for(const at of [-1,1.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1]){let error;try{completeTask(task,at);}catch(e){error=e;}check(error&&error.name==="RangeError");}'}]}),
 m(1,9,'复测：类型正确的外部任务','外部 JSON 经过断言变成 Task 后，可以信任其状态和完成时间关联吗？',['不能，还需验证判别字段、各字段业务值，以及不允许出现的属性','可以，断言会删除非法属性','可以，Task 联合会在运行时自动解析 JSON','只要 id 是字符串就可相信其他字段'],'类型模型约束受检查代码，外部对象仍要通过运行解析才能进入项目状态。','输入来自什么边界？｜编译器是否看到了真实 JSON？｜状态关联需要运行校验。'),
 t(1,10,'复测：从外部对象恢复任务','只读 model.ts 定义 Task。实现 parseTask(raw:unknown):Task|null：非数组对象，id/title 修剪后非空，tags 为全部修剪后非空的字符串并去重；open 状态不能拥有 completedAt 键，done 状态必须有非负安全整数 completedAt。成功返回只含公开字段的新对象，否则 null。',
 'import type {Task} from "./model";export function parseTask(raw:unknown):Task|null{return null;}',
 'import type {Task} from "./model";export function parseTask(raw:unknown):Task|null{if(typeof raw!=="object"||raw===null||Array.isArray(raw)||!("id" in raw)||typeof raw.id!=="string"||raw.id.trim()===""||!("title" in raw)||typeof raw.title!=="string"||raw.title.trim()===""||!("tags" in raw)||!("state" in raw)||!Array.isArray(raw.tags)||!raw.tags.every((value:unknown)=>typeof value==="string"&&value.trim()!==""))return null;const tags=[...new Set(raw.tags.map((value:string)=>value.trim()))];const base={id:raw.id.trim(),title:raw.title.trim(),tags};if(raw.state==="open"){if(Object.hasOwn(raw,"completedAt"))return null;return {...base,state:"open"};}if(raw.state==="done"&&"completedAt" in raw&&typeof raw.completedAt==="number"&&Number.isSafeInteger(raw.completedAt)&&raw.completedAt>=0)return {...base,state:"done",completedAt:raw.completedAt};return null;}',[
 ok('解析结果须处理缺失','import {parseTask} from "./main";import type {Task} from "./model";const task:Task|null=parseTask({});'),
 bad('不能假定外部数据正确','import {parseTask} from "./main";import type {Task} from "./model";const task:Task=parseTask({});'),
 ],'先验证外部形状，再建立状态与字段的对应关系。open 即使 completedAt:undefined 也要拒绝，因为输入不应包含该键；成功结果用新对象限制公开字段。','共同字段先验证。｜open 明确拒绝完成时间键。｜done 验证完成时间范围。',{supportFiles:{'model.ts':taskModel},runtime:[{name:'两种合法状态与规范化',code:'const {parseTask}=load("main.js");const open=Object.freeze({id:" a ",title:" A ",tags:Object.freeze([" x ","x"]),state:"open",secret:1});equal(parseTask(open),{id:"a",title:"A",tags:["x"],state:"open"});equal(parseTask({id:"b",title:"B",tags:[],state:"done",completedAt:0}),{id:"b",title:"B",tags:[],state:"done",completedAt:0});equal(open.id," a ");'},{name:'非法组合和不可信字段拒绝',code:'const {parseTask}=load("main.js");for(const raw of [null,[],{}, {id:"a",title:"A",tags:[],state:"open",completedAt:undefined},{id:"a",title:"A",tags:[],state:"open",completedAt:1},{id:"a",title:"A",tags:[],state:"done"},{id:"a",title:"A",tags:[],state:"done",completedAt:-1},{id:"a",title:"A",tags:[""],state:"open"},{id:" ",title:"A",tags:[],state:"open"},{id:"a",title:"A",tags:[],state:"other"}])equal(parseTask(raw),null);'}]}),
 m(2,1,'创建与添加的职责','已有 createTask 负责规范化单个任务，addTask 负责加入列表时还应验证什么？',['列表中的 ID 是否冲突，并保持旧列表不被修改','只需给数组起一个新变量名','只要 title 不同就说明 ID 不冲突','把重复项默默覆盖最安全'],'单项合法不代表能加入集合。集合规则和更新语义应在业务函数中明确检查。','两个任务可能各自合法。｜集合还要求什么唯一性？｜更新后原列表怎么办？'),
 m(2,2,'数组复制的边界','用 [...tasks] 得到新数组后，对其中任务对象直接改 title，会怎样？',['仍可能修改原列表指向的同一任务对象，需要对被更新项创建新对象','数组复制会递归克隆所有任务','readonly 会在运行时冻结每项','只要使用 spread 就不会共享任何引用'],'浅复制只创建新的外层数组。不可变更新还需在被修改的对象层创建新对象，并用运行测试核对引用关系。','旧数组和新数组的元素指向哪里？｜改 title 作用于哪个对象？｜为目标项创建新对象。'),
 m(2,3,'找不到 ID 时如何处理','updateTask 的需求规定找不到 ID 应报错。实现返回旧数组但类型仍为 Task[]，是否满足需求？',['不满足，返回类型相同不代表失败路径行为正确','满足，编译器会自动补抛错','满足，找不到就保持不变等价于报错','不满足，因为 Task[] 不能包含完成任务'],'业务规则需要行为测试。类型可检查调用形状，却不能单凭数组类型证明异常契约。','需求规定的失败行为是什么？｜返回数组与抛错不同。｜测试缺失 ID。'),
 t(2,4,'加入任务并拒绝重复 ID','实现 addTask(tasks:readonly Task[],draft:OpenTask):Task[]。若已有任务 ID 与 draft.id 相同，抛 RangeError；否则返回包含原顺序和末尾 draft 的新数组。不得修改输入数组或任务，不克隆已有任务。',
 'import type {Task,OpenTask} from "./model";export function addTask(tasks:readonly Task[],draft:OpenTask):Task[]{return [...tasks,draft];}',
 'import type {Task,OpenTask} from "./model";export function addTask(tasks:readonly Task[],draft:OpenTask):Task[]{if(tasks.some(task=>task.id===draft.id))throw new RangeError("duplicate id");return [...tasks,draft];}',[
 ok('接收只读列表','import {addTask} from "./main";import type {Task,OpenTask} from "./model";declare const items:readonly Task[],draft:OpenTask;const next:Task[]=addTask(items,draft);'),
 bad('新增必须是待办任务','import {addTask} from "./main";import type {Task,DoneTask} from "./model";declare const items:readonly Task[],done:DoneTask;addTask(items,done);'),
 ],'单个任务和任务集合具有不同约束。ID 冲突必须显式失败；成功时只复制外层列表，原有任务对象保持同一引用。','用 some 查找现有 ID。｜冲突先抛错。｜成功返回新数组并追加 draft。',{supportFiles:{'model.ts':taskModel},runtime:[{name:'新列表保留顺序与引用',code:'const {addTask}=load("main.js");const old=Object.freeze({id:"a",title:"A",tags:Object.freeze([]),state:"done",completedAt:1}),draft=Object.freeze({id:"b",title:"B",tags:Object.freeze([]),state:"open"}),items=Object.freeze([old]);const next=addTask(items,draft);equal(next,[old,draft]);check(next!==items);check(next[0]===old&&next[1]===draft);equal(items,[old]);'},{name:'重复 ID 无法加入',code:'const {addTask}=load("main.js");const items=Object.freeze([{id:"a",title:"A",tags:[],state:"open"}]);let error;try{addTask(items,{id:"a",title:"Other",tags:[],state:"open"});}catch(e){error=e;}check(error&&error.name==="RangeError");equal(items.length,1);'}]}),
 m(2,5,'更新完成任务的标题','一个 done 任务已经有 completedAt，更新其标题时应该如何保持任务模型？',['创建保留 done 状态和完成时间的新任务对象，其他任务引用不变','删除 completedAt 后仍标成 done','把所有任务重建成 open','直接修改旧对象的 title'],'更新部分字段仍需遵守状态联合的完整契约。测试应覆盖 open 与 done 两种分支。','目标项原本属于哪个分支？｜哪些字段必须保留？｜只创建新目标项。'),
 t(2,6,'实现不可变标题更新','实现 renameTask(tasks:readonly Task[],id:string,title:string):Task[]。title 修剪后非空；找不到 id 抛 RangeError。成功返回新数组，目标项是保留原状态、标签与完成时间的新对象；其他任务沿用原引用，全部输入不变。',
 'import type {Task} from "./model";export function renameTask(tasks:readonly Task[],id:string,title:string):Task[]{const task=tasks.find(item=>item.id===id);if(task)task.title=title;return [...tasks];}',
 'import type {Task} from "./model";export function renameTask(tasks:readonly Task[],id:string,title:string):Task[]{const clean=title.trim();if(clean==="")throw new RangeError("empty title");if(!tasks.some(task=>task.id===id))throw new RangeError("missing id");return tasks.map(task=>task.id===id?{...task,title:clean}:task);}',[
 ok('列表结果保留 Task 联合','import {renameTask} from "./main";import type {Task} from "./model";declare const tasks:readonly Task[];const next:Task[]=renameTask(tasks,"a","New");'),
 bad('输入列表不是可变参数要求','import {renameTask} from "./main";renameTask([],1,"New");'),
 ],'不可变更新要创建外层新数组和目标新对象。展开目标对象保留状态字段；其他项目无需复制。缺失或空标题按需求失败。','先验证标题和目标是否存在。｜map 只替换命中项。｜保持其他引用。',{supportFiles:{'model.ts':taskModel},runtime:[{name:'两类任务更新及引用',code:'const {renameTask}=load("main.js");const open=Object.freeze({id:"a",title:"A",tags:Object.freeze(["x"]),state:"open"}),done=Object.freeze({id:"b",title:"B",tags:Object.freeze([]),state:"done",completedAt:2}),items=Object.freeze([open,done]);const next=renameTask(items,"b"," New ");equal(next,[open,{id:"b",title:"New",tags:[],state:"done",completedAt:2}]);check(next!==items&&next[0]===open&&next[1]!==done);equal(done.title,"B");const again=renameTask(items,"a","Open");equal(again[0].state,"open");check(again[1]===done);'},{name:'缺失及空标题拒绝',code:'const {renameTask}=load("main.js"),items=Object.freeze([{id:"a",title:"A",tags:[],state:"open"}]);for(const [id,title] of [["none","X"],["a","  "]]){let error;try{renameTask(items,id,title);}catch(e){error=e;}check(error&&error.name==="RangeError");}equal(items[0].title,"A");'}]}),
 m(2,7,'组合筛选条件','筛选同时指定 state、tag、search，应如何组合？',['三个启用的条件都要满足，未指定或空查询不限制结果','满足任意一个条件就算命中','只检查第一个条件即可','先排序即可自动完成筛选'],'组合筛选需明确 AND/OR 语义。列表输出还应保持原顺序，避免隐式副作用。','题目要求哪些条件同时成立？｜没有设置的条件怎么办？｜检查顺序稳定。'),
 t(2,8,'迁移：组合筛选任务','实现 filterTasks(tasks:readonly Task[],filter:Filter):Task[]。Filter 只读 model.ts 给出可选 state、tag、search。启用条件取交集：state 精确匹配；tag 修剪后非空时按标签原文精确匹配；search 修剪后非空时按标题不区分大小写包含。返回新数组，保留原顺序及各任务原引用。',
 'import type {Task,Filter} from "./model";export function filterTasks(tasks:readonly Task[],filter:Filter):Task[]{return tasks.filter(task=>task.state===filter.state);}',
 'import type {Task,Filter} from "./model";export function filterTasks(tasks:readonly Task[],filter:Filter):Task[]{const tag=filter.tag?.trim(),search=filter.search?.trim().toLowerCase();return tasks.filter(task=>(filter.state===undefined||task.state===filter.state)&&(!tag||task.tags.includes(tag))&&(!search||task.title.toLowerCase().includes(search)));}',[
 ok('过滤接口可用','import {filterTasks} from "./main";import type {Task} from "./model";declare const tasks:readonly Task[];const next:Task[]=filterTasks(tasks,{state:"open",tag:"x"});'),
 bad('非法状态不能作为条件','import {filterTasks} from "./main";filterTasks([],{state:"paused"});'),
 ],'三个启用条件共同决定命中项。filter 返回新列表并复用条目，适合只读输入；空白 tag/search 不应意外排除全部任务。','先规范化可选文本条件。｜分别判断 state、tag、search。｜用 AND 组合并保持顺序。',{supportFiles:{'model.ts':taskModel+'\nexport interface Filter{readonly state?:"open"|"done";readonly tag?:string;readonly search?:string}'},runtime:[{name:'交集筛选、顺序与引用',code:'const {filterTasks}=load("main.js");const a=Object.freeze({id:"a",title:"Alpha",tags:Object.freeze(["web"]),state:"open"}),b=Object.freeze({id:"b",title:"BETA",tags:Object.freeze(["web"]),state:"done",completedAt:1}),c=Object.freeze({id:"c",title:"alphabet",tags:Object.freeze(["ts"]),state:"open"}),items=Object.freeze([a,b,c]);const all=filterTasks(items,{});equal(all,items);check(all!==items&&all[0]===a);equal(filterTasks(items,{state:"open",tag:" web ",search:" AL "}),[a]);equal(filterTasks(items,{search:"AL"}),[a,c]);equal(filterTasks(items,{tag:" ",search:" "}),items);equal(filterTasks(items,{tag:"WEB"}),[]);'}]}),
 m(2,9,'复测：Array.sort 与只读输入','需要为用户显示不同排序方式，直接 tasks.sort(...) 会有什么问题？',['可能改动共享输入数组，应先创建独立数组并明确同值时的顺序','sort 永远不修改输入','只读类型会在运行时自动复制数组','排序只能用于字符串数组'],'排序是可观察行为。必须保证输入不变，并为并列值定义稳定规则，避免切换视图后列表顺序不可预测。','sort 会修改谁？｜并列项目如何排列？｜检查引用和旧数组。'),
 t(2,10,'复测：稳定排序任务视图','实现 sortTasks(tasks:readonly Task[],mode:"title"|"recent"):Task[]。title 按标题 Unicode 码点升序；recent 按完成时间降序，open 视为 -1。相同键保留原始顺序；始终返回新数组，任务对象引用不变，输入不修改。',
 'import type {Task} from "./model";export function sortTasks(tasks:readonly Task[],mode:"title"|"recent"):Task[]{return [...tasks];}',
 'import type {Task} from "./model";export function sortTasks(tasks:readonly Task[],mode:"title"|"recent"):Task[]{const rank=(task:Task)=>task.state==="done"?task.completedAt:-1;return tasks.map((task,index)=>({task,index})).sort((a,b)=>{const order=mode==="title"?(a.task.title<b.task.title?-1:a.task.title>b.task.title?1:0):rank(b.task)-rank(a.task);return order||a.index-b.index;}).map(entry=>entry.task);}',[
 ok('排序结果保留模型','import {sortTasks} from "./main";import type {Task} from "./model";declare const items:readonly Task[];const next:Task[]=sortTasks(items,"recent");'),
 bad('未知排序模式拒绝','import {sortTasks} from "./main";sortTasks([],"priority");'),
 ],'显式装饰原始索引，保证比较键相同的项目保留原顺序。视图数组是新的，但元素仍是原对象；运行测试验证标题和时间两种顺序。','先定义两种排序键。｜复制而非修改输入。｜并列时比较原始索引。',{supportFiles:{'model.ts':taskModel},runtime:[{name:'标题与最近完成排序且不修改输入',code:'const {sortTasks}=load("main.js");const a=Object.freeze({id:"a",title:"z",tags:[],state:"open"}),b=Object.freeze({id:"b",title:"b",tags:[],state:"done",completedAt:2}),c=Object.freeze({id:"c",title:"A",tags:[],state:"done",completedAt:2}),d=Object.freeze({id:"d",title:"a",tags:[],state:"done",completedAt:1}),items=Object.freeze([a,b,c,d]);const title=sortTasks(items,"title"),recent=sortTasks(items,"recent");equal(title.map(x=>x.id),["c","d","b","a"]);equal(recent.map(x=>x.id),["b","c","d","a"]);check(title!==items&&recent!==items&&title[0]===c&&recent[0]===b);equal(items.map(x=>x.id),["a","b","c","d"]);'},{name:'并列项稳定保留原顺序',code:'const {sortTasks}=load("main.js");const a={id:"a",title:"same",tags:[],state:"open"},b={id:"b",title:"same",tags:[],state:"open"};equal(sortTasks([b,a],"title").map(x=>x.id),["b","a"]);equal(sortTasks([b,a],"recent").map(x=>x.id),["b","a"]);'}]}),

 m(3,1,'异步状态为何分支建模','同时允许 loading:true、data 和 error 共存在一个对象里，主要风险是什么？',['会出现业务上矛盾的组合，使用状态判别联合表达互斥阶段更清楚','TypeScript 无法使用布尔值','Promise 会被自动取消','所有错误都必须变成数据数组'],'加载状态描述单一阶段。判别字段让成功数据和失败信息各有合法分支，调用处据此缩窄。','加载中是否已有最终数据？｜成功和失败能同时成立吗？｜让状态与字段关联。'),
 m(3,2,'发起后何时标记 loading','点击加载后才等待 request，直到 Promise 兑现再把状态设成 loading，会遗漏什么？',['等待期间的可观察加载态，应在调用异步请求前或紧接着设置','不会遗漏，Promise 会自动设置状态','会自动把错误变成功','只会影响 TS 静态类型'],'加载中的状态必须反映实际进行中的请求。用未兑现的 Promise 测试可以验证这一时点。','Promise 尚未兑现时 UI 该看到什么？｜状态设置发生在哪一步？｜挂起测试。'),
 m(3,3,'旧请求晚返回','先发出的请求比后发出的请求更晚完成，页面只应展示最近一次刷新，应该关注什么？',['用请求版本号或等价机制，只有当前请求能更新状态','按完成顺序无条件覆盖就等于最近请求','把 Promise 类型改成 readonly 即可','只用 try/catch 就能消除竞态'],'请求发起顺序和完成顺序不同。需要显式定义过时结果如何处理，而不是让最后完成的旧请求覆盖新状态。','哪个请求才是当前用户意图？｜响应可能乱序。｜比较发起标识。'),
 t(3,4,'定义互斥加载状态','编辑 main.ts，定义并导出 AsyncState<T>：idle/loading 不含 data/message；success 必须有 data:T，不含 message；error 必须有 message:string，不含 data。各分支 status 为字面量并只读；即使对象先保存在变量里，也应拒绝同时带数据与错误信息的状态。',
 'export type AsyncState<T>={status:string;data?:T;message?:string};',
 'export type AsyncState<T>={readonly status:"idle";readonly data?:never;readonly message?:never}|{readonly status:"loading";readonly data?:never;readonly message?:never}|{readonly status:"success";readonly data:T;readonly message?:never}|{readonly status:"error";readonly message:string;readonly data?:never};',[
 ok('四个合法阶段','import type {AsyncState} from "./main";const states:AsyncState<number>[]=[{status:"idle"},{status:"loading"},{status:"success",data:0},{status:"error",message:"failed"}];'),
 bad('成功必须含数据','import type {AsyncState} from "./main";const state:AsyncState<number>={status:"success"};'),
 bad('错误必须含消息','import type {AsyncState} from "./main";const state:AsyncState<number>={status:"error"};'),
 bad('已存变量的成功态仍拒绝错误消息','import type {AsyncState} from "./main";const mixed={status:"success" as const,data:1,message:"failed"};const state:AsyncState<number>=mixed;'),
 bad('加载态不能含最终数据','import type {AsyncState} from "./main";const state:AsyncState<number>={status:"loading",data:1};'),
 ],'每个阶段只携带可用字段。可选 never 对已有变量的额外字段也施加限制；运行时外部状态仍需解析。','先列四种状态。｜success 只带 data。｜error 只带 message，其他状态排除两者。'),
 m(3,5,'同时点击加载','同一个 loader 仍在加载时再次调用 load，需求说不得重复请求，应怎样设计？',['保存当前 Promise，后续调用复用它并保持只发一次请求','每次调用都立即新发请求','返回一个永不兑现的 Promise','只检查 loading 但仍执行 request'],'合并进行中的同一操作需要保存其 Promise，完成后清除，下一次才允许真正重试。','请求还未结束时已有哪个 Promise？｜复用它。｜结束后如何开放新尝试？'),
 t(3,6,'设计可观察且可重试的加载器','实现 createTaskLoader(request:()=>Promise<readonly Task[]>):Loader。初始 idle；load 立即设 loading 并发起一次请求，未结束时再次调用须复用正在进行的同一 Promise。成功返回 success 与新数组，不改原数组；失败返回 error，Error 的非空消息保留，否则用“加载失败”。结束后再次 load 可真正重试。',
 'import type {Loader} from "./model";export function createTaskLoader(request:()=>Promise<readonly import("./model").Task[]>):Loader{return {getState:()=>({status:"idle"}),load:async()=>({status:"idle"})};}',
 'import type {Loader,Task,LoadState} from "./model";export function createTaskLoader(request:()=>Promise<readonly Task[]>):Loader{let state:LoadState={status:"idle"};let pending:Promise<LoadState>|null=null;function load():Promise<LoadState>{if(pending)return pending;state={status:"loading"};pending=(async()=>{try{const tasks=await request();state={status:"success",data:[...tasks]};}catch(error){state={status:"error",message:error instanceof Error&&error.message.trim()!==""?error.message:"加载失败"};}finally{pending=null;}return state;})();return pending;}return {getState:()=>state,load};}',[
 ok('状态和加载方法可使用','import {createTaskLoader} from "./main";import type {Loader} from "./model";const loader:Loader=createTaskLoader(async()=>[]);const result:Promise<import("./model").LoadState>=loader.load();'),
 bad('加载请求必须给出任务列表','import {createTaskLoader} from "./main";createTaskLoader(async()=>"wrong");'),
 ],'运行测试用未兑现 Promise 检查中间状态和重复调用次数。完成后清掉进行中的请求，才能允许下一次真正重试；成功数据数组应独立于外部输入。','保存 state 和 pending。｜有 pending 时直接返回。｜结束时设置结果并清空 pending。',{supportFiles:{'model.ts':taskModel+'\nexport type LoadState={status:"idle"}|{status:"loading"}|{status:"success";data:readonly Task[]}|{status:"error";message:string};export interface Loader{getState():LoadState;load():Promise<LoadState>}'},runtime:[{name:'中间态、合并请求与可重试',code:'const {createTaskLoader}=load("main.js");let release,calls=0;const gate=new Promise(resolve=>release=resolve);const source=Object.freeze([{id:"a",title:"A",tags:[],state:"open"}]);const loader=createTaskLoader(()=>{calls++;return calls===1?gate:Promise.resolve([]);});equal(loader.getState(),{status:"idle"});const first=loader.load();equal(loader.getState(),{status:"loading"});const same=loader.load();check(first===same);equal(calls,1);release(source);equal(await first,{status:"success",data:source});check(loader.getState().data!==source);equal(await same,loader.getState());equal(await loader.load(),{status:"success",data:[]});equal(calls,2);'},{name:'失败后保留消息并可再次加载',code:'const {createTaskLoader}=load("main.js");let calls=0;const loader=createTaskLoader(async()=>{calls++;if(calls===1)throw Error("offline");if(calls===2)throw {reason:"unknown"};return [];});equal(await loader.load(),{status:"error",message:"offline"});equal(await loader.load(),{status:"error",message:"加载失败"});equal(await loader.load(),{status:"success",data:[]});equal(calls,3);'}]}),
 m(3,7,'忽略旧响应还要忽略什么','旧请求最终失败，而新请求已经成功，如何处理旧请求的 catch？',['同样按请求版本判断，旧失败不能覆盖较新的成功','旧失败总应覆盖所有成功','只判断旧请求的 then，catch 不重要','把错误对象改名即可'],'成功和失败都能在乱序响应后改变状态。过时请求的两条结束路径都应被忽略。','旧请求的失败何时到来？｜当前页面状态属于哪个请求？｜统一检查版本。'),
 t(3,8,'迁移：最近一次刷新优先','实现 createTaskRefresher(request:()=>Promise<readonly Task[]>):Refresher。初始 idle；每次 refresh 均发起一次新请求并立刻设 loading。只允许最近发起的请求更新 success/error 状态，旧请求随后成功或失败均不得覆盖。成功返回新的列表数组；失败使用非空 Error.message 或“加载失败”。refresh 兑现时返回 void。',
 'import type {Refresher} from "./model";export function createTaskRefresher(request:()=>Promise<readonly import("./model").Task[]>):Refresher{return {getState:()=>({status:"idle"}),refresh:async()=>{}};}',
 'import type {Refresher,Task,LoadState} from "./model";export function createTaskRefresher(request:()=>Promise<readonly Task[]>):Refresher{let state:LoadState={status:"idle"},version=0;return {getState:()=>state,async refresh(){const current=++version;state={status:"loading"};try{const data=await request();if(current===version)state={status:"success",data:[...data]};}catch(error){if(current===version)state={status:"error",message:error instanceof Error&&error.message.trim()!==""?error.message:"加载失败"};}}};}',[
 ok('刷新接口可用','import {createTaskRefresher} from "./main";import type {Refresher} from "./model";const service:Refresher=createTaskRefresher(async()=>[]);const result:Promise<void>=service.refresh();'),
 bad('请求仍返回任务数组','import {createTaskRefresher} from "./main";createTaskRefresher(async()=>1);'),
 ],'每次刷新拥有自己的版本号。无论旧请求成功还是失败，结束时都检查自己是否仍是最新；只有最新结果能改变当前状态。','刷新开始先递增版本。｜旧结果完成时比较版本。｜两个结束分支都要检查。',{supportFiles:{'model.ts':taskModel+'\nexport type LoadState={status:"idle"}|{status:"loading"}|{status:"success";data:readonly Task[]}|{status:"error";message:string};export interface Refresher{getState():LoadState;refresh():Promise<void>}'},runtime:[{name:'后发请求成功时忽略旧失败',code:'const {createTaskRefresher}=load("main.js");let resolveOld,rejectOld,resolveNew,calls=0;const old=new Promise((resolve,reject)=>{resolveOld=resolve;rejectOld=reject;});const fresh=new Promise(resolve=>resolveNew=resolve);const loader=createTaskRefresher(()=>++calls===1?old:fresh);const first=loader.refresh();equal(loader.getState(),{status:"loading"});const second=loader.refresh();equal(calls,2);const data=Object.freeze([{id:"new",title:"New",tags:[],state:"open"}]);resolveNew(data);await second;equal(loader.getState(),{status:"success",data});check(loader.getState().data!==data);rejectOld(Error("old failed"));await first;equal(loader.getState(),{status:"success",data});'},{name:'新失败后旧成功不能覆盖',code:'const {createTaskRefresher}=load("main.js");let resolveOld,rejectNew,calls=0;const old=new Promise(resolve=>resolveOld=resolve),fresh=new Promise((resolve,reject)=>rejectNew=reject);const loader=createTaskRefresher(()=>++calls===1?old:fresh);const first=loader.refresh(),second=loader.refresh();rejectNew(Error("new failed"));await second;equal(loader.getState(),{status:"error",message:"new failed"});resolveOld([{id:"old",title:"Old",tags:[],state:"open"}]);await first;equal(loader.getState(),{status:"error",message:"new failed"});'}]}),
 m(3,9,'复测：重试不能无限循环','自动重试需要怎样的边界才能让失败可处理？',['限制最大尝试次数并报告最终失败，成功则立即停止','遇到错误永远重试','在类型上写 Promise<void> 就会自动限制次数','只在第一次尝试成功时停止'],'重试是业务策略。尝试次数、停止条件和最终错误信息都应明确，并用调用次数测试。','失败可能持续多久？｜成功之后还能再请求吗？｜记录实际次数。'),
 t(3,10,'复测：有上限的异步重试','实现 retryTasks(request:()=>Promise<readonly Task[]>,maxAttempts:number):Promise<RetryResult>。maxAttempts 必须是 1–5 的安全整数，否则立刻抛 RangeError，且不调用 request。最多尝试指定次数；成功立即返回复制的新数组和实际 attempts；全部失败返回最后的非空 Error.message，其他错误用“加载失败”，不返回部分任务。',
 'import type {RetryResult} from "./model";export async function retryTasks(request:()=>Promise<readonly import("./model").Task[]>,maxAttempts:number):Promise<RetryResult>{return {ok:false,attempts:0,message:"failed"};}',
 'import type {RetryResult,Task} from "./model";export async function retryTasks(request:()=>Promise<readonly Task[]>,maxAttempts:number):Promise<RetryResult>{if(!Number.isSafeInteger(maxAttempts)||maxAttempts<1||maxAttempts>5)throw new RangeError("invalid attempts");let message="加载失败";for(let attempt=1;attempt<=maxAttempts;attempt++){try{const items=await request();return {ok:true,items:[...items],attempts:attempt};}catch(error){message=error instanceof Error&&error.message.trim()!==""?error.message:"加载失败";}}return {ok:false,attempts:maxAttempts,message};}',[
 ok('结果联合可分支使用','import {retryTasks} from "./main";const result=retryTasks(async()=>[],3);async function read(){const value=await result;if(value.ok){const count:number=value.attempts;}}'),
 bad('请求必须提供任务数组','import {retryTasks} from "./main";retryTasks(async()=>"bad",2);'),
 ],'限制次数后再开始请求。每次失败更新最后的可显示信息；一旦成功立即停止，并复制列表防止外部后续修改影响结果。','先验证上限。｜for 循环顺序等待每次结果。｜成功提前返回，全部失败才汇总。',{supportFiles:{'model.ts':taskModel+'\nexport type RetryResult={ok:true;items:readonly Task[];attempts:number}|{ok:false;attempts:number;message:string};'},runtime:[{name:'成功停止与列表独立',code:'const {retryTasks}=load("main.js");let calls=0;const data=Object.freeze([{id:"a",title:"A",tags:[],state:"open"}]);const result=await retryTasks(async()=>{calls++;if(calls<3)throw Error("temporary");return data;},5);equal(result,{ok:true,items:data,attempts:3});check(result.items!==data);equal(calls,3);'},{name:'次数上限与最后错误',code:'const {retryTasks}=load("main.js");let calls=0;const failed=await retryTasks(async()=>{calls++;if(calls===1)throw Error("old");throw Error("final");},2);equal(failed,{ok:false,attempts:2,message:"final"});equal(calls,2);for(const count of [0,6,-1,1.5,NaN,Infinity]){let error;try{await retryTasks(async()=>{calls++;return [];},count);}catch(e){error=e;}check(error&&error.name==="RangeError");}equal(calls,2);'}]}),

 m(4,1,'导入文件的信任边界','用户选择的 JSON 文件内容进入任务管理器前，为什么不能直接写成 Task[]？',['文件内容不受本地类型系统控制，需要解析并验证每项任务','扩展名 .json 保证每个字段都合法','Task[] 标注会在运行时过滤坏项','只要能读到文本就代表可导入'],'外部文件既可能不是合法 JSON，也可能语法合法而业务结构错误。导入函数要分别处理。','语法正确和模型正确分几步？｜用户文件从哪里来？｜运行验证建立信任。'),
 m(4,2,'解析成功后的类型','JSON.parse("null") 可以成功，是否意味着得到了任务数组？',['不意味着，解析成功只获得一个运行值，还需检查数组与每项结构','意味着，JSON.parse 总返回数组','意味着，null 会自动转成空数组','不意味着，因为 null 不是合法 JSON'],'JSON 语法与任务协议是两层。空数组可以合法，但 null、对象或坏条目不能冒充集合。','null 是合法 JSON。｜返回值的实际形状是什么？｜再验证业务元素。'),
 m(4,3,'导入时静默丢弃坏任务','导入 10 条记录，过滤掉 2 条不合法项后报告“10 条全部成功”，有什么问题？',['会让用户误以为完整保存，应明确失败位置或取得明确的部分导入授权','类型检查会自动补回两条','只要数组类型是 Task[] 就没问题','所有导入都必须静默忽略错误'],'全有或全无的导入需收集错误并拒绝发布部分结果。错误位置能帮助用户修复文件。','用户预期处理了几条？｜哪些条目坏了？｜错误要可定位。'),
 t(4,4,'区分 JSON 语法失败','实现 decodeTaskFile(text:string):DecodeResult。只读 model.ts 定义成功 {ok:true;raw:unknown}、失败 {ok:false;reason:"syntax"}。文本语法错误返回失败，不抛出；任何语法合法的 JSON，包括 null 和对象，都原样作为 unknown 返回，留给下一步验证。',
 'import type {DecodeResult} from "./model";export function decodeTaskFile(text:string):DecodeResult{return {ok:true,raw:JSON.parse(text)};}',
 'import type {DecodeResult} from "./model";export function decodeTaskFile(text:string):DecodeResult{try{return {ok:true,raw:JSON.parse(text)};}catch{return {ok:false,reason:"syntax"};}}',[
 ok('解码成功仍是未知值','import {decodeTaskFile} from "./main";const result=decodeTaskFile("[]");if(result.ok){const raw:unknown=result.raw;}'),
 bad('未知值不能直接当任务列表','import {decodeTaskFile} from "./main";import type {Task} from "./model";const result=decodeTaskFile("[]");if(result.ok){const tasks:Task[]=result.raw;}'),
 ],'只处理 JSON 语法这一步。成功结果仍保留 unknown，避免解码成功时便假定业务数据可信。','用 try/catch 包住解析。｜成功不要给 raw 过度承诺。｜null 也是合法 JSON。',{supportFiles:{'model.ts':taskModel+'\nexport type DecodeResult={ok:true;raw:unknown}|{ok:false;reason:"syntax"};'},runtime:[{name:'合法内容不提前伪造任务',code:'const {decodeTaskFile}=load("main.js");equal(decodeTaskFile("null"),{ok:true,raw:null});equal(decodeTaskFile("[]"),{ok:true,raw:[]});equal(decodeTaskFile("{}"),{ok:true,raw:{}});equal(decodeTaskFile("{bad"),{ok:false,reason:"syntax"});'}]}),
 m(4,5,'逐字段错误位置','任务记录有坏字段时，比只返回 false 更有帮助的结果是什么？',['返回哪个字段失败，让导入层再附上记录索引','返回整个输入对象并宣称成功','随便返回一个字段名即可','把所有坏值改成空字符串'],'先按模型规则验证字段并返回定位信息，批量导入再组合索引，用户才能修复来源文件。','具体哪里不合规？｜单项函数知道字段。｜列表函数知道索引。'),
 t(4,6,'验证单项导入记录','实现 validateTask(raw:unknown):ParseResult。只读 model.ts 定义 Task；失败返回首个字段名，检查顺序 id/title/tags/state/completedAt。id/title 修剪后非空；tags 是成员非空的字符串数组并修剪去重。open 不许有 completedAt 键，done 要非负安全整数时间；成功只返回公开字段的新对象。整体形状错记 id。',
 'import type {Task} from "./model";export type ParseResult={ok:true;task:Task}|{ok:false;field:"id"|"title"|"tags"|"state"|"completedAt"};export function validateTask(raw:unknown):ParseResult{return {ok:false,field:"id"};}',
 recordParser,[
 ok('成功后可读取任务','import {validateTask} from "./main";const result=validateTask({});if(result.ok){const id:string=result.task.id;}'),
 bad('失败分支不含任务','import {validateTask} from "./main";const result=validateTask({});if(!result.ok){const task=result.task;}'),
 ],'按字段顺序检查可稳定定位第一个问题。成功投影为新对象并按状态构造正确分支；外部额外字段不会进入任务模型。','整体形状先验证。｜共同字段依次检查。｜再区分 open/done 时间规则。',{supportFiles:{'model.ts':taskModel},runtime:[{name:'状态合法且字段规范化',code:'const {validateTask}=load("main.js");const raw=Object.freeze({id:" a ",title:" A ",tags:Object.freeze([" x ","x"]),state:"open",secret:1});equal(validateTask(raw),{ok:true,task:{id:"a",title:"A",tags:["x"],state:"open"}});equal(validateTask({id:"b",title:"B",tags:[],state:"done",completedAt:0}),{ok:true,task:{id:"b",title:"B",tags:[],state:"done",completedAt:0}});equal(raw.id," a ");'},{name:'首个错误字段明确',code:'const {validateTask}=load("main.js");for(const [raw,field] of [[null,"id"],[{id:" ",title:"A",tags:[],state:"open"},"id"],[{id:"a",title:" ",tags:[],state:"open"},"title"],[{id:"a",title:"A",tags:[""],state:"open"},"tags"],[{id:"a",title:"A",tags:[],state:"other"},"state"],[{id:"a",title:"A",tags:[],state:"open",completedAt:undefined},"completedAt"],[{id:"a",title:"A",tags:[],state:"done",completedAt:-1},"completedAt"]])equal(validateTask(raw),{ok:false,field});'}]}),
 m(4,7,'批量导入中的重复 ID','两条各自合法的记录使用同一 ID，批量导入还需要什么检查？',['在列表层检查重复 ID，并指出重复条目的位置','单项解析器自然知道列表里所有记录','重复 ID 会自动被 Map 修复','只要标题不同就允许重复 ID'],'单项验证和集合约束互补。批量导入应在验证每项后检查跨项唯一性。','单项函数能看到其他记录吗？｜ID 是集合键。｜记录重复发生的索引。'),
 t(4,8,'迁移：全有或全无导入列表','只读 validator.ts 提供 validateTask。实现 importTaskList(raw:unknown):ImportResult。整体必须是数组，否则报 {index:-1,field:"items"}；逐项验证，记录 {index,field}；有效条目 id 重复则该条报 id。按输入顺序累计所有错误，有错误只返回错误列表；全通过才返回新 Task[]。',
 'import {validateTask} from "./validator";import type {Task} from "./model";export type ImportResult={ok:true;tasks:Task[]}|{ok:false;errors:{index:number;field:string}[]};export function importTaskList(raw:unknown):ImportResult{return {ok:true,tasks:[]};}',
 importList,[
 ok('正确结果分支','import {importTaskList} from "./main";import type {Task} from "./model";const result=importTaskList([]);if(result.ok){const tasks:Task[]=result.tasks;}'),
 bad('错误分支没有完整列表','import {importTaskList} from "./main";const result=importTaskList([]);if(!result.ok){const tasks=result.tasks;}'),
 ],'复用单项验证器，在列表层追加索引和重复 ID 规则。不能静默过滤坏项，否则会把不完整数据当成完整成功。','先验证数组。｜逐项解析并记索引。｜合法项再检查 ID 冲突。',{supportFiles:{'model.ts':taskModel,'validator.ts':recordParser},runtime:[{name:'空与合法列表返回新数据',code:'const {importTaskList}=load("main.js");equal(importTaskList([]),{ok:true,tasks:[]});const raw=Object.freeze([{id:" a ",title:"A",tags:[],state:"open"},{id:"b",title:"B",tags:[],state:"done",completedAt:0}]);const result=importTaskList(raw);equal(result,{ok:true,tasks:[{id:"a",title:"A",tags:[],state:"open"},{id:"b",title:"B",tags:[],state:"done",completedAt:0}]});check(result.tasks!==raw);'},{name:'定位坏字段与重复 ID，拒绝部分导入',code:'const {importTaskList}=load("main.js");equal(importTaskList(null),{ok:false,errors:[{index:-1,field:"items"}]});const raw=[{id:"a",title:"A",tags:[],state:"open"},{id:"a",title:"B",tags:[],state:"open"},{id:"c",title:"C",tags:[""],state:"open"},{id:"d",title:"D",tags:[],state:"done"}];equal(importTaskList(raw),{ok:false,errors:[{index:1,field:"id"},{index:2,field:"tags"},{index:3,field:"completedAt"}]});'}]}),
 m(4,9,'复测：导入与现有任务冲突','导入列表内部没有重复 ID，但与当前已有任务冲突，导入流程应在哪里检查？',['合并步骤还要对比现有 ID，冲突时保持当前列表不变','列表内部去重已经覆盖所有外部冲突','只要任务标题不同就直接覆盖','先把当前列表清空再导入'],'数据入库时还要满足当前集合的约束。即使导入文件本身合法，合并仍可能失败。','新数据与已有数据是两份集合。｜唯一性需要跨集合检查。｜失败不能产生部分合并。'),
 t(4,10,'复测：事务式合并导入','只读 importer.ts 提供 importTaskList。实现 mergeImport(existing:readonly Task[],raw:unknown):MergeResult。导入无效时把每个错误映射成 index:field；合法导入与现有 ID 冲突则按导入顺序返回 duplicate:id 错误。任一错误都不改变 existing、不返回部分任务；全通过才返回由原任务引用加新任务构成的新数组。',
 'import {importTaskList} from "./importer";import type {Task} from "./model";export type MergeResult={ok:true;tasks:Task[]}|{ok:false;errors:string[]};export function mergeImport(existing:readonly Task[],raw:unknown):MergeResult{return {ok:true,tasks:[...existing]};}',
 'import {importTaskList} from "./importer";import type {Task} from "./model";export type MergeResult={ok:true;tasks:Task[]}|{ok:false;errors:string[]};export function mergeImport(existing:readonly Task[],raw:unknown):MergeResult{const parsed=importTaskList(raw);if(!parsed.ok)return {ok:false,errors:parsed.errors.map(error=>`${error.index}:${error.field}`)};const ids=new Set(existing.map(task=>task.id));const conflicts=parsed.tasks.filter(task=>ids.has(task.id)).map(task=>`duplicate:${task.id}`);return conflicts.length?{ok:false,errors:conflicts}:{ok:true,tasks:[...existing,...parsed.tasks]};}',[
 ok('合并结果分支可用','import {mergeImport} from "./main";import type {Task} from "./model";const result=mergeImport([],[]);if(result.ok){const tasks:Task[]=result.tasks;}'),
 bad('失败结果不暴露部分任务','import {mergeImport} from "./main";const result=mergeImport([],null);if(!result.ok){const tasks=result.tasks;}'),
 ],'合并步骤继续检查现有 ID 冲突。解析或合并失败都只返回可定位错误；成功返回新数组并保留原有任务对象引用。','先调用导入解析器。｜然后对比 existing ID。｜无错误才组合数组。',{supportFiles:{'model.ts':taskModel,'validator.ts':recordParser,'importer.ts':importList},runtime:[{name:'合法合并与现有引用不变',code:'const {mergeImport}=load("main.js");const existing=Object.freeze([{id:"a",title:"A",tags:[],state:"open"}]),raw=Object.freeze([{id:"b",title:" B ",tags:[],state:"open"}]);const result=mergeImport(existing,raw);equal(result,{ok:true,tasks:[existing[0],{id:"b",title:"B",tags:[],state:"open"}]});check(result.tasks!==existing&&result.tasks[0]===existing[0]);equal(existing.length,1);'},{name:'冲突与导入错误都不产生部分结果',code:'const {mergeImport}=load("main.js"),existing=Object.freeze([{id:"a",title:"A",tags:[],state:"open"}]);equal(mergeImport(existing,[{id:"a",title:"Other",tags:[],state:"open"},{id:"b",title:"B",tags:[],state:"open"}]),{ok:false,errors:["duplicate:a"]});equal(mergeImport(existing,[{id:"b",title:"B",tags:[],state:"open"},{id:"c",title:"C",tags:[""],state:"open"}]),{ok:false,errors:["1:tags"]});equal(existing.length,1);'}]}),

 m(5,1,'共享模型的归属','store.ts、view.ts 都需要 Task，模型由谁提供更稳妥？',['由清晰的共享契约模块导出，两边导入同一个类型','两个模块分别复制一份相似接口','view.ts 直接把输入写成 any','只靠文件名相同即可共享类型'],'共享契约减少漂移。修改模型后，让各模块和调用测试一起检查，能更早发现不一致。','有几份 Task 定义？｜修改状态要改几处？｜统一来源。'),
 m(5,2,'类型导出与值导出','公共入口需要导出 Task 类型和 createTask 函数，哪种做法更能表达运行时差异？',['用 export type 导出模型，用普通 export 导出实际函数','把所有内容都写成 type 导出','把 Task 接口当运行时构造函数','用类型断言让未实现函数可调用'],'类型导出会被擦除，实际函数需要保留运行出口。公共入口还应控制不需要暴露的内部名称。','哪些是纯静态模型？｜哪些是运行值？｜入口作为明确白名单。'),
 m(5,3,'改完一处后为什么仍报错','修改 model.ts 后，service.ts 或 view.ts 出现诊断，应怎么理解？',['依赖模块使用了旧契约，需要沿导入链修正并验证行为','编译器只随机检查其中一个文件','复制一份旧模型到每个文件即可','关闭所有检查就代表需求完成'],'多文件练习的价值在于让契约变化传导。诊断指向具体依赖用法，可以帮助定位仍未同步的模块。','谁导入了模型？｜报错位置属于哪个用法？｜修正后复测运行行为。'),
 t(5,4,'修复被两个模块共享的任务契约','只编辑 model.ts，导出 TaskBase、OpenTask、DoneTask、Task。只读 store.ts 和 view.ts 都导入它：open 不带数值完成时间，done 必须有完成时间，id/title/tags 只读。修复宽泛的 state 与可选时间模型，使两个模块均可使用且非法组合被拒绝。',
 {'model.ts':'export type Task={id:string;title:string;tags:string[];state:string;completedAt?:number};'},
 {'model.ts':taskModel},[
 ok('公共模块可以创建并展示','import {getSample} from "./store";import {render} from "./view";import type {Task} from "./model";const task:Task=getSample();const text:string=render(task);'),
 bad('完成态不能缺时间','import type {Task} from "./model";const task:Task={id:"a",title:"A",tags:[],state:"done"};'),
 bad('待办已有变量仍拒绝完成时间','import type {Task} from "./model";const input={id:"a",title:"A",tags:[],state:"open" as const,completedAt:1};const task:Task=input;'),
 bad('共享模型标题只读','import type {Task} from "./model";declare const task:Task;task.title="x";'),
 ],'两个只读模块直接消费同一 Task 契约。模型修复后可由类型用例验证非法状态，并用实际展示调用检查正常流程。','找到 state 与 completedAt 的关联。｜抽取共享字段。｜让 store/view 保持同一模型。',{supportFiles:{'store.ts':'import type {OpenTask} from "./model";export function getSample():OpenTask{return {id:"a",title:"A",tags:[],state:"open"};}','view.ts':'import type {Task} from "./model";export function render(task:Task):string{return task.state==="done"?`${task.title}@${task.completedAt}`:task.title;}'},runtime:[{name:'跨模块创建与展示',code:'const {getSample}=load("store.js"),{render}=load("view.js");equal(render(getSample()),"A");equal(render({id:"b",title:"B",tags:[],state:"done",completedAt:0}),"B@0");'}]}),
 m(5,5,'公共入口的边界','库内部模块有 debugValue，但入口只需要 createTask。若用 export * 全部转出，有什么影响？',['调试字段也成为公开 API，调用者可能依赖它；应明确导出白名单','export * 会自动清理所有内部字段','只有类型能穿过 export *','输出文件会因此自动打包'],'公开出口决定使用方能看到什么。题目会验证真实函数保留，同时内部名称不可从入口导入。','入口有什么职责？｜内部调试名称会被转出吗？｜列出真正要暴露的符号。'),
 t(5,6,'设计只暴露必要能力的入口','只编辑 index.ts。共享模型 model.ts 和实现 internal.ts 均只读。公共入口需提供 Task 类型与 createTask 值函数，不能再公开 debugValue；调用 createTask("a"," A ") 返回规范的 open 任务。',
 'export * from "./model";export * from "./internal";',
 'export type {Task} from "./model";export {createTask} from "./internal";',[
 ok('公开类型与值可用','import {createTask} from "./index";import type {Task} from "./index";const task:Task=createTask("a","A");'),
 bad('内部调试值不能由入口导入','import {debugValue} from "./index";const value:string=debugValue;',[2305]),
 bad('创建函数拒绝数值标题','import {createTask} from "./index";createTask("a",1);'),
 ],'公共入口是稳定边界。显式类型导出不会制造运行值，普通函数导出仍能被调用；内部调试字段留在实现模块。','保留 Task 类型。｜保留 createTask 函数。｜移除星号转出。',{supportFiles:{'model.ts':taskModel,'internal.ts':'import type {OpenTask} from "./model";export const debugValue="internal";export function createTask(id:string,title:string):OpenTask{const clean=title.trim();if(id.trim()===""||clean==="")throw new RangeError("invalid task");return {id:id.trim(),title:clean,tags:[],state:"open"};}'},runtime:[{name:'公开函数实际可调用且内部值不外泄',code:'const api=load("index.js");equal(api.createTask(" a "," A "),{id:"a",title:"A",tags:[],state:"open"});check(!Object.hasOwn(api,"debugValue"));equal(load("internal.js").debugValue,"internal");'}]}),
 m(5,7,'修改多文件函数时的引用规则','完成任务函数返回新对象，但仍复用原 tags 数组，若需求要求数组也独立，该如何验证？',['比较输入与输出的数组引用，并用冻结输入测试行为','只看返回类型 DoneTask','把原对象标注为 readonly 就会自动复制数组','把 tags 改名为 copiedTags'],'不可变性有具体层级。类型约束和运行时引用检查一起验证，不应把浅复制当成完全独立的输出。','两个对象的 tags 指向同一个数组吗？｜类型会自动复制吗？｜运行断言引用。'),
 t(5,8,'迁移：模型与业务实现共同修复','同时编辑 model.ts 和 service.ts。共享 Task 契约须区分 open/done，保留只读字段；complete(task:OpenTask,at:number):DoneTask 验证非负安全整数时间、返回新任务并复制 tags，不修改输入。只读 view.ts 会展示两种任务。',
 {'model.ts':'export type Task={id:string;title:string;tags:string[];state:string;completedAt?:number};export type OpenTask=Task;export type DoneTask=Task;','service.ts':'import type {OpenTask,DoneTask} from "./model";export function complete(task:OpenTask,at:number):DoneTask{return {...task,state:"done",completedAt:at};}'},
 {'model.ts':taskModel,'service.ts':'import type {OpenTask,DoneTask} from "./model";export function complete(task:OpenTask,at:number):DoneTask{if(!Number.isSafeInteger(at)||at<0)throw new RangeError("invalid time");return {id:task.id,title:task.title,tags:[...task.tags],state:"done",completedAt:at};}'},[
 ok('跨模块状态转换可用','import {complete} from "./service";import {render} from "./view";import type {OpenTask,DoneTask} from "./model";declare const open:OpenTask;const done:DoneTask=complete(open,0);const text:string=render(done);'),
 bad('已完成任务不应再次完成','import {complete} from "./service";import type {DoneTask} from "./model";declare const done:DoneTask;complete(done,1);'),
 bad('待办状态不带数值完成时间','import type {OpenTask} from "./model";const task:OpenTask={id:"a",title:"A",tags:[],state:"open",completedAt:1};'),
 ],'两个可编辑模块需一起修复：正确模型阻止非法调用，实际函数验证时间并复制数据。只读展示模块提供跨文件的行为检查。','先建立 OpenTask/DoneTask。｜函数输入只接受 open。｜输出新任务和新标签数组。',{supportFiles:{'view.ts':'import type {Task} from "./model";export function render(task:Task):string{return task.state==="done"?`${task.title}@${task.completedAt}`:task.title;}'},runtime:[{name:'完成态和展示行为',code:'const {complete}=load("service.js"),{render}=load("view.js");const tags=Object.freeze(["x"]),open=Object.freeze({id:"a",title:"A",tags,state:"open"});const done=complete(open,0);equal(done,{id:"a",title:"A",tags:["x"],state:"done",completedAt:0});equal(render(done),"A@0");check(done!==open&&done.tags!==tags);equal(open.state,"open");let error;try{complete(open,-1);}catch(e){error=e;}check(error&&error.name==="RangeError");'}]}),
 m(5,9,'复测：多文件验收','三个可编辑模块分别建模、实现和公开出口，怎样判断它们共同满足需求？',['检查非法状态与非法调用被拒绝，公开函数可以运行，模块只暴露约定名称','只看每个文件独立能否转译','只检查 index.ts 的名字是否存在','只要入口 export * 就证明所有内容正确'],'多文件验收需要跨模块编译与运行调用。入口可能掩盖模型过宽，函数也可能有类型但返回错误行为。','契约如何跨文件流动？｜运行函数是否真可调用？｜内部名称是否外泄？'),
 t(5,10,'复测：完整公开任务模块','同时编辑 model.ts、service.ts、index.ts。定义区分 open/done 的只读 Task；提供 createTask(id,title):OpenTask（修剪且拒绝空白）与 finishTask(open,at):DoneTask（验证非负安全整数并复制标签）；index 只导出 Task/OpenTask/DoneTask 类型及两个函数，不能公开 debugValue。只读 app.ts 通过入口构建一组任务。',
 {'model.ts':'export type Task={id:string;title:string;tags:string[];state:string;completedAt?:number};export type OpenTask=Task;export type DoneTask=Task;','service.ts':'import type {OpenTask,DoneTask} from "./model";export const debugValue="internal";export function createTask(id:string,title:string):OpenTask{return {id,title,tags:[],state:"open"};}export function finishTask(task:OpenTask,at:number):DoneTask{return {...task,state:"done",completedAt:at};}','index.ts':'export * from "./model";export * from "./service";'},
 {'model.ts':taskModel,'service.ts':'import type {OpenTask,DoneTask} from "./model";export const debugValue="internal";export function createTask(id:string,title:string):OpenTask{const cleanId=id.trim(),cleanTitle=title.trim();if(cleanId===""||cleanTitle==="")throw new RangeError("invalid task");return {id:cleanId,title:cleanTitle,tags:[],state:"open"};}export function finishTask(task:OpenTask,at:number):DoneTask{if(!Number.isSafeInteger(at)||at<0)throw new RangeError("invalid time");return {id:task.id,title:task.title,tags:[...task.tags],state:"done",completedAt:at};}','index.ts':'export type {Task,OpenTask,DoneTask} from "./model";export {createTask,finishTask} from "./service";'},[
 ok('公开入口被消费者使用','import {buildList} from "./app";import {createTask,finishTask} from "./index";import type {Task,OpenTask,DoneTask} from "./index";const tasks:Task[]=buildList();const open:OpenTask=createTask("a","A");const done:DoneTask=finishTask(open,0);'),
 bad('完成态必须含时间','import type {Task} from "./index";const task:Task={id:"a",title:"A",tags:[],state:"done"};'),
 bad('完成态不能作为待办输入','import {finishTask} from "./index";import type {DoneTask} from "./index";declare const task:DoneTask;finishTask(task,1);'),
 bad('调试值不应通过公共入口','import {debugValue} from "./index";void debugValue;',[2305]),
 ],'跨模块公共入口、数据模型和业务函数必须同时成立。类型反例检验非法组合，运行测试通过只读 app.ts 调用公开 API，并确认内部调试值不外泄。','先修复模型。｜再让函数返回符合模型的真实值。｜入口只列公开类型和函数。',{supportFiles:{'app.ts':'import {createTask,finishTask} from "./index";import type {Task} from "./index";export function buildList():Task[]{return [createTask("a"," A "),finishTask(createTask("b","B"),0)];}'},runtime:[{name:'应用模块通过公共入口构建任务',code:'const api=load("index.js"),{buildList}=load("app.js");equal(buildList(),[{id:"a",title:"A",tags:[],state:"open"},{id:"b",title:"B",tags:[],state:"done",completedAt:0}]);check(!Object.hasOwn(api,"debugValue"));let error;try{api.createTask(" ","A");}catch(e){error=e;}check(error&&error.name==="RangeError");'},{name:'公开完成函数复制输入数据',code:'const {finishTask}=load("index.js");const tags=Object.freeze(["x"]),open=Object.freeze({id:"a",title:"A",tags,state:"open"});const done=finishTask(open,1);check(done!==open&&done.tags!==tags);equal(done,{id:"a",title:"A",tags:["x"],state:"done",completedAt:1});'}]}),

 m(6,1,'审查公共类型','公共接口里有 any，即使参考实现能运行，审查时为什么仍要处理？',['非法调用可能被放行并传播到其他模块，需要用正反调用验证约束','因为 any 会自动导致运行时报错','只要有运行测试就不需要类型约束','把 any 改成断言就能恢复检查'],'审查关注错误调用是否能被拒绝以及正常使用是否继续可用。类型与运行证据共同判断。','调用者能传什么？｜any 是否让坏调用通过？｜正反例都要看。'),
 m(6,2,'重复类型的漂移','同一 TaskView 在两个文件手写一遍，源模型改变后最容易发生什么？',['复制版本可能遗漏新约束，应从共享契约派生或统一来源','两个版本会自动同步','编辑器会删除其中一份','只能用 any 才能避免冲突'],'派生类型让公共视图随来源字段类型变化，同时可以明确选择要公开的字段。','模型谁维护？｜字段类型变化如何传播？｜Pick 选择公开范围。'),
 m(6,3,'修复时保留合法流程','发现有一个非法调用通过类型检查，能否直接把函数全部改为 never 来让它报错？',['不能，还需验证合法调用继续成功；修复必须保留所需能力','可以，红线越多越安全','可以，运行时会自动适配 never','只要注释说明即可'],'只让错误样例失败很容易，真正的修复还需通过正常用例和运行行为。','合法用户还要调用函数。｜正例是否仍通过？｜运行结果是否正确？'),
 t(6,4,'从共享模型派生公共视图','只编辑 public.ts。只读 canonical.ts 导出 Task，字段有 id/title/state/secret。公开 TaskView 只含 id/title/state 且字段类型随来源变化，不暴露 secret；来源模型的 title 类型在额外用例中可能扩展。',
 {'public.ts':'export interface TaskView{id:string;title:string;state:string;secret?:string}'},
 {'public.ts':'import type {Task} from "./canonical";export type TaskView=Pick<Task,"id"|"title"|"state">;'},[
 ok('公共视图保持来源字段','import type {TaskView} from "./public";const view:TaskView={id:"a",title:"A",state:"open"};'),
 bad('不能公开内部字段','import type {TaskView} from "./public";const view:TaskView={id:"a",title:"A",state:"open",secret:"private"};'),
 bad('状态只能取来源允许值','import type {TaskView} from "./public";const view:TaskView={id:"a",title:"A",state:"paused"};'),
 {name:'来源 title 扩展时同步公共视图',expect:'pass',supportFiles:{'canonical.ts':'export interface Task{id:string;title:string|number;state:"open"|"done";secret:string}'},code:'import type {TaskView} from "./public";const view:TaskView={id:"a",title:42,state:"done"};'},
 ],'Pick 让字段类型来自单一模型，并限定公开白名单。额外模型变体检验类型变化是否被正确传递，不接受硬编码当前字符串标题。','导入 Task 来源。｜只挑公开三字段。｜验证来源 title 改变后的推断。',{supportFiles:{'canonical.ts':'export interface Task{id:string;title:string;state:"open"|"done";secret:string}'}}),
 m(6,5,'只读模型的补丁边界','任务补丁只允许修改 title/tags，为什么直接写 Partial<Task> 不够精确？',['它还会允许 id、状态等字段进入补丁类型，需要限制可编辑键','Partial 会自动验证运行时输入','Partial 会禁止修改所有字段','Pick 只能用于运行时对象'],'工具类型可以组合，但应从业务白名单出发。运行实现也不能让未授权字段通过对象展开覆盖身份。','Task 中哪些字段可变？｜Partial 作用于哪些字段？｜先 Pick 再 Partial。'),
 t(6,6,'设计安全的任务补丁','实现 TaskPatch 与 patchTask(current:Task,patch:TaskPatch):Task。只允许可选 title、tags，不允许 id/state/completedAt。title 有值时修剪且须非空；tags 有值时每项修剪且须非空并复制新数组。返回新任务对象，保留状态与完成时间、当前对象和数组不变。',
 'import type {Task} from "./model";export type TaskPatch=Partial<Task>;export function patchTask(current:Task,patch:TaskPatch):Task{return {...current,...patch};}',
 'import type {Task} from "./model";export type TaskPatch=Partial<Pick<Task,"title"|"tags">>;export function patchTask(current:Task,patch:TaskPatch):Task{const title=patch.title===undefined?current.title:patch.title.trim();if(title==="")throw new RangeError("invalid title");const tags=patch.tags===undefined?[...current.tags]:patch.tags.map(tag=>{const clean=tag.trim();if(clean==="")throw new RangeError("invalid tag");return clean;});return {...current,title,tags};}',[
 ok('合法标题和标签补丁','import {patchTask} from "./main";import type {Task} from "./model";declare const task:Task;const updated:Task=patchTask(task,{title:"A",tags:["x"]});'),
 bad('补丁不能修改身份','import {patchTask} from "./main";import type {Task} from "./model";declare const task:Task;patchTask(task,{id:"other"});'),
 bad('补丁不能伪造状态','import {patchTask} from "./main";import type {Task} from "./model";declare const task:Task;patchTask(task,{state:"done"});'),
 bad('补丁不能伪造完成时间','import {patchTask} from "./main";import type {Task} from "./model";declare const task:Task;patchTask(task,{completedAt:1});'),
 ],'可编辑键由 Pick 白名单定义，再用 Partial 表示可选。运行实现只投影允许的字段，不把整个 patch 展开到任务上。','先定义补丁白名单。｜处理可选标题与标签。｜最后仅重建允许字段。',{supportFiles:{'model.ts':taskModel},runtime:[{name:'身份和状态保持、输入独立',code:'const {patchTask}=load("main.js");const tags=Object.freeze(["old"]),task=Object.freeze({id:"a",title:"A",tags,state:"done",completedAt:2});const next=patchTask(task,{title:" New ",tags:[" x "]});equal(next,{id:"a",title:"New",tags:["x"],state:"done",completedAt:2});check(next!==task&&next.tags!==tags);equal(task.title,"A");const unchanged=patchTask(task,{});check(unchanged!==task&&unchanged.tags!==tags);'},{name:'空白值按需求拒绝',code:'const {patchTask}=load("main.js"),task={id:"a",title:"A",tags:[],state:"open"};for(const patch of [{title:" "},{tags:[" "]}]){let error;try{patchTask(task,patch);}catch(e){error=e;}check(error&&error.name==="RangeError");}'}]}),
 m(6,7,'宽泛辅助函数的风险','把每个外部值都写成 `value as Task`，即使正例通过了，审查还应关注什么？',['错误对象是否也被接纳；应让真实验证器建立可信 Task','只要有一个正例就足够','断言会自动删除额外字段','把断言改为 any 就能改善质量'],'单个正例无法证明边界安全。典型坏输入、缺字段和非法状态需要被拒绝。','查看反例。｜断言不产生校验。｜已有验证器可以复用。'),
 t(6,8,'迁移：用类型谓词代替万能断言','实现 guardValue<T>(value:unknown,guard:(input:unknown)=>input is T):T|null。仅调用 guard 一次；为 true 返回原值，为 false 返回 null。不使用 any/断言。必须保留泛型推断，能处理 Task 和其他模型。',
 'export function guardValue<T>(value:unknown,guard:(input:unknown)=>input is T):T{return value as T;}',
 'export function guardValue<T>(value:unknown,guard:(input:unknown)=>input is T):T|null{return guard(value)?value:null;}',[
 ok('泛型守卫保留模型','import {guardValue} from "./main";import type {Task} from "./model";declare const raw:unknown,guard:(value:unknown)=>value is Task;const task:Task|null=guardValue(raw,guard);'),
 bad('调用者不能忽略失败','import {guardValue} from "./main";const result:number=guardValue(1,(value):value is number=>typeof value==="number");'),
 {name:'不同模型仍由守卫推导',expect:'pass',code:'import {guardValue} from "./main";const label:string|null=guardValue("x",(value):value is string=>typeof value==="string");'},
 ],'类型谓词在调用处提供真实缩窄证据，泛型保留校验器决定的目标类型。不能把未知输入直接断言成目标；运行测试检查守卫调用次数与原值引用。','让 guard 决定是否可信。｜true 分支 TS 能缩窄 value。｜false 分支明确返回 null。',{supportFiles:{'model.ts':taskModel},runtime:[{name:'只运行一次守卫且保留原对象',code:'const {guardValue}=load("main.js");const input=Object.freeze({id:"a"});let calls=0;const result=guardValue(input,value=>{calls++;return value===input;});check(result===input);equal(calls,1);equal(guardValue(1,value=>typeof value==="string"),null);'}]}),
 m(6,9,'复测：审查完成的证据','修复了编译器红线后，什么证据能更充分说明公共 API 真的更安全？',['合法调用继续通过，非法调用被拒绝，运行时边界与行为用例通过','只看错误总数变成零','只看代码里不再有 any 字符串','只看函数注释写了安全'],'审查必须同时验证能力和约束。类型检查发现错用，运行测试确认真实边界与业务行为。','合法与非法调用都要看。｜静态与运行证据互补。｜不可只数红线。'),
 t(6,10,'复测：审核导入验证公开入口','只读 validator.ts 导出 validateTask(raw:unknown)，可返回成功 Task 或失败字段。实现 readImported(raw:unknown):Result：成功只返回验证后的 task；失败返回 {ok:false,message:"invalid:字段名"}。Result 由只读 model.ts 定义。不能断言 raw 为 Task 或用 any 放宽入口，不能绕过验证器。',
 'import type {Result,Task} from "./model";export function readImported(raw:unknown):Result{return {ok:true,task:raw as Task};}',
 'import {validateTask} from "./validator";import type {Result} from "./model";export function readImported(raw:unknown):Result{const result=validateTask(raw);return result.ok?{ok:true,task:result.task}:{ok:false,message:`invalid:${result.field}`};}',[
 ok('结果按分支使用','import {readImported} from "./main";const result=readImported({});if(result.ok){const id:string=result.task.id;}else{const message:string=result.message;}'),
 bad('错误分支没有任务','import {readImported} from "./main";const result=readImported({});if(!result.ok){const task=result.task;}'),
 ],'把不可信输入交给真实验证器，公共入口只处理已验证的结果或可定位错误。运行测试核对成功值规范化以及非法状态拒绝。','调用只读 validateTask。｜成功取返回 task。｜失败利用 field 构造消息。',{supportFiles:{'model.ts':taskModel+'\nexport type Result={ok:true;task:Task}|{ok:false;message:string};','validator.ts':recordParser},runtime:[{name:'验证成功后仅返回公开任务',code:'const {readImported}=load("main.js");equal(readImported({id:" a ",title:" A ",tags:[],state:"open",secret:1}),{ok:true,task:{id:"a",title:"A",tags:[],state:"open"}});'},{name:'非法任务不被断言成成功',code:'const {readImported}=load("main.js");equal(readImported({id:"a",title:"A",tags:[],state:"done"}),{ok:false,message:"invalid:completedAt"});equal(readImported({id:" ",title:"A",tags:[],state:"open"}),{ok:false,message:"invalid:id"});'}]}),

 m(7,1,'新增状态会影响哪里','Task 从 open/done 增加 archived，为什么只改模型还不足以完成需求？',['创建与转换、展示、筛选及外部数据解析都可能需要处理新分支','类型模型变了，运行逻辑会自动补齐','只要网页多一个颜色就完整了','新增状态不会影响已有模块'],'状态是跨模块契约。类型错误能提示部分遗漏，但运行输出和导入旧数据仍需要测试。','哪些模块读取 state？｜哪些模块产生状态？｜外部文件也可能出现新状态。'),
 m(7,2,'归档和完成是否相同','需求新增 archivedAt，表示从待办归档；把 archived 直接当 done 并复用 completedAt 有什么风险？',['混淆业务含义，应给 archived 独立判别分支和归档时间','两个字段都是 number，因此语义完全相同','TypeScript 会自动把 archivedAt 改名','归档任务无法被展示'],'字段类型相同不代表业务语义相同。独立分支便于禁止归档任务携带错误时间字段。','完成与归档对应哪种操作？｜使用哪个时间字段？｜非法组合如何排除？'),
 m(7,3,'穷尽检查的提示','switch 已覆盖 open/done，模型加入 archived 后，默认分支给 task 赋值为 never 出错，说明什么？',['还有新状态未处理，需要为 archived 补上业务逻辑','编译器不能识别 switch','应该删掉新状态类型','给 task 加 any 即可证明处理完成'],'穷尽检查使需求变化显现为需要修复的代码位置。修好静态分支后还需验证输出内容。','剩下的分支是什么？｜为什么不再是 never？｜为新状态实现行为。'),
 t(7,4,'为项目添加归档任务模型','只编辑 model.ts，保留只读 id/title/tags。新增 ArchivedTask 状态 "archived" 且必须有 archivedAt:number；open 不能有 completedAt/archivedAt 数值，done 必须有 completedAt 且不能有 archivedAt，archived 不能有 completedAt。Task 联合包含三种状态。',
 {'model.ts':taskModel},
 {'model.ts':extendedTaskModel},[
 ok('三种任务可用','import type {Task,OpenTask,DoneTask,ArchivedTask} from "./model";const open:OpenTask={id:"a",title:"A",tags:[],state:"open"};const done:DoneTask={id:"b",title:"B",tags:[],state:"done",completedAt:0};const archived:ArchivedTask={id:"c",title:"C",tags:[],state:"archived",archivedAt:0};const all:Task[]=[open,done,archived];'),
 bad('归档必须有时间','import type {Task} from "./model";const task:Task={id:"a",title:"A",tags:[],state:"archived"};'),
 bad('归档不能误用完成时间','import type {Task} from "./model";const task:Task={id:"a",title:"A",tags:[],state:"archived",archivedAt:1,completedAt:1};'),
 bad('完成态不能含归档时间','import type {Task} from "./model";const task:Task={id:"a",title:"A",tags:[],state:"done",completedAt:1,archivedAt:2};'),
 ],'新状态拥有自己的时间字段。open/done/archived 的字段排斥关系让非法组合在受检查代码中失败，外部 JSON 仍需运行校验。','从共享字段开始。｜为 archived 定义字面量分支。｜排除其他分支的时间字段。'),
 m(7,5,'转换函数应接收谁','archiveTask 只允许待办任务归档，函数输入应怎样表达？',['接收 OpenTask，输出 ArchivedTask，并验证归档时间','接收任意 Task 后靠断言选择','接收 DoneTask 因为它已有时间','接收 unknown 并直接返回 Task'],'准确的输入输出分支能拒绝不合适的调用。时间的整数和范围仍需运行时验证。','哪个状态允许归档？｜输出是什么新状态？｜数值业务约束不在 number 中。'),
 t(7,6,'实现待办归档转换','只读 model.ts 已定义归档分支。实现 archiveTask(task:OpenTask,at:number):ArchivedTask，at 为非负安全整数。返回新任务和新 tags 数组，保留 id/title，不修改输入；归档输出只能有 archivedAt，不能用 completedAt。',
 'import type {OpenTask,ArchivedTask} from "./model";export function archiveTask(task:OpenTask,at:number):ArchivedTask{return {...task,state:"archived",archivedAt:at};}',
 archiveService,[
 ok('待办可归档','import {archiveTask} from "./main";import type {OpenTask,ArchivedTask} from "./model";declare const task:OpenTask;const archived:ArchivedTask=archiveTask(task,0);'),
 bad('完成任务不能作为输入','import {archiveTask} from "./main";import type {DoneTask} from "./model";declare const task:DoneTask;archiveTask(task,1);'),
 ],'转换函数连接静态状态约束和运行时日期范围。构造新对象并复制 tags，保证归档不修改原待办任务。','先验证时间。｜只接受 open。｜输出 archivedAt 与复制后的标签。',{supportFiles:{'model.ts':extendedTaskModel},runtime:[{name:'归档时间和对象独立',code:'const {archiveTask}=load("main.js");const tags=Object.freeze(["x"]),open=Object.freeze({id:"a",title:"A",tags,state:"open"});const archived=archiveTask(open,0);equal(archived,{id:"a",title:"A",tags:["x"],state:"archived",archivedAt:0});check(archived!==open&&archived.tags!==tags);equal(open.state,"open");for(const at of [-1,1.5,NaN,Infinity]){let error;try{archiveTask(open,at);}catch(e){error=e;}check(error&&error.name==="RangeError");}'}]}),
 m(7,7,'新增展示分支','模型已有 archived，但页面标签函数在 default 里返回空串，即使通过编译仍有什么问题？',['归档任务没有有意义的展示内容，需要明确归档分支和运行测试','空串会自动显示归档时间','default 只影响编译，不影响运行','把状态改成 done 即可保留语义'],'穷尽检查能提示漏分支，运行测试进一步验证分支实际输出。返回空串会掩盖新任务状态。','页面用户会看到什么？｜归档时间显示在哪里？｜不要用空串吞掉分支。'),
 t(7,8,'迁移：模型和展示一起扩展','同时编辑 model.ts 与 view.ts。增加 archived 分支与 archivedAt，并让 label(task) 分别返回“待办:标题”“完成:标题@completedAt”“归档:标题@archivedAt”。view 用穷尽检查确保三种状态都有逻辑，不能给新状态返回空串。',
 {'model.ts':taskModel,'view.ts':'import type {Task} from "./model";export function label(task:Task):string{switch(task.state){case "open":return "待办:"+task.title;case "done":return "完成:"+task.title+"@"+task.completedAt;default:return "";}}'},
 {'model.ts':extendedTaskModel,'view.ts':taskView},[
 ok('三种模型可以传给视图','import {label} from "./view";import type {Task,ArchivedTask} from "./model";declare const task:Task,archived:ArchivedTask;const a:string=label(task),b:string=label(archived);'),
 bad('归档必须有归档时间','import type {Task} from "./model";const task:Task={id:"a",title:"A",tags:[],state:"archived"};'),
 ],'模型新增 archived 后，展示模块必须同步处理。穷尽检查在将来再加状态时继续提示遗漏；运行测试验证当前三种输出。','先扩展 Task 联合。｜在 switch 中新增 archived。｜默认分支只接 never。',{runtime:[{name:'三个状态有明确展示',code:'const {label}=load("view.js");equal(label({id:"a",title:"A",tags:[],state:"open"}),"待办:A");equal(label({id:"b",title:"B",tags:[],state:"done",completedAt:0}),"完成:B@0");equal(label({id:"c",title:"C",tags:[],state:"archived",archivedAt:2}),"归档:C@2");'}]}),
 m(7,9,'复测：旧导入文件与新状态','项目新增 archived 后，导入解析器仍只接受 open/done，接下来应怎样处理？',['明确 archived 的结构与业务规则，更新解析器并回归旧状态数据','把所有旧数据强制改为 archived','只修改 Task 类型，解析器会自动识别 JSON','关闭外部数据验证'],'外部输入不会随类型声明自动升级。解析器要同时保留合法旧数据，并对归档时间和互斥字段做新检查。','旧文件是否仍需导入？｜归档需要什么新字段？｜互斥规则要在运行时实施。'),
 t(7,10,'复测：模型、转换、展示与导入共同演进','同时编辑 model.ts、service.ts、view.ts、parser.ts：增加 archived 状态与 archivedAt；待办可通过 archiveTask 转换；label 显示三种状态并穷尽检查；parseTask 从 unknown 接受合法 open/done/archived，拒绝混用时间字段，规范化文本和标签。只读 app.ts 串联转换、导入和展示。',
 {'model.ts':taskModel,'service.ts':'import type {OpenTask} from "./model";export function archiveTask(task:OpenTask,at:number){return {...task,state:"archived",archivedAt:at};}','view.ts':'import type {Task} from "./model";export function label(task:Task):string{return task.state==="done"?"完成:"+task.title:"待办:"+task.title;}','parser.ts':'import type {Task} from "./model";export function parseTask(raw:unknown):Task|null{return null;}'},
 {'model.ts':extendedTaskModel,'service.ts':archiveService,'view.ts':taskView,'parser.ts':extendedParser},[
 ok('公开流程含归档状态','import {run,renderImported} from "./app";import type {Task,ArchivedTask} from "./model";const text:string=run();const task:ArchivedTask={id:"a",title:"A",tags:[],state:"archived",archivedAt:0};const all:Task[]= [task];const imported:string=renderImported(task);'),
 bad('归档不能缺少时间','import type {Task} from "./model";const task:Task={id:"a",title:"A",tags:[],state:"archived"};'),
 bad('归档不能保留完成时间','import type {Task} from "./model";const task:Task={id:"a",title:"A",tags:[],state:"archived",archivedAt:0,completedAt:0};'),
 bad('完成态不能直接归档','import {archiveTask} from "./service";import type {DoneTask} from "./model";declare const task:DoneTask;archiveTask(task,0);'),
 ],'最终变化跨四个可编辑模块：静态契约排除非法组合，状态转换验证时间，展示与解析都处理新分支。应用模块的真实调用验证这些文件协作。','先扩展共享模型。｜分别修复 service/view/parser。｜用 app.ts 核对贯通行为。',{supportFiles:{'app.ts':'import {archiveTask} from "./service";import {parseTask} from "./parser";import {label} from "./view";import type {Task} from "./model";export function run():string{const open:Task={id:"a",title:"A",tags:[],state:"open"};return label(archiveTask(open,0));}export function renderImported(raw:unknown):string{const task=parseTask(raw);return task===null?"invalid":label(task);}'},runtime:[{name:'真实应用串联归档及三种导入',code:'const {run,renderImported}=load("app.js"),{parseTask}=load("parser.js");equal(run(),"归档:A@0");equal(renderImported({id:"a",title:"A",tags:[],state:"open"}),"待办:A");equal(renderImported({id:"b",title:"B",tags:[],state:"done",completedAt:1}),"完成:B@1");equal(renderImported({id:"c",title:" C ",tags:[" x ","x"],state:"archived",archivedAt:2}),"归档:C@2");equal(parseTask({id:"c",title:" C ",tags:[" x ","x"],state:"archived",archivedAt:2}),{id:"c",title:"C",tags:["x"],state:"archived",archivedAt:2});'},{name:'混用时间字段和无效值必须拒绝',code:'const {parseTask}=load("parser.js"),{archiveTask}=load("service.js");for(const raw of [{id:"a",title:"A",tags:[],state:"archived"},{id:"a",title:"A",tags:[],state:"archived",archivedAt:-1},{id:"a",title:"A",tags:[],state:"archived",archivedAt:0,completedAt:1},{id:"a",title:"A",tags:[],state:"done",completedAt:1,archivedAt:0},{id:"a",title:"A",tags:[],state:"open",archivedAt:undefined}])equal(parseTask(raw),null);let error;try{archiveTask({id:"a",title:"A",tags:[],state:"open"},-1);}catch(e){error=e;}check(error&&error.name==="RangeError");'}]}),

];

const publicEntry=questions.find(q=>q.id==='t14-l05-q06');publicEntry.files={'index.ts':publicEntry.files['main.ts']};publicEntry.solution={'index.ts':publicEntry.solution['main.ts']};

for(const [id,from,to] of [
 ['t14-l01-q06','tags:cleanTags','tags'],
 ['t14-l01-q08','tags:[...task.tags]','tags:task.tags'],
 ['t14-l01-q10','const tags=[...new Set(raw.tags.map((value:string)=>value.trim()))];','const tags=raw.tags.map((value:string)=>value.trim());'],
]){
 const q=questions.find(item=>item.id===id);
 q.wrongSolutions=[{'main.ts':q.solution['main.ts'].replace(from,to)}];
}

for(const [id,from,to] of [
 ['t14-l02-q06',':task',':{...task}'],
 ['t14-l02-q10','mode==="title"?','true?'],
]){const q=questions.find(item=>item.id===id);q.wrongSolutions=[{'main.ts':q.solution['main.ts'].replace(from,to)}];}

for(const [id,from,to] of [
 ['t14-l03-q06','if(pending)return pending;',''],
 ['t14-l03-q08','if(current===version)state=','state='],
 ['t14-l03-q10','message=error instanceof Error&&error.message.trim()!==""?error.message:"加载失败";','if(message==="加载失败")message=error instanceof Error&&error.message.trim()!==""?error.message:"加载失败";'],
]){const q=questions.find(item=>item.id===id);q.wrongSolutions=[{'main.ts':q.solution['main.ts'].replaceAll(from,to)}];}
